lib/psci/psci_off.c
psci_set_power_off_state only initializes a local variable, so there
isn't any reason why it should be done while the lock is held.
Change-Id: I1c62f4cd5d860d102532e5a5350152180d41d127
=> Reduce time lock in psci_do_cpu_off

Makefile
TRUSTED_BOARD_BOOT and GENERATE_COT is not
compatible with EL3_PAYLOAD_BASE
Change-Id: I538c77e1f6c7da400d30ae4d633b8fcc55742202
Signed-off-by: Qixiang Xu <qixiang.xu@arm.com>
=> Filter out invalid configure for EL3_PAYLOAD_BASE

tools/cert_create/Makefile
Using the OIDs defined in tbbr_oids.h is the recommended way to build
the cert_create tool. This patch hence sets default value of the build
flag USE_TBBR_DEFS to 1 in the Makefile in `tools/cert_create` folder
when cert_create is built from this folder.
Fixes ARM-software/tf-issues#482
Change-Id: Id1d224826b3417770bccbefa1b68d9bdb3b567f0
=> Set default value of USE_TBBR_DEFS

include/lib/aarch32/arch.h, include/lib/aarch64/arch.h, include/lib/xlat_tables/xlat_tables_defs.h
This patch provides helper macros for both Device and Normal memory MAIR
encodings as defined by the ARM Architecture Reference Manual for ARMv8-A
(ARM DDI0487B.A).
Change-Id: I5faae7f2cf366390ad4ba1d9253c6f3b60fd5e20
=> Helper macro to create MAIR encodings

plat/hisilicon/hikey/hikey_pm.c, plat/hisilicon/hikey/hisi_pwrc.c, plat/hisilicon/hikey/include/hisi_pwrc.h
Every CPU has its own debug module and this module is used by JTAG
debugging and coresight tracing. If without enabling it, it's easily to
introduce lockup issue when we enable debugging features.
This patch is to enable CPU debug module when power on CPU; this allows
connecting to all cores through JTAG and used by kernel coresight
driver.
Signed-off-by: Matthias Welwarsky <maw@sysgo.com>
Signed-off-by: Leo Yan <leo.yan@linaro.org>
=> Hikey: enable CPU debug module

include/lib/xlat_tables/xlat_tables_v2.h, lib/xlat_tables_v2/xlat_tables_internal.c
Use the MAP_REGION to build the mmap_region_t argument in wrappers like
mmap_add_region(). Evolution of the mmap_region_t might require adding
new members with a non-zero default value. Users of MAP_REGION are
protected against such evolution. This commit also protects users of
mmap_add_region() and mmap_add_dynamic_region() functions against these
evolutions.
Also make the MAP_REGION macro implementation more explicit and make it
a mmap_region_t compound literal to make it useable as a function
parameter on its own and to prevent using it in initialization of
variables of different type.
Change-Id: I7bfc4689f6dd4dd23c895b65f628d8ee991fc161
=> xlat: Use MAP_REGION macro as compatibility layer

plat/xilinx/zynqmp/pm_service/pm_api_sys.h
Synchronize argument order between function definition and declaration
of pm_fpga_load.
Fixes ARM-software/tf-issues#514
=> zynqmp: Sync function declaration and definition

lib/xlat_tables_v2/xlat_tables_internal.c
mmap_add_region_ctx and mmap_add_dynamic_region_ctx are clearing members
that they are not aware of by copying each member one by one. Replace
this by structure assignment.
Change-Id: I7c70cb408c8a8eb551402a5d8d956c1fb7f32b55
=> xlat: fix mm copy when adding a region

drivers/arm/ccn/ccn.c, drivers/arm/ccn/ccn_private.h, include/drivers/arm/gic_v3.h, include/lib/aarch64/arch.h, include/lib/utils_def.h, plat/nvidia/tegra/common/tegra_gic.c, plat/nvidia/tegra/soc/t186/drivers/mce/ari.c
The type `unsigned long` is 32 bit wide in AArch32, but 64 bit wide in AArch64. This is inconsistent and that's why we avoid using it as per the Coding Guidelines. This patch changes all `UL` occurrences to `U` or `ULL` depending on the context so that the size of the constant is clear.
This problem affected the macro `BIT(nr)`. As long as this macro is used to fill fields of registers, that's not a problem, since all registers are 32 bit wide in AArch32 and 64 bit wide in AArch64. However, if the macro is used to fill the fields of a 64-bit integer, it won't be able to set the upper 32 bits in AArch32.
By changing the type of this macro to `unsigned long long` the behaviour is always the same regardless of the architecture, as this type is 64-bit wide in both cases.
Some Tegra platform …
=> Fix type of `unsigned long` constants

include/lib/aarch64/arch.h, lib/xlat_tables/aarch64/xlat_tables.c, lib/xlat_tables_v2/aarch64/xlat_tables_arch.c
In the S-EL1&0 translation regime we aren't using the higher VA range, whose translation table base address is held in TTBR1_EL1. The bit TCR_EL1.EPD1 can be used to disable translations using TTBR1_EL1, but the code wasn't setting it to 1. Additionally, other fields in TCR1_EL1 associated with the higher VA range (TBI1, TG1, SH1, ORGN1, IRGN1 and A1) weren't set correctly as they were left as 0. In particular, 0 is a reserved value for TG1. Also, TBBR1_EL1 was not explicitly set and its reset value is UNKNOWN.
Therefore memory accesses to the higher VA range would result in unpredictable behaviour as a translation table walk would be attempted using an UNKNOWN value in TTBR1_EL1.
On the FVP and Juno platforms accessing the higher VA range resulted in a translation fault, but this may not …
=> Set TCR_EL1.EPD1 bit to 1

plat/arm/board/fvp/include/platform_def.h
platform_def.h doesn't need all the definitions in utils.h,
the ones in utils_def.h are enough. This patch is related
to the changes introduced by commit 53d9c9c85b.
=> FVP: Include utils_def.h instead of utils.h

plat/socionext/uniphier/platform.mk
Uses the xlat tables library's Makefile instead of directly including
the source files in the Uniphier platform port.
Change-Id: I27294dd71bbf9bf3e82973c75324652b037e5bce
=> Uniphier: fix xlat tables lib inclusion

plat/arm/board/fvp/tsp/tsp-fvp.mk
Commit 11ad8f208db42f7729b0ce2bd16c631c293e665c added supporting
multi-threaded CPUs on FVP platform, including modifications for
calculating CPU IDs. This patch imports the strong definition of the
same CPU ID calculation on FVP platform for TSP.
Without this patch, TSP on FVP was using the default CPU ID calculation,
which would end up being wrong on CPUs with multi-threading.
Change-Id: If67fd492dfce1f57224c9e693988c4b0f89a9a9a
=> TSP: Support multi-threading CPUs on FVP

docs/porting-guide.rst, drivers/arm/gic/v3/arm_gicv3_common.c, drivers/arm/gic/v3/gic500.c, drivers/arm/gic/v3/gic600.c, drivers/arm/gic/v3/gicv3_main.c, drivers/arm/gic/v3/gicv3_private.h, include/drivers/arm/arm_gicv3_common.h, include/drivers/arm/gic_common.h, include/drivers/arm/gicv3.h, include/lib/utils_def.h, plat/arm/board/fvp/platform.mk
Introduce helpers to save and restore the context of GICv3:
Distributor
Redistributor
For Distributor and Redistributor, the helpers also support the implementation-defined part of GIC-500 and GIC-600
ITS (only the architectural part, most of the work needs to be done according to the ITS implementation of the platform)
=> GICv3 context save and restore

include/plat/arm/board/common/board_arm_def.h
The MEM_PROTECT support adds a MMAP region for DRAM2, which when
building with TBBR support and OP-TEE tsp requires an additional
entry in the MMAP region array in BL2 - PLAT_ARM_MMAP_ENTRIES is
increased.
The MEM_PROTECT support also adds a new region in BL31, and when
BL31 is placed in DRAM, the memory mappings require an additional
translation table - MAX_XLAT_TABLES is increased.
Change-Id: I0b76260da817dcfd0b8f73a7193c36efda977625
=> Increase PLAT_ARM_MMAP_ENTRIES and MAX_XLAT_TABLES

drivers/arm/gic/v3/gicv3_main.c
This patch fixes an assertion check in the GICv3 ITS helper function.
Change-Id: I75f50d7bf6d87c12c6e24a07c9a9889e5facf4a5
=> Fix assertion in GIC ITS helper

tools/cert_create/src/key.c
Commit a8eb286adaa73e86305317b9cae15d41c57de8e7 introduced the
following error when creating ECDSA certificates.
ERROR:   Error creating key 'Trusted World key'
Makefile:634: recipe for target 'certificates' failed
make: *** [certificates] Error 1
this patch adds the function to create PKCS#1 v1.5.
Change-Id: Ief96d55969d5e9877aeb528c6bb503b560563537
Signed-off-by: Qixiang Xu <qixiang.xu@arm.com>
=> cert_tool: Fix ECDSA certificates create failure

docs/xlat-tables-lib-v2-design.rst, include/lib/xlat_tables/xlat_tables_defs.h, include/lib/xlat_tables/xlat_tables_v2.h, include/lib/xlat_tables/xlat_tables_v2_helpers.h, lib/xlat_tables_v2/aarch32/xlat_tables_arch.c, lib/xlat_tables_v2/aarch32/xlat_tables_arch_private.h, lib/xlat_tables_v2/aarch64/xlat_tables_arch.c, lib/xlat_tables_v2/aarch64/xlat_tables_arch_private.h, lib/xlat_tables_v2/xlat_tables.mk, lib/xlat_tables_v2/xlat_tables_internal.c, lib/xlat_tables_v2/xlat_tables_private.h
This patch adds support to the translation tables library v2 for EL0 mappings in the EL1&0 translation regime through the use of the `MT_USER` and `MT_PRIVILEGED` attributes.
Also, it is now possible to specify the granularity of the mappings of each region. For example, it can force a 2 MB region to be mapped using level 3 descriptors, that only map 4 KB.
For more details, please check the individual commit messages.
=> Improvements to the translation tables library v2

tools/cert_create/src/cert.c, tools/cert_create/src/ext.c, tools/cert_create/src/key.c, tools/cert_create/src/main.c
This patch fixes incompatibility issues that prevent building the cert_tool
with OpenSSL >= v1.1.0. The changes introduced are still backwards
compatible with OpenSSL v1.0.2.
Fixes arm-software/trusted-fw#521
=> cert_tool: update for compatibility with OpenSSL v1.1

tools/fiptool/fiptool.c, tools/fiptool/fiptool.h, tools/fiptool/fiptool_platform.h
In order to compile the source of Fiptool using Visual Studio a number
of adjustments are required to the source.  This commit modifies the
source with changes that will be required, but makes no functional
modification.  The intent is to allow confirmation that the GCC build
is unaffected.
Change-Id: I4055bd941c646dd0a1aa2e24b940a1db3bf629ce
Signed-off-by: Evan Lloyd <evan.lloyd@arm.com>
=> fiptool: Precursor changes for Visual Studio

include/lib/aarch64/arch_helpers.h
The macro DEFINE_SYSREG_WRITE_CONST_FUNC defines an inline function
to an assembly statement that uses the MSR (immediate) instruction
to access the PSTATE.  The "i" (immediate) assembly constraint on
the operand was only satisfied when compiling with optimizations
enabled which resulted in the function being optimized out - the
"const uint64_t v" parameter was optimized out and replaced by a
literal value.
When compiling without optimizations, the function call remained and
therefore the parameter is not optimized out - compilation fails as
the constraint is impossible to satisfy by the compiler.
This patch replaces the function encapsulating the use of
the MSR (immediate) with a macro that allows the literal value to be
directly fed to the inline assembly statement
Change-Id: …
=> Fix use of MSR (immediate)

include/lib/aarch64/arch_helpers.h, include/lib/xlat_tables/xlat_tables_defs.h, include/lib/xlat_tables/xlat_tables_v2.h, include/lib/xlat_tables/xlat_tables_v2_helpers.h, lib/aarch64/misc_helpers.S, lib/xlat_tables_v2/aarch32/xlat_tables_arch.c, lib/xlat_tables_v2/xlat_tables_internal.c
Also:
- Small fix to AArch32 port of the library.
- Add functions to disable MMU in EL1.
For more details, check the individual commits.
=> Add APIs to get and modify attributes of memory regions

tools/fiptool/fiptool_platform.h, tools/fiptool/win_posix.c, tools/fiptool/win_posix.h
Updates are required to enable the fiptool utility to be built on a
Windows platform.  This change modifies the source files to enable
building with Visual Studio (detected via preprocessor settings).
The primary changes are:
1.  Provide an implementation of the getopt_long function.  This does
not exist in the Visual Studio CRT libraries because Windows
commands normally use '/' not '-' as an option indicator.
2.  Redirect some function names to match those supported by the
Visual Studio libraries (when building with Visual Studio).
2.  Modify a structure name (stat) to match that provided
by the Visual Studio libraries (_stat).
Note - this change does not provide makefile updates.  It only modifies
the sources to enable the fiptool to be built from a Visual
Studio project.  In normal …
=> fiptool: Enable Visual Studio build

bl31/bl31.ld.S, bl32/sp_min/sp_min.ld.S, docs/firmware-design.rst, include/lib/el3_runtime/pubsub.h, include/lib/el3_runtime/pubsub_events.h, lib/psci/psci_on.c
This light-weight framework allows for calling into EL3 components without having explicit dependency. This works by defining events, registering subscribers, and publishing those events at required code path.
=> Publish and Subscribe framework

plat/qemu/platform.mk, plat/qemu/qemu_io_storage.c, plat/qemu/qemu_rotpk.S, plat/qemu/qemu_trusted_boot.c
This patch adds support for TBB to qemu. An RSA ROT keypair is generated at build
time and is included into BL1/BL2. The key and content certificates are
read over semihosting.
Fixes ARM-software/tf-issues#526
=> qemu: Add support for Trusted Board Boot

plat/qemu/include/platform_def.h
OP-TEE dedicates the end of the Qemu secure DRAM as specific out-of-TEE
secure RAM. To support this configuration the trusted firmware should
not load OP-TEE resources in this area.
To overcome the issue, OP-TEE pageable image is now loaded 2MByte above
the secure RAM base address.
Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>
=> qemu/optee: load OP-TEE pageable part 2MB above OP-TEE image

docs/user-guide.rst, include/drivers/auth/mbedtls/mbedtls_config.h, include/plat/arm/board/common/board_arm_def.h, plat/arm/board/juno/include/platform_def.h, plat/arm/common/arm_common.mk
1. Change the default option of ARM_TSP_RAM_LOCATION
On Arm standard platforms, it runs out of SRAM space when TBB is enabled, so the TSP default location is changed to dram when TBB is enabled.
2. Enlarge the BL2 size on Arm platforms when TBB is enabled
For Trusted Board Boot, BL2 needs more space to support the ECDSA and ECDSA+RSA algorithms.
=> Change the default option of ARM_TSP_RAM_LOCATION and Enlarge the BL2 size on ARM platforms

bl2/bl2_main.c, common/bl_common.c, docs/porting-guide.rst, include/plat/common/platform.h, plat/common/aarch32/platform_helpers.S, plat/common/aarch64/platform_helpers.S
These hooks are intended to allow one platform to try load
images from alternative places. There is a hook to initialize
the sequence of boot locations and a hook to pass to the next
sequence.
Change-Id: Ia0f84c415208dc4fa4f9d060d58476db23efa5b2
=> Add platform hooks for boot redundancy support

docs/user-guide.rst
FWU uses additional images that have to be loaded,
and this patch adds the documentation of how to do
it in FVP and Juno.
Change-Id: I1a40641c11c5a4c8db0aadeaeb2bec30c9279e28
=> Add FWU booting instructions to the user guide

docs/firmware-design.rst, include/lib/el3_runtime/pubsub_events.h, lib/el3_runtime/aarch64/context_mgmt.c
Add events that trigger before entry to normal/secure world.  The
events trigger after the normal/secure context has been restored.
Similarly add events that trigger after leaving normal/secure world.
The events trigger after the normal/secure context has been saved.
Change-Id: I1b48a7ea005d56b1f25e2b5313d77e67d2f02bc5
=> aarch64: Add PubSub events to capture security state transitions

plat/qemu/qemu_bl31_setup.c
Registered interrupts are configured in edge detection as the default
previous configuration assumed in previous code.
Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>
=> qemu: update deprecated interrupt registering

include/lib/el3_runtime/cpu_data.h
Change sizeof call so it references a static type instead of return of
a function in order to be MISRA compliant.
Change-Id: I6f1adb206073d6cd200156e281b8d76249e3af0e
Signed-off-by: Joel Hutton <joel.hutton@arm.com>
=> Change sizeof to use type of struct not function

common/aarch64/debug.S, include/lib/xlat_tables/xlat_tables_v2_helpers.h, plat/arm/common/arm_common.mk, plat/hisilicon/hikey/aarch64/hikey_common.c, plat/hisilicon/hikey/hikey_io_storage.c, plat/hisilicon/hikey/include/platform_def.h, plat/hisilicon/hikey960/aarch64/hikey960_common.c, plat/hisilicon/hikey960/include/platform_def.h, plat/rockchip/rk3328/include/platform_def.h
There are several cases where some macros are used in prepocessor conditionals without a previous definition and in some cases it was generating some problems.
=> Avoid use of undefined macros

lib/psci/psci_common.c, lib/psci/psci_suspend.c, plat/common/plat_psci_common.c
This patch includes various fixes for PSCI STAT functionality
relating to timestamp collection:
1. The PSCI stat accounting for retention states for higher level
power domains were done outside the locks which could lead to
spurious values in some race conditions. This is moved inside
the locks. Also, the call to start the stat accounting was redundant
which is now removed.
2. The timestamp wrap-around case when calculating residency did
not cater for AArch32. This is now fixed.
3. In the warm boot path, `plat_psci_stat_accounting_stop()` was
getting invoked prior to population of target power states. This
is now corrected.
Change-Id: I851526455304fb74ff0a724f4d5318cd89e19589
=> Fix PSCI STAT time stamp collection

services/std_svc/spm/secure_partition_setup.c
The MP info struct is placed right after the boot info struct. However, when calculating the address of the MP info, the size of the boot info struct was being multiplied by the size of the MP boot info. This left a big gap of empty space between the structs.
This didn't break any code because the boot info struct has a pointer to the MP info struct. It was just wasting space.
=> SPM: Fix pointer to MP info in boot info struct

bl31/aarch64/crash_reporting.S, docs/firmware-design.rst, include/lib/el3_runtime/aarch64/context.h, lib/el3_runtime/aarch64/context.S
The FPEXC32_EL2 register controls SIMD and FP functionality when the
lower ELs are executing in AArch32 mode. It is architecturally mapped
to AArch32 system register FPEXC.
This patch removes FPEXC32_EL2 register from the System Register context
and adds it to the floating-point context. EL3 only saves / restores the
floating-point context if the build option CTX_INCLUDE_FPREGS is set to 1.
The rationale for this change is that if the Secure world is using FP
functionality and EL3 is not managing the FP context, then the Secure
world will save / restore the appropriate FP registers.
NOTE - this is a break in behaviour in the unlikely case that
CTX_INCLUDE_FPREGS is set to 0 and the platform contains an AArch32
Secure Payload that modifies FPEXC, but does not save and restore
this register …
=> Move FPEXC32_EL2 to FP Context

docs/user-guide.rst, drivers/auth/mbedtls/mbedtls_crypto.c, drivers/auth/mbedtls/mbedtls_crypto.mk, drivers/auth/tbbr/tbbr_cot.c, include/drivers/auth/mbedtls/mbedtls_config.h, make_helpers/tbbr/tbbr_tools.mk, tools/cert_create/include/cert.h, tools/cert_create/include/key.h, tools/cert_create/include/sha.h, tools/cert_create/src/cert.c, tools/cert_create/src/main.c, tools/cert_create/src/sha.c
add an option -hash-alg for cert_create and add build flag HASH_ALG to let the user to select the SHA
It supports the following options:
- sha256 (default)
- sha384
- sha512
=> Add support sha512 for hash algorithm

lib/psci/psci_main.c
There is an edge case where the cache maintaince done in
psci_do_cpu_off may not seen by some cores. This case is handled in
psci_cpu_on_start but it hasn't handled in psci_affinity_info.
Change-Id: I4d64f3d1ca9528e364aea8d04e2d254f201e1702
=> Flush the affinity data in psci_affinity_info

Makefile
Commit 26e63c4450 broke the Makefile for ARMv8-A AArch32 platforms.
This patch fixes it.
=> Fix Makefile for ARMv8-A AArch32 builds

lib/cpus/aarch32/cortex_a53.S, lib/cpus/aarch32/cortex_a57.S, lib/cpus/aarch32/cortex_a72.S, make_helpers/defaults.mk
This patch replaces the macro ASM_ASSERTION with the macro
ENABLE_ASSERTIONS in ARM Cortex-A53/57/72 MPCore Processor
related files. There is build error when ASM_ASSERTION is set
to 1 and ENABLE_ASSERTIONS is set to 0 because function
asm_assert in common/aarch32/debug.S is defined in the macro
ENABLE_ASSERTIONS but is called with the macro ASM_ASSERTION.
There is also the indication to use ENABLE_ASSERTIONS but not
ASM_ASSERTION in the Makefile.
Signed-off-by: Matt Ma <matt.ma@spreadtrum.com>
=> Replace macro ASM_ASSERTION with macro ENABLE_ASSERTIONS

docs/plat/rpi3.rst, maintainers.rst, plat/rpi3/aarch64/plat_helpers.S, plat/rpi3/aarch64/rpi3_bl2_mem_params_desc.c, plat/rpi3/include/plat_macros.S, plat/rpi3/include/platform_def.h, plat/rpi3/platform.mk, plat/rpi3/rpi3_bl1_setup.c, plat/rpi3/rpi3_bl2_setup.c, plat/rpi3/rpi3_bl31_setup.c, plat/rpi3/rpi3_common.c, plat/rpi3/rpi3_hw.h, plat/rpi3/rpi3_image_load.c, plat/rpi3/rpi3_io_storage.c, plat/rpi3/rpi3_pm.c, plat/rpi3/rpi3_private.h, plat/rpi3/rpi3_topology.c
This port can be compiled to boot an AArch64 or AArch32 payload with the build option `RPI3_BL33_AARCH32`.
Note: This is not a secure port of the Trusted Firmware. This port is only meant to be a reference implementation to experiment with an inexpensive board in real hardware.
This port is based on the work of Ard Biesheuvel (@ardbiesheuvel), that can be found in http://www.workofard.com/2017/02/uefi-on-the-pi/, see repository in https://github.com/ardbiesheuvel/arm-trusted-firmware/tree/rpi3. That port has been heavily modified. For starters, that port didn't manage to boot Linux or to release the secondary CPUs from their wait loop because the RAM wasn't initialized to 0 before entering the loop.
=> Introduce AArch64 Raspberry Pi 3 port

maintainers.rst
This patch updates Xilinx maintainers details
as sorenb is no more the maintainer for xilinx
and the email id is invalid now.
Signed-off-by: Siva Durga Prasad Paladugu <sivadur@xilinx.com>
=> Update Xilinx maintainer details

maintainers.rst
Miscellaneous fixes to maintainers.rst
* Update the RockChip sub-maintainer from rkchrome to rockchip-linux
in maintainers.rst.
* Add missing documentation files and change extensions from `md` to `rst`.
* Add sub-maintainer for Socionext UniPhier platform.
=>  Miscellaneous fixes to maintainers.rst

bl1/bl1.ld.S, bl2/bl2.ld.S, bl2u/bl2u.ld.S, bl31/bl31.ld.S, bl32/sp_min/sp_min.ld.S, bl32/tsp/tsp.ld.S, include/plat/arm/common/arm_common.ld.S, plat/mediatek/mt6795/bl31.ld.S, plat/rockchip/rk3399/include/plat.ld.S
When defining different sections in linker scripts it is needed to align them to multiples of the page size. In most linker scripts this is done by aligning to the hardcoded value 4096 instead of PAGE_SIZE.
This may be confusing when taking a look at all the codebase, as 4096 is used in some parts that aren't meant to be a multiple of the page size.
=> Replace magic numbers in linkerscripts by PAGE_SIZE

plat/rockchip/rk3399/plat_sip_calls.c
This includes the stdint header to declare the various types used within
the file, preventing build errors with recent GCC versions.
Change-Id: I9e7e92bb31deb58d4ff2732067dd88b53124bcc9
Signed-off-by: Paul Kocialkowski <contact@paulk.fr>
=> rockchip: Include stdint header in plat_sip_calls.c

plat/arm/common/arm_tzc400.c
This patch allows non-secure bus masters to access TZC region0 as well
as the EL3 Payload itself.
Change-Id: I7e44f2673a2992920d41503fb4c57bd7fb30747a
=> ARM Platforms: Change the TZC access permissions for EL3 payload

common/bl_common.c, include/common/bl_common.h
Previously the cache flush happened in 2 different places in code
depending on whether TRUSTED_BOARD_BOOT is enabled or not. This
patch unifies this code path for both the cases. The `load_image()`
function is now made an internal static function.
Change-Id: I96a1da29d29236bbc34b1c95053e6a9a7fc98a54
=> Unify cache flush code path after image load

services/std_svc/sdei/sdei_main.c
At present, both SDEI_PRIVATE_RESET and SDEI_SHARED_RESET returns
SDEI_PENDING if they fail to unregister an event. The SDEI specification
however requires that the APIs return SDEI_EDENY in these cases. This
patch fixes the return codes for the reset APIs.
Change-Id: Ic14484c91fa8396910387196c256d1ff13d03afd
=> SDEI: Fix return value of reset calls

plat/arm/board/fvp/fvp_pm.c, plat/arm/board/fvp/include/platform_def.h, services/std_svc/spm/secure_partition_setup.c
After returning from SYSTEM_SUSPEND state, BL31 reconfigures the TrustZone Controller during the boot sequence. If BL31 is placed in TZC-secured DRAM, it will try to change the permissions of the memory it is being executed from, causing an exception.
The solution is to disable SYSTEM_SUSPEND when the Trusted Firmware has been compiled with ``ARM_BL31_IN_DRAM=1``.
Also, a small issue regarding an Arm platform header has been fixed.
=> fvp: Disable SYSTEM_SUSPEND when ARM_BL31_IN_DRAM 

include/lib/xlat_tables/xlat_tables_v2.h, include/lib/xlat_tables/xlat_tables_v2_helpers.h, include/plat/arm/board/common/board_arm_def.h, include/plat/arm/common/arm_spm_def.h, services/std_svc/spm/secure_partition_setup.c
A new platform define, `PLAT_SP_IMAGE_XLAT_SECTION_NAME`, has been introduced to select the section where the translation tables used by the S-EL1/S-EL0 are placed.
This define has been used to move the translation tables to DRAM secured by TrustZone.
Most of the extra needed space in BL31 when SPM is enabled is due to the large size of the translation tables. By moving them to this memory region we can save 44 KiB.
A new argument has been added to REGISTER_XLAT_CONTEXT2() to specify the region where the translation tables have to be placed by the linker.
=> SPM: Move S-EL1/S-EL0 xlat tables to TZC DRAM

Makefile, make_helpers/build_macros.mk
This is a revamp of the original approach in:
https://github.com/ARM-software/arm-trusted-firmware/pull/747
Current build system has no means to automatically generate dtbs from
dts, instead, stores the dtbs in the fdts/ folder. While this makes
perfect sense for many reference platforms, this becomes a minor
breakage in development flow for newer platforms.
However, this can be solved by providing a rule for the dtbs while
building the ATF binaries by purely describing which dts sources we
need.
For example, with this change, we will now be able to describe the
dtbs we need for the platform in the corresponding platform.mk file:
FDT_SOURCES += fdts/abc.dts
This should be able to generate the abc.dtb appropriately.
Since device trees are specification of hardware, we don't tie the rule
to …
=> Makefile: Add ability to build dtb (v2)

drivers/io/io_block.c
The block operations were trying to optimize the number of memory
copies, and it tried to use directly the buffer supplied by the user
to them. This was a mistake because it created too many corner cases:
1- It was possible to generate unaligned
operations to unaligned buffers. Drivers that were using
DMA transfer failed in that case.
2- It was possible to generate read operations
with sizes that weren't a multiple of the block size. Some
low level drivers assumed that condition and they calculated
the number of blocks dividing the number of bytes by the
size of the block, without considering the remaining bytes.
3- The block_* operations didn't control the
number of bytes actually copied to memory, because the
low level drivers were writing directly to the user buffer.
This patch rewrite …
=> io: block: fix block_read/write may read/write overlap buffer

Makefile
ARM TF does not work correctly if built with a version of gcc
that is configured to use PIE by default (e.g. Debian Stretch).
This patch identifies when such a version of gcc is being used
(by searching for --enable-default-pie) and adds -fno-PIE option
to TF_CFLAGS.
fixes arm-software/tf-issues#519
Change-Id: I2322122c49841746d35d152694e14f6f73beb0fd
Co-Authored-by: Evan Lloyd <evan.lloyd@arm.com>
Tested-by: Steve Capper <steve.capper@arm.com>
Tested-by: Alexei Fedorov <alexei.fedorov@arm.com>
=> Disable PIE compilation option

include/plat/arm/board/common/board_arm_def.h, plat/arm/common/arm_common.mk
To allow BL31 to grow in SRAM, move TSP in TZC secured DRAM
by default.
Increase the BL31 max limit by one page.
Change-Id: Idd3479be02f0f9bafac2f275376d7db0c2015431
=> Move TSP to TZC secured DRAM

docs/user-guide.rst
ARM TF has been tested as part of its CI system with the following
dependencies updated:
- Linaro binaries:    17.04 --> 17.10
- mbed TLS library:   2.4.2 --> 2.6.0
The version of AEM, Cortex-A and Foundation models that ARM TF is
tested on has also been updated:
- v11.1 build 11.1:22 --> v11.2 build 11.2:33
- v8.9 build 0.8:8805 --> v9.0 build 0.8:9005
This patch updates the user guide documentation to reflect these
changes to the dependencies.
Additionally, links to Linaro resources have been updated.
Change-Id: I9ea5cb76e7443c9dbb0c9525069f450a02f59e58
=> Update dependencies for ARM TF

docs/firmware-design.rst, tools/fiptool/fiptool.c
This patch adds padding bytes at the end of the last image in the
fip to be able to transfer by DMA the last image.
Change-Id: I8c6f07dee389cb3d1dc919936d9d52841d7e5723
docs: Update the ToC end marker description in the document
jtzhou2016 committed with davidcunado-arm on 24 Nov 2017
Change-Id: I2e29a63f08aed3b8ea0bb10170a3d55b8d033e62
Signed-off-by: Jett Zhou <jett.zhou@arm.com>
=> Add padding at the end of the last entry

services/std_svc/spm/spm_main.c, services/std_svc/spm/spm_private.h
The Secure Partition should be able to be used from any CPU, not just the lead one. This patch point the secure contexts of all secondary CPUs to the same one used by the lead CPU for the Secure Partition. This way, they can also use it.
In order to prevent more than one CPU from using the Secure Partition at the same time, a lock has been added.
=> SPM: Allow secondary CPUs to use the Secure Partition

plat/xilinx/zynqmp/ipi_mailbox_service/ipi_mailbox_svc.c, plat/xilinx/zynqmp/ipi_mailbox_service/ipi_mailbox_svc.h, plat/xilinx/zynqmp/platform.mk, plat/xilinx/zynqmp/pm_service/pm_api_sys.c, plat/xilinx/zynqmp/pm_service/pm_common.h, plat/xilinx/zynqmp/pm_service/pm_ipi.c, plat/xilinx/zynqmp/pm_service/pm_ipi.h, plat/xilinx/zynqmp/pm_service/pm_svc_main.c, plat/xilinx/zynqmp/sip_svc_setup.c, plat/xilinx/zynqmp/zynqmp_ipi.c, plat/xilinx/zynqmp/zynqmp_ipi.h
This patch series will:
* centralize the ZynqMP IPI(Inter Processor Interrupt) IP core access management
* provide ZynqMP IPI mailbox service
v4:
- fix include headers sequence in zynqmp_ipi.c
- update the comments to check if IPI is within valid range to match the function implementation
v3:
- use ((x & y) && z)
- use macro to check if the IPI is secure
v2:
- updated the license text
- use U instead of UL for 32bit macros
- use ARRAY_SIZE to get the size of IPI table
- adjust the include headers sequence
- move ipi mailbox validation to IPI SMC handler
=> plat: xilinx: Add ZynqMP IPI mailbox service [v4]

include/plat/arm/board/common/board_arm_def.h
On some build configurations BL31 is running out of space.  Now that
TSP is moved to secure dram, we have a bit of additional space to use
in BL31.
Change-Id: Ib89fcd8bae99c85c9c5e5d9228bb42fb7048dcb6
=> Increase BL31 memory space by 2 pages

lib/extensions/amu/aarch32/amu.c, lib/extensions/amu/aarch64/amu.c
If AMU is not supported by the hardware but it is enabled in Trusted
Firmware, the console will be spammed with warnings every time a CPU
is brought up with a CPU ON call.
Remove the warning message as this is more in line with how other
extensions like SPE and SVE are handled.
Change-Id: Iba6d367e4d1375ab554d23d2eaceab3ae1362c5a
=> AMU: Remove unnecessary WARN()

docs/porting-guide.rst
If boot redundancy is required in BL1 then the initialization
of the boot sequence must be done in bl1_platform_setup. In BL2,
we had to add a new function, bl2_preload_setup, because
bl2_platform_setup is called after the images are loaded, making it
invalid for the boot sequence initialization.
Change-Id: I5c177ff142608ed38b4192288b06614343b2b83b
=> Add documentation about plat_try_next_boot_source to bl1_platform_setup

include/bl32/payloads/tlk.h, services/spd/tlkd/tlkd_main.c
This patch adds support to receive function ID with NS world's
memory ranges to provide the memory snapshot to TLK.
=> spd: tlkd: support for "NS memory ranges" function ID

plat/hisilicon/hikey960/hikey960_bl1_setup.c, plat/hisilicon/hikey960/include/hi3660.h
Set IOC_AO_IOMG_033 function from GPIO213 to PCIE_CLKREQ_N
bit[0-2]:  000: GPIO_213;
001: PCIE_CLKREQ_N;
010: GPIO_018_SH;
100: GPIO_014_SE;
110: FAC_TEST24;
111: FAC_TEST24;
bit[3-31]: reserved
Signed-off-by: Guangtao Zhang <zhangguangtao@hisilicon.com>
Tested-by: Yao Chen <chenyao11@huawei.com>
Acked-by: Haojian Zhuang <haojian.zhuang@linaro.org>
=> Hikey960: Fix hikey960 pcie mount fail

lib/xlat_tables_v2/xlat_tables_internal.c
`mm_cursor` doesn't have the needed data because the `memmove()` that is called right before it overwrites that information. In order to get the information of the region that was being mapped, `mm` has to be used instead (like it is done to fill the fields of `unmap_mm`).
If the incorrect information is read, this check isn't reliable and `xlat_tables_unmap_region` may be requested to unmap memory that isn't mapped at all, triggering assertions.
=> xlat v2: Correctly unmap regions on map error

include/services/mm_svc.h, include/services/spm_svc.h, services/std_svc/spm/spm_main.c
Rename SP_VERSION macros to MM_VERSION, which is the name used in the MM specification [1]. Also, a few more helper macros have been added.
MM-specific definitions have been moved to their own header file.
[1] http://infocenter.arm.com/help/topic/com.arm.doc.den0060a/DEN0060A_ARM_MM_Interface_Specification.pdf
=> SPM: Fix version header definitions

drivers/synopsys/emmc/dw_mmc.c
When check HLE bit in interrupt register, it should check whether
HLE bit is set, not clear.
=> emmc/dw_mmc: fix the assert on HLE bit

drivers/emmc/emmc.c, include/drivers/emmc.h
Add some macros according to JEDEC Standard Embedded Multi-Media
Card (eMMC) Electrical Standard (5.1)": Table 145 - Bus Mode
Selection.
The specification could be downloaded from here:
https://www.jedec.org/sites/default/files/docs/JESD84-B51.pdf
=> emmc: add macros CMD21, BUS_WIDTH_DDR_4 and BUS_WIDTH_DDR_8

lib/cpus/aarch32/cortex_a72.S
In AARCH32 mode, cortex_a72_reset_func branches to address in lr
register instead of r5 register. This leads to linux boot failure
of Cortex-A72 cores in AARCH32 mode on Juno-R2 board.
This patch fixes the branching of cortex_a72_reset_func to r5
register as in cortex_a57_reset_func implementation.
Signed-off-by: Manoj Kumar <manoj.kumar3@arm.com>
=> lib/cpus: fix branching in reset function for cortex-a72 AARCH32 mode

plat/socionext/uniphier/platform.mk
The `override ERROR_DEPRECATION = 1` setting in uniphier platform
makes deprecation of API difficult. Hence removing the same. This
flag should be specified on the command line if needed.
Change-Id: I8c82d8d13944e450a8cd636de3326137c04d7560
=> Allow API deprecation for uniphier platform

bl32/sp_min/aarch32/entrypoint.S, bl32/sp_min/sp_min.mk, bl32/sp_min/workaround_cve_2017_5715_bpiall.S, bl32/sp_min/workaround_cve_2017_5715_icache_inv.S, include/common/aarch32/el3_common_macros.S, include/lib/aarch32/arch.h, include/lib/aarch32/smcc_helpers.h, include/lib/cpus/aarch32/cortex_a15.h, lib/cpus/aarch32/cortex_a15.S, lib/cpus/aarch32/cortex_a17.S, lib/cpus/aarch32/cortex_a57.S, lib/cpus/aarch32/cortex_a72.S, lib/cpus/aarch32/cortex_a9.S, lib/cpus/aarch64/cortex_a57.S, lib/cpus/aarch64/cortex_a72.S, lib/cpus/aarch64/cortex_a73.S, lib/cpus/aarch64/cortex_a75.S, lib/cpus/errata_report.c
This PR includes the workarounds for A9, A15 and A17.  The workarounds target sp_min but can easily be adapted to work on other implementations.
Two patches are included to enable workaround reporting on the affected AArch64 and AArch32 CPUs.
=> Workarounds for CVE-2017-5715 on A9/A15 and A17 + serial console reporting

plat/hisilicon/hikey/hikey_bl2_setup.c, plat/hisilicon/hikey/hikey_private.h, plat/hisilicon/hikey/hikey_security.c, plat/hisilicon/hikey/platform.mk
The upstream HiKey ATF support doesn't actually secure the DDR where OP-TEE is running or the secure data path buffers. This pull request adds those missing patches by Jerome Forissier which I've re-based so they apply upstream.
=> Hikey protect optee / sdp memory

plat/hisilicon/hikey/hikey_security.c
`assert(e)` was used in place of `if (e) ERROR()` when sec_protect() was
ported from hikey fork so the logic should have been reversed.
Fixes: 3d5d9f5a ("hikey: configure the top 16MB of DRAM as secure")
Fixes: 52988b38 ("hikey: configure 4 MB of secure DRAM for OP-TEE
Secure Data Path")
=> hikey: fix assert in sec_protect()

docs/plat/hikey.rst
The correct name of the manufacturer is LeMaker.
=> docs: hikey: Fix typo

docs/firmware-design.rst
The CnP bit documentation in the Firmware Design Guide incorrectly
used the term "Page Entries" instead of "Processing Elements".
Fix that.
=> Fix documentation for CnP bit

plat/arm/board/fvp/fvp_common.c
This patch maps the devices in the first GB of the system address map
on the FVP into the S-EL1&0 translation regime when SPM support is
enabled. This grants the Secure Partition access to the devices in
this region, for example the memory-mapped Generic Timer device.
=> SPM: Map devices in the 1st GB

drivers/delay_timer/delay_timer.c, include/lib/utils_def.h
This fixes a minor problem we noticed that can result in udelay() calls delaying for slightly less time than the programmer intended.
=> Fix udelay issues that can make duration slightly too short

Makefile
In the Makefile we use findstring to locate gcc toolchains
that have PIE enabled by default.
Unfortunately the result of findstring is compared against
an integer, 1, rather than a non-empty string; the logic to
disable PIE then doesn't get applied.
This patch fixes the flag test.
=> Correct the Makefile logic for disabling PIE

Makefile
Some toolchain distributions install both the BFD and GOLD linkers under
the names [target]-ld.bfd and [target]-ld.gold. [target]-ld will then be
a symlink that may point to either one of these.
Trusted Firmware should always be linked with the BFD linker, since GOLD
is meant primarily for userspace programs and doesn't support many of
the more obscure linker script features that may be needed for firmware.
With this patch the Makefile will auto-detect if ld.bfd is available and
use it explicitly in that case.
Change-Id: I7017055f67db3bd57d191d20a7af06ca646937d7
Signed-off-by: Julius Werner <jwerner@chromium.org>
=> Makefile: Use ld.bfd linker if available

tools/fiptool/fiptool.c
Commit 880b9e8b4c99ad99eee14079d5a6162733ef4931 (Add padding at the end
of the last entry) added code using toc_entry pointer, whose memory is
already freed via variable buf. This causes enormous padding on openSUSE.
Free the memory buffer only after padding is done.
This fixes #1204.
=> fiptool: Fix use after free

drivers/arm/gic/v3/arm_gicv3_common.c, plat/rockchip/common/plat_pm.c, plat/rockchip/rk3399/drivers/pmu/pmu.c, plat/rockchip/rk3399/drivers/pmu/pmu.h, plat/rockchip/rk3399/platform.mk
This fixes several things in generic GICv3 code and RK3399 specific code. It then enables save/restore for the GICv3 on RK3399.
=> RK3399 GIC save/restore

.checkpatch.conf, Makefile
With the old system `checkpatch.pl` gets one sole input that consists of the commit message and commit diff of each commit between BASE_COMMIT and HEAD. It also filters out changes in some files, which makes `git format-patch` completely ignore that commit, even the commit message.
With the new system the commit message and commit diff are analyzed separately. This means that, even if all the files modified by a commit are filtered out, the commit message will still be analyzed.
Also, all commits are analyzed individually. This way it's easier to know which commit caused the problem, and there are no warnings about repeated "Signed-off-by" lines.
=> Analyze coding style of patches individually

plat/rockchip/rk3399/drivers/pmu/pmu.c
Coverity scan done for the coreboot project found the issue:
Coverity (*** CID 1385418: Memory - illegal accesses (OVERRUN))
Coverity (*** CID 1385419: Memory - corruptions  (OVERRUN))
Fix the Converity error issue with store_cru[] loop needs to be one
element bigger.
Fixes: ARM-software/tf-issues#544
Change-Id: I420f0a660b24baaa5fc5e78fca242cf750c9bbc7
Signed-off-by: Caesar Wang <wxt@rock-chips.com>
=> rockchip/rk3399: Fix memory corruptions or illegal memory access

lib/zlib/tf_gunzip.c
When enabling VERBOSE() traces, the zlib library fails to compile
because of an incompatible format specifier string. Fix that.
=> zlib: Fix build error when LOG_LEVEL=50

lib/optee/optee_utils.c
Currently optee header info is only printed after it is validated,
but this does not help with debugging in case of error, so print it
before.
=> optee: print header info before validate

drivers/arm/tzc/tzc400.c, drivers/io/io_fip.c, services/std_svc/sdei/sdei_state.c
This fixes all defects according to MISRA Rule 3.1: "The character sequences /* and // shall not be used within a comment". This affects all URLs in comments, so they have been removed:
- The link in `sdei_state.c` can also be found in the documentation file `docs/sdei.rst`.
- The bug that the file `io_fip.c` talks about doesn't affect the currently supported version of GCC, so it doesn't make sense to keep the comment. Note that the version of GCC officially supported is the one that comes with Linaro Release 17.10, which is GCC 6.2.
- The link in `tzc400.c` was broken, and it didn't correctly direct to the Technical Reference Manual it should. The link has been replaced by the title of the document, which is more convenient when looking for the document.
=> Remove URLs from comments

plat/arm/common/aarch32/arm_helpers.S, plat/arm/common/aarch64/arm_helpers.S
The console core flush API expects the base address in the first
register, but ARM helpers currently sets the second register with the
base address. This causes an assert failure.
This patch fixes that.
Change-Id: Ic54c423cd60f2756902ab3cfc77b3de2ac45481e
=> ARM platforms: Fix console address for flush

bl31/ehf.c
When deactivating, it's not an error if the priority being deactivating
is equal to the active priority. Fix this.
Change-Id: I66f0e9e775ac9aba8a7cc48cd3ecd3b358be63c0
=> EHF: Fix priority check

plat/hisilicon/hikey960/hikey960_pm.c
Avoid hardcode on uart port. The uart port could be auto detected
on HiKey960 platform.
=> hikey960: avoid hardcode on uart port

plat/nvidia/tegra/include/tegra_private.h, plat/nvidia/tegra/soc/t132/plat_setup.c, plat/nvidia/tegra/soc/t186/plat_setup.c, plat/nvidia/tegra/soc/t210/plat_setup.c
Commit fdb1964c34968921379d3592e7ac6e9a685dbab1 ("xlat: Introduce
MAP_REGION2() macro") added a granularity field to mmap_region_t.
Tegra platforms were using the v2 xlat_tables implementation in
common/tegra_common.mk, but v1 xlat_tables.h headers in soc/*/plat_setup.c
where arrays are being defined. This caused the next physical address to
be read as granularity, causing EINVAL error and triggering an assert.
Consistently use xlat_tables_v2.h header to avoid this.
Fixes ARM-software/tf-issues#548.
=> tegra: Fix mmap_region_t struct mismatch

bl31/aarch64/runtime_exceptions.S, include/lib/smcc.h
According to the SMC Calling Convention (ARM DEN0028B):
> The Unknown SMC Function Identifier is a sign-extended value of (-1) that is returned in R0, W0 or X0 register.
The value wasn't sign-extended because it was defined as a 32-bit unsigned value (`0xFFFFFFFF`).
`SMC_PREEMPT` has been redefined as -2 for the same reason.
NOTE: This might be a compatibility break for some AArch64 platforms that don't follow the previous version of the SMCCC (ARM DEN0028A) correctly. That document specifies that only the bottom 32 bits of the returned value must be checked. If a platform relies on the top 32 bits of the result being 0 (so that `SMC_UNK` is `0x00000000FFFFFFFF`), it will have to fix its code to comply with the SMCCC.
=> Redefine SMC_UNK as -1 instead of 0xFFFFFFFF

drivers/arm/tzc/tzc_common_private.h
Previously the definition of `_tzc_read_peripheral_id()` was wrapped
in ENABLE_ASSERTIONS build flag. This causes build issue for TZC400 driver
when DEBUG=1 and ENABLE_ASSERTIONS=0. This patch fixes the same by
moving the definitions outside the ENABLE_ASSERTIONS build flag.
Change-Id: Ic1cad69f02ce65ac34aefd39eaa96d5781043152
=> Resolve TZC400 build issue when DEBUG=1 and ENABLE_ASSERTIONS=0

lib/cpus/aarch32/cpu_helpers.S
The AArch32 assembly implementation of `print_errata_status` did not save
a register which was getting clobbered by a `get_cpu_ops_ptr`. This
patch fixes that.
Change-Id: Id0711e46b7c685a18a10328d4b513e952a5d860b
=> Fixup AArch32 errata printing framework

docs/user-guide.rst
The Arm Trusted Firmware is built by default for ARMv8-A version 8.0. However, the Foundation FVP runs by default in the highest version of the architecture it supports. This causes problems when trying to run the Arm Trusted Firmware on it.
This patch adds a note to the User Guide about this problem.
=> Fix Foundation FVP instructions in User Guide

drivers/synopsys/ufs/dw_ufs.c, drivers/ufs/ufs.c, include/drivers/ufs.h
Hynix ufs has deviations on hi36xx platform which will result
in ufs bursts transfer failures at a very low probability.
To fix the problem, the Hynix device must set the register
VS_DebugSaveConfigTime to 0x10, which will set time reference
for SaveConfigTime is 250 ns. The time reference for SaveConfigTime
is 40 ns by default.
Signed-off-by: fengbaopeng <fengbaopeng@hisilicon.com>
=> drivers:ufs: fix hynix ufs bug with quirk on hi36xx SoC

make_helpers/build_macros.mk
This makes incremental builds work when the only change is to a
definition in a makefile.
Fixes arm-software/tf-issues#551
Signed-off-by: Stephen Warren <swarren@nvidia.com>
=> Make all build results depend on all makefiles

bl1/aarch64/bl1_exceptions.S, plat/rockchip/rk3328/drivers/pmu/pmu.c, services/std_svc/spm/secure_partition_setup.c
After executing a TLBI a DSB is needed to ensure completion of the TLBI.
rk3328: The MMU is allowed to load TLB entries for as long as it is enabled. Because of this, the correct place to execute a TLBI is right after disabling the MMU.
@TonyXie06, @Caesar-github, could you explain why this TLBI is needed in the first place?
=> Ensure the correct execution of TLBI instructions

plat/arm/board/fvp/platform.mk
This patch restricts building the dynamic config DTBs to the Unix
build environment as the Device Tree compiler may not be available
on other build environments.
Change-Id: Ie690e80010a174300e966240fd977b37561156e0
=> FVP: restrict dynamic config to Unix build environment

plat/arm/board/juno/platform.mk
The SCP binaries provided in the 17.10 Linaro release (and onwards)
have migrated to the SCMI/SDS protocols. Therefore, the ARM TF should
now use the corresponding drivers by default.
This patch changes the default value of the CSS_USE_SCMI_SDS_DRIVER
build option to 1 for Juno.
=> Select SCMI/SDS drivers by default on Juno

make_helpers/build_macros.mk
Seems to have unintended side-effects on the build system such as
rebuilding certain parts of TF even though nothing has changed.
This reverts commit c6f651f9a3322857c8e1f8250274a0984c024283.
Change-Id: I1472e6c630cb6371ec629b7d97a5748d9a6fd096
=> Revert "Make all build results depend on all makefiles"

plat/arm/board/fvp/include/platform_def.h
This was correct according to the model specifications , but it seems
that FVP doesn't implement it. It is safer to use the size exposed by
the DTB which is currently used by Linux.
Change-Id: I9aabe3284a50ec2a36ed94966eb7e4ddf37cec3b
=> Fix FVP DRAM2 size

bl32/sp_min/sp_min.mk, include/plat/arm/common/plat_arm.h, plat/arm/board/fvp/sp_min/fvp_sp_min_setup.c, plat/arm/common/sp_min/arm_sp_min_setup.c, plat/common/aarch32/plat_common.c, plat/common/aarch32/plat_sp_min_common.c
This patch removes default platform implementations of sp_min
platform APIs from plat/common/aarch32/plat_common.c. The APIs
are now implemented in `plat_sp_min_common.c` file within the
same folder.
The ARM platform layer had a weak definition of sp_min_platform_setup2()
which conflicted with the weak definition in the common file. Hence this
patch fixes that by introducing a `plat_arm_` version of the API thus
allowing individual boards within ARM platforms to override it if they
wish to.
Fixes ARM-Software/tf-issues#559
Change-Id: I11a74ecae8191878ccc7ea03f12bdd5ae88faba5
=> Remove sp_min functions from plat_common.c

plat/qemu/include/platform_def.h
The register address range of UART1 (crash console) are outside the
address ranges mapped for MMIO, resulting to an MMU abort when the
device registers are accessed.
Increase the size of DEVICE1 memory to include the range of UART1.
Fixes ARM-software/tf-issues#560
=> qemu: Accessing UART1 causes a data abort

common/desc_image_load.c
This patch modifies the common utility function
`populate_next_bl_params_config()` to only modify the entrypoint arguments
to an executable image only if they are not initialized earlier.
This issue was detected while testing Optee on ARM platforms which needed
the current arguments to be preserved in the absence of corresponding
config files.
Change-Id: I1e3fb4be8176fc173959e72442396dd33a99a316
Signed-off-by: Amit Daniel Kachhap <amit.kachhap@arm.com>
=> Dynamic cfg: Do not populate args if already initialized

bl2/aarch32/bl2_el3_entrypoint.S
When using BL2_EL3, we need to ensure that lr_svc is
properly given to bl32 as it was previously made by bl1.
Fixes ARM-Software/tf-issues#562
Signed-off-by: Lionel Debieve <lionel.debieve@st.com>
=> bl2-el3: Fix bl32 lr_svc used for bl33 entry address

plat/arm/board/fvp/fvp_common.c
The FVP platform port for SP_MIN (BL32) didn't map the flash memory
in BL32 for storing the mem_protect enable state information leading
to synchronous exception. The patch fixes it by adding the region to
the BL32 mmap tables.
Change-Id: I37eec83c3e1ea43d1b5504d3683eebc32a57eadf
=> FVP AArch32: Fix flash access in BL32 for mem_protect

docs/firmware-design.rst, docs/porting-guide.rst, docs/user-guide.rst
This patch updates the `firmware-design.rst` document for
changes in ARM-TF for supporting dynamic configuration features
as presented in `Secure Firmware BoF SFO'17`[1].
The patch also updates the user-guide for 2 build options for FVP
pertaining to dynamic config.
[1] https://www.slideshare.net/linaroorg/bof-device-tree-and-secure-firmware-bof-sfo17310
Change-Id: Ic099cf41e7f1a98718c39854e6286d884011d445
=> Docs: Update design guide for dynamic config

docs/user-guide.rst
Following Out of Box testing for v1.5 release:
Update host OS version to Ubuntu 16.04
Clarify configuration files needed for checkpatch
Add note on using Linaro precompiled binaries
Change-Id: Ia4ae61e01128ddff1a288972ddf84b79370fa52c
=> Update user guide

readme.rst
Change-Id: Id9bd0c20a5af4f41269a51a675018dcc59e93f6c
=> Update readme.rst for v1.5 release

make_helpers/plat_helpers.mk, tools/cert_create/Makefile
Since we use "?=" to set PLATFORM_ROOT, it is better to change the
name to be more special, or else it may override by some environment
variables, such as in some CI build environments.
Signed-off-by: Heyi Guo <heyi.guo@linaro.org>
=> Change PLATFORM_ROOT to TF_PLATFORM_ROOT

make_helpers/build_macros.mk
This prevents the build system from continually rebuilding random parts
of the source tree due to timestamps on generated dependency makefiles.
Continues work on arm-software/tf-issues#551
Signed-off-by: Stephen Warren <swarren@nvidia.com>
=> Don't make build results depend on dependency files

plat/arm/board/fvp/aarch64/fvp_helpers.S
x3 will be assigned by the folloing instructions.
So the first instruction is not needed any more.
old method:
(ClusterId * FVP_MAX_CPUS_PER_CLUSTER)
\+ (CPUId * FVP_MAX_PE_PER_CPU)
\+ ThreadId
it should be
(ClusterId * FVP_MAX_CPUS_PER_CLUSTER) * FVP_MAX_PE_PER_CPU
\+ (CPUId * FVP_MAX_PE_PER_CPU)
\+ ThreadId
So new method will be
(ClusterId * FVP_MAX_CPUS_PER_CLUSTER + CPUId) * FVP_MAX_PE_PER_CPU + ThreadId
Signed-off-by: Wang Feng <feng_feng.wang@spreadtrum.com>
=> FVP: change the method for translating MPIDR values to a linear indices

drivers/arm/pl011/aarch64/pl011_console.S, plat/qemu/aarch64/plat_helpers.S, plat/qemu/platform.mk, plat/qemu/qemu_bl1_setup.c, plat/qemu/qemu_bl2_setup.c, plat/qemu/qemu_bl31_setup.c, plat/qemu/qemu_console.c, plat/qemu/qemu_private.h
Hi,
I moved all console initialization to C, as I found it cleaner than the way recommended in the Porting Guide, ie
```
.section .data.crash_console      /* Reserve space for console structure */
crash_console:
.zero 6 * 8                       /* console_16550_t has 6 8-byte words */
```
=> qemu: Support MULTI_CONSOLE_API

services/spd/trusty/trusty.c
This patch fixes the sanity check on the non-secure entrypoint value
returned by bl31_plat_get_next_image_ep_info(). This issue has been
reported by Coverity Scan Online:
CID 264893 (#1 of 1): Dereference null return value (NULL_RETURNS)
Dereferencing a null pointer ns_ep_info.
=> Trusty: Fix sanity check on NS entry point

Makefile
Include stack_protector's makefile after including platform.mk
to allow platforms override ENABLE_STACK_PROTECTOR
Fixes ARM-software/tf-issues#567
=> Platforms cannot override ENABLE_STACK_PROTECTOR

plat/hisilicon/hikey/aarch64/hikey_common.c, plat/hisilicon/hikey/aarch64/hikey_helpers.S, plat/hisilicon/hikey/hikey_bl1_setup.c, plat/hisilicon/hikey/hikey_bl2_mem_params_desc.c, plat/hisilicon/hikey/hikey_bl2_setup.c, plat/hisilicon/hikey/hikey_bl31_setup.c, plat/hisilicon/hikey/hikey_pm.c, plat/hisilicon/hikey/include/hikey_def.h, plat/hisilicon/hikey/include/hikey_layout.h, plat/hisilicon/hikey/include/platform_def.h
Boot Memory Layout is specific for a platform, but should not be mixed up with other platform specific attributes. A separate file is much cleaner and better to compare with other platforms. Take a look at plat/poplar where it is done the same way.
hikey_def.h and hikey_private.h should also be in the include folder.
=> plat/hikey: split boot memory layout to dedicated file

include/drivers/console.h, plat/qemu/platform.mk, plat/qemu/qemu_console.c
Add crash_console_init declaration to console.h
Only enable MULTI_CONSOLE_API for AArch64
Fixes ARM-software/tf-issues#571
=> qemu: MULTI_CONSOLE_API=0 causes build error

lib/psci/psci_stat.c
Initializes each element of the last_cpu_in_non_cpu_pd array in PSCI
stat implementation to -1, the reset value. This satisfies MISRA rule
9.3.
Previously, only the first element of the array was initialized to -1.
Change-Id: I666c71e6c073710c67c6d24c07a219b1feb5b773
Signed-off-by: Jonathan Wright <jonathan.wright@arm.com>
=> psci: initialize array fully to comply with MISRA

bl1/bl1_private.h, common/runtime_svc.c, drivers/auth/img_parser_mod.c, include/common/bl_common.h, include/common/runtime_svc.h, include/lib/utils_def.h, include/plat/common/common_def.h, include/services/secure_partition.h, lib/locks/bakery/bakery_lock_normal.c, lib/pmf/pmf_main.c, plat/hisilicon/hikey/hikey_bl1_setup.c, plat/hisilicon/hikey960/hikey960_bl1_setup.c, plat/hisilicon/poplar/bl1_plat_setup.c, plat/mediatek/mt6795/bl31_plat_setup.c, plat/mediatek/mt8173/bl31_plat_setup.c, plat/nvidia/tegra/common/tegra_bl31_setup.c, plat/rockchip/common/bl31_plat_setup.c, services/std_svc/spm/spm_shim_private.h
Void pointers have been used to access linker symbols, by declaring an
extern pointer, then taking the address of it. This limits symbols
values to aligned pointer values. To remove this restriction an
IMPORT_SYM macro has been introduced, which declares it as a char
pointer and casts it to the required type.
Change-Id: I89877fc3b13ed311817bb8ba79d4872b89bfd3b0
=> Clean usage of void pointers to access symbols

docs/plat/rpi3.rst, drivers/ti/uart/aarch64/16550_console.S, plat/rpi3/aarch64/plat_helpers.S, plat/rpi3/platform.mk, plat/rpi3/rpi3_bl1_setup.c, plat/rpi3/rpi3_bl2_setup.c, plat/rpi3/rpi3_bl31_setup.c, plat/rpi3/rpi3_common.c, plat/rpi3/rpi3_private.h
- Migrate to the new multi console API.
- The flush API was missing in the 16550 console driver. The placeholder has been replaced by an actual implementation.
=> rpi3: Migrate to the multi console API

plat/hisilicon/hikey960/hikey960_pm.c
If system is still accessing storage device, reboot operation
may cause data broken. So add the flush and delay operation
before system reset.
=> hikey960: add delay before reset

plat/qemu/include/platform_def.h, plat/qemu/platform.mk, plat/qemu/qemu_stack_protector.c
Allow qemu users to enable stack protection. Since the virt platform
does not provide an RNG, use a basic, timer-based, canary generation,
similarly to FVP.
Increase SRAM size and BL2 size to fit images when stack protection is
enabled.
Notice that stack protection is not enabled by default in qemu.
Fixes ARM-software/tf-issues#568
=> qemu: Add support for stack canary protection

drivers/arm/gic/common/gic_common.c, drivers/arm/gic/v3/gicv3_helpers.c, include/drivers/arm/gic_common.h
- Interrupt configuration is a 2-bit field, so the field shift has to
be double that of the bit number.
- Interrupt configuration (level- or edge-trigger) is specified in the
MSB of the field, not LSB.
Fixes applied to both GICv2 and GICv3 drivers.
Fixes ARM-software/tf-issues#570
Change-Id: Ia6ae6ed9ba9fb0e3eb0f921a833af48e365ba359
=> GIC: Fix interrupt setting interrupt configuration

include/drivers/console.h, plat/qemu/aarch64/plat_helpers.S, plat/qemu/qemu_console.c, plat/qemu/qemu_private.h
Use the console_pl011_core_* functions directly in the crash console
callbacks.
This bypasses the MULTI_CONSOLE_API for the crash console (UART1), but
allows using the crash console before the C runtime has been initialized
(eg to call ASM_ASSERT). This retains backwards compatibilty with respect
to functionality when the old API is used.
Use the MULTI_CONSOLE_API to register UART0 as the boot and runtime
console.
Fixes ARM-software/tf-issues#572
=> qemu: don't use C functions for the crash console callbacks

docs/cpu-specific-build-macros.rst, services/arm_arch_svc/arm_arch_svc_setup.c
Only return -1 if the workaround for CVE-2017-5715 is not compiled in.
Change-Id: I1bd07c57d22b4a13cf51b35be141a1f1ffb065ff
=> Fixup SMCCC_FEATURES return value for SMCCC_ARCH_WORKAROUND_1

Makefile, bl2/bl2_el3.ld.S, bl2/bl2_private.h, docs/porting-guide.rst, docs/user-guide.rst, include/common/aarch64/el3_common_macros.S, include/plat/common/common_def.h, make_helpers/defaults.mk
When bl2 runs in el3, it will be the first TF image to
be executed, so in some cases bl2 will be in ROM just
like bl1. This patch enable bl2 in ROM in case of it
runs in el3.
Signed-off-by: Jiafei Pan <Jiafei.Pan@nxp.com>
=> Add support for BL2 in XIP memory

drivers/arm/tzc/tzc_dmc500.c, include/drivers/arm/tzc_dmc500.h
Some low end platforms using DMC500 memory controller do not have
CCI(Cache Coherent Interconnect) interface and only have non-coherent
system interface support. Hence this patch makes the system interface
count configurable from the platforms.
Change-Id: I6d54c90eb72fd18026c6470c1f7fd26c59dc4b9a
Signed-off-by: Amit Daniel Kachhap <amit.kachhap@arm.com>
=> DMC500: Add platform support to set system interface count

plat/arm/board/fvp/aarch32/fvp_helpers.S
The current AArch32 version of plat_arm_calc_core_pos uses an incorrect
algorithm to calculate the linear position of a core / PE from its
MPIDR.
This patch corrects the algorithm to:
(ClusterId * FVP_MAX_CPUS_PER_CLUSTER) * FVP_MAX_PE_PER_CPU
+ (CPUId * FVP_MAX_PE_PER_CPU)
+ ThreadId
which supports cores where there are more than 1 PE per CPU.
NOTE: the AArch64 version was fixed in 39b21d1
Change-Id: I72aea89d8f72f8b1fef54e2177a0fa6fef0f5513
=> FVP: Fix function for translating MPIDR to linear index

plat/arm/css/common/css_common.mk, plat/arm/css/common/sp_min/css_sp_min.mk, plat/arm/css/drivers/mhu/css_mhu.c, plat/arm/css/drivers/mhu/css_mhu.h, plat/arm/css/drivers/mhu/css_mhu_doorbell.c, plat/arm/css/drivers/mhu/css_mhu_doorbell.h, plat/arm/css/drivers/scmi/scmi.h, plat/arm/css/drivers/scmi/scmi_common.c, plat/arm/css/drivers/scmi/scmi_private.h, plat/arm/css/drivers/scp/css_bom_bootloader.c, plat/arm/css/drivers/scp/css_pm_scmi.c, plat/arm/css/drivers/scpi/css_scpi.c
Currently the SCMI driver supports MHUv1, but Arm platforms may have
varied versions of MHU driver, with MHUv2 controllers being in the
latest Arm platforms.
This patch updates the SCMI driver to support MHUv2, specifically that
the sender must send the wake-up to the receiver before initiating any
data transfer.
Also, the existing mhu driver files, css_mhu.c and css_mhu.h, have been
moved from the scpi directory to a new directory, css/drivers/mhu.
Change-Id: I9b46b492a3e1d9e26db12d83a9773958a8c8402f
Signed-off-by: Samarth Parikh <samarth.parikh@arm.com>
=> plat/arm: Add MHUv2 support to SCMI driver

plat/arm/css/sgi/sgi-common.mk
SGI-575 platform is based on Cortex-A75 processor which has its MT bit
in the MPIDR register set to '1'. So the Arm platform layer code has
to be made aware of this.
Signed-off-by: Sudipto Paul <sudipto.paul@arm.com>
=> css/sgi575: enable ARM_PLAT_MT flag

plat/rockchip/rk3399/drivers/dram/suspend.c
This fixes an off by 576x bug the the sram_udelay code. The wrong
value was multipled by the system ticks per mhz value (which is 24),
so we delayed for 1/576th of the requested time.
Signed-off-by: Derek Basehore <dbasehore@chromium.org>
=> rockchip/rk3399: Fix sram_udelay

Makefile, bl31/aarch64/runtime_exceptions.S, common/runtime_svc.c, docs/user-guide.rst, include/common/runtime_svc.h, include/lib/smccc.h, include/lib/smccc_v1.h, include/lib/smccc_v2.h, make_helpers/defaults.mk
Due to differences in the bitfields of the SMC IDs, it is not possible to support SMCCC 1.X and 2.0 at the same time.
The behaviour of `SMCCC_MAJOR_VERSION` has changed. Now, it is a build option that specifies the major version of the SMCCC that the Trusted Firmware supports. The only two allowed values are 1 and 2, and it defaults to 1. The value of `SMCCC_MINOR_VERSION` is derived from it.
Note: Support for SMCCC v2.0 is an experimental feature to enable prototyping of secure partition specifications. Support for this convention is disabled by default and could be removed without notice.
=> Add support for the SMC Calling Convention 2.0

include/lib/xlat_tables/xlat_tables_defs.h, lib/xlat_tables/xlat_tables_common.c, lib/xlat_tables_v2/xlat_tables_internal.c
According to the ARMv8 ARM issue C.a:
AP[1] is valid only for stage 1 of a translation regime that can
support two VA ranges. It is RES 1 when stage 1 translations can
support only one VA range.
This means that, even though this bit is ignored, it should be set to 1 in the EL3 and EL2 translation regimes.
For translation regimes consisting on EL0 and a higher regime this bit selects between control at EL0 or at the higher Exception level. The regimes that support two VA ranges are EL1&0 and EL2&0 (the later one is only available since ARMv8.1).
This fix has to be applied to both versions of the translation tables library.
=> xlat: Set AP[1] to 1 when it is RES1

plat/hisilicon/poplar/platform.mk
Fixes: c939d13a ("Build: rename FIP_ADD_IMG to TOOL_ADD_IMG")
=> poplar: rename FIP_ADD_IMG to TOOL_ADD_IMG

fdts/fvp-base-gicv3-psci-common.dtsi, fdts/fvp-foundation-motherboard.dtsi, fdts/rtsm_ve-motherboard-aarch32.dtsi, fdts/rtsm_ve-motherboard.dtsi
DTC generates warnings when unit names begin with 0, or
when a node containing a reg or range property doesn't have a unit name
in the node name. This patch fixes those cases.
Change-Id: If24ec68ef3034fb3fcefb96c5625c47a0bbd8474
=> Remove dtc warnings

bl2/bl2_main.c
If BL2_AT_EL3 is enabled, bl2_run_next_image is called at the end of BL2.
This function calls disable_mmu_icache_secure.
It is then useless to call it in bl2_main in that case.
fixes arm-software/tf-issues#582
=> BL2_AT_EL3: do not try to disable MMU twice on AARCH32

tools/cert_create/Makefile
Spurious whitespace existed in the BINARY shell variable which meant
the cert_tool executable was not being removed on 'make realclean'.
Change-Id: Ibfd2fd17889514f6613e33c6df58d53b9232ec14
Signed-off-by: Jonathan Wright <jonathan.wright@arm.com>
=> Fix the makefile to remove the cert_create executable on 'make realclean'

.checkpatch.conf
The Linux kernel expects the SPDX license tag in the first line of each source code file in a comment.
In the context of the Linux kernel repository this makes sense because they have many different license headers across their codebase. Moving the tag to the first line of the source code files makes it easier for analyzers to see the license of each file.
In the Trusted Firmware, we control all headers and make sure that they follow the same pattern, so this is not needed.
Fixes: https://github.com/ARM-software/tf-issues/issues/581
=> checkpatch: Ignore SPDX_LICENSE_TAG

Makefile
The C standards specify that this macro is used to
disable asserts but, in our code, the assert macro
is controlled with ENABLE_ASSERTIONS. Having this macro
here creates confusion about the behaviour of assert.
Change-Id: Iab8689a14dc2b8790729857d56585ce43c0c4f51
=> Remove the unused macro NDEBUG

lib/xlat_tables/aarch64/xlat_tables.c, lib/xlat_tables_v2/aarch64/xlat_tables_arch.c
In AArch64, the field ID_AA64MMFR0_EL1.PARange has a different set of allowed values depending on the architecture version.
Previously, we only compiled the Trusted Firmware with the values that were allowed by the architecture. However, given that this field is read-only, it is easier to compile the code with all values regardless of the target architecture.
=> xlat: Have all values of PARange for 8.x architectures

tools/fiptool/fiptool.c
Free desc->image->buffer before freeing desc->image. We make sure that
the desc->image is non-null before attempting this.
Change-Id: I35c5674629a41d7cf1a78b7b41ca4b930d0fb688
Signed-off-by: Jonathan Wright <jonathan.wright@arm.com>
=> Fix memory leaks in fiptool

include/lib/xlat_tables/xlat_tables_arch.h, lib/xlat_tables_v2/xlat_tables_internal.c
Fix some warnings generated by clang compiling aarch32 code.
=> Compiler warnings

drivers/console/aarch64/multi_console.S, include/drivers/console.h, include/plat/arm/board/common/board_arm_def.h, include/plat/arm/common/plat_arm.h, plat/arm/common/aarch64/arm_helpers.S, plat/arm/common/arm_bl1_setup.c, plat/arm/common/arm_bl2_el3_setup.c, plat/arm/common/arm_bl2_setup.c, plat/arm/common/arm_bl2u_setup.c, plat/arm/common/arm_bl31_setup.c, plat/arm/common/arm_common.mk, plat/arm/common/arm_console.c, plat/arm/common/arm_pm.c, plat/arm/common/tsp/arm_tsp_setup.c
In AArch64 builds, Arm platforms have moved to the multi console driver for regular operation. They still use the raw console driver functions for the crash console.
Also, fix an issue when registering the same console struct twice.
=> Arm platforms: Migrate to multi console driver

lib/el3_runtime/aarch64/context_mgmt.c
The context management library initialises the CPU context for the
secure/non-secure worlds to zero. This leads to zeros being stored
to the actual registers when we restore the CPU context, during a
world switch. Denver CPUs dont expect zero to be written to the
implementation defined, actlr_el1 register, at any point of time.
Writing a zero to some fields of this register, results in an
UNDEFINED exception.
This patch bases the context actlr_el1 value on the actual hardware
register, to maintain parity with the expected settings
Change-Id: I1c806d7ff12daa7fd1e5c72825494b81454948f2
=> lib: el3_runtime: initialise actlr_el1 to hardware defaults

docs/user-guide.rst, plat/arm/common/arm_bl31_setup.c, plat/arm/common/arm_common.mk
Normally, BL33 needs to contain a boot loader like U-Boot or UEFI that eventually gives control to the OS. However, in some cases, this boot sequence may be too slow. For example, when doing tests in a cycle-accurate emulator, the user may only be interested in the interaction between the Trusted Firmware and the OS, not in the boot process itself.
The new option `ARM_LINUX_KERNEL_AS_BL33` allows BL33 to contain the Linux kernel image by changing the value of registers x0-x3 to the values expected by the kernel. This option requires the device tree blob (DTB) to be present in memory. Its address must be specified in the newly introduced `ARM_PRELOADED_DTB_BASE` build option. For now, it only supports AArch64 kernels.
This option is only available when `RESET_TO_BL31=1`. For this reason …
=> plat/arm: Introduce ARM_LINUX_KERNEL_AS_BL33 build option

docs/porting-guide.rst
In the porting guide, fix the function name and the argument type to
reflect the code.
=> Fix doc for bl31_plat_get_next_image_ep_info()

services/std_svc/spm/secure_partition_setup.c
This allows secure partitions to access these registers. This is
needed in some cases. For example, it has been reported that in order
to implement secure storage services, a secure partition needs to
encrypt/decrypt some authentication variables, which requires FP/SIMD
support.
Note that SPM will not do any saving/restoring of these registers on
behalf of the SP. This falls under the SP's responsibility.
Also note that if the SP gets preempted, it might not get a chance to
save/restore FP/SIMD registers first. This patch does not address this
problem. It only serves as a temporary solution to unblock development
on the secure partition side.
=> SPM: Do not trap S-EL0 access to SVE/SIMD/FP regs

drivers/console/aarch64/multi_console.S, include/drivers/console.h
Change type of scope from unsigned int to match the type of flags in console_t
=> Ensure read and write of flags defined in the console struct are 32 bit

lib/cpus/aarch64/wa_cve_2017_5715_mmu.S
When SMCCC_ARCH_WORKAROUND_1 is invoked from a lower EL running in
AArch32 state, ensure that the SMC call will take a shortcut in EL3.
This minimizes the time it takes to apply the mitigation in EL3.
When lower ELs run in AArch32, it is preferred that they execute the
`BPIALL` instruction to invalidate the BTB.  However, on some cores
the `BPIALL` instruction may be a no-op and thus would benefit from
making the SMCCC_ARCH_WORKAROUND_1 call go through the fast path.
Change-Id: Ia38abd92efe2c4b4a8efa7b70f260e43c5bda8a5
=> Fast path SMCCC_ARCH_WORKAROUND_1 calls from AArch32

docs/firmware-design.rst, include/plat/arm/common/arm_def.h
For the BL2_AT_EL3 configuration, move BL2 higher up to make more
space for BL31.  Adjust the BL31 limit to be up to BL2 base.  This is
because BL2 is always resident for the BL2_AT_EL3 configuration and
thus we cannot overlay it with BL31.
Change-Id: I71e89863ed48f5159e8b619f49c7c73b253397aa
=> Adjust BL2_AT_EL3 memory layout

lib/xlat_tables_v2/xlat_tables_internal.c
Rule 21.15: The pointer arguments to the Standard Library functions
memcpy, memmove and memcmp shall be pointers to qualified or unqualified
versions of compatible types.
Basically that means that both pointer arguments must be of the same
type. However, even if the pointers passed as arguments to the above
functions are of the same type, Coverity still thinks it's a violation
if we do pointer arithmetics directly at the function call. Thus the
pointer arithmetic operations were moved outside of the function
argument.
First detected on the following configuration
make PLAT=fvp LOG_LEVEL=50
=> MISRA rule 21.15 fix

drivers/ti/uart/aarch64/16550_console.S, include/drivers/ti/uart/uart_16550.h
On TI platforms the UART is disabled by default and must be explicitly
enabled using the MDR1 register.
NOTE: The original definition of
http://www.ti.com/lit/ds/symlink/pc16550d.pdf has no MDR register, but
many TI SoCs implementing 16550 do have a quirky MDR register
implemented. So, this should be enabled with TI_16550_MDR_QUIRK
NOTE: In such implementation, the CSR register does not exist.
=> drivers: ti: uart: Add TI specific 16550 initialization

plat/rockchip/rk3399/drivers/dram/dfs.h, plat/rockchip/rk3399/plat_sip_calls.c
The stdint header was introduced to rk3399's plat_sip_calls.c in order
to fix missing stdint definitions. However, ordering headers
alphabetically caused the fix to be ineffective, as stint was then
included after the offending header file (dfs.h).
Move the stdint include to that header to properly fix the issue.
Change-Id: Ieaad37a7932786971488ab58fc5b169bfa79e197
Signed-off-by: Paul Kocialkowski <contact@paulk.fr>
=> rockchip: Move stdint header to the offending header file

docs/user-guide.rst
Changed the ordering of the log levels in the documentation to
mate the code
Change-Id: Ief1930b73d833fdf675b039c98046591c0c264c1
=> Correct ordering of log levels in documentation

docs/plat/rpi3.rst
The order of the arguments of memmap was swapped. The old command was reserving 256 MiB from the 16 MiB barrier, it should be reserving only 16 MiB at the 256 MiB barrier.
It worked because the memory used by the Trusted Firmware was reserved anyway.
=> rpi3: Fix kernel boot documentation

services/std_svc/spm/spm_main.c, services/std_svc/spm/spm_private.h
Only use synchronous calls to enter the Secure Partition in order to simplify the SMC handling code.
=> SPM: Refactor entry and exit of the SP

lib/xlat_tables_v2/xlat_tables_internal.c
The issue can occur if end_va is equal to the max architecture address,
and when mm_cursor point to the last entry of mmap_region_t table: {0}.
The first line of the while will then be true, e.g. on AARCH32, we have:
mm_cursor->base_va (=0) + mm_cursor->size (=0) - 1 == end_va (=0xFFFFFFFF)
And the mm_cursor->size = 0 will be lesser than mm->size
A check on mm_cursor->size != 0 should be done as in the previous while,
to avoid such kind of infinite loop.
fixes arm-software/tf-issues#594
=> xlat_v2: add a check on mm_cursor->size to avoid infinite loop

include/drivers/console.h, include/plat/arm/board/common/board_arm_def.h, include/plat/arm/common/plat_arm.h, plat/arm/common/aarch64/arm_helpers.S, plat/arm/common/arm_bl1_setup.c, plat/arm/common/arm_bl2_el3_setup.c, plat/arm/common/arm_bl2_setup.c, plat/arm/common/arm_bl2u_setup.c, plat/arm/common/arm_bl31_setup.c, plat/arm/common/arm_common.mk, plat/arm/common/arm_console.c, plat/arm/common/arm_pm.c, plat/arm/common/tsp/arm_tsp_setup.c, plat/common/plat_bl1_common.c
The old API is deprecated and will eventually be removed.
Arm platforms now use the multi console driver for boot and runtime consoles. However, the crash console uses the direct console API because it doesn't need any memory access to work. This makes it more robust during crashes.
The AArch32 port of the Trusted Firmware doesn't support this new API yet, so it is only enabled in AArch64 builds. Because of this, the common code must maintain compatibility with both systems. SP_MIN doesn't have to be updated because it's only used in AArch32 builds. The TSP is only used in AArch64, so it only needs to support the new API without keeping support for the old one.
Special care must be taken because of PSCI_SYSTEM_SUSPEND. In Juno, this causes the UARTs to reset (except for the one used by …
=>  plat/arm: Migrate AArch64 port to the multi console driver

plat/arm/common/arm_dyn_cfg.c
In Arm platforms, when using dynamic configuration, the necessary
parameters are made available as a DTB. The DTB is loaded by BL1 and,
later on, is parsed by BL1, BL2 or even both, depending on when
information from the DTB is needed.
When the DTB is going to be parsed, it must be validated first, to
ensure that it is properly structured. If an invalid DTB is detected
then:
- BL1 prints a diagnostic but allows execution to continue,
- BL2 prints a diagnostic and panics.
Now the behaviour of BL1 is changed so for it also to panic. Thus, the
behaviour of BL1 and BL2 is now similar.
Keep in mind that if BL1 only loads the DTB but it doesn't need to
read/write it, then it doesn't validate it. The validation is done only
when the DTB is actually going to be accessed.
Change-Id: …
=> Panic in BL1 when TB_FW_CONFIG is invalid

docs/plat/rpi3.rst, plat/rpi3/aarch64/rpi3_bl2_mem_params_desc.c, plat/rpi3/include/platform_def.h, plat/rpi3/platform.mk, plat/rpi3/rpi3_bl2_setup.c, plat/rpi3/rpi3_common.c, plat/rpi3/rpi3_io_storage.c
In order to load optee, we need to set SPD=opteed.
plat_interrupt_type_to_line() is a needed function for SPD.
Signed-off-by: Ying-Chun Liu (PaulLiu) <paulliu@debian.org>
@igoropaniuk Please help reviewing this patch. Thanks.
=> rpi3: BL32 optee support

Makefile, make_helpers/build_macros.mk
This is an add-on feature that allows processing
device tree with external includes.
fixes arm-software/tf-issues#595
Signed-off-by: Lionel Debieve <lionel.debieve@st.com>
=> Build: add cpp build processing for dtb

lib/xlat_tables_v2/xlat_tables_internal.c
The XN, PXN and UXN bits are part of the upper attributes, not the lower attributes.
=> xlat_v2: Fix descriptor debug print

include/services/spm_svc.h, services/std_svc/spm/spm_main.c
It may be needed to enter the Secure Partition through other means than an MM_COMMUNICATE SMC. This patch enables this behaviour by extracting the necessary code from mm_communicate() and allowing other parts of the code to use it.
=> SPM: Allow entering the SP without needing a SMC

docs/xlat-tables-lib-v2-design.rst, include/lib/xlat_tables/xlat_tables.h, include/lib/xlat_tables/xlat_tables_v2.h, lib/utils/mem_region.c, lib/xlat_tables/xlat_tables_common.c, lib/xlat_tables_v2/xlat_tables_internal.c, lib/xlat_tables_v2/xlat_tables_private.h
The values defined in this type are used in logical operations, which goes against MISRA Rule 10.1: "Operands shall not be of an inappropriate essential type".
Now, `unsigned int` is used instead. This also allows us to move the dynamic mapping bit from 30 to 31. It was an undefined behaviour in the past because an enum is signed by default, and bit 31 corresponds to the sign bit. It is undefined behaviour to modify the sign bit. Now, bit 31 is free to use as it was originally meant to be.
mmap_attr_t is now defined as an `unsigned int` for backwards compatibility.
=> xlat: Remove mmap_attr_t enum type

services/std_svc/sdei/sdei_intr_mgmt.c
The Commit cdb6ac94ecb3c4caa784cd4d7580cf6252146196 introduced a bug
because of which the SDEI dispatcher wrongly panic when an SDEI event
dispatched earlier as a result of interrupt. This patch fixes the check
for a bound interrupt.
Change-Id: If55c8f0422ff781731248bbbc9c1b59fa0d3c4b0
=> SDEI: Fix dispatch bug

docs/porting-guide.rst, docs/user-guide.rst
In the porting guide, there are blue boxes that describe the argument
types and the return type of each function. A small typo caused some of
these boxes not being properly rendered.
In the user guide, small typos were fixed that caused random text being
unintentionally rendered as bold.  Also, a slight rewording was done in
the section describing the DYN_DISABLE_AUTH flag.
Change-Id: I57303ca609436a82162fa9b42c06b0d5a63da6df
=> Fix typos in documentation

include/plat/arm/board/common/board_arm_def.h, plat/arm/board/fvp/fvp_def.h, plat/arm/board/juno/juno_def.h, plat/arm/css/sgi/include/platform_def.h
Having these definitions in board_arm_def.h forces to
all the arm platforms to use the same definition for
PLAT_ARM_MEM_PROT_ADDR.
This macro also enables the mem-protect mechanism,
which means that all the arm platform has enabled
mem-protect and they cannot get rid of it.
Change-Id: Id29d2c51cbe6edc15f010a9f5a20c42266c48a08
=> Move mem-protect definitions to board specific files

plat/arm/board/fvp/fdts/fvp_tb_fw_config.dts
Set the ability to dynamically disable Trusted Boot Board
authentication to be off by default
Change-Id: Ibd2aa179179f7d9b0e7731c6e450f200a8c67529
=> Set FVP DYN_DISABLE_AUTH authentication default to 0

maintainers.rst
The previous format was not very practical and hard to parse by scripts. The current format is easier as it uses more tokens that can be identified by scripts, while maintaining a reasonably good result when it is rendered.
Some maintainers maintain more than one subsystem but they were all part of the same entry. In cases like this the entry has been split into two to clarify what file belongs to which subsystem.
The list of maintainers of the Trusted Firmware has been updated.
=> maintainers: Modify format of file

tools/cert_create/src/main.c
Print_help was used in different contexts and returning no
error in that function was hiding the error when incorrect
options were used.
Change-Id: Ic3f71748be7ff8440c9d54810b986e9f177f4439
=> make_cert: return error when invalid options are used

docs/plat/allwinner.rst, plat/allwinner/common/include/platform_def.h, plat/allwinner/common/sunxi_bl31_setup.c
This pull request is an attempt to run Trusted OS (OP-TEE OS being one of them) along
side BL31 image.
This is the second version of PR  #1431, @Andre-ARM can you please have a look.
Trusted OS image can be fetched from below link:
https://github.com/Amit-Radur/Images.git
Signed-off-by: Amit Singh Tomar <amittomer25@gmail.com>
=> allwinner: Add BL32 (corresponds to Trusted OS) support

docs/xlat-tables-lib-v2-design.rst
Update documentation to reflect the current state of the library.
See: https://github.com/ARM-software/arm-trusted-firmware/pull/1459.
=> xlat v2: Update documentation

docs/plat/rpi3.rst, plat/rpi3/include/platform_def.h, plat/rpi3/platform.mk, plat/rpi3/rpi3_io_storage.c, plat/rpi3/rpi3_rotpk.S, plat/rpi3/rpi3_trusted_boot.c
This patch adds support for TBB to qemu. The ROTPK is generated at build
time and is included into BL1/BL2. The key and content certificates are
read over semihosting.
=> rpi3: Add support for Trusted Board Boot

tools/cert_create/Makefile
Previously build_msg.o is built by CC. It causes FTBFS when CC
is not equal to HOSTCC.
Signed-off-by: Ying-Chun Liu (PaulLiu) <paulliu@debian.org>
=> tools/cert_create: fix makefile to build build_msg.o by HOSTCC

docs/user-guide.rst
Updated the user guide with the build dependency - device-tree-compiler
Change-Id: Ia7800dae52f152b2c3a3b41f1078ab7499d2f4b6
=> Add device-tree-compiler to the list of packages

Makefile, bl1/aarch64/bl1_exceptions.S, bl1/bl1.ld.S, bl2/aarch64/bl2_el3_exceptions.S, bl2/bl2.ld.S, bl2/bl2_el3.ld.S, bl2u/bl2u.ld.S, bl31/aarch64/runtime_exceptions.S, bl31/bl31.ld.S, bl32/sp_min/sp_min.ld.S, bl32/tsp/aarch64/tsp_exceptions.S, bl32/tsp/tsp.ld.S, common/aarch64/early_exceptions.S, docs/user-guide.rst, include/common/aarch64/asm_macros.S, include/common/asm_macros_common.S, include/lib/cpus/aarch32/cpu_macros.S, include/lib/cpus/aarch64/cpu_macros.S, include/plat/arm/common/aarch64/arm_macros.S, include/plat/arm/common/arm_common.ld.S, lib/cpus/aarch64/cortex_a76.S, lib/cpus/aarch64/denver.S, lib/cpus/aarch64/wa_cve_2017_5715_bpiall.S, lib/cpus/aarch64/wa_cve_2017_5715_mmu.S, plat/mediatek/mt6795/bl31.ld.S, plat/rockchip/common/pmusram/pmu_sram_cpus_on.S, plat/rockchip/rk3399/drivers/pmu/plat_pmu_macros.S, services/std_svc/spm/aarch64/spm_shim_exceptions.S
These changes are oriented to minimize the need of using GNU tools to build TF. After this change all the major tools involved (compiler, assembler and linker) can be substituted by the  equivalent Clang tools.
=> Make TF compatible with Clang assembler and linker

docs/plat/rpi3.rst, plat/rpi3/rpi3_common.c
The Raspberry Pi 3 doesn't have secure peripherals, so all interrupts are treated as non-secure interrupts to be handled by the non-secure world.
=> rpi3: Implement simple interrupt routing

drivers/mmc/mmc.c, include/drivers/mmc.h
It is largely based on existing eMMC framework by Haojian Zhuang
(@hzhuang1).
The MMC framework supports both eMMC and SD card devices. It was
written as a new framework since breaking few eMMC framework APIs.
At card probe and after the reset to idle command (CMD0), a Send
Interface Condition Command is sent (CMD8) to distinguish between
eMMC and SD card devices. eMMC devices go through the same
sequence as in the former eMMC framework. Else the framework
uses commands dedicated to SD-cards for init or frequency switch.
A structure is created to share info with the driver. It stores:
- the MMC type (eMMC, SD or SD HC)
- the device size
- the max frequency supported by the device
- the block size: 512 for eMMC and SD-HC and read from CSD
structure for older SD-cards
Restriction to align …
=> [RFC] Add MMC framework

include/common/debug.h, plat/nvidia/tegra/common/tegra_bl31_setup.c, services/std_svc/sdei/sdei_main.c
These patches modify the debug macros (INFO, NOTICE, ...) to get the compiler to evaluate them all the time. They also fix the build issues that this uncovered.
=> Always compile debug macros

plat/hisilicon/hikey/hikey_io_storage.c, plat/hisilicon/hikey/hikey_rotpk.S, plat/hisilicon/hikey/hikey_tbbr.c, plat/hisilicon/hikey/include/hikey_layout.h, plat/hisilicon/hikey/include/platform_def.h, plat/hisilicon/hikey/platform.mk
This patch adds experimental support for TRUSTED_BOARD_BOOT to the
Hikey. This is adapted from the RPi3 and QEMU implementations.
Since the Hikey starts from BL2 the TRUSTED_BOARD_BOOT ROT begins there
too. When TRUSTED_BOARD_BOOT is defined, the BL1 build is skipped.
See the following example:
make \
PLAT=hikey \
BL33=u-boot.bin \
SCP_BL2=mcuimage.bin \
TRUSTED_BOARD_BOOT=1 \
MBEDTLS_DIR=../../mbedtls \
GENERATE_COT=1 \
all fip
--
This is a RFC because this does not work and I am having trouble debugging.
After building the `bl2.bin` and creating a `l-loader.bin` and flashing, the debug output is:
```
NOTICE:  BL2: v1.5(debug):v1.5-373-g3be75e7
NOTICE:  BL2: Built : 23:41:25, Jun 23 2018
INFO:    Using crypto library 'mbed TLS'
INFO:    BL2: Doing platform setup
INFO:    ddr3 rank1 init …
```
=> hikey: Add experimental TBB support

docs/plat/rpi3.rst, plat/rpi3/aarch64/plat_helpers.S, plat/rpi3/include/platform_def.h, plat/rpi3/platform.mk, plat/rpi3/rpi3_bl31_setup.c, plat/rpi3/rpi3_hw.h, plat/rpi3/rpi3_pm.c, plat/rpi3/rpi3_private.h, plat/rpi3/rpi3_rng.c, plat/rpi3/rpi3_stack_protector.c
- ``RESET_TO_BL31`` was broken. It doesn't make sense to keep it as this port is using BL1 and BL2 as well, so it has been removed.
- Added support for the hardware RNG. It is used for the stack protector.
- ``PSCI_CPU_ON`` was broken, but it somehow worked in some cases. It has been fixed and tested in an AArch64 Linux kernel.
- Improve support for direct boot of Linux kernel:
- Switched dtb and kernel addresses to leave more room for growth for the kernel (it only had 16 MB, and that size is easy to overflow).
- Add ``RPI3_DIRECT_LINUX_BOOT`` to support direct-to-kernel boot.
- Documentation updated to reflect the changes.
=> rpi3: PSCI and Linux boot improvements

plat/hisilicon/hikey/include/hikey_layout.h, plat/hisilicon/hikey/platform.mk
BL1 is used in recovery mode on HiKey. The TBB implementation
on HiKey is in BL2. It means that user need to build ATF BL2
with TBB and ATF BL1 with non-TBB. It's inconvenient.
So include TBB in BL1, too.
Signed-off-by: Teddy Reed <teddy@prosauce.org>
=> hikey: include TBB in BL1

plat/socionext/synquacer/platform.mk, plat/socionext/synquacer/sq_bl31_setup.c
OP-TEE loading is optional on Developerbox controlled via SCP
firmware. To check if OP-TEE is loaded or not, we use DRAM1 region
info passed by SCP firmware.
Signed-off-by: Sumit Garg <sumit.garg@linaro.org>
Reviewed-by: Daniel Thompson <daniel.thompson@linaro.org>
=> synquacer: Enable optional OP-TEE support

include/plat/arm/common/plat_arm.h, plat/arm/common/arm_pm.c
This also gets rid of MISRA violations for Rule 8.3 and 8.4.
Change-Id: I45bba011b16f90953dd4b260fcd58381f978eedc
=> Arm platforms: Fix type mismatch for arm_pm_idle_states

drivers/arm/sp805/sp805.c, include/drivers/arm/sp805.h, include/lib/xlat_tables/aarch32/xlat_tables_aarch32.h, include/lib/xlat_tables/aarch64/xlat_tables_aarch64.h, include/lib/xlat_tables/xlat_mmu_helpers.h, include/lib/xlat_tables/xlat_tables.h, include/lib/xlat_tables/xlat_tables_arch.h, include/lib/xlat_tables/xlat_tables_defs.h, include/lib/xlat_tables/xlat_tables_v2.h, include/lib/xlat_tables/xlat_tables_v2_helpers.h, lib/xlat_tables/aarch32/xlat_tables.c, lib/xlat_tables/aarch64/xlat_tables.c, lib/xlat_tables/xlat_tables_common.c, lib/xlat_tables/xlat_tables_private.h, lib/xlat_tables_v2/aarch32/xlat_tables_arch.c, lib/xlat_tables_v2/aarch64/xlat_tables_arch.c, lib/xlat_tables_v2/xlat_tables_context.c, lib/xlat_tables_v2/xlat_tables_core.c, lib/xlat_tables_v2/xlat_tables_private.h, lib/xlat_tables_v2/xlat_tables_utils.c, plat/rpi3/include/platform_def.h
Note that this PR doesn't fix all problems in the xlat tables lib, this is an initial cleanup that fixes a big number of them. It will be needed to do a more fine-grained cleanup when other parts of the code are cleaned of MISRA defects.
=> Fix MISRA defects in xlat tables lib and SP805 driver

include/drivers/console.h
Set the function pointers in the console struct and the functions
they point to to const since they only need to be defined when
the console is being initialised and should not be changed after
Change-Id: I0574307111e3ab2f13d1a4a74c3fa75532dfa4be
=> Set console function pointers to const

services/spd/trusty/generic-arm64-smcall.c
Fix the types of the arguments of trusty_generic_platform_smc()
to match the expected prototype of a runtime service handler
(see rt_svc_handle_t type).
=> Fix handler prototype in Trusty generic dispatcher

include/lib/xlat_tables/xlat_mmu_helpers.h, include/lib/xlat_tables/xlat_tables_v2_helpers.h, lib/psci/psci_main.c, lib/psci/psci_private.h, lib/xlat_tables/xlat_tables_common.c, lib/xlat_tables_v2/aarch32/xlat_tables_arch.c, lib/xlat_tables_v2/aarch64/xlat_tables_arch.c, lib/xlat_tables_v2/xlat_tables_core.c, lib/xlat_tables_v2/xlat_tables_private.h, lib/xlat_tables_v2/xlat_tables_utils.c
This is done to comply with MISRA rules about essential types.
=> xlat: psci: Use bool instead of int

include/plat/arm/common/arm_def.h, plat/arm/common/arm_bl1_setup.c, plat/arm/common/arm_bl2_el3_setup.c, plat/arm/common/arm_bl2_setup.c, plat/arm/common/arm_bl2u_setup.c, plat/arm/common/arm_bl31_setup.c, plat/arm/common/sp_min/arm_sp_min_setup.c, plat/arm/common/tsp/arm_tsp_setup.c
TF won't build since no memory region is specified
for when SEPARATE_CODE_AND_RODATA=0 it still relies on
the ARM_MAP_BL_RO_DATA region which is never defined for
this case. Create memory region combining code and RO data for
when the build flag SEPARATE_CODE_AND_RODATA=0 to fix this
Change-Id: I6c129eb0833497710cce55e76b8908ce03e0a638
=> Fix build for SEPARATE_CODE_AND_RODATA=0

drivers/arm/cci/cci.c
The functions cci_enable_snoop_dvm_reqs and cci_disable_snoop_dvm_reqs write
in the SNOOP_CTRL_REGISTER of the slave interface and it polls the status
register to be sure that the operation is finished before leaving the
functions. If the write in SNOOP_CTRL_REGISTER is reordered after the first
read in the status register then these functions can finish before
enabling/disabling snoops and DVM messages.
The CCI500 TRM specifies:
Wait for the completion of the write to the Snoop Control Register
before testing the change_pending bit.
Change-Id: Idc7685963f412be1c16bcd3c6e3cca826e2fdf38
=> cci: Wait before reading status register

include/lib/xlat_tables/xlat_tables_v2.h, lib/psci/aarch32/psci_helpers.S, lib/psci/aarch64/psci_helpers.S, lib/xlat_tables_v2/aarch32/xlat_tables_arch.c, lib/xlat_tables_v2/aarch64/xlat_tables_arch.c, lib/xlat_tables_v2/xlat_tables_context.c, lib/xlat_tables_v2/xlat_tables_core.c, lib/xlat_tables_v2/xlat_tables_private.h, lib/xlat_tables_v2/xlat_tables_utils.c, services/std_svc/spm/sp_xlat.c
- The functions to get and change attributes could only work on a xlat context passed as a pointer. This is not practical if you want to modify the current translation tables as it is needed to export the xlat tables context, which is not a clean fix. The old functions have been renamed and new functions have been created to not need to export the context. Trying to use the old names will now result in a compilation error so that it is obvious that the new functions exist and the user can choose the correct one, potentially making the code cleaner.
- The following bug has been fixed:
```
During cold boot, the initial translation tables are created with data
caches disabled, so all modifications go to memory directly. After the
MMU is enabled and data cache is enabled, any modification to …
```
=> xlat v2: Cleanup and dcache coherency bug fix

bl1/aarch32/bl1_exceptions.S, include/lib/aarch32/arch.h, include/lib/aarch32/arch_helpers.h, include/lib/aarch64/arch.h, include/lib/xlat_tables/xlat_mmu_helpers.h, include/lib/xlat_tables/xlat_tables_v2.h, lib/xlat_tables/aarch32/xlat_tables.c, lib/xlat_tables_v2/aarch32/enable_mmu.S, lib/xlat_tables_v2/aarch32/xlat_tables_arch.c, lib/xlat_tables_v2/aarch64/enable_mmu.S, lib/xlat_tables_v2/aarch64/xlat_tables_arch.c, lib/xlat_tables_v2/xlat_tables_context.c, lib/xlat_tables_v2/xlat_tables_core.c, lib/xlat_tables_v2/xlat_tables_utils.c, plat/arm/common/arm_bl1_setup.c, plat/arm/common/arm_bl2_el3_setup.c, plat/arm/common/arm_bl2_setup.c, plat/arm/common/arm_bl2u_setup.c, plat/arm/common/sp_min/arm_sp_min_setup.c, plat/common/aarch32/plat_common.c, plat/layerscape/common/ls_bl1_setup.c, plat/layerscape/common/ls_bl2_setup.c, plat/st/stm32mp1/stm32mp1_common.c
This library is not only used in the TF. In order to help maintainability, it's better to backport EL2 support to this repository.
Platforms have been updated to use new AArch32 APIs.
=> xlat v2: Support EL2 translation regime

drivers/arm/cci/cci.c
The CCI500 TRM explicitily requires completion of the write
operation before the read operation, and it is not guaranteed
by dmb but it is dsb.
Change-Id: Ieeaa0d1a4b8fcb87108dea9b6de03d9c8a150829
=> cci: Use dsb to wait before reading status register

common/tf_snprintf.c, drivers/marvell/comphy/phy-comphy-cp110.c, drivers/partition/partition.c, drivers/st/clk/stm32mp1_clk.c, plat/hisilicon/hikey/hisi_ipc.c, plat/marvell/a8k/common/mss/mss_bl2_setup.c, services/spd/trusty/generic-arm64-smcall.c
Functions provided by stdio.h such as printf and sprintf are available in the codebase, but they add a lot of code to the final image if they are used:
- AArch64: ~4KB
- AArch32: ~2KB in T32, ~3KB in A32
tf_printf and tf_snprintf are a lot more simple, but it is preferable to use them when possible because they are also used in common code.
=> Replace stdio.h functions by TF functions

plat/rpi3/include/plat_macros.S, plat/rpi3/platform.mk
The Raspberry Pi 3 port doesn't actually depend on any Arm platform code, so the dependencies can be removed.
=> rpi3: Remove dependencies on Arm platform code

bl1/bl1.mk, bl2/bl2.mk, bl31/bl31.mk, docs/cpu-specific-build-macros.rst, include/lib/cpus/aarch64/dsu_def.h, lib/cpus/aarch64/cortex_a55.S, lib/cpus/aarch64/cortex_a75.S, lib/cpus/aarch64/cortex_a76.S, lib/cpus/aarch64/dsu_helpers.S, lib/cpus/cpu-ops.mk
If the system is in near idle conditions, this erratum could cause a
deadlock or data corruption. This patch applies the workaround that
prevents this.
This DSU erratum affects only the DSUs that contain the ACP interface
and it was fixed in r2p0. The workaround is applied only to the DSUs
that are actually affected.
Link to respective Arm documentation:
http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.epm138168/index.html
Change-Id: I033213b3077685130fc1e3f4f79c4d15d7483ec9
=> DSU erratum 936184 workaround

plat/rockchip/common/aarch64/plat_helpers.S
This function is required for platforms where
COLD_BOOT_SINGLE_CPU=0 however it was missing from rockchip
platforms
Change-Id: I32a85f226a4f22085a27113903f34bdb6f28dbcc
=> rockchip: Add plat_is_my_cpu_primary function

lib/cpus/aarch64/denver.S
This patch uses the 'declare_cpu_ops_workaround_cve_2017_5715' macro, to
set the check function, to report that Denver cores are mitigated.
Change-Id: I1bb6eefdec8c01fb8b645e112f8d04d4bb8811ef
=> cpus: denver: report CVE_2017_5715 mitigation to higher layers

include/plat/marvell/a8k/common/plat_marvell.h, plat/marvell/common/marvell_bl31_setup.c
Move from bl31_early_platform_setup to bl31_early_platform_setup2
Signed-off-by: Konstantin Porotchkin <kostap@marvell.com>
=> plat: marvell: bl31: Update the early platform setup API

lib/cpus/aarch64/dsu_helpers.S
The initial implementation was corrupting registers that it shouldn't.
Now this is fixed.
Change-Id: Iaa407c18e668b2d9381391bf10d6876fe936aded
=> DSU erratum 936184 workaround: bug fix

plat/arm/common/arm_dyn_cfg.c
Small patch which removes some redundant casts to (void *).
Change-Id: If1cfd68f2989bac1d39dbb3d1c31d4119badbc21
=> Remove unnecessary casts

maintainers.rst
Folders drivers/st/ and include/drivers/st/ are added in maintainers.rst,
under STM32MP1 platform port.
This will allow notifications for the files modified there.
=> maintainers: add drivers folders for STM32MP1

Makefile, common/backtrace.c, docs/user-guide.rst, include/common/debug.h, include/lib/aarch32/arch.h, include/lib/aarch32/arch_helpers.h, include/lib/aarch64/arch_helpers.h, lib/libc/assert.c, make_helpers/defaults.mk
This PR adds a backtrace function that works in A32 and A64. It is called by default inside ``panic()`` and ``assert()``.
It doesn't work in T32, so this PR also adds the new build option ``AARCH32_INSTRUCTION_SET`` that allows the user to compile in A32 or T32.
For more information check the commit messages.
=> Introduce backtrace function

docs/user-guide.rst, lib/el3_runtime/aarch64/context_mgmt.c
This patch fixes a bug in the context management code that causes it to
ignore the HANDLE_EA_EL3_FIRST compile-time option and instead always
configure SCR_EL3 to force all external aborts to trap into EL3. The
code used #ifdef to read compile-time option declared with add_define in
the Makefile... however, those options are always defined, they're just
defined to either 0 or 1, so #if is the correct syntax to check for
them.
This bug has existed since the Nov 2017 commit 76454ab (AArch64:
Introduce External Abort handling), which changed the
HANDLE_EA_EL3_FIRST option to use add_define.
Change-Id: I7189f41d0daee78fa2fcf4066323e663e1e04d3d
Signed-off-by: Julius Werner <jwerner@chromium.org>
=> context_mgmt: Fix HANDLE_EA_EL3_FIRST implementation

common/runtime_svc.c
A pointer to rt_svc_desc_t is defined both in the function
handle_runtime_svc() and globally. Since the value of the
pointer RT_SVC_DESCS_START is defined by the linker and
never changes make this definition local in both
handle_runtime_svc() and runtime_svc_init() to reduce the
number of loads
Change-Id: Iea42c778d8599a26c87700009163b5a8d7d60be2
=> Remove rt_svc_descs pointer from global scope

plat/ti/k3/common/k3_psci.c
Use TI-SCI messages to request core power down from system controller
firmware.
Signed-off-by: Andrew F. Davis <afd@ti.com>
=> Add PSCI core power down for K3

plat/xilinx/zynqmp/pm_service/pm_api_clock.c, plat/xilinx/zynqmp/pm_service/pm_api_clock.h, plat/xilinx/zynqmp/pm_service/pm_api_sys.c, plat/xilinx/zynqmp/pm_service/pm_api_sys.h
Add new query data parameter to get actual number of
clocks so Linux can get actual clock numbers in advance
and allocate memory accordingly.
Signed-off-by: Rajan Vaja <rajan.vaja@xilinx.com>
=> zynqmp: pm: Add API to get number of clocks

services/spd/opteed/opteed_pm.c
Some platforms might chose to take different actions depending on this
value; this is precisely the case for rcar-gen3.
Signed-off-by: Jorge Ramirez-Ortiz <jramirez@baylibre.com>
=> opteed: pass power level on suspend

plat/qemu/platform.mk, plat/qemu/qemu_bl1_setup.c, plat/qemu/qemu_bl2_setup.c, plat/qemu/qemu_bl31_setup.c
Makes LOAD_IMAGE_V2=1 mandatory
And addresses https://github.com/ARM-software/tf-issues/issues/613 by replacing bl31_early_platform_setup() and bl2_early_platform_setup()
=> Qemu updates

include/lib/aarch32/arch_helpers.h, lib/locks/bakery/bakery_lock_coherent.c, lib/locks/bakery/bakery_lock_normal.c
With the current implementation, it's possible for a contender to
observe accesses in the Critical Section before acquiring or releasing
the lock. Insert fencing in the locking and release codes to prevent any
reorder.
Fixes ARM-software/tf-issues#609
Change-Id: I773b82aa41dd544a2d3dbacb9a4b42c9eb767bbb
=> Add missing barriers to Bakery Locks

bl31/bl31_main.c
If BL32 isn't present or it fails to initialize the current code prints an error message in both debug and release builds. This is too verbose for release builds, so it has been converted into a warning.
Also, it was missing a newline at the end of the message.
=> Convert BL31 error message into warning

services/std_svc/sdei/sdei_main.c
The specification requires that, after wakeup from a CPU suspend, the
dispatcher must mask all events on the CPU. This patch adds the feature
to the SDEI dispatcher by subscribing to the PSCI suspend to power down
event, and masking all events on the PE.
Change-Id: I9fe1d1bc2a58379ba7bba953a8d8b275fc18902c
=> SDEI: Mask events after CPU wakeup

include/plat/arm/board/common/board_arm_def.h, plat/arm/common/arm_dyn_cfg.c, plat/arm/common/arm_dyn_cfg_helpers.c
This patch refines parts of the initial Mbed TLS shared heap implementation (https://github.com/ARM-software/arm-trusted-firmware/pull/1554). Each commit describes the various changes.
=> Improvements to Mbed TLS shared heap code

include/plat/arm/board/common/v2m_def.h, include/plat/arm/common/plat_arm.h, plat/arm/board/juno/juno_bl1_setup.c, plat/arm/board/juno/juno_err.c, plat/arm/board/juno/platform.mk, plat/arm/common/arm_bl1_setup.c, plat/arm/common/arm_err.c
The patch 7b56928 unified the FWU mechanism on FVP and Juno
platforms due to issues with MCC firmware not preserving the
NVFLAGS. With MCCv150 firmware, this issue is resolved. Also
writing to the NOR flash while executing from the same flash
in Bypass mode had some stability issues. Hence, since the
MCC firmware issue is resolved, this patch reverts to the
NVFLAGS mechanism to detect FWU. Also, with the introduction
of SDS (Shared Data Structure) by the SCP, the reset syndrome
needs to queried from the appropriate SDS field.
Change-Id: If9c08f1afaaa4fcf197f3186887068103855f554
Signed-off-by: Soby Mathew <Soby.Mathew@arm.com>
=> juno: Revert FWU update detect mechanism

plat/arm/css/common/css_common.mk, plat/arm/soc/common/soc_css_security.c
Adds an undocumented build option that enables non-secure access to
the PL011 UART1.
This allows a custom build where the UART can be used as a serial debug
port for WinDbg (or other debugger) connection.
This option is not documented in the user guide, as it is provided as a
convenience for Windows debugging, and not intended for general use.
In particular, enabling non-secure access to the UART might allow
a denial of service attack!
Change-Id: I4cd7d59c2cac897cc654ab5e1188ff031114ed3c
Signed-off-by: Evan Lloyd <evan.lloyd@arm.com>
=> ARM Platforms:Enable non-secure access to UART1

plat/hisilicon/hikey960/hikey960_io_storage.c, plat/hisilicon/hikey960/hikey960_rotpk.S, plat/hisilicon/hikey960/hikey960_tbbr.c, plat/hisilicon/hikey960/include/platform_def.h, plat/hisilicon/hikey960/platform.mk
This patch adds experimental support for TBB to the HiKey960 board. To build and test with TBB modify the uefi-tools project platforms.config
```
+ATF_BUILDFLAGS=TRUSTED_BOARD_BOOT=1 GENERATE_COT=1 SAVE_KEYS=1 \
MBEDTLS_DIR=./mbedtls
```
Signed-off-by: Teddy Reed <teddy@casualhacking.io>
=> hikey960: Add development TBB support

lib/cpus/aarch64/cortex_ares.S
This patch fixes the name of the Cortex-ares errata function which was
previously named `cortex_a72_errata_report` which was an error.
Change-Id: Ia124df4628261021baa8d9a30308bc286d45712b
=> Fix the Cortex-ares errata reporting function name

plat/arm/css/drivers/scp/css_pm_scmi.c
This patch fixes an array overrun in CSS scmi driver if the
system power domain level is less than 2. This was reported from
https://scan.coverity.com/projects/arm-software-arm-trusted-firmware
CID 308492
Change-Id: I3a59c700490816718d20c71141281f19b2b7e7f7
=> CSS: Fix overrun if system power level is not available

common/tf_log.c
When using the tf_log_set_max_level() function, one can dynamically
set the log level to a value smaller than then compile time specified
one, but not equal. This means that when the log level have been
lowered, it can't be reset to the previous value. This commit modifies
this function to allow setting the log level back to the compile time
value.
Fixes ARM-software/tf-issues#624
Change-Id: Ib157715c8835982ce4977ba67a48e18ff23d5a61
Signed-off-by: Junhan Zhou <Junhan@mellanox.com>
=> Allow setting log level back to compile time value

plat/arm/common/arm_bl1_setup.c, plat/arm/common/arm_bl2_setup.c, plat/arm/common/arm_common.mk
The patch d323af9 removed the support for coherent memory in BL1 and
BL2 for ARM platforms. But the CryptoCell SBROM  integration depends
on use of coherent buffers for passing data from the AP CPU to the
CryptoCell. Hence this patch reintroduces support for coherent
memory in BL1 and BL2 if ARM_CRYPTOCELL_INTEG=1.
Change-Id: I011482dda7f7a3ec9e3e79bfb3f4fa03796f7e02
Signed-Off-by: Soby Mathew <soby.mathew@arm.com>
=> ARM platforms: Reintroduce coherent memory for BL1 and BL2

bl31/bl31_main.c
The expected value for failure is 0, so the warning only has to be shown in that case. This is the way the TSPD has done it since it was introduced, and the way SPM and OP-TEE do it.
Trusty wrongly returns 0 on success.
In the case of TLK, the return value of tlkd_init() is passed from the secure world in register X1 when calling the SMC TLK_ENTRY_DONE.
=> BL31: Fix warning about BL32 init function

services/spd/trusty/trusty.c
The value used to signal failure is 0. It is needed to return a different value on success.
=> trusty: Fix return value of trusty_init()

drivers/mentor/i2c/mi2cv.c, plat/allwinner/common/include/mentor_i2c_plat.h, plat/allwinner/sun50i_h6/platform.mk, plat/allwinner/sun50i_h6/sunxi_power.c, plat/marvell/a8k/common/a8k_common.mk, plat/marvell/a8k/common/include/mentor_i2c_plat.h
Fix some minor things we discussed before that didn't make it into the original PR.
This addresses some minor issues during the Allwinner I2C platform setup and improves the code readability on the way. Also this (re-)initialises the I2C controller (again) just before we are using it in the PSCI handler for powering down the system, so we can cope with anything the rich OS may have done meanwhile.
Also this changes the I2C driver stubs for Allwinner and Marvell to be header files instead, and let the actual driver include them.
@Icenowy: Could you please have a look and confirm that these changs are fine? I briefly tested it yesterday on my PineH64 board.
@kostapr: Can you please check that the third patch matches what you were talking about before?
=> Allwinner PMIC fixes

include/lib/aarch32/arch.h
PAR register used here is a 64 bit register.
On AARCH32 BIT macro is BIT_32.
PAR_ADDR_MASK should then use BIT_64 to avoid overflow.
=> aarch32: PAR_ADDR_MASK should explicitly use BIT_64

plat/arm/css/sgm/include/sgm_base_platform_def.h
For sgm775 the SCP_BL2 build in debug mode is around 94KiB which
is higher than the maximum size for SCP_BL2.
This patch increase the maximum allowed size for SCP_BL2 to
96KiB.
Change-Id: Ibca0daadba41429301c651ae21cbba87e45ccddf
Signed-off-by: Elieva Pignat <Elieva.Pignat@arm.com>
=> sgm: increase SCP_BL2 maximum size

plat/hisilicon/poplar/bl1_plat_setup.c, plat/hisilicon/poplar/bl2_plat_setup.c
Commit eba1b6b3c724 ("plat/poplar: migrate to mmc framework") defines
variable 'info' without !POPLAR_RECOVERY protection, and hence causes
the following unused variable error with POPLAR_RECOVERY=1 build.
plat/hisilicon/poplar/bl1_plat_setup.c: In function ‘bl1_platform_setup’:
plat/hisilicon/poplar/bl1_plat_setup.c:95:25: error: unused variable ‘info’ [-Werror=unused-variable]
struct mmc_device_info info;
^~~~
The patches fixes the build error with POPLAR_RECOVERY=1.
Signed-off-by: Shawn Guo <shawn.guo@linaro.org>
=> poplar: fix build error with POPLAR_RECOVERY=1

drivers/mmc/mmc.c
The Poplar is broken on eMMC initialization because of commit
2a82a9c95f6c ("drivers: emmc: dw_mmc: Add response flag into response ID
definition").  It changes the driver behavior on response type handling
in dw_send_cmd(), because MMC_RESPONSE_R(2) and MMC_RESPONSE_R2 are
different things.  MMC core is still sending the former while we already
changed to check the latter in dw_mmc driver.
This patch fixes R2 response type in MMC core code.  It's the same
thing as what commit 94522ff7f6d2 ("drivers: mmc: Fix R3 response type
definition") does for R3 response.
With this fix, Poplar is back to work.
Signed-off-by: Shawn Guo <shawn.guo@linaro.org>
=> drivers: mmc: Fix R2 response type definition

docs/user-guide.rst, include/plat/arm/board/common/board_arm_def.h, plat/arm/board/common/board_common.mk, plat/arm/board/fvp/include/platform_def.h, plat/arm/board/juno/include/platform_def.h, plat/arm/board/juno/platform.mk, plat/arm/css/sgi/include/platform_def.h, plat/arm/css/sgm/include/sgm_base_platform_def.h
This option makes it hard to optimize the memory definitions of all Arm platforms because any change in the common defines must work in all of them. The best thing to do is to remove it and move the definition to each platform's header.
FVP, SGI and SGM were using the definitions in board_arm_def.h. The definitions have been copied to each platform's platform_def.h. Juno was already using the ones in platform_def.h, so there have been no changes.
=> plat/arm: Remove option ARM_BOARD_OPTIMISE_MEM

plat/marvell/a8k/common/include/a8k_plat_def.h, plat/marvell/a8k/common/include/platform_def.h, plat/marvell/common/aarch64/marvell_bl2_mem_params_desc.c, plat/marvell/common/marvell_bl1_setup.c, plat/marvell/common/marvell_bl2_setup.c, plat/marvell/common/marvell_bl31_setup.c, plat/marvell/common/marvell_common.mk, plat/marvell/common/marvell_image_load.c
- Fix build issue
- Add initial memory parameters descriptors for BL2
- Migrate to image load V2
Basic build an run test passed on MacchiatoBin board.
Need to fix the service CPU (CM3) image load procesure and test
OPTEE functionality, which probably wiull require additional work.
Signed-off-by: Konstantin Porotchkin <kostap@marvell.com>
=> marvell: Continue migration to new APIs

bl1/bl1_fwu.c, lib/libc/printf.c, lib/libc/snprintf.c, plat/common/plat_gicv2.c, plat/common/plat_gicv3.c, plat/rockchip/rk3399/drivers/dp/cdn_dp.c, plat/xilinx/zynqmp/pm_service/pm_api_ioctl.c, services/spd/tlkd/tlkd_common.c, services/spd/tspd/tspd_main.c
Ensure case clauses:
*   Terminate with an unconditional break, return or goto statement.
*   Use conditional break, return or goto statements as long as the end
of the case clause is unreachable; such case clauses must terminate
with assert(0) /* Unreachable */ or an unconditional  __dead2 function
call
*   Only fallthough when doing otherwise would result in less
readable/maintainable code; such case clauses must terminate with a
/* Fallthrough */ comment to make it clear this is the case and
indicate that a fallthrough is intended.
This reduces the chance of bugs appearing due to unintended flow through a
switch statement
Change-Id: I70fc2d1f4fd679042397dec12fd1982976646168
=> Ensure the flow through switch statements is clear

docs/marvell/build.txt, plat/marvell/a8k/common/a8k_common.mk, plat/marvell/a8k/common/ble/ble.ld.S, plat/marvell/a8k/common/ble/ble.mk, plat/marvell/a8k/common/ble/ble_main.c, plat/marvell/a8k/common/ble/ble_mem.S, tools/doimage/Makefile, tools/stm32image/Makefile
This series moves BLE from outside repository to Marvell TF-A platform tree as requested by @antonio-nino-diaz-arm.
Additional patch fixes broken rules in tools - the patch is provided by @jan-kiszka in https://github.com/ARM-software/tf-issues/issues/631
=> plat/marvell: Move BLE into the platform tree, minor fix in tools.

Makefile
When attempting to compile TF-A with "SPD=something ARCH=aarch32", the
following error message is printed:
Makefile:291: *** recipe commences before first target.  Stop.
This is because the call to the error function is indented using a tab
whereas it's not part of a rule's recipe. Replace the tab by spaces.
=> Remove incorrect tabulation in Makefile

lib/xlat_tables/xlat_tables_common.c, lib/xlat_tables_v2/xlat_tables_core.c
Commit 79621f0038b789de23ecc8891024f7cf6aa65999 broke sgi575.
It is possible to have a region with 0 as value for the attributes. It means device memory, read only, secure, executable. This is legitimate if the code is in flash and the code is executed from there.
This is the case for SGI_MAP_FLASH0_RO, defined in the file plat/arm/css/sgi/sgi_plat.c.
This problem is solved by checking both size and attributes in xlat v1. In xlat v2, it is enough to check the granularity, as it can never be 0.
=> xlat: Fix checks in mmap_add() and mmap_add_ctx()

tools/doimage/doimage.c
Signed-off-by: Matteo Croce <mcroce@redhat.com>
=> doimage: get rid of non null terminated strings by strncpy

plat/arm/css/sgm/sgm_bl1_setup.c
In the function, bl1_early_platform_setup in the file
plat/arm/css/sgm/sgm_bl1_setup.c:
plat_config_init();
arm_bl1_early_platform_setup();
The debug messages logged by plat_config_init() are lost because
the console is initialized in the function
arm_bl1_early_platform_setup()
To see the logs of plat_config_init, this fix re-orders above calls
so that the console is initialized before call to plat_config_init.
Change-Id: I2e98f1f67c591cca24e28905acd0838ea3697a7c
Signed-off-by: Girish Pathak <girish.pathak@arm.com>
=> plat/arm/css/sgm: Reorder early platform init

tools/cert_create/Makefile, tools/doimage/Makefile, tools/fiptool/Makefile, tools/stm32image/Makefile
HOSTCC should be used in any of the tools inside the tools/ directory instead of CC. That way it is possible to override both values from the command line when building the Trusted Firmware and the tools at the same time. Also, use HOSTCCFLAGS instead of CFLAGS.
Also, instead of printing the strings CC and LD in the console during the compilation of the tools, HOSTCC and HOSTLD have to be used for clarity. This is how it is done in other projects like U-Boot or Linux.
=> tools: Make invocation of host compiler correct

plat/arm/board/juno/platform.mk, plat/arm/css/common/css_common.mk, plat/arm/css/sgi/sgi-common.mk, plat/arm/css/sgm/sgm-common.mk
This lets any future CSS platforms to use RESET_TO_BL31 flag.
Change-Id: I32a90fce43cb0c6f4d33589653a0fd6a7ecc9577
Signed-off-by: Deepak Pandey <Deepak.Pandey@arm.com>
=> plat/arm: allow RESET_TO_BL31 for CSS-based platforms

docs/change-log.rst, docs/user-guide.rst, include/common/debug.h, plat/arm/common/arm_bl31_setup.c, plat/hisilicon/poplar/bl31_plat_setup.c, plat/layerscape/common/ls_bl31_setup.c, plat/marvell/common/marvell_bl31_setup.c, plat/mediatek/mt6795/bl31_plat_setup.c, plat/mediatek/mt8173/bl31_plat_setup.c, plat/qemu/qemu_bl31_setup.c, plat/rockchip/common/bl31_plat_setup.c, plat/rpi3/rpi3_bl31_setup.c, plat/xilinx/zynqmp/bl31_zynqmp_setup.c
This patch fixes typos in both code comments and documentation and adds some small clarifications in documentation.
=> Various corrections of typos

lib/psci/psci_main.c
Some platforms can only resume from system suspend from the boot
CPU, hence they should only enter that state from that same core.
The following commit presents an interface that allows the platform to
reject system suspend entry near its very last stage (last CPU).
=> psci: platform control of SYSTEM_SUSPEND entry

drivers/imx/usdhc/imx_usdhc.c
After merging in PR-1596 we found breakage in the i.MX7 MMC driver.
This PR fixes the breakage in the right place - our driver, where before the main MMC driver had been erroneously churned by us.
Please apply.
=> drivers: imx: mxc_usdhc: Do not set MMC_RSP_48 for MMC_RESPONSE_R2

Makefile, make_helpers/build_macros.mk
"-s" is a command line option to the make tool, to suppress normal output,
something to the effect of prepending every line with '@' in the Makefile.
However with our V={0|1} support, we now print the shortened command line
output in any case (even with V=1, in addition to the long line!).
Normally -s helps to not miss non-fatal warnings, which tend to scroll out
of the window easily.
Introduce a new Makefile variable ECHO, to control the shortened output.
We only set it in the (current default) V=0 case, and replace every
occurence of "@echo" with that variable.
When the user specifies "-s", we set ECHO to some magic string which
changes the output line into a comment, so the output is suppressed.
Beside suppressing every output for "-s", we also avoid the redundant
short output when …
=> Makefile: Support totally quiet output with -s

drivers/arm/pl011/aarch32/pl011_console.S, drivers/arm/pl011/aarch64/pl011_console.S, drivers/cadence/uart/aarch64/cdns_console.S, drivers/coreboot/cbmem_console/aarch64/cbmem_console.S, drivers/ti/uart/aarch64/16550_console.S
The comments with the prototypes of the register functions of the console drivers are incorrect. The arguments are wrong. This patch fixes them.
=> pl011: cnds: cbmem: 16550: Fix comments

include/lib/object_pool.h
The object pool allocator provides a simplistic interface to manage
allocation in a fixed-size static array. The caller creates a static
"object pool" out of such an array and may then call pool_alloc() to
get the next available object within the pool. There is also a variant
to get multiple consecutive objects: pool_alloc_n().
Note that this interface does not provide any way to free the objects
afterwards. This is by design and it is not a limitation. We do not
want to introduce complexity induced by memory freeing, such as
use-after-free bugs, memory fragmentation and so on.
=> Introduce object pool allocator

include/lib/cpus/aarch32/cpu_macros.S, include/lib/cpus/aarch64/cpu_macros.S, plat/arm/board/juno/aarch32/juno_helpers.S, plat/arm/board/juno/aarch64/juno_helpers.S, plat/arm/css/sgi/aarch64/sgi_helper.S, plat/arm/css/sgm/aarch64/css_sgm_helpers.S
macro jump_if_cpu_midr is used commonly by many arm platform.
It has now been relocated to common place to remove duplication
of code.
Change-Id: Ic0876097dbc085df4f90eadb4b7687dde7c726da
Signed-off-by: Deepak Pandey <Deepak.Pandey@arm.com>
=> plat/arm: relocate the jump_if_cpu_midr macro.

bl31/bl31.ld.S, include/plat/arm/common/plat_arm.h, plat/arm/css/drivers/scmi/scmi.h, plat/arm/css/drivers/scmi/scmi_common.c, plat/arm/css/drivers/scp/css_pm_scmi.c
When HW_ASSISTED_COHERENCY is enabled we can use spinlocks
instead of using the more complex and slower bakery algorithm.
Change-Id: I9d791a70050d599241169b9160a67e57d5506564
=> Optimize bakery locks when HW_ASSISTED_COHERENCY is enabled

lib/cpus/aarch64/cortex_a53.S, plat/ti/k3/common/k3_psci.c, plat/ti/k3/common/plat_common.mk
Hello all,
The first two patches should be simple enough. The third is a bit more interesting and is kinda an RFC.
For K3, we have hardware assisted coherency but as I've argued before the flag "HW_ASSISTED_COHERENCY" is a misnomer and is targeted specifically for DynamIQ platforms. An example of this is in psci_do_pwrdown_sequence(), where we assume all platforms with the hardware assisted coherency flag will use a core's with a *_core_pwr_dwn function that will not disable the cache. This is not the case for K3 with A53 cores.
We introduce a new flag "DISABLE_DCACHE_LATE" designed as the inverse of "WARMBOOT_ENABLE_DCACHE_EARLY". It is for platforms that do not need (or cannot have due to hardware issues) cache disabled in the power down path.
As you can see we need to make a check for …
=> Allow D-Cache to remain on during core power-down

drivers/arm/tzc/tzc400.c, drivers/arm/tzc/tzc_common_private.h, drivers/arm/tzc/tzc_dmc500.c, include/drivers/arm/tzc400.h, include/drivers/arm/tzc_common.h, include/drivers/arm/tzc_dmc500.h, include/plat/arm/common/arm_def.h, include/plat/arm/common/plat_arm.h, plat/arm/common/arm_tzc400.c, plat/arm/common/arm_tzc_dmc500.c
The definitions FAIL_CONTROL_*_SHIFT were incorrect, they have been fixed.
The types tzc_region_attributes_t and tzc_action_t have been removed and replaced by unsigned int because it is not allowed to do logical operations on enums.
Also, fix some address definitions in arm_def.h.
=> tzc: Fix MISRA defects

plat/qemu/include/platform_def.h
Since upstream QEMU commit 14ec3cbd7c1e ("device_tree: Increase
FDT_MAX_SIZE to 1 MiB"), which is included in release v2.12.1
and later, BL2 initialization fails with the following error (-3 is
-FDT_ERR_NOSPACE):
ERROR:   Invalid Device Tree at 0x40000000: error -3
Increase PLAT_QEMU_DT_MAX_SIZE accordingly.
Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>
=> qemu: increase PLAT_QEMU_DT_MAX_SIZE to 1 MiB

Makefile, make_helpers/unix.mk, make_helpers/windows.mk
Commit ee1ba6d4ddf1 ("Makefile: Support totally quiet output with -s") broke verbose (V=1) builds on Windows. This patch fixes it by adding helpers to silence echo prints in a OS-dependent way.
=> Makefile: Fix verbose builds on Windows

docs/firmware-design.rst, include/common/aarch64/el3_common_macros.S, include/lib/aarch64/arch.h, lib/el3_runtime/aarch64/context_mgmt.c
Pointer authentication is an Armv8.3 feature that introduces
instructions that can be used to authenticate and verify pointers.
Pointer authentication instructions are allowed to be accessed from all
ELs but only when EL3 explicitly allows for it; otherwise, their usage
will trap to EL3. Since EL3 doesn't have trap handling in place, this
patch unconditionally disables all related traps to EL3 to avoid
potential misconfiguration leading to an unhandled EL3 exception.
Fixes ARM-software/tf-issues#629
Change-Id: I9bd2efe0dc714196f503713b721ffbf05672c14d
=> AArch64: Enable lower ELs to use pointer authentication

plat/arm/board/juno/juno_topology.c, plat/arm/css/drivers/scmi/scmi.h, plat/arm/css/drivers/scp/css_pm_scmi.c, plat/arm/css/sgi/sgi_bl31_setup.c, plat/arm/css/sgm/sgm_bl31_setup.c
The default values of 'plat_css_scmi_plat_info' is not applicable for
all the platforms. There should be a provision to let platform code to
register a platform specific instance of scmi_channel_plat_info_t.
Add a new API 'plat_css_get_scmi_info' which lets the platform to
register a platform specific instance of scmi_channel_plat_info_t and
remove the default values.
In addition to this, the existing 'plat_css_scmi_plat_info' structure
is removed from the common code and instantiated for the platforms that
need it. This allows for a consistent provisioning of the SCMI channel
information across all the existing and upcoming platforms.
Change-Id: I4fb65d7f2f165b78697b4677f1e8d81edebeac06
Signed-off-by: Chandni Cherukuri <chandni.cherukuri@arm.com>
=> plat/arm/scmi: introduce plat_css_get_scmi_info API

docs/plat/rpi3.rst, plat/rpi3/platform.mk, plat/rpi3/rpi3_bl31_setup.c, plat/rpi3/rpi3_common.c
When a device tree blob is pressent at a know address, instead of, for example, relying on the user modifying the Linux command line to warn about the memory reserved for the Trusted Firmware, pass it on the DTB.
In order to add this information to the DTB the code looks for an already existent reserve region (which is most likely the one reserved for the official EL3 bootstrap) and reuses it for the Trusted Firmware.
This system replaces the previous one consisting on adding ``memmap=16M$256M`` to the Linux command line. It's also meant to be used by U-Boot and any other bootloader that understands DTB files.
=> rpi3: Add mem reserve region to DTB if present

drivers/arm/pl011/aarch32/pl011_console.S, drivers/arm/pl011/aarch64/pl011_console.S, drivers/cadence/uart/aarch64/cdns_console.S, drivers/console/aarch64/skeleton_console.S, drivers/coreboot/cbmem_console/aarch64/cbmem_console.S, drivers/ti/uart/aarch64/16550_console.S, include/common/aarch32/console_macros.S, include/common/aarch64/console_macros.S, plat/imx/common/lpuart_console.S, plat/layerscape/common/aarch64/ls_console.S
The `finish_console_register` macro is used by the multi console
framework to register the `console_t` driver callbacks. It relied
on weak references to the `ldr` instruction to populate 0 to the
callback in case the driver has not defined the appropriate
function. Use of `ldr` instruction to load absolute address to a
reference makes the binary position dependant. These instructions
should be replaced with adrp/adr instruction for position independant
executable(PIE). But adrp/adr instructions don't work well with weak
references as described in GNU ld bugzilla issue 22589.
This patch defines a new version of `finish_console_register` macro
which takes the driver callbacks as arguments and deprecates the old
one. If any of the argument is left blank, then the macro populates
0 for that …
=> Multi-console: Deprecate the `finish_console_register` macro

docs/porting-guide.rst, plat/arm/common/aarch64/arm_helpers.S, plat/common/aarch32/crash_console_helpers.S, plat/common/aarch32/platform_helpers.S, plat/common/aarch64/crash_console_helpers.S, plat/common/aarch64/platform_helpers.S, plat/hisilicon/hikey/aarch64/hikey_helpers.S, plat/hisilicon/hikey960/aarch64/hikey960_helpers.S, plat/imx/common/imx8_helpers.S, plat/imx/imx7/warp7/aarch32/warp7_helpers.S, plat/marvell/common/aarch64/marvell_helpers.S, plat/nvidia/tegra/common/aarch64/tegra_helpers.S, plat/rockchip/rk3328/platform.mk, plat/rockchip/rk3368/platform.mk, plat/rockchip/rk3399/platform.mk, plat/ti/k3/common/k3_helpers.S, plat/xilinx/zynqmp/aarch64/zynqmp_helpers.S, plat/xilinx/zynqmp/plat_zynqmp.c, plat/xilinx/zynqmp/platform.mk, plat/xilinx/zynqmp/zynqmp_def.h, plat/xilinx/zynqmp/zynqmp_private.h
The default behaviour of the plat_crash_console_xxx functions isn't obvious to someone that hasn't read all the documentation. As they are not mandatory, it is unlikely that the code will be checked when doing a platform port, which may mean that some platforms may not have crash console support at all.
The idea of this patch is to force platform maintainers to decide how the crash console has to behave so that the final behaviour isn't unexpected.
This PR also fixes all upstream platforms that need it.
=>  Deprecate weak crash console functions 

drivers/meson/console/aarch64/meson_console.S
It isn't possible to build this driver without adding this define.
=> meson: console: Add missing define to fix build

services/std_svc/sdei/sdei_private.h
This patch includes context.h from sdei_private.h to fix the
following compilation errors:
> In file included from services/std_svc/sdei/sdei_event.c:9:0:
> services/std_svc/sdei/sdei_private.h: In function 'sdei_client_el':
> services/std_svc/sdei/sdei_private.h:164:2: error: unknown type name 'cpu_context_t'
>   cpu_context_t *ns_ctx = cm_get_context(NON_SECURE);
>   ^
> services/std_svc/sdei/sdei_private.h:165:2: error: unknown type name 'el3_state_t'
>   el3_state_t *el3_ctx = get_el3state_ctx(ns_ctx);
>   ^
> services/std_svc/sdei/sdei_private.h:165:2: error: implicit declaration of function 'get_el3state_ctx' [-Werror=implicit-function-declaration]
> services/std_svc/sdei/sdei_private.h:165:25: error: initialization makes pointer from integer without a cast [-Werror]
>   el3_state_t …
=> sdei: include "context.h" to fix compilation errors

plat/arm/board/n1sdp/aarch64/n1sdp_helper.S, plat/arm/board/n1sdp/include/plat_macros.S, plat/arm/board/n1sdp/include/platform_def.h, plat/arm/board/n1sdp/n1sdp_bl31_setup.c, plat/arm/board/n1sdp/n1sdp_interconnect.c, plat/arm/board/n1sdp/n1sdp_plat.c, plat/arm/board/n1sdp/n1sdp_security.c, plat/arm/board/n1sdp/n1sdp_topology.c, plat/arm/board/n1sdp/platform.mk
This patch adds support for the N1SDP (NeoVerse N1 System Development
Platform). It is an initial port and additional features are expected
to be added later.
The port includes only BL31 support as the System Control Processor
(SCP) is expected to take the role of primary boatloader
Change-Id: Ife17d8215a7bfcc1420204a72205e7ef920d0c10
Signed-off-by: Deepak Pandey <Deepak.Pandey@arm.com>
=> plat/arm: Introduce the N1SDP.

include/lib/libfdt/libfdt.h, include/lib/libfdt/libfdt_env.h, lib/libfdt/fdt.c, lib/libfdt/fdt_addresses.c, lib/libfdt/fdt_overlay.c, lib/libfdt/fdt_ro.c, lib/libfdt/fdt_rw.c, lib/libfdt/fdt_sw.c, lib/libfdt/libfdt_internal.h
Version 1.4.7 introduces a big performance hit to functions that access the FDT. Downgrade the library to version 1.4.6-9, before the changes that introduce the problem. Version 1.4.6 isn't used because one of the libfdt files (fdt_overlay.c) is missing the license header. This problem is also fixed in 1.4.6-9.
This version corresponds to commit ``aadd0b65c987`` checks: centralize printing of property names in failure messages.
Fixes ARM-software/tf-issues#643
=> libfdt: Downgrade to version 1.4.6-9

plat/ti/k3/common/k3_bl31_setup.c, plat/ti/k3/common/plat_common.mk
A recent patch[0] has made setting up page tables into generic
code, complete the conversion for TI platforms by removing the
use of plat_arm_get_mmap() and using the mmap table directly.
[0] 0916c38deca4 ("Convert arm_setup_page_tables into a generic helper")
Signed-off-by: Andrew F. Davis <afd@ti.com>
=> ti: k3: common: Remove use of ARM platform code

plat/arm/board/juno/juno_topology.c
When CSS_USE_SCMI_DRIVER is not defined or set to 0, we get the
following build error.
plat/arm/board/juno/juno_topology.c:16:19: error: ‘CSS_SCMI_PAYLOAD_BASE’ undeclared here (not in a function)
.scmi_mbx_mem = CSS_SCMI_PAYLOAD_BASE,
^~~~~~~~~~~~~~~~~~~~~
plat/arm/board/juno/juno_topology.c:17:38: error: ‘CSS_SCMI_MHU_DB_REG_OFF’ undeclared here (not in a function)
.db_reg_addr = PLAT_CSS_MHU_BASE + CSS_SCMI_MHU_DB_REG_OFF,
^~~~~~~~~~~~~~~~~~~~~~~
CSS_CPU_PWR_STATE_OFF
Fix the error in order to get function legacy SCPI support functional.
Change-Id: I00cb80db9968aa0be546e33a3a682a2db87719be
Signed-off-by: Sudeep Holla <sudeep.holla@arm.com>
=> plat: juno: fix build for !CSS_USE_SCMI_DRIVER

plat/hisilicon/hikey/hikey_bl2_setup.c
It boots failure on CircuitCo HiKey board. The delay could fix the
hang issue.
=> hikey: add delay after eMMC initialized

bl32/sp_min/sp_min_main.c, docs/user-guide.rst, plat/arm/common/arm_common.mk, plat/arm/common/sp_min/arm_sp_min_setup.c
This option allows the Trusted Firmware to directly jump to Linux
kernel for aarch32 without the need of an intermediate loader such
as U-Boot.
Similar to AArch64 ARM_LINUX_KERNEL_AS_BL33 only available with
RESET_TO_SP_MIN=1 as well as BL33 and DTB are preloaded in memory.
Change-Id: I908bc1633696be1caad0ce2f099c34215c8e0633
Signed-off-by: Manish Pandey <manish.pandey2@arm.com>
=> plat/arm: Support direct Linux kernel boot in AArch32

docs/plat/xilinx-versal.md, plat/xilinx/versal/aarch64/versal_common.c, plat/xilinx/versal/aarch64/versal_helpers.S, plat/xilinx/versal/bl31_versal_setup.c, plat/xilinx/versal/include/plat_macros.S, plat/xilinx/versal/include/platform_def.h, plat/xilinx/versal/plat_psci.c, plat/xilinx/versal/plat_topology.c, plat/xilinx/versal/plat_versal.c, plat/xilinx/versal/platform.mk, plat/xilinx/versal/sip_svc_setup.c, plat/xilinx/versal/versal_def.h, plat/xilinx/versal/versal_gicv3.c, plat/xilinx/versal/versal_private.h
This request mainly adds support for new Xilinx Versal platforms.
The first patch in series removes unnecessary header inclusion arm_def.h in arm_gicv3.c and second patch adds support for this new platform Versal.
Xilinx is introducing Versal, an adaptive compute acceleration platform
(ACAP), built on 7nm FinFET process technology. Versal ACAPs combine Scalar
Processing Engines, Adaptable Hardware Engines, and Intelligent Engines with
leading-edge memory and interfacing technologies to deliver powerful
heterogeneous acceleration for any application. The Versal AI Core series has
five devices, offering 128 to 400 AI Engines. The series includes dual-core Arm
Cortex-A72 application processors, dual-core Arm Cortex-R5 real-time
processors, 256KB of on-chip memory with ECC, more than 1,900 …
=> Add support new Xilinx Versal ACAP platform

docs/plat/rpi3.rst, plat/rpi3/platform.mk, plat/rpi3/rpi3_common.c
Some OSes (e.g. Ubuntu 18.04 LTS on Raspberry Pi 3) may disable the
runtime UART in a manner that prevents the system from rebooting if
ATF tries to send runtime messages there.
Also, we don't want the firmware to share the UART with normal
world, as this can be a DoS attack vector into the secure world.
This patch fixes these 2 issues by introducing new build option
RPI3_RUNTIME_UART, that disables the runtime UART by default.
Fixes ARM-software/tf-issues#647
Signed-off-by: Pete Batard <pete@akeo.ie>
=> rpi3: add RPI3_RUNTIME_UART build option

drivers/marvell/uart/a3700_console.S, include/drivers/marvell/uart/a3700_console.h, include/plat/marvell/a3700/common/plat_marvell.h, include/plat/marvell/a8k/common/plat_marvell.h, plat/marvell/a3700/common/a3700_common.mk, plat/marvell/a8k/common/a8k_common.mk, plat/marvell/a8k/common/ble/ble.mk, plat/marvell/a8k/common/ble/ble_main.c, plat/marvell/a8k/common/plat_pm.c, plat/marvell/common/aarch64/marvell_helpers.S, plat/marvell/common/marvell_bl1_setup.c, plat/marvell/common/marvell_bl2_setup.c, plat/marvell/common/marvell_bl31_setup.c, plat/marvell/common/marvell_common.mk, plat/marvell/common/marvell_console.c
This patch fixes small bug in A3700 image encryption command and  introduces migration to the multi-console API for all supported Marvell platforms.
=> Marvell: Migrate to multi console API

plat/hisilicon/hikey/hikey_bl2_setup.c
Some eMMC chips require a longer delay, otherwise we run into a receive timeout when attempting to read FIP image. After testing different chips, 20ms appears to work reliably. I have tested Sandisk SDINADF4-32G and Samsung KLMBG4GEAC.
=> hikey: increase delay after eMMC initialized

docs/plat/rpi3.rst, plat/rpi3/include/platform_def.h, plat/rpi3/platform.mk
The default Raspberry Pi 3 memory mapping for ATF is geared towards
the use of uboot + Linux. This creates issues when trying to use
ATF with an UEFI payload and Windows on ARM64.
We therefore introduce new build option RPI3_USE_UEFI_MAP, that
enables the build process to use an alternate memory mapping that
is compatible with UEFI + Windows (as well as UEFI + Linux).
Fixes ARM-software/tf-issues#649
Signed-off-by: Pete Batard <pete@akeo.ie>
=> rpi3: add RPI3_USE_UEFI_MAP build option

docs/plat/rpi3.rst
d4fd0219 (pull request #1685) introduced unwanted formatting
such as bold/italic in the description for `RPI3_USE_UEFI_MAP`.
=> rpi3: fix bad formatting in rpi3.rst

plat/renesas/rcar/bl2_secure_setting.c, plat/renesas/rcar/platform.mk
This feature was enabled to allow u-boot reprograming the ATF firmware
using a FIP image instead of having to toggle numerous DIP switches on
the board.
The code being disabled with this commit should only be re-enabled for
debugging (_never_ on a product release)
Signed-off-by: Jorge Ramirez-Ortiz <jorge.ramirez.ortiz@gmail.com>
=> rcar-gen3: lock RPC hyper-flash access

include/lib/xlat_tables/xlat_tables_v2.h, lib/xlat_tables_v2/xlat_tables_context.c, lib/xlat_tables_v2/xlat_tables_core.c
Provide new APIs to add new regions without specifying the base VA.
- `mmap_add_region_alloc_va` adds a static region to mmap choosing as base VA the first possible address after all the currently mapped regions. It is aligned to an appropriate boundary in relation to the size and base PA of the requested region. No attempt is made to fill any unused VA holes.
- `mmap_add_dynamic_region_alloc_va` it adds a region the same way as `mmap_add_region_alloc_va` does, but it's dynamic instead of static.
- `mmap_add_alloc_va` takes an array of non const `mmap_region_t`, maps them in the same way as `mmap_add_region_alloc_va` and fills their `base_va` field. A helper macro has been created to help create the array, called `MAP_REGION_ALLOC_VA`.
Note that this code is already present in TF-A-Tests: …
=> xlat v2: Support mapping regions with allocated VA

include/lib/aarch32/arch.h, include/lib/aarch32/arch_helpers.h, include/lib/aarch64/arch.h, include/lib/aarch64/arch_helpers.h, include/lib/utils_def.h, plat/arm/common/arm_common.c
The headers forked at some point in the past and have diverged a lot. In order to make it easier to share code between TF-A-Tests and TF-A, this patch synchronises most of the definitions in the mentioned headers.
This is not a complete sync, it has to be followed by more cleanup.
This patch also removes the read helpers for the AArch32 instructions ``ats1cpr`` and ``ats1hr`` (they are write-only).
This PR depends on https://github.com/ARM-software/arm-trusted-firmware/pull/1694
=> Synchronise arch.h and arch_helpers.h with TF-A-Tests

include/lib/aarch32/arch_helpers.h
This reverts commit 6f512a3dfd61662dbdae4912fb6a320ae4d754d5.
According to the 'Cortex-A57 MPCore Software Developers Errata Notice':
This bug will only affect secure AArch64 EL3. If the above
conditions occur, the CPU will not invalidate the targeted EL3 TLB
entries and incorrect translations might occur.
For this reason it is not needed in AArch32.
=> Revert "aarch32: Apply workaround for errata 813419 of Cortex-A57"

plat/arm/board/fvp/fvp_pm.c, plat/arm/board/juno/juno_pm.c, plat/arm/board/juno/platform.mk, plat/arm/board/juno/sp_min/sp_min-juno.mk, plat/arm/board/n1sdp/n1sdp_bl31_setup.c, plat/arm/common/arm_pm.c, plat/arm/css/drivers/scmi/scmi.h, plat/arm/css/drivers/scp/css_pm_scmi.c, plat/arm/css/sgi/sgi_bl31_setup.c, plat/arm/css/sgm/sgm_bl31_setup.c
In order to allow Arm platforms to override the default list of PSCI
callbacks, remove the existing weak implementation of
'plat_arm_psci_override_pm_ops' function and let all the Arm platforms
implement their own 'plat_arm_psci_override_pm_ops' function.
For platforms that support SCMI protocol, the function
'css_scmi_override_pm_ops' can be additionally used as well to
override the default PSCI callbacks.
=> plat/arm: remove weak implemention of 'plat_arm_psci_override_pm_ops'

lib/romlib/gen_combined_bl1_romlib.sh, plat/arm/board/juno/include/platform_def.h, plat/arm/board/juno/platform.mk
This patch builds the combined BL1 and ROMLIB
binary file with filler bytes for the right page
size alignment in Juno. The build option
USE_ROMLIB=1 generates the combined file:
bl1_romlib.bin which has to be used instead of
bl1.bin for Juno.
Change-Id: I407efbe48d3e522fa6ef855538a9587193cb1919
=> romlib: Add juno support for romlib

include/lib/utils_def.h, lib/psci/psci_stat.c
Initial Spectre Variant 1 mitigations (CVE-2017-5753).
A potential speculative data leak was found in PSCI code, this depends
on a non-robust implementation of the `plat_get_core_pos_by_mpidr()`
function. This is considered very low-risk. This patch adds a macro to
mitigate this. Note not all code paths could be analyzed with current
tools.
Add a macro which makes a variable 'speculation safe', using the
__builtin_speculation_safe_value function of GCC and llvm. This will be
available in GCC 9, and is planned for llvm, but is not currently in
mainline GCC or llvm. In order to implement this mitigation the compiler
must support this builtin. Support is indicated by the
__HAVE_SPECULATION_SAFE_VALUE flag.
The -mtrack-speculation option maintains a 'tracker' register, which
determines if the …
=> Initial Spectre V1 mitigations (CVE-2017-5753).

plat/arm/board/sgi575/platform.mk, plat/arm/board/sgi575/sgi575_plat.c, plat/arm/board/sgiclarka/platform.mk, plat/arm/board/sgiclarka/sgiclarka_plat.c, plat/arm/css/sgi/include/sgi_variant.h, plat/arm/css/sgi/sgi_bl31_setup.c, plat/arm/css/sgi/sgi_image_load.c
Add two new functions 'plat_arm_sgi_get_platform_id' and
'plat_arm_sgi_get_config_id' which will be implemented by all the
SGI platforms. These functions can be used to determine the part
number and configuration id of the SGI platforms.
In BL2, these functions are used to populate the 'system-id' node.
In BL31, these functions are used to populate the 'sgi_plat_info_t'
structure with the part number and configuration id of the platform.
Change-Id: I3bacda933527724a3b4074ad4ed5b53a81ea4689
Signed-off-by: Chandni Cherukuri <chandni.cherukuri@arm.com>
=> plat/arm/sgi: Use platform specific functions to get platform ids

plat/hisilicon/hikey960/hikey960_bl31_setup.c, plat/hisilicon/hikey960/include/hi3660.h
This is needed to utilize the DMA controller on the hikey960
Signed-off-by: Ryan Grachek <ryan@edited.us>
=> hikey960: initialize EDMAC and channels

bl31/aarch64/runtime_exceptions.S
Use the helper function `save_gp_registers` to save the register
state to cpu_context on entry to EL3 in SMC handler. This has the
effect of saving x0 - x3 as well into the cpu_context which was
not done previously but it unifies the register save sequence
in BL31.
Change-Id: I5753c942263a5f9178deda3dba896e3220f3dd83
=> BL31: Use helper function to save registers in SMC handler

include/common/aarch32/el3_common_macros.S, include/common/aarch64/el3_common_macros.S, include/lib/aarch32/arch.h, include/lib/aarch64/arch.h, lib/cpus/aarch64/cortex_a76.S, services/arm_arch_svc/arm_arch_svc_setup.c
The Armv8.5 extensions introduces PSTATE.SSBS (Speculation Store Bypass
Safe) bit to mitigate against Variant 4 vulnerabilities. Although an
Armv8.5 feature, this can be implemented by CPUs implementing earlier
version of the architecture.
With this patch, when both PSTATE.SSBS is implemented and
DYNAMIC_WORKAROUND_CVE_2018_3639 is active, querying for
SMCCC_ARCH_WORKAROUND_2 via. SMCCC_ARCH_FEATURES call would return 1 to
indicate that mitigation on the PE is either permanently enabled or not
required.
When SSBS is implemented, SCTLR_EL3.DSSBS is initialized to 0 at reset
of every BL stage. This means that EL3 always executes with mitigation
applied.
For Cortex A76, if the PE implements SSBS, the existing mitigation (by
using a different vector table) is not used.
Change-Id: …
=> AArch64: Use SSBS for CVE_2018_3639 mitigation

drivers/arm/ccn/ccn.c
For RN-I, node id is used instead of node postion in the bitmap
to calculate the region id.
Signed-off-by: Pankaj Gupta <pankaj.gupta@nxp.com>
=> ccn: for RN-I, used node id instead of node postion

Makefile, bl2/aarch32/bl2_arch_setup.c, bl2/bl2_private.h, drivers/io/io_block.c, plat/common/plat_log_common.c, plat/hisilicon/hikey/include/platform_def.h, plat/hisilicon/hikey960/include/platform_def.h, plat/hisilicon/poplar/include/platform_def.h, plat/imx/imx7/warp7/include/platform_def.h, plat/socionext/uniphier/include/platform_def.h
This is based on the same warnings lists as defined in kernel.
To activate this, the option W=x has to be provided in make command, with x=1, 2 or 3.
W=1 adds warning of the first list, W=2 adds warnings of the first and second list, and W=3 adds the warnings of the 3 lists.
When activating this, the -Werror is disabled, or else we would only have the first warning(s), and the compilation would end.
This series also includes 2 patches that corrects some warnings.
=> Add possibility to add compilation warnings

docs/marvell/build.txt
Replace "Uboot" with "Ubuntu".
Signed-off-by: Ding Tao <miyatsu@qq.com>
=> docs: marvell: Fix typo in file build.txt

include/drivers/arm/gic_common.h
The GIC lowest priority values for each world depends on the number of
priority values implemented in hardware. These constants currently
defined in gic_common.h only meant to enumerate lowest possible
architectural values. Since these values are not used in generic code or
upstream platforms, and that general use of these constants can be
wrong, remove these. Platforms should either define and use these as
appropriate, or determine correct values at run time.
Change-Id: I3805cea8ceb8a592b9eff681ea1b63b7496cec5f
=> GIC: Remove lowest priority constants

plat/st/stm32mp1/platform.mk
On AARCH32, thumb is used by default, no need to redefine it.
As all our binaries are compiled with thumb, interwork is not needed.
The binaries compiled with or without those flags are the same,
except of course for the date.
=> stm32mp1: remove useless compilation flags

Makefile
This patch modifies the search criteria to see if we are using 'armclang'
as the compiler. Switch over to using 'findstring' which enables platforms
to do fancy stuff using scripts e.g. check if armclang timed out and retry
compilation.
Change-Id: If2162ebadb9033f6457a4e8d4243345e711defe6
Signed-off-by: Kalyani Chidambaram Vaidyanathan <kalyanic@nvidia.com>
=> build: find "armclang" string in the 'CC' variable

Makefile, lib/romlib/Makefile, lib/romlib/gentbl.sh, lib/romlib/genwrappers.sh, lib/romlib/jmptbl.i, plat/arm/board/fvp/jmptbl.i, plat/arm/board/juno/jmptbl.i
This patch allows platforms to define their
own jump table list for library at ROM. The
file has the list of functions to be used
from library at ROM. It can also include
other list files.
Change-Id: I721c35d7dad3dcadbb3a7f3277bfd5d3e1f6e00a
=> romlib: Add platform specific jump table list

Makefile
This is done for other compilers, and without this some code does not
compile, like inline assembly code.
Fixes ARM-software/tf-issues#657.
=> clang: 32 bit compilation should include march32-directive

include/common/aarch32/el3_common_macros.S, include/common/aarch64/el3_common_macros.S, include/lib/aarch32/arch.h, include/lib/aarch64/arch.h
This patch enables the Data Independent Timing
functionality (DIT) in EL3 if supported
by the PE.
Change-Id: Ia527d6aa2ee88a9a9fe1c941220404b9ff5567e5
=> Enable DIT if supported

plat/arm/common/arm_common.mk
This option was removed in v2.0.
=> plat/arm: Remove comment that mentions LOAD_IMAGE_V2

Makefile
ASM_ASSERTION was deprecated long ago, this check is no longer needed.
=> Remove ASM_ASSERTION check in Makefile

drivers/st/clk/stm32mp1_clk.c, drivers/st/clk/stm32mp1_clkfunc.c, drivers/st/ddr/stm32mp1_ddr.c, drivers/st/ddr/stm32mp1_ram.c, drivers/st/io/io_stm32image.c, drivers/st/mmc/stm32_sdmmc2.c, drivers/st/pmic/stm32mp1_pmic.c, include/drivers/st/stm32mp1_pmic.h, plat/st/stm32mp1/platform.mk, plat/st/stm32mp1/stm32mp1_def.h
Instead, only platform_def.h is included.
The required files to be included are added in stm32mp1_def.h.
=> stm32mp1: do not include platform header files directly in drivers

plat/arm/board/juno/juno_pm.c
A previous commit 89f2e589856f ("plat/arm: remove weak implemention of
'plat_arm_psci_override_pm_ops' function") introduced a problem with the
CSS_USE_SCMI_SDS_DRIVER configuration. In juno_pm.c the
css_scmi_override_pm_ops function was used regardless of whether the
flag was set. This patch ifdefs the function to restore the original
behaviour.
Change-Id: I508025ba70cf3a9250cc6270c1df209179c37ae7
=> juno:Fix CSS_USE_SCMI_SDS_DRIVER=0 configuration

drivers/mmc/mmc.c
Running TF-A 2.0 and later seems to cause a regression on the old CircuitCo HiKey 620 4GB (issue is not seen when running on LeMaker HiKey 620 8GB).
NOTICE:  BL2: v2.0(release):v2.0
NOTICE:  BL2: Built : 17:41:23, Dec 17 2018
NOTICE:  acpu_dvfs_set_freq: set acpu freq success!ERROR:   CMD1 failed after 100 retries
ERROR:   BL2: Failed to load image (-5)
The reason seems to be that during emmc enumeration when BL2 sends the command
OCR_SECTOR_MODE | OCR_VDD_MIN_2V7 | OCR_VDD_MIN_1V7
it for some reason takes some more time to get a reply. So a delay with
mdelay(1), seems to not be enough any longer and therefore we increase it to
mdelay(10) instead which makes the device boot as expected again.
Signed-off-by: Joakim Bech <joakim.bech@linaro.org>
Note that I've tried with mdelay(5) which …
=> mmc: increase delay when initializing mmc

readme.rst
Cleaning up some sentences in the readme, adjusting case and adding the SCMI abbreviation where the "System Control and Management Interface" is first mentioned.
=> doc: Minor reword & reformatting in readme.rst

maintainers.rst
This patch adds me to various maintainer activities in
the ATF tree associated with the NXP i.MX8M platform.
Signed-off-by: Jacky Bai <ping.bai@nxp.com>
=> maintainers: Add maintainter for NXP i.MX8M platform.

include/arch/aarch32/arch.h, include/arch/aarch32/arch_features.h, include/arch/aarch32/arch_helpers.h, include/arch/aarch64/arch.h, include/arch/aarch64/arch_features.h, include/arch/aarch64/arch_helpers.h, lib/xlat_tables_v2/aarch32/xlat_tables_arch.c, lib/xlat_tables_v2/aarch64/xlat_tables_arch.c
ARMv8.2-TTCNP is mandatory from ARMv8.2 onwards, but it can be implemented in CPUs that don't implement all mandatory 8.2 features (and so have to claim to be a lower version).
This patch removes usage of the ARM_ARCH_AT_LEAST() macro and uses system ID registers to detect whether it is needed to set the bit or not.
=> xlat v2: Dynamically detect need for CnP bit

make_helpers/build_macros.mk
With this patch, each BL image can have its own compiler flags.
=> build: Support BL-specific build flags

bl31/bl31.ld.S, bl31/bl31_main.c, bl32/sp_min/sp_min.ld.S, bl32/sp_min/sp_min_main.c, bl32/tsp/tsp_main.c, bl32/tsp/tsp_timer.c, common/backtrace/backtrace.c, docs/auth-framework.rst, docs/change-log.rst, docs/firmware-design.rst, docs/firmware-update.rst, docs/porting-guide.rst, docs/psci-lib-integration-guide.rst, docs/ras.rst, docs/secure-partition-manager-design.rst, docs/user-guide.rst, drivers/arm/ccn/ccn.c, drivers/partition/partition.c, lib/aarch32/arm32_aeabi_divmod.c, lib/el3_runtime/aarch64/context_mgmt.c, plat/arm/common/arm_gicv3.c, plat/arm/common/tsp/arm_tsp_setup.c, plat/arm/css/drivers/mhu/css_mhu_doorbell.c, services/spd/opteed/teesmc_opteed.h, services/spd/tlkd/tlkd_main.c, services/spd/trusty/trusty.c, services/spd/tspd/tspd_main.c, services/std_svc/sdei/sdei_private.h
Corrects typos in core files, documentation files, drivers, Arm
platforms and services.
None of the corrections are functional; they are limited to comments
in code and other documentation.
Change-Id: I5c1027b06ef149864f315ccc0ea473e2a16bfd1d
=> Correct typographical errors

plat/imx/common/imx_uart_console.S, plat/imx/common/include/imx_uart.h, plat/imx/common/lpuart_console.S, plat/imx/imx8m/imx8mq/imx8mq_bl31_setup.c
lpuart driver needs to implement .console_flush callback to make debug mode work, since common code will call debug uart's .console_flush callback without checking if it is valid. imx uart build failed with debug mode enabled and also need to add .console_flush callback to make it work.
=> make lpuart and imx uart work for debug mode

bl1/bl1_private.h, bl2/bl2_private.h, include/common/bl_common.h, plat/arm/common/arm_bl1_setup.c, plat/arm/css/sgi/sgi_plat.c, plat/hisilicon/hikey/hikey_bl1_setup.c, plat/hisilicon/hikey960/hikey960_bl1_setup.c, plat/hisilicon/poplar/bl1_plat_setup.c, plat/layerscape/common/ls_bl1_setup.c, plat/marvell/common/marvell_bl1_setup.c, plat/qemu/qemu_private.h, plat/rpi3/rpi3_bl1_setup.c
The definitions in bl1/bl1_private.h and bl2/bl2_private.h are useful for platforms that may need to access them.
=> Move BL1 and BL2 private defines to bl_common.h

plat/imx/common/imx_sip_handler.c, plat/imx/common/imx_sip_svc.c, plat/imx/common/include/imx_sip_svc.h, plat/imx/common/include/sci/sci.h, plat/imx/common/include/sci/svc/timer/sci_timer_api.h, plat/imx/common/sci/sci_api.mk, plat/imx/common/sci/svc/timer/sci_timer_rpc.h, plat/imx/common/sci/svc/timer/timer_rpc_clnt.c, plat/imx/imx8qm/platform.mk, plat/imx/imx8qx/platform.mk
This patch set adds i.MX8QM/i.MX8QX SRTC/cpu-freq SIP runtime service support, as these functions need to be done from secure world, so SIP runtime service is necessary for Linux's RTC and cpu-freq driver to support some functions like setting RTC time, changing cpu-freq etc..
=> Add i.MX8 SoC SRTC/cpu-freq SIP runtime service support

plat/ti/k3/common/drivers/sec_proxy/sec_proxy.c
The logic is correct here, but the error messages are
reversed, switch them.
Signed-off-by: Andrew F. Davis <afd@ti.com>
Acked-by: Nishanth Menon <nm@ti.com>
=> ti: k3: drivers: sec_proxy: Switch error messages

plat/ti/k3/common/plat_common.mk, plat/ti/k3/include/platform_def.h
To accommodate scenarios where we want to use a UART baud rate other than
the default 115,200 allow the associated compiler definition to be set
via the K3_USART_BAUD build option by updating the platform make file.
Since the platform make file now also contains the default value (still
115,200), go ahead and remove the redundant definition from the platform
header file.
Suggested-by: Andrew F. Davis <afd@ti.com>
Signed-off-by: Andreas Dannenberg <dannenberg@ti.com>
=> ti: k3: common: Allow customizing UART baud rate using build options

services/spd/trusty/trusty.c
When an unknown Trusty image is found, there's no point of still trying
to register the BL32 init handler. Instead, we just should bail out of
the trusty_setup() and allow the system to continue to boot.
Signed-off-by: David Lin <dtwlin@google.com>
=> spd: trusty: trusty_setup should bail on unknown image

Makefile, make_helpers/build_macros.mk
Following changes are done to make DT pre-processing similar to that of
U-boot/Linux kernel.
1. Creating seperate CPPFLAGS for DT preprocessing so that compiler
options specific to it can be accommodated.
e.g: "-undef" compiler option avoids replacing "linux" string(used in
device trees) with "1" as "linux" is a pre-defined macro in gnu99
standard.
2. Replace CPP with PP for DT pre-processing, as CPP in U-boot/Linux is
exported as "${CROSS_COMPILE}gcc -E" while in TF-A it is exported as
"${CROSS_COMPILE}cpp".
Change-Id: If4c61a249d51614d9f53ae30b602036d50c02349
Signed-off-by: Manish Pandey <manish.pandey2@arm.com>
=> Make device tree pre-processing similar to U-boot/Linux

tools/fiptool/fiptool.c
Commit 033648652f ("Make TF UUID RFC 4122 compliant") changed the scanf
parsing string to handle endianness correctly.
However that changed the number of items sscanf handles, without
adjusting the sanity check just below.
Increase the expected return value from 11 to 16 to let fiptool handle
UUIDs given as blob parameters correctly again.
Signed-off-by: Andre Przywara <andre.przywara@arm.com>
=> tools/fiptool: Fix UUID parsing in blob handling

plat/rpi3/rpi3_io_storage.c, plat/rpi3/rpi3_pm.c
Signed-off-by: Florian La Roche <Florian.LaRoche@gmail.com>
=> rpi3: Remove duplicate initialization for BL32_IMAGE_ID and mark one more function as static.

plat/rockchip/common/rockchip_gicv2.c, plat/rockchip/rk3328/rk3328_def.h, plat/rockchip/rk3368/rk3368_def.h
After the removal of deprecated interfaces in TF 2.0 the migration to the new GIC driver interfaces was done incorrectly in rk3328 and rk3368: 2d6f1f01b141 ("rockchip: Migrate to new interfaces").
In the GICv2 driver it is mandated that all interrupts are Group 0 interrupts. This patch simply moves all Group 1 interrupts to Group 0.
Fixes https://github.com/ARM-software/tf-issues/issues/663
=> rockchip: Fix GICv2 interrupts

drivers/mmc/mmc.c
In patch 93768644, ret will be MMC_STATE_TRAN (=4), which is a valid value.
We shouldn't exit the function in that case, but only if ret is < 0.
=> mmc: correctly check ret in mmc_fill_device_info

docs/coding-guidelines.rst, docs/user-guide.rst
This set of patches takes the content from the GitHub wiki's "ARM Trusted Firmware Coding Guidelines" page (currently located at https://github.com/ARM-software/arm-trusted-firmware/wiki/ARM-Trusted-Firmware-Coding-Guidelines) and moves that content into the repository, under the docs/ folder.
To move the content it is first converted from Markdown to ReStructured Text (RST) format. Some missing links are added and minor clarifications made. The document is then re-ordered for clarity and, finally, the details of include ordering are expanded upon.
=> Move coding guidelines into docs directory

plat/marvell/a8k/common/include/a8k_plat_def.h
The macro has n > 32.
It has to be n > 31 since GPIO 0-31 are on Register 0 and 32-63 on Register 1.
Signed-off-by: Sven Auhagen <sven.auhagen@voleatech.de>
=> Armada8k GPIO Register macro fix

docs/coding-guidelines.rst
Sections 2.2, 2.3 and 2.4 contained example code blocks that were not
being formatted properly due to missing newlines.
Change-Id: I0dbce90c931cf69e4f47d2ccbcc8bc0e20f8fd66
=> doc: Fix broken code blocks in coding guidelines

docs/user-guide.rst
ARM_PLAT_MT build flag is specific to Arm platforms so should not
be classified as a common build option.
=> User Guide: Move ARM_PLAT_MT doc to Arm build flags

plat/hisilicon/hikey960/hikey960_bl31_setup.c
Channel 0 is used to communicate with LPM3, a coprocessor
for power management. Leave it as secure.
Signed-off-by: Ryan Grachek <ryan@edited.us>
=> hikey960: EDMAC: leave channel 0 as secure

drivers/arm/gic/v3/gicv3_helpers.c
Previously the GICv3 redistributor probe function
(gicv3_rdistif_base_addrs_probe()) asserted that the number of
per-CPU redistributor interfaces expected to be probed by the
platform is equal to the number exported by the redistributor
frame. This is a problem in case the number of CPUs in the
platform is less than the number of redistributor interfaces
in the frame. Hence this patch removes the assertion check
and allows probe for fewer redistributor interfaces as required
by the platform.
Change-Id: I3449763a3ad70817224442cbe184d001030c9874
=> GICv3: Allow probe for fewer GICR interfaces than exposed by the frame

maintainers.rst
Add a second maintainer for Arm's SGI and SGM platform support in
trusted firmware to handle the review and maintenance of
existing and upcoming platforms.
Change-Id: Ie7fa8da280d9351f7543122fb261d6ac6c7e15ad
Signed-off-by: Thomas Abraham <thomas.abraham@arm.com>
=> sgi/sgm: add a second maintainer for Arm's SGI and SGM platforms

drivers/delay_timer/generic_delay_timer.c, include/arch/aarch32/arch.h, include/arch/aarch32/arch_features.h, include/arch/aarch64/arch_features.h
The Generic Timer is an optional extension to an ARMv7-A implementation. The generic delay timer can be used from any architecture supported by the Trusted Firmware. In ARMv7 it is needed to check that this feature is present. In ARMv8 it is always present.
=> drivers: generic_delay_timer: Assert presence of Generic Timer

services/spd/trusty/trusty.mk
Trusty requires dynamic translation tables support, so the makefile of Trusty itself should request it. Not doing so causes platforms such as FVP to fail to build with Trusty. Other platforms like Tegra still build because they use dynamic translation tables by default.
=> trusty: Require dynamic translation tables

docs/change-log.rst, docs/cpu-specific-build-macros.rst, docs/plat/hikey.rst, docs/plat/hikey960.rst, docs/plat/meson-gxbb.rst, docs/platform-compatibility-policy.rst, docs/porting-guide.rst, docs/trusted-board-boot.rst, docs/user-guide.rst
Using Sphinx linkcheck on the TF-A docs revealed some broken
or permanently-redirected links. These have been updated where
possible.
Change-Id: Ie1fead47972ede3331973759b50ee466264bd2ee
=> doc: Fix broken external links

services/spd/tlkd/tlkd.mk, services/spd/tlkd/tlkd_main.c, services/spd/tlkd/tlkd_pm.c, services/spd/tspd/tspd.mk
Commit 09d40e0e0828 ("Sanitise includes across codebase") modified the include paths of the TSP includes but it didn't remove the include path from the makefile or did the same for TLK. This patch does the remaining work.
=> Sanitize SPD include paths

include/lib/cpus/aarch32/aem_generic.h, include/lib/cpus/aarch32/cortex_a12.h, include/lib/cpus/aarch32/cortex_a15.h, include/lib/cpus/aarch32/cortex_a17.h, include/lib/cpus/aarch32/cortex_a32.h, include/lib/cpus/aarch32/cortex_a5.h, include/lib/cpus/aarch32/cortex_a53.h, include/lib/cpus/aarch32/cortex_a57.h, include/lib/cpus/aarch32/cortex_a7.h, include/lib/cpus/aarch32/cortex_a72.h, include/lib/cpus/aarch32/cortex_a9.h, include/lib/cpus/aarch64/aem_generic.h, include/lib/cpus/aarch64/cortex_a35.h, include/lib/cpus/aarch64/cortex_a53.h, include/lib/cpus/aarch64/cortex_a55.h, include/lib/cpus/aarch64/cortex_a57.h, include/lib/cpus/aarch64/cortex_a72.h, include/lib/cpus/aarch64/cortex_a73.h, include/lib/cpus/aarch64/cortex_a75.h, include/lib/cpus/aarch64/cortex_a76.h, include/lib/cpus/aarch64/cortex_deimos.h, include/lib/cpus/aarch64/cortex_helios.h, include/lib/cpus/aarch64/dsu_def.h
There were several CPU definitions with incorrect widths. This patch sets the width of all definitions to the correct ones according to the TRMs of the CPUs.
There are some values that should be 64-bit immediates but that resolve to 0 because the type of the value is 32-bit wide. This patch casts the expressions to 64-bit before the shift so that the definition has the correct value.
The definitions are only used in assembly so far, so the code is not actually affected by this bug. The assembler treats all values as 64-bit values, so there are no overflows.
=> Fix CPU headers' definitions

drivers/imx/uart/imx_uart.c, drivers/imx/uart/imx_uart.h, plat/imx/common/aarch32/imx_uart_console.S, plat/imx/imx7/warp7/platform.mk, plat/imx/imx7/warp7/warp7_bl2_el3_setup.c
This commit migrates to MULTI_CONSOLE_API for IMX Warp7 board.
We also rename the functions in imx_uart driver to more specific one.
Signed-off-by: Ying-Chun Liu (PaulLiu) <paulliu@debian.org>
=> imx: warp7: Migrate to MULTI_CONSOLE_API

docs/porting-guide.rst
Platforms are not allowed to use any file inside include/plat/arm or plat/arm to prevent dependencies between Arm platforms and non-Arm platforms.
=> docs: Update note about plat/arm in Porting Guide

services/std_svc/spm/sprt.c
Since commit 01fc1c24b9a0 ("BL31: Use helper function to save registers in SMC handler") all the general-purpose registers are saved when entering EL3. It isn't needed to save them here.
=> SPM: Remove unnecessary register save

plat/arm/board/fvp/platform.mk, services/spd/trusty/trusty.mk
Rather than letting the Trusty makefile set the option to enable dynamic translation tables, make platforms do it themselves.
This also allows platforms to replace the implementation of the translation tables library as long as they use the same function prototypes.
=> fvp: trusty: Move dynamic xlat enable to platform

include/lib/cpus/aarch64/cpu_macros.S
Armv8.5 introduces the field ``CSV2`` to register ``ID_AA64PFR0_EL1``. It can have the following 3 values:
- 0: Branch targets trained in one hardware described context may affect speculative execution in a different hardware described context. In some CPUs it may be needed to apply mitigations.
- 1: Branch targets trained in one hardware described context can only affect speculative execution in a different hardware described context in a hard-to-determine way. No mitigation required.
- 2: Same as 1, but the device is also aware of ``SCXTNUM_ELx`` register contexts. The TF doesn't use the registers, so there is no difference with 1.
The field CSV2 was originally introduced in the TRM of the Cortex-A76 before the release of the Armv8.5 architecture. That TRM only mentions the meaning of …
=> Update macro to check need for CVE-2017-5715 mitigation

docs/firmware-design.rst
Commit 2559b2c8256f ("xlat v2: Dynamically detect need for CnP bit") modified the code to convert the compile-time check for ARMv8.2-TTCNP to a runtime check, but forgot to update the documentation associated to it.
=> docs: Update documentation about ARMv8.2-TTCNP

plat/renesas/rcar/platform.mk, plat/renesas/rcar/rcar_common.c
Small fix adding PCIe link L1 state fixup.
=> rcar_gen3: plat: Prevent PCIe hang during L1X config access

plat/allwinner/common/include/sunxi_private.h, plat/allwinner/common/sunxi_bl31_setup.c, plat/allwinner/common/sunxi_common.c, plat/allwinner/common/sunxi_cpu_ops.c, plat/allwinner/common/sunxi_pm.c, plat/allwinner/common/sunxi_topology.c, plat/allwinner/sun50i_a64/sunxi_power.c
In the process of [developing SCPI support](https://github.com/smaeul/arm-trusted-firmware/commits/crust) for the Allwinner platforms, I came up with a few small improvements that are independent of the PSCI changes.
* ~~Make indentation/alignment consistent (though the only really "wrong" indentation was the `NOTICE` in sunxi_bl31_setup.c).~~
* Constify data structures where possible, so they get put in `.rodata`
* Make the CPU ops functions simpler to call, saving about 50 bytes. This will also save some line wrapping when the SCPI case is added.
=> allwinner: A few minor improvements

include/arch/aarch32/arch.h, include/arch/aarch32/el3_common_macros.S, include/arch/aarch64/arch.h, include/arch/aarch64/el3_common_macros.S
In a system with ARMv8.5-PMU implemented:
- If ``EL3`` is using AArch32, setting ``MDCR_EL3.SCCD`` to 1 disables counting in Secure state in ``PMCCNTR``.
- If ``EL3`` is using AArch64, setting ``SDCR.SCCD`` to 1 disables counting in Secure state in ``PMCCNTR_EL0``.
So far this effect has been achieved by setting ``PMCR_EL0.DP`` (in AArch64) or ``PMCR.DP`` (in AArch32) to 1 instead, but this isn't considered secure as any EL can change that value.
=> Disable processor Cycle Counting in Secure state

docs/plat/intel-stratix10.rst, plat/intel/soc/stratix10/aarch64/plat_helpers.S, plat/intel/soc/stratix10/bl31_plat_setup.c, plat/intel/soc/stratix10/include/plat_macros.S, plat/intel/soc/stratix10/include/s10_mailbox.h, plat/intel/soc/stratix10/plat_psci.c, plat/intel/soc/stratix10/plat_sip_svc.c, plat/intel/soc/stratix10/plat_topology.c, plat/intel/soc/stratix10/platform.mk, plat/intel/soc/stratix10/platform_def.h, plat/intel/soc/stratix10/soc/s10_mailbox.c
This adds BL31 support to Intel Stratix10 SoCFPGA platform. BL31 in TF-A
supports:
- PSCI calls to enable 4 CPU cores
- PSCI mailbox calls for FPGA reconfiguration
Signed-off-by: Loh Tien Hock <tien.hock.loh@intel.com>
=> plat: intel: Add BL31 support to Intel Stratix10 SoCFPGA platform

drivers/rpi3/sdhost/rpi3_sdhost.c, include/drivers/rpi3/sdhost/rpi3_sdhost.h, plat/rpi3/rpi3_bl2_setup.c
This commit improves the SDHost driver for RPi3 as following:
* Unblock MMC_CMD(17). Using MMC_CMD(17) is more efficient on
block reading.
* In some low probability that SEND_OP_COND might results CRC7
error. We can consider that the command runs correctly. We don't
need to retry this command so removing the code for retry.
* Using MMC_BUS_WIDTH_1 as MMC default value to improve the stability.
* Increase the clock to 50Mhz in data mode to speed up the io.
* Change the pull resistors configuration to gain more stability.
Signed-off-by: Ying-Chun Liu (PaulLiu) <paulliu@debian.org>
=> RaspberryPi3 sdhost driver improvement.

services/spd/trusty/generic-arm64-smcall.c
The GIC definitions used in this file have to be provided by the platform but ``platform_def.h`` wasn't included.
=> trusty: Include file with GIC definitions

include/arch/aarch64/arch.h, lib/extensions/mpam/mpam.c
Complete the MPAM enablement in TF-A for lower ELs by enabling the EL2
traps in MPAMHCR_EL2 and MPAM2_EL2.This prevents an
MPAM-unaware-hypervisor to be restricted by an MPAM-aware-guest.
=> MPAM: enable MPAM EL2 traps

plat/imx/common/plat_imx8_gic.c
GICR_WAKER.ProcessorSleep can only be set to zero when:
— GICR_WAKER.Sleep bit[0] == 0.
— GICR_WAKER.Quiescent bit[31] == 0.
On some platforms, when system reboot with GIC in sleep
mode but with power ON, such as on NXP's i.MX8QM, Linux
kernel enters suspend but could be requested to reboot,
and GIC is in sleep mode and it is inside a power domain
which is ON in this scenario, when CPU reset, the GIC
driver trys to set CORE's redistributor interface to awake,
with GICR_WAKER.Sleep bit[0] and GICR_WAKER.Quiescent bit[31]
both set, the ProcessorSleep bit[1] will never be clear
and cause system hang.
This patch makes sure GICR_WAKER.Sleep bit[0] and
GICR_WAKER.Quiescent bit[31] are both zeor before clearing
ProcessorSleep bit[1].
Signed-off-by: Anson Huang <Anson.Huang@nxp.com>
=> gic: make sure ProcessorSleep bit clear successfully

plat/imx/imx8m/imx8mq/imx8mq_bl31_setup.c, plat/imx/imx8m/imx8mq/include/platform_def.h
Derived from [this commit](https://source.codeaurora.org/external/imx/imx-atf/commit/plat/imx/imx8mq/imx8m_bl31_setup.c?h=imx_4.14.78_1.0.0_ga&id=6c485ce1f3e62723b1ac2a2b8385126ce8a4fe1d) in the NXP repo. The Linux CAAM driver is not able to initialise correctly without this.
=> imx: Configure CAAM job rings master ID for i.MX8MQ

common/bl_common.c, include/arch/aarch64/arch_features.h
Check for both IMPLEMENTATION_DEFINED and Architected algorithms of Address Authentication.
=> Correctly check for support of Address Authentication

plat/arm/css/sgi/include/sgi_variant.h, plat/arm/css/sgi/sgi_bl31_setup.c, plat/arm/css/sgi/sgi_topology.c
Replace all uses of 'SGI_CLARK' with 'RD_N1E1_EDGE' and
'SGI_CLARK_HELIOS' with 'RD_E1_EDGE' as per the updated product
names
Change-Id: Ib8136e421b1a46da1e5df58c6b1432d5c78d279b
Signed-off-by: Chandni Cherukuri <chandni.cherukuri@arm.com>
=> css/sgi: replace all uses of Clark with new product names

plat/nvidia/tegra/common/tegra_common.mk, plat/nvidia/tegra/common/tegra_io_storage.c, plat/nvidia/tegra/include/platform_def.h, plat/nvidia/tegra/platform.mk
This patch provides dummy macros and platform files to compile
the io_storage driver backend. This patch is necessary to
remove the "--unresolved=el3_panic" linker flag from Tegra's
makefiles and allow us to revert this workaround, previously
suggested by the ARM toolchain team.
The "--unresolved=el3_panic" flag actually was a big hammer that
allowed Tegra platforms to work with armlink previously but it
masks legit errors with the code as well.
Change-Id: I0421d35657823215229f84231896b84167f90548
=> Tegra: dummy support for the io_storage backend

drivers/auth/mbedtls/mbedtls_common.c, plat/common/plat_bl_common.c
Fixes https://github.com/ARM-software/tf-issues/issues/677
Due to the shared Mbed TLS heap optimisation introduced in 6d01a463,
common code files were depending on Mbed TLS specific headers. This
dependency is now removed by moving the default, unoptimised heap
implementation inside the Mbed TLS specific files.
Change-Id: I11ea3eb4474f0d9b6cb79a2afd73a51a4a9b8994
=> Remove Mbed TLS dependency from plat_bl_common.c

docs/firmware-design.rst
While the TODO might be relevant in the codebase itself, keeping
it in the example code is a bit untidy.
Change-Id: Ia95246208cee48df1536b4317a8c896ab2c84fc2
=> doc: Remove todo from example code

plat/st/common/bl2_io_storage.c
The change of the structure highlighted the fact that all fields are not
correctly initialized with zeroes.
Replace the other memset in the function with zeromem, as it is faster.
Change-Id: I27f45a64e34637f79fa519f486bf5936721ef396
=> stm32mp1: zeromem device_info struct

plat/intel/soc/stratix10/soc/s10_memory_controller.c
We should be using zeromem to scrub memory instead of memset. This would
improve the performance by 200x
=> plat: intel: Improve ECC scrubbing performance

drivers/mmc/mmc.c, include/drivers/mmc.h, plat/intel/soc/stratix10/bl2_plat_setup.c
Some bugs in MMC stack needs to be fixed:
- scr cannot be local as this will cause cache issue when invalidating
after the read DMA transfer is completed
- ACMD41 needs to send voltage information in initialization, otherwise the
command is a query, thus will not initialize the controller
- when checking device state, retry until the retries counter goes to zero
before failing
=> drivers: mmc: Fix some issues with MMC stack

plat/intel/soc/stratix10/bl2_plat_setup.c
MMC stack needs OCR voltage information for the platform to initialize
MMC controller correctly.
=> plat: intel: Add MMC OCR voltage information for initialization

bl31/aarch64/bl31_entrypoint.S
In the current Pointer Authentication support added in
commit b86048c
PAuth gets enabled in BL31 cold boot entrypoint only,
(see bl31_entrypoint() in bl31\aarch64\bl31_entrypoint.S)
but not in bl31_warm_entrypoint().
This results in EnIA bit [31] in SCTLR_EL3 not being set
and pointer authentication disabled after CPU wake-up event.
Fixes ARM-software/tf-issues#684
Change-Id: I27a67804764dfba2a6d72ca119ca2bcff4f536d6
=> BL31: Enable pointer authentication support in warm boot path

plat/xilinx/zynqmp/pm_service/pm_api_sys.c
Allow EL2 (e.g. U-Boot) to load the configuration object at runtime
into the Xilinx ZynqMP PMU firmware. This allows booting with U-Boot
and U-Boot SPL with PMU FW without hard-coding the configuration
object.
fixes arm-software/tf-issues#678
Signed-off-by: Luca Ceresoli <luca@lucaceresoli.net>
=> zynqmp: pm: Add support for setting PMU configuration object

lib/cpus/aarch32/cpu_helpers.S
The BL handover interface stores the bootloader arguments in
registers r9-r12, so when the reset_handler stores the lr pointer
in r10 it clobers one of the arguments.
Adapt to use r8 and adapt the comment about registers allowed
to clober.
I've checked aarch32 reset_handlers and none seem to use higher
registers as far as I can tell.
Fixes: a6f340fe58b9 ("Introduce the new BL handover interface")
Cc: Soby Mathew <soby.mathew@arm.com>
Signed-off-by: Heiko Stuebner <heiko@sntech.de>
=> Fixup register handling in aarch32 reset_handler

plat/allwinner/sun50i_a64/sunxi_power.c
So far the DT node describing the AXP803 PMIC used in many Allwinner A64
boards had only one subnode, so our code just entering the first subnode
to find all regulators worked fine.
However recent DT updates in the Linux kernel add more subnodes *before*
that, so we need to make sure to explicitly enter the "regulators"
subnode to find the information we are after.
Signed-off-by: Andre Przywara <andre.przywara@arm.com>
=> allwinner: regulators: pick correct DT subnode

drivers/st/mmc/stm32_sdmmc2.c
STM32MP1 SDMMC device voltage is 3.3V. We should then precise the 2 ranges
3.2 to 3.3V and 3.3 to 3.4V in ocr_voltage field.
Change-Id: I88e479f8f16bfe608a7808eace0df3fdec48deab
=> mmc: stm32_sdmmc2: fill ocr_voltage

fdts/stm32mp157a-dk1.dts, fdts/stm32mp157c-ed1.dts, fdts/stm32mp157c-security.dtsi
This node is added in a new file stm32mp157c-security.dtsi.
This node includes OTPs that should be shadowed and made readable
to non secure world.
The stgen node is also moved to this file.
Change-Id: I3c89a01588d2e411fecfc44997e1c5df2fc37cad
=> fdts: stm32mp1: add bsec node

.checkpatch.conf, Makefile
The first patch removes BRACES warning with conflicts with MISRA.
The second patch gives the possibility to use checkpatch with --strict option, and also removes some messages not compliant with TF-A or MISRA.
=> Update checkpatch options

bl1/aarch32/bl1_exceptions.S, bl2/aarch32/bl2_el3_entrypoint.S
We are observing a failure mode on a small minority of i.MX7 boards we have in our ATF setup.
Investigating this issue shows that the failure point is when 'eret' is executed to switch from BL2 to BL3.
On first blush, I thought it was down to misuse of eret intself for the particular mode the processor was in. With feedback from @Yann-lms though it was apparent my fix and diagnosis were wrong.
https://github.com/ARM-software/arm-trusted-firmware/pull/1876
Looking at OP-TEE and indeed other parts of the ATF codebase though we can see that the error is mis-setting of the SPSR, in the current case only setting bits 31:24 and 7:0 respectively.
Setting the full SPSR value though will negate the failure for me and ought to be correct for anybody else interested in bits 23:8 of the SPSR on eret.
=> bl2-el3: Fix exit to bl32 by ensuring full write to SPSR

drivers/synopsys/emmc/dw_mmc.c, include/drivers/synopsys/dw_mmc.h
There are some issues with synopsys MMC driver:
- CMD8 should not expect data
- CMD51 should expect data (MMC read)
- dw_prepare should not dictate size to be MMC_BLOCK_SIZE, block size is
now handled in the dw_prepare function
- after the CMD completes, when doing dw_read, we need to invalidate cache
- Need to set FIFO threshold, otherwise DMA will never get the interrupt to
read or write
=> drivers: synopsys: Fix synopsys MMC driver

lib/xlat_tables_v2/xlat_tables_core.c, lib/xlat_tables_v2/xlat_tables_utils.c
This PR converts recursive translation table traverses to simple stack based version. It keeps exactly same translation table traversal order compared to recursive version.
fixes arm-software/tf-issues#664
=> Remove recursion from xlat_tables_v2 library

bl2/aarch32/bl2_entrypoint.S, bl2/aarch64/bl2_entrypoint.S, bl2u/aarch32/bl2u_entrypoint.S, bl2u/aarch64/bl2u_entrypoint.S, bl32/tsp/aarch64/tsp_entrypoint.S
The SCTLR.DSSBS bit is zero by default thus disabling speculative loads.
However, we also explicitly set it to zero for BL2 and TSP images when
each image initialises its context. This is done to ensure that the
image environment is initialised in a safe state, regardless of the
reset value of the bit.
Change-Id: If25a8396641edb640f7f298b8d3309d5cba3cd79
=> Apply stricter speculative load restriction

plat/arm/board/fvp/include/platform_def.h
When RECLAIM_INIT_CODE is 1, the stack is used to contain the .text.init
section. This is by default enable on FVP. Due to the size increase of
the .text.init section, the stack had to be adjusted contain it.
Change-Id: Ia392341970fb86c0426cf2229b1a7295453e2e32
Signed-off-by: Louis Mayencourt <louis.mayencourt@arm.com>
=> fvp: Increase the size of the stack for FVP

include/arch/aarch64/arch.h, lib/cpus/aarch64/neoverse_n1.S
This patch applies the new MSR instruction to directly set the
PSTATE.SSBS bit which controls speculative loads. This new instruction
is available on Neoverse N1 core so it's utilised.
Change-Id: Iee18a8b042c90fdb72d2b98f364dcfbb17510728
=> Apply variant 4 mitigation for Neoverse N1

plat/rockchip/common/params_setup.c, plat/rockchip/rk3328/platform.mk, plat/rockchip/rk3368/platform.mk, plat/rockchip/rk3399/platform.mk
The Rockchip ATF platform can be entered from both Coreboot and U-Boot.
While Coreboot does submit the list of linked parameter structs as
platform param, upstream u-boot actually always provides a pointer
to a devicetree as parameter.
This results in current ATF not running at all when started from U-Boot.
To fix this, add a stub that checks if the parameter is a fdt so we
can at least boot and not get stuck. Later on we can extend this with
actual parsing of information from the devicetree.
Signed-off-by: Heiko Stuebner <heiko@sntech.de>
Cc: Philipp Tomsich <philipp.tomsich@theobroma-systems.com>
=> rockchip: add an fdt parsing stub for platform param

lib/el3_runtime/aarch64/context.S, plat/arm/common/aarch64/arm_pauth.c
- Fix restoring APIBKey registers
- Put Pointer Authentication key value in BSS section
=> Pointer authentication fixes

Makefile, docs/firmware-design.rst, docs/user-guide.rst
Declare ENABLE_PAUTH and CTX_INCLUDE_PAUTH_REGS
build options as experimental.
Pointer Authentication is enabled for Non-secure world
irrespective of the value of these build flags if the
CPU supports it.
The patch also fixes the description of fiptool 'help' command.
Change-Id: I46de3228fbcce774a2624cd387798680d8504c38
=> Declare ENABLE_PAUTH build option as experimental

lib/xlat_tables_v2/xlat_tables_core.c, lib/xlat_tables_v2/xlat_tables_utils.c
This commit reverts the following commits:
- c54c7fc35842 ("xlat_tables_v2: print xlat tables without recursion")
- db8cac2d986a ("xlat_tables_v2: unmap region without recursion.")
- 0ffe269215bd ("xlat_tables_v2: map region without recursion.")
This was part of PR #1843.
A problem has been detected in one of our test run configurations
involving dynamic mapping of regions and it is blocking the next
release. Until the problem can be solved, it is safer to revert
the changes.
Change-Id: I3d5456e4dbebf291c8b74939c6fb02a912e0903b
=> xlat_tables_v2: Revert recent changes to remove recursion

lib/cpus/aarch64/cortex_a76.S
Remove the static !DYNAMIC_WORKAROUND_CVE_2018_3639 check and add a runtime assert after the new SSBS check, in case SSBS is not implemented. This allows platforms that know they don't need the dynamic firmware workaround (e.g. they know all CPUs are an SSBS-enabled version of A76) to compile out all code under DYNAMIC_WORKAROUND_CVE_2018_3639.
=> Cortex-A76: Optimize CVE_2018_3639 workaround

docs/romlib-design.rst, lib/romlib/Makefile, lib/romlib/genwrappers.sh, plat/arm/board/fvp/jmptbl.i, plat/arm/board/juno/jmptbl.i
Fixed the below bugs:
1) Bug related to build flag V=1: if the flag is V=0, building with
ROMLIB fails.
2) Due to a syntax bug in genwrappers.sh, index file entries marked as
"patch" or "reserved" were ignored.
3) Added a prepending hash to constants that genwrappers.sh is generating.
4) Due to broken dependencies, currently the inclusion functionality is
intentionally not utilised. This is why the contents of romlib/jmptbl.i
have been copied to platform specific jmptbl.i files. As a result of the
broken dependencies, when changing the index files (e.g. when patching
functions) a clean build is always required. This is a known issue that
will be fixed in the future.
Change-Id: I9d92aa9724e86d8f90fcd3e9f66a27aa3cab7aaa
=> ROMLIB bug fixes

drivers/synopsys/emmc/dw_mmc.c
dw_params.mmc_dev_type should be assigned before mmc_init, otherwise SDMMC
initialization will fail as the initialization treats the device as EMMC
instead of SD.
=> driver: synosys: Fix SD MMC not initializing correctly

bl31/aarch64/bl31_entrypoint.S
The relocation fixup code must be called at the beginning of bl31
entrypoint to ensure that CPU specific reset handlers are fixed up for
relocations.
=> PIE: Fix reloc at the beginning of bl31 entrypoint

docs/user-guide.rst
The latest version of GCC are required to use the new features of TF-A.
Suggest to use the latest version available on developer.arm.com instead
of the version specified on the Linaro Release notes.
At the time of writing, GCC 8.2-2019.01 is the latest version available.
=> doc: Suggest to use the latest version of GCC 8.2

plat/renesas/rcar/bl2_plat_setup.c
The M3W ULCB board has 2 GiB of DRAM, set it so.
=> rcar_gen3: plat: Set M3W ULCB DRAM size to 2 GiB

include/arch/aarch64/arch.h, lib/xlat_tables/aarch64/xlat_tables.c, lib/xlat_tables_v2/aarch64/xlat_tables_arch.c, services/std_svc/spm/spm_main.c, services/std_svc/spm/spm_private.h, services/std_svc/spm/spm_setup.c, services/std_svc/spm/spm_shim_private.h, services/std_svc/spm/spm_xlat.c
Move shim layer mapping to TTBR1_EL1 to allow partitions to reduce the address space size in TBBR0_EL0. This way they need less memory for translation tables as there can be less levels of translation.
Check the individual commits for more information.
=> SPM: Some improvements to xlat handling code
