docs/cpu-specific-build-macros.md, docs/firmware-design.md, docs/interrupt-framework-design.md, docs/porting-guide.md, docs/rt-svc-writers-guide.md, docs/user-guide.md
Fixes arm-software/tf-issues#276
=> Create TOC links in the User Guide markdown file

Makefile, docs/change-log.md, docs/firmware-design.md, docs/rt-svc-writers-guide.md, readme.md
Final updates to readme.md and change-log.md for ARM Trusted Firmware version
1.1. Also increment the version in the Makefile.
Change-Id: Ib001a6ec9a9c570985841d06f0ff80ed76c2996b
=> Documentation for version 1.1

Makefile, docs/user-guide.md, drivers/arm/cci/cci.c, drivers/arm/cci400/cci400.c, drivers/io/io_fip.c, include/common/bl_common.h, include/drivers/arm/cci.h, include/lib/aarch64/arch.h, lib/aarch64/xlat_tables.c, plat/fvp/aarch64/fvp_common.c, plat/fvp/fvp_def.h, plat/fvp/fvp_pm.c, plat/fvp/fvp_private.h, plat/fvp/include/plat_macros.S, plat/fvp/platform.mk, plat/juno/aarch64/juno_common.c, plat/juno/bl1_plat_setup.c, plat/juno/bl31_plat_setup.c, plat/juno/include/plat_macros.S, plat/juno/juno_def.h, plat/juno/juno_private.h, plat/juno/plat_pm.c, plat/juno/platform.mk
This pull request contains changes for implementing a common driver for ARM Cache coherent Interconnects and use it for the platform ports of FVP and Juno
=> Common driver for ARM cache coherent Interconnects

drivers/arm/gic/arm_gic.c
On a GICv2 system, the group status of PPIs and SGIs is set in the GICD_IGROUPR0
register. On a GICv3 system, if affinity routing is enabled for the non-secure
state, then the group status of PPIs and SGIs should be set in the GICR_IGROUPR0
register. ARM Trusted firmware sets the group status using the GICv2
sequence. On a GICv3 system, if the group status of an interrupt is set to Group
1 through a write to the GICD_IGROUPR0, then the GICR_IGROUPR0 is updated as
well.
The current sequence is incorrect since it first marks all PPIs and SGIs as
Group 1. It then clears the bits in GICD_IGROUPR0 corresponding to secure
interrupts to set their group status to Group 0. This operation is a no-op. It
leaves the secure generic timer interrupt (#29) used by the TSP marked as Group
1. This causes …
=> Set group status of PPIs and SGIs correctly on GICv3 systems

acknowledgements.md, docs/tlk-dispatcher.md, include/bl32/payloads/tlk.h, include/lib/aarch64/arch_helpers.h, services/spd/tlkd/tlkd.mk, services/spd/tlkd/tlkd_common.c, services/spd/tlkd/tlkd_helpers.S, services/spd/tlkd/tlkd_main.c, services/spd/tlkd/tlkd_pm.c, services/spd/tlkd/tlkd_private.h
This topic branch adds the TLK dispatcher to the mix. This dispatcher helps TLK to run with the Trusted Firmware.
Verification: Code compiles with the master branch.
v1: fixes comments from tlkd branch.
v2: fixes comments from tlkd-fixed-v1 branch.
v3: fixes Dan's comments from tlkd-fixed-v2 branch.
=> TLK dispatcher

bl2/bl2_main.c
The return value of bl2_plat_handle_bl30() used to be ignored.
This patch modifies the function load_bl30() so that it now
checks this return value and returns it to bl2_main().
This patch also unifies the error handling code across the
load_blx() functions so that they return a status code in all
cases and bl2_main() has the sole responsibility of panicking
if appropriate.
=> Panic if platform specific BL3-0 handling fails

bl2/bl2_main.c
The return value of bl2_plat_handle_bl30() used to be ignored.
This patch modifies the function load_bl30() so that it now
checks this return value and returns it to bl2_main().
This patch also unifies the error handling code across the
load_blx() functions so that they return a status code in all
cases and bl2_main() has the sole responsibility of panicking
if appropriate.
Change-Id: I2b26cdf65afa443b48c7da1fa7da8db956071bfb
=> Panic if platform specific BL3-0 handling fails v2

services/std_svc/psci/psci_afflvl_on.c
In the debug build of the function get_power_on_target_afflvl(), there is a
check to ensure that the CPU is emerging from a SUSPEND or ON_PENDING state.
The state is checked without acquiring the lock for the CPU node. The state
could be updated to ON_PENDING in psci_afflvl_on() after the target CPU has
been powered up. This results in a race condition which could cause the
check for the ON_PENDING state in get_power_on_target_afflvl() to fail.
This patch resolves this race condition by setting the state of the target
CPU to ON_PENDING before the platform port attempts to power it on. The
target CPU is thus guaranteed to read the correct the state. In case
the power on operation fails, the state of the CPU is restored to OFF.
Fixes ARM-software/tf-issues#302
Change-Id: …
=> PSCI: Set ON_PENDING state early during CPU_ON

bl31/aarch64/runtime_exceptions.S, drivers/arm/gic/arm_gic.c, include/drivers/arm/gic_v2.h
Fixes for tf-issues #305 and #306
=> Ag/tf issues#306

docs/user-guide.md
Linaro produce monthly software releases for the Juno and AEMv8-FVP
platforms. These provide an integrated set of software components
that have been tested together on these platforms.
From now on, it is recommend that Trusted Firmware developers use the
Linaro releases (currently 15.06) as a baseline for the dependent
software components: normal world firmware, Linux kernel and device
tree, file system as well as any additional micro-controller firmware
required by the platform.
This patch updates the user guide to document this new process. It
changes the instructions to get the source code of the full software
stack (including Trusted Firmware) and updates the dependency build
instructions to make use of the build scripts that the Linaro releases
provide.
Change-Id: …
=> Update user guide to use Linaro releases

plat/nvidia/tegra/common/aarch64/tegra_helpers.S, plat/nvidia/tegra/common/drivers/flowctrl/flowctrl.c, plat/nvidia/tegra/common/drivers/pmc/pmc.c, plat/nvidia/tegra/common/tegra_bl31_setup.c, plat/nvidia/tegra/common/tegra_common.mk, plat/nvidia/tegra/common/tegra_delay_timer.c, plat/nvidia/tegra/soc/t210/plat_psci_handlers.c, plat/nvidia/tegra/soc/t210/plat_secondary.c, plat/nvidia/tegra/soc/t210/platform_t210.mk
=> Tegra misc fixes v3

docs/plat/nvidia-tegra.md, include/lib/cpus/aarch64/denver.h, lib/cpus/aarch64/denver.S, plat/nvidia/tegra/common/tegra_common.mk, plat/nvidia/tegra/common/tegra_pm.c, plat/nvidia/tegra/common/tegra_sip_calls.c, plat/nvidia/tegra/include/t132/tegra_def.h, plat/nvidia/tegra/include/tegra_private.h, plat/nvidia/tegra/platform.mk, plat/nvidia/tegra/soc/t132/plat_psci_handlers.c, plat/nvidia/tegra/soc/t132/plat_secondary.c, plat/nvidia/tegra/soc/t132/plat_setup.c, plat/nvidia/tegra/soc/t132/platform_t132.mk, plat/nvidia/tegra/soc/t210/plat_psci_handlers.c, plat/nvidia/tegra/soc/t210/platform_t210.mk
Support for "Project Denver" CPU based platforms
=> Tegra denver plat support v3

drivers/arm/gic/arm_gic.c
From Linux 3.17 onwards, the mainline kernel has support for GICv3
systems and if EL3 exists, it only needs to initialise ICC_SRE_EL3.SRE
and ICC_SRE_EL3.Enable to 1. Hence, this patch removes the redundant
updates of ICC_SRE_EL2 and ICC_PMR_EL1.
NOTE: For partner software's which enter kernel in EL1,
ICC_SRE_EL2.Enable and ICC_SRE_EL2.SRE bit needs to be set to 1
in EL2 before jumping to linux.
Change-Id: I09ed47869351b08a3b034735f532bc677eaa6917
=> Remove EL2/EL1 GICv3 register updates

include/drivers/arm/nic_400.h, include/plat/arm/common/arm_def.h, include/plat/arm/css/common/css_def.h, plat/arm/board/fvp/include/platform_def.h, plat/arm/board/juno/juno_security.c, plat/arm/common/arm_bl31_setup.c, plat/arm/common/arm_security.c, plat/arm/soc/common/soc_css_security.c
Reworked ARM platform port to support  more configuration options for different ARM platforms.
=> Add more configurability options in ARM platform port code

services/std_svc/psci/psci_off.c
This patch fixes an issue in the PSCI framework where the affinity info
state of a core was being set to OFF even when the SPD had denied the
CPU_OFF request. Now, the state remains set to ON instead.
Fixes ARM-software/tf-issues#323
Change-Id: Ia9042aa41fae574eaa07fd2ce3f50cf8cae1b6fc
=> PSCI: Update state only if CPU_OFF is not denied by SPD

docs/user-guide.md, include/plat/arm/common/arm_def.h, include/plat/arm/common/plat_arm.h, include/plat/arm/css/common/css_pm.h, plat/arm/board/fvp/include/platform_def.h, plat/arm/board/juno/include/platform_def.h, plat/arm/board/juno/juno_pm.c, plat/arm/board/juno/platform.mk, plat/arm/common/aarch64/arm_common.c, plat/arm/common/arm_bl31_setup.c, plat/arm/common/arm_pm.c, plat/arm/css/common/css_pm.c, plat/arm/css/common/css_topology.c, plat/arm/soc/common/soc_css.mk
These patches add system power domain node to the topology description
and also enable system support on Juno.
=> Support SYSTEM SUSPEND on Juno

bl1/aarch64/bl1_exceptions.S, bl1/bl1_main.c, bl31/bl31_main.c, common/bl_common.c, include/common/bl_common.h
Various improvements to the code printing debug information
when transitioning from one image to the next.
=> Improve images transitions debugging messages

plat/nvidia/tegra/common/aarch64/tegra_helpers.S, plat/nvidia/tegra/common/drivers/flowctrl/flowctrl.c, plat/nvidia/tegra/common/tegra_common.mk, plat/nvidia/tegra/common/tegra_pm.c, plat/nvidia/tegra/common/tegra_topology.c, plat/nvidia/tegra/include/drivers/flowctrl.h, plat/nvidia/tegra/include/platform_def.h, plat/nvidia/tegra/include/t132/tegra_def.h, plat/nvidia/tegra/include/tegra_private.h, plat/nvidia/tegra/platform.mk, plat/nvidia/tegra/soc/t132/plat_psci_handlers.c, plat/nvidia/tegra/soc/t132/plat_setup.c, plat/nvidia/tegra/soc/t210/plat_psci_handlers.c, plat/nvidia/tegra/soc/t210/plat_setup.c
Support for new platform APIs. Deprecate support for the PLAT_COMPAT layer.
Previous PR - #450
=> Tegra new platform apis v2

bl1/bl1_fwu.c
The current implementation of FWU_SMC_IMAGE_RESUME when called
from the normal world, uses the provided image_id argument to
determine which secure image to resume into. This implies that
the normal world has a choice of which secure image to resume
into when in fact it is only possible to resume into the
previously interrupted secure image.
This patch removes the argument, tightens up the pre-conditions
for the SMC and adds additional asserts.
The pre-conditions for FWU_SMC_SEC_IMAGE_DONE are also
tightened up.
Change-Id: Ia5a46753bb01e8f8dad8a2999314f90db8f300e8
=> FWU: Remove image_id arg from FWU_SMC_IMAGE_RESUME

docs/interrupt-framework-design.md, docs/porting-guide.md, docs/user-guide.md
This patch updates the relevant documentation in ARM Trusted Firmware
for the new GIC drivers. The user-guide.md and porting-guide.md have been
updated as follows:
*  The build option to compile Trusted Firmware with different GIC drivers
for FVP has been explained in the user-guide.md.
*  The implementation details of interrupt management framework porting
APIs for GICv3 have been added in porting-guide.md.
*  The Linaro tracking kernel release does not work OOB in GICv3 mode.
The instructions for changing UEFI configuration in order to run with
the new GICv3 driver in ARM TF have been added to user-guide.md.
The interrupt-framework-design.md has been updated as follows:
*  Describes support for registering and handling interrupts targeted to EL3
e.g. Group 0 interrupts in GICv3.
* …
=> Documentation updates for the new GIC drivers

Makefile, docs/change-log.md, readme.md
Updated readme, changelog and Makefile version number
=> Final v1.2 release changes

docs/user-guide.md
This patch reworks the section about booting an EL3 payload in the
User Guide:
- Centralize all EL3 payload related information in the same
section.
- Mention the possibility to program the EL3 payload in flash memory
and execute it in place.
- Provide model parameters for both the Base and Foundation FVPs.
- Provide some guidance to boot an EL3 payload on Juno.
=> Clarify EL3 payload documentation

docs/firmware-design.md
This patch adds a brief explanation of the top/bottom load approach
to the Firmware Design guide and how Trusted Firmware keeps track of
the free memory at boot time. This will help platform developers to
avoid unexpected results in the memory layout.
Fixes ARM-software/tf-issues#319
Change-Id: I04be7e24c1f3b54d28cac29701c24bf51a5c00ad
=> Improve memory layout documentation

lib/aarch64/xlat_tables.c
The current translation table code maps in a series of regions, zeroing
the unmapped table entries before and in between the mapped regions. It
doesn't, however, zero the unmapped entries after the last mapped
region, leaving those entries at whatever value that memory has
initially.
This is bad because those values can look like valid translation table
entries, pointing to valid physical addresses. The CPU is allowed to do
speculative reads from any such addresses. If the addresses point to
device memory, the results can be unpredictable.
This patch zeroes the translation table entries following the last
mapped region, ensuring all table entries are either valid or zero
(invalid).
In addition, it limits the value of ADDR_SPACE_SIZE to those allowed by
the architecture and supported by …
=> Initialize all translation table entries

drivers/io/io_memmap.c
Hence memmap device can be used to load an image without being wrapped in a
FIP.
Fixes arm-software/tf-issues#371
Signed-off-by: Gerald Lejeune <gerald.lejeune@st.com>
=> Add "size" function to IO memmap device driver

common/tf_printf.c
This patch adds support to differentiate between `long` and `long long`
format specifiers in tf_printf(). In AArch64, they are the same which is
a 64-bit word. But, in AArch32 they are different and tf_printf() needs
to handle these format specifiers separately. This patch also fixes the
type of variables used to generic C types.
Change-Id: If3bbb0245cd0183acbe13bc1fe0d9743f417578f
=> Differentiate `long` and `long long` formats in tf_printf

bl31/aarch64/crash_reporting.S, docs/porting-guide.md, include/plat/arm/common/aarch64/cci_macros.S, include/plat/arm/css/common/aarch64/css_macros.S, plat/arm/board/fvp/include/plat_macros.S, plat/arm/board/juno/include/plat_macros.S, plat/mediatek/mt8173/include/plat_macros.S, plat/nvidia/tegra/include/plat_macros.S, plat/rockchip/common/include/plat_macros.S, plat/xilinx/zynqmp/include/plat_macros.S
Fixes: arm-software/tf-issues#373
Signed-off-by: Gerald Lejeune <gerald.lejeune@st.com>
=> Allow to dump platform-defined regs in crash log

docs/user-guide.md
This patch updates the TF User Guide, simplifying some of the steps
to build and run TF and trying to avoid duplicated information that
is already available on the ARM Connected Community or the Linaro
website.
The recommended Linaro release is now 16.02.
Change-Id: I21db486d56a07bb10f5ee9a33014ccc59ca12986
=> Update User Guide and move up to Linaro 16.02

lib/xlat_tables/xlat_tables_common.c
The only case in which regions can now overlap is if they are
identity mapped or they have the same virtual to physical address
offset (identity mapping is just a particular case of the latter).
They must overlap completely (i.e. one of them must be completely
inside the other one) and not cover the same area.
This allow future enhancements to the xlat_tables library without
having to support unnecessarily complex edge cases.
Outer regions are now sorted by mmap_add_region() before inner
regions with the same base virtual address for consistency: all
regions contained inside another one must be placed after the outer
one in the list.
If an inner region has the same attributes as the outer ones it will
be merged when creating the tables with init_xlation_table(). This
cannot be done as …
=> Limit support for region overlaps in xlat_tables

common/bl_common.c
- Fix the function documentation.
Since commit 16948ae1, load_image() uses image IDs rather than image
names.
- Clarify the consequences of a null entry point argument.
- Slightly reorganize the code to remove an unnecessary 'if' statement.
=> Update comments in load_image()

Makefile, bl31/bl31.ld.S, bl31/bl31.mk, docs/firmware-design.md, docs/porting-guide.md, docs/user-guide.md, include/bl31/services/psci.h, include/lib/pmf.h, include/lib/pmf_helpers.h, lib/pmf/pmf_main.c, lib/pmf/pmf_smc.c, plat/arm/board/juno/juno_pm.c, plat/arm/common/arm_common.mk, services/std_svc/psci/psci_common.c, services/std_svc/psci/psci_main.c, services/std_svc/psci/psci_off.c, services/std_svc/psci/psci_private.h, services/std_svc/psci/psci_setup.c, services/std_svc/psci/psci_stat.c, services/std_svc/psci/psci_suspend.c
This patch-set introduces the Performance Measurement Framework (PMF)
and implements the PSCI_STAT_COUNT and PSCI_STAT_RESIDENCY
APIs.
=> Introduce PMF and implement PSCI STAT APIs

common/bl_common.c, common/runtime_svc.c, include/lib/utils.h, lib/psci/psci_main.c, lib/psci/psci_stat.c
This patch stack introduces minor improvements to harden the code:
some extra checks on input values, some extra debug assertions.
=> Minor improvements to harden TF code

docs/firmware-design.md, docs/user-guide.md
This patch documents the effect, cost and benefits of the
SEPARATE_CODE_AND_RODATA build flag.
=> Documentation for SEPARATE_CODE_AND_RODATA build flag

drivers/io/io_block.c
If buffer address parameter isn't aligned, it may cause
DMA issue in block device driver, as eMMC. Now check the buffer
address. If it's not aligned, use temporary buffer in io block
driver instead.
=> io: block: fix unaligned buffer

tools/fiptool/Makefile
The output is shown only when built with V=1.
Change-Id: I17fef10df6f127f07956a78b478ff3cadba4bd61
=> fiptool: Suppress verbose messages during normal build

common/bl_common.c
At the end of successful image authentication in load_auth_image(),
the data cache for the virtual address range corresponding to the
image is invalidated (by a call to inv_dcache_range()). The intent
seems to be to ensure the data caches do not contain any sensitive
data used during authentication, which subsequent code can read.
However, this same address range is already flushed (cleaned and
invalidated by a call to flush_dcache_range()) at the end of
load_image(), and the subsequent invalidate has no functional
effect.
This patch removes the redundant call to inv_dcache_range(). It
also moves the flush_dcache_range() call from the end of load_image()
to the end of load_auth_image(), so the image data will remain in
the caches during authentication, improving performance.
This also …
=> Remove dcache invalidation after image authentication

plat/rockchip/common/include/plat_private.h, plat/rockchip/common/plat_pm.c, plat/rockchip/rk3399/drivers/pmu/pmu.c, plat/rockchip/rk3399/drivers/pmu/pmu.h
This series patches to make sure the suspend/resume is better, and fixes some bugs.
=> Fixes suspend/resume bugs

drivers/arm/gic/v3/gicv3_main.c
Currently the GICv3 driver mandates that platform populate
both G1S and G0 interrupts. However, it is possible that a
given platform is not interested in both the groups and
just needs to specify either one of them.
This patch modifies the `gicv3_rdistif_init()` & `gicv3_distif_init()`
functions to allow either G1S or G0 interrupts to be configured.
Fixes ARM-software/tf-issues#400
Change-Id: I43572b0e08ae30bed5af9334f25d35bf439b0d2b
=> GICv3: Allow either G1S or G0 interrupts to be configured

docs/firmware-design.md
This patch updates the firmware-design.md for AArch32 related changes.
Change-Id: Idf392a44861ab9c1f59f3de4f3435f508b17c678
=> AArch32: Update firmware-design.md

docs/firmware-design.md
Add a Performance Measurement Framework (PMF) section
to the firmware design document.
Change-Id: I5953bd3b1067501f190164c8827d2b0d8022fc0b
=> PMF: Add documentation

docs/porting-guide.md, drivers/partition/gpt.c, drivers/partition/partition.c, include/drivers/partition/gpt.h, include/drivers/partition/mbr.h, include/drivers/partition/partition.h
Now only support GPT partition table. MBR partition table isn't
supported yet.
=> partition: check GPT partition table

docs/porting-guide.md
fixes ARM-Software/tf-issues#346
Change-Id: I946c8eab650bba7407775462ce91f394d767e079
=> Document plat_psci_ops.(system_off|system_reset)

docs/interrupt-framework-design.md
The API description currently states that interrupt handlers
(interrupt_type_handler_t pointers) SHOULD return a pointer
to the target cpu_context.
This patch rewords the description of the interrupts handlers to state
that it MUST return a pointer to the target security context. It also
warns about potential portability issue. Specifically, this pointer is
not used on AArch64 and calls to context library APIs must be used to
ask BL31 to return to a specific context. However, this could change in
the future and interrupt handlers must always return the pointer.
Change-Id: I3f82a046de4d7a5b51a8cbebe7eb2a00dbbdb4f0
=> Docs: Clarify IRQ/FIQ handler API in Interrupt Design Guide

services/spd/trusty/trusty.c
- Fix a compilation warning message showing in release builds only
- Fix a coding style issue
=> Minor fixes in the Trusty SPD code

lib/locks/bakery/bakery_lock_normal.c
This patch fixes an issue in the normal memory bakery lock
implementation. During assertion of lock status, there is a possibility
that the assertion could fail. This is because the previous update done
to the lock status by the owning CPU when not participating in cache
coherency could result in stale data in the cache due to cache maintenance
operations not propagating to all the caches. This patch fixes this issue
by doing an extra read cache maintenance operation prior to the assertion.
Fixes ARM-software/tf-issues#402
Change-Id: I0f38a7c52476a4f58e17ebe0141d256d198be88d
=> Fix normal memory bakery lock implementation

common/bl_common.c
When loading and authenticating an image, all parent images must also
be authenticated. The parent images are just certificates that don't
need to be used by any other CPU except the one loading the image, and
so there is no need to flush the cache of memory regions where they
are loaded.
Change-Id: Ice8d6979d1c02eabf1a543281ae1a07d098e4a99
=> Optimize cache flush when authenticating images

tools/fiptool/fiptool.c
See individual commits for details.  This prepares the ground for some upcoming features.
=> Various fiptool enhancements and bug fixes

docs/user-guide.md
Change-Id: I28b2790ff2f87b9fe3cf1020e59e1e0a00be6f97
=> Docs: Fix monospace formatting in user guide

include/lib/stdlib/sys/uuid.h, tools/fiptool/fiptool.c, tools/fiptool/fiptool.h, tools/fiptool/tbbr_config.c, tools/fiptool/tbbr_config.h
See individual commits for details.
=> fiptool: Add support for operating on binary blobs using the UUID

drivers/auth/mbedtls/mbedtls_crypto.c, drivers/auth/mbedtls/mbedtls_x509_parser.c, include/lib/stdlib/string.h, lib/stdlib/stdlib.mk, lib/stdlib/timingsafe_bcmp.c
See individual commits for details.
=> Import constant-time bcmp() and use it where necessary

plat/common/tbbr/plat_tbbr.c
These are equivalent so use the reduced form.
Change-Id: I40ca097411b9abab69985b8e4dbccf7582eae49e
=> tbbr: Simplify conditional

drivers/io/io_memmap.c
The memmap IO driver doesn't perform bounds check when reading, writing,
or seeking. The onus to vet parameters is on the caller, and this patch
asserts that:
- non-negative size is specified for for backing memory;
- valid parameters are passed into the driver for read, write and seek
operations.
Change-Id: I6518c4065817e640e9e7e39a8a4577655f2680f7
=> Add bounds checking asserts to memmap IO driver

services/spd/tspd/tspd_main.c
ABORT SMC used to return to the previously executing world, which
happened to be S-EL1 as it calls a TSP handler using synchronous entry
into the TSP.
Now properly save and restore the non-secure context (including system
registers) and return to non-secure world as it should.
fixes ARM-Software/tf-issues#453
Change-Id: Ie40c79ca2636ab8b6b2ab3106e8f49e0f9117f5f
=> Fix TSPD implementation of STD SMC ABORT

docs/firmware-design.md
Fixes ARM-software/tf-issues#463
Change-Id: I73e0c5fbd87004953df8b1fa19319ad562ecc867
=> firmware-design: Fix typo in ToC header flags specification

Makefile
At present, the build option checks are done prior to inclusion of
BL makefiles. This meant if the BL makefiles modified any of the options
then these checks were bypassed. This patch corrects this problem.
Change-Id: I0b591392a74d6d456d2b19bbe292f42b5aeae048
=> Include all makefiles before build option checks

bl1/bl1_main.c, bl2/bl2_main.c, bl2u/bl2u_main.c, bl31/aarch64/crash_reporting.S, bl31/bl31_main.c, common/aarch32/debug.S, common/aarch64/debug.S, docs/porting-guide.md, drivers/arm/pl011/aarch32/pl011_console.S, drivers/arm/pl011/aarch64/pl011_console.S, drivers/cadence/uart/aarch64/cdns_console.S, drivers/console/aarch32/console.S, drivers/console/aarch32/skeleton_console.S, drivers/console/aarch64/console.S, drivers/console/aarch64/skeleton_console.S, drivers/ti/uart/aarch64/16550_console.S, include/drivers/console.h, include/plat/common/platform.h, lib/psci/psci_system_off.c, lib/stdlib/assert.c, plat/arm/common/aarch32/arm_helpers.S, plat/arm/common/aarch64/arm_helpers.S, plat/common/aarch32/platform_helpers.S, plat/common/aarch64/platform_helpers.S, plat/mediatek/common/drivers/uart/8250_console.S
For more details, check the individual commits.
=> Implement console_flush()

plat/nvidia/tegra/common/drivers/smmu/smmu.c, plat/nvidia/tegra/common/tegra_common.mk, plat/nvidia/tegra/platform.mk, plat/nvidia/tegra/soc/t132/plat_psci_handlers.c
Enable the 'ENABLE_ASSERTIONS' macro for Tegra platforms
=> Asserts release nvidia

lib/xlat_tables/xlat_tables_common.c
-1 is not a defined mmap_attr_t type. Instead of using invalid enum
types, we can either choose to define a INVALID type OR handle the
condition specifically.
Since the usage of mmap_region_attr is limited, it is easier to just
handle the error condition specifically and return 0 or -1 depending
on success or fail.
Fixes: ARM-Software/tf-issues#473
Fixes: 28fa2e9ee8f4 ("xlat lib: Use mmap_attr_t type consistently")
Signed-off-by: Nishanth Menon <nm@ti.com>
=> xlat lib: Don't set mmap_attr_t enum to be -1

Makefile, make_helpers/build_macros.mk, make_helpers/unix.mk, make_helpers/windows.mk
Fixes for arm-software/tf-issues#474
These are simple makefile issues, with no functional impact.
=> Minor makefile fixes

plat/rockchip/common/drivers/parameter/ddr_parameter.c, plat/rockchip/common/drivers/parameter/ddr_parameter.h, plat/rockchip/rk3328/drivers/pmu/plat_pmu_macros.S, plat/rockchip/rk3328/drivers/pmu/pmu.c, plat/rockchip/rk3328/drivers/pmu/pmu.h, plat/rockchip/rk3328/drivers/soc/soc.c, plat/rockchip/rk3328/drivers/soc/soc.h, plat/rockchip/rk3328/include/plat.ld.S, plat/rockchip/rk3328/include/platform_def.h, plat/rockchip/rk3328/platform.mk, plat/rockchip/rk3328/rk3328_def.h
Change-Id: I7f54f45db65f32481cc05e1bd2c9c683b756e19a
=> Use SPDX license identifiers for remaining files

include/lib/xlat_tables/xlat_tables_v2.h, lib/xlat_tables_v2/aarch64/xlat_tables_arch.c, lib/xlat_tables_v2/xlat_tables_common.c, lib/xlat_tables_v2/xlat_tables_private.h
- Fix some comments.
- Remove duplicated definition.
- Make xlat_arch_get_max_supported_pa() private in aarch64.
=> Minor fixes to the xlat tables lib v2

Makefile, bl1/aarch32/bl1_context_mgmt.c, bl1/aarch32/bl1_entrypoint.S, bl1/aarch32/bl1_exceptions.S, bl1/bl1_fwu.c, bl1/bl1_main.c, bl2u/aarch32/bl2u_entrypoint.S, bl2u/bl2u.mk, bl2u/bl2u_main.c, bl32/sp_min/aarch32/entrypoint.S, bl32/sp_min/sp_min_main.c, common/tf_printf.c, include/lib/aarch32/smcc_helpers.h, include/lib/aarch32/smcc_macros.S, include/plat/arm/common/arm_def.h, lib/compiler-rt/LICENSE.TXT, lib/compiler-rt/builtins/arm/aeabi_uldivmod.S, lib/compiler-rt/builtins/assembly.h, lib/compiler-rt/builtins/int_endianness.h, lib/compiler-rt/builtins/int_lib.h, lib/compiler-rt/builtins/int_math.h, lib/compiler-rt/builtins/int_types.h, lib/compiler-rt/builtins/int_util.c, lib/compiler-rt/builtins/int_util.h, lib/compiler-rt/builtins/udivmoddi4.c, lib/compiler-rt/compiler-rt.mk, make_helpers/tbbr/tbbr_tools.mk, plat/arm/board/fvp/platform.mk, plat/arm/common/arm_bl2u_setup.c
This has only been tested on the FVP models.  Juno is not currently supported.
=> Add TBBR and FWU support for AArch32

plat/hisilicon/hikey/hikey_bl31_setup.c, plat/hisilicon/hikey/hikey_pm.c, plat/hisilicon/hikey/hikey_topology.c, plat/hisilicon/hikey/platform.mk
Fix https://github.com/ARM-software/tf-issues/issues/484
=> Finish hikey psci

docs/firmware-design.md
Change-Id: Ic0a9b3c6d212e7171b37f944e11f079282dcce87
Signed-off-by: Summer Qin <summer.qin@arm.com>
=> Update the path for firmware_image_package.h in firmware-design.md

plat/hisilicon/hikey/hisi_sip_svc.c, plat/hisilicon/hikey/include/hisi_sip_svc.h, plat/hisilicon/hikey/platform.mk
This patch enable PMF and runtime instrumentation for hikey
=> Enable pmf rt instr hikey

drivers/ufs/ufs.c, plat/hisilicon/hikey960/hikey960_boardid.c
Fix issues in https://github.com/ARM-software/tf-issues/issues/494
=> Fix hikey960

bl1/aarch32/bl1_arch_setup.c, bl1/aarch32/bl1_context_mgmt.c, bl1/aarch64/bl1_arch_setup.c, bl1/aarch64/bl1_context_mgmt.c, bl1/bl1_fwu.c, bl32/sp_min/sp_min_main.c, drivers/delay_timer/delay_timer.c, drivers/delay_timer/generic_delay_timer.c, drivers/io/io_dummy.c, drivers/io/io_storage.c, include/lib/aarch32/smcc_helpers.h, include/lib/el3_runtime/context_mgmt.h, lib/psci/psci_system_off.c
This P-R propose few minor implementation fixes toward strict types use and prototypes declaration.
=> Minor build fixes

docs/user-guide.md
Updated section 6, building a FIP for Juno and FVP, adding
instructions for AArch32 and AArch64.
Updated section 4.1, summary of build options, to include a
description of the `JUNO_AARCH32_EL3_RUNTIME` build flag.
Change-Id: I4ed006522cab981371c382859063f088fbfcb8f7
Signed-off-by: Isla Mitchell <isla.mitchell@arm.com>
=> Add Juno AArch32 and AArch64 User Guide instructions

docs/change-log.rst
Updated change-log.rst with summary of changes since release v1.3.
Change-Id: Iecd31ed315bd9ad7ffe8bce6550f7c90e1e3a9b0
=> Release v1.4: update change-log.rst

readme.rst
Update the release notes (readme.rst) for the ARM Trusted Firmware v1.4 release.
Also, reorder and fix some of the links following the conversion to
reStructured text format.
Change-Id: I8f5e8aa86cb891f61b6b62cf9fab0ad0f0ebb36b
=> Update readme for v1.4 release

docs/user-guide.rst
Change-Id: I0cd355d9fc7f14fb4eabb443d596d6f0858f609e
Signed-off-by: Eleanor Bonnici <Eleanor.bonnici@arm.com>
=> Updates user guide following out of box testing.

Makefile
Change-Id: I8676a22649dce92d0ddd98013fc6dafcfbe94c90
=> Release v1.4: Update minor version number to 4

plat/rockchip/rk3399/drivers/pmu/pmu.c
This patch fixes the two things as follows:
1) rk3399_flash_l2_b" seems to be a typo. That's "flush", not "flash".
2) fixes the warnings log.
We always hit the warnings thing during the suspend, as below log:
..
[   51.022334] CPU5: shutdown
[   51.025069] psci: CPU5 killed.
INFO:    sdram_params->ddr_freq = 928000000
WARNING: rk3399_flash_l2_b:reg 28830380,wait
When the L2 completes the clean and invalidate sequence, it asserts the
L2FLUSHDONE signal. The SoC can now deassert L2FLUSHREQ signal and then
the L2 deasserts L2FLUSHDONE.
Then, a loop without a delay isn't really great to measure time. We should
probably add a udelay(10) or so in there and then maybe replace the WARN()
after the loop. In the actual tests, the L2 cache will take ~4ms by
default for big cluster.
In the real world …
=> rockchip/rk3399: fixes the typo and the WARNINGS during suspend/resume

docs/plat/hikey960.rst, plat/hisilicon/hikey960/aarch64/hikey960_common.c, plat/hisilicon/hikey960/hikey960_bl2_setup.c, plat/hisilicon/hikey960/hikey960_def.h, plat/hisilicon/hikey960/hikey960_io_storage.c, plat/hisilicon/hikey960/include/platform_def.h, plat/hisilicon/hikey960/platform.mk
=> hikey960 updates

docs/plat/hikey.rst, plat/hisilicon/hikey/aarch64/hikey_common.c, plat/hisilicon/hikey/hikey_bl2_setup.c, plat/hisilicon/hikey/hikey_def.h, plat/hisilicon/hikey/hikey_io_storage.c, plat/hisilicon/hikey/include/platform_def.h, plat/hisilicon/hikey/platform.mk
=> hikey: Add BL32 (OP-TEE) support v2

readme.rst
Clarify the license information for imported third party code in
the readme.rst file.
Change-Id: I96e26fda687a290a6dffb475aca20b169d85784d
=> Clarify third party license info in readme

lib/psci/psci_on.c
There is a theoretical edge case during CPU_ON where the cache
may contain stale data for the target CPU data - this can occur
under the following conditions:
- the target CPU is in another cluster from the current
- the target CPU was the last CPU to shutdown on its cluster
- the cluster was removed from coherency as part of the CPU shutdown
In this case the cache maintenace that was performed as part of the
target CPUs shutdown was not seen by the current CPU's cluster. And
so the cache may contain stale data for the target CPU.
This patch adds a cache maintenance operation (flush) for the
cache-line containing the target CPU data - this ensures that the
target CPU data is read from main memory.
Change-Id: If8cfd42639b03174f60669429b7f7a757027d0fb
Signed-off-by: David Cunado …
=> Address edge case for stale PSCI CPU data in cache

Makefile, docs/firmware-design.rst
2 minor fixes related to documentation.
=> Minor docs

docs/plat/hikey.rst, plat/hisilicon/hikey/aarch64/hikey_common.c, plat/hisilicon/hikey/hikey_bl1_setup.c, plat/hisilicon/hikey/hikey_bl2_mem_params_desc.c, plat/hisilicon/hikey/hikey_bl2_setup.c, plat/hisilicon/hikey/hikey_bl31_setup.c, plat/hisilicon/hikey/hikey_def.h, plat/hisilicon/hikey/hikey_image_load.c, plat/hisilicon/hikey/hikey_io_storage.c, plat/hisilicon/hikey/include/platform_def.h, plat/hisilicon/hikey/platform.mk, plat/hisilicon/hikey960/aarch64/hikey960_common.c, plat/hisilicon/hikey960/hikey960_bl1_setup.c, plat/hisilicon/hikey960/hikey960_bl2_mem_params_desc.c, plat/hisilicon/hikey960/hikey960_bl2_setup.c, plat/hisilicon/hikey960/hikey960_bl31_setup.c, plat/hisilicon/hikey960/hikey960_image_load.c, plat/hisilicon/hikey960/hikey960_io_storage.c, plat/hisilicon/hikey960/hikey960_private.h, plat/hisilicon/hikey960/include/platform_def.h, plat/hisilicon/hikey960/platform.mk
=> hikey*: Add LOAD_IMAGE_V2 and OP-TEE header parsing support

plat/hisilicon/hikey/hikey_bl2_setup.c, plat/hisilicon/hikey/include/platform_def.h, plat/hisilicon/hikey960/hikey960_bl2_setup.c, plat/hisilicon/hikey960/include/platform_def.h
=> hikey*: boot without spd

lib/xlat_tables_v2/xlat_tables_internal.c
Use a mmap_region_t as parameter instead of getting a parameter for each
structure member. This reduces the scope of changes when adding members
to mmap_region_t.
Also align on the convention of using mm_cursor as a variable name for
the currently inspected region when iterating on the region array.
Change-Id: If40bc4351b56c64b214e60dda27276d11ce9dbb3
=> xlat: simplify mmap_add_region_check parameters

docs/plat/hikey.rst, docs/plat/hikey960.rst
=> hikey*: Update docs

services/spd/trusty/trusty.c
Currently, Trusty OS/LK implemented FPU context switch in internal
thread switch but does not implement the proper mechanism for world
switch. This commit just simply saves/restores FPU registes in world
switch to prevent FPU context from being currupted when Trusty OS uses
VFP in its applications.
It should be noted that the macro *CTX_INCLUDE_FPREGS* must be defined
in trusty.mk if Trusty OS uses VFP
Signed-off-by: goodbach <goodbach@gmail.com>
=> trusty: save/restore FPU registers in world switch

include/lib/psci/psci.h, lib/psci/psci_main.c, lib/psci/psci_private.h, lib/psci/psci_setup.c, lib/psci/psci_system_off.c, plat/arm/css/common/css_pm.c, plat/arm/css/drivers/scp/css_pm_scmi.c, plat/arm/css/drivers/scp/css_scp.h
Integration of reset2 PSCI v1.1 functionality.
=> Integration of reset2 PSCI v1.1 functionality

docs/plat/poplar.rst
The document was being rendered incorrectly.
=> poplar: Fix format of documentation

plat/hisilicon/poplar/aarch64/platform_common.c, plat/hisilicon/poplar/bl2_plat_setup.c, plat/hisilicon/poplar/bl31_plat_setup.c, plat/hisilicon/poplar/include/hi3798cv200.h, plat/hisilicon/poplar/include/platform_def.h, plat/hisilicon/poplar/include/poplar_layout.h, plat/hisilicon/poplar/plat_storage.c, plat/hisilicon/poplar/platform.mk
=> poplar: Add BL32 (OP-TEE) support and misc updates

services/std_svc/spm/spm_main.c
This partially reverts commit d6b532b50f8, keeping only the fixes to
the assertions. The changes related to the order of arguments passed
to the secure partition were not correct and violated the
specification of the SP_EVENT_COMPLETE SMC.
This patch also improves the MM_COMMUNICATE argument validation.  The
cookie argument, as it comes from normal world, can't be trusted and thus
needs to always be validated at run time rather than using an assertion.
Also validate the communication buffer address and return
INVALID_PARAMETER if it is zero, as per the MM specification.
Fix a few typos in comments and use the "secure partition" terminology
rather than "secure payload".
=> SPM: Fix MM_COMMUNICATE_AARCH32/64 parameters

common/tf_printf.c
Add support to formats %i, %d, %p, %x and %u for left-padding numbers with zeroes (e.g. `%08x`).
=> Add support to left-pad with zeroes in tf_printf

plat/hisilicon/hikey960/hikey960_bl1_setup.c
=> hikey960: set isp clks as unsecure mode

plat/hisilicon/poplar/bl1_plat_setup.c, plat/hisilicon/poplar/bl2_plat_setup.c, plat/hisilicon/poplar/include/hi3798cv200.h, plat/hisilicon/poplar/include/platform_def.h, plat/hisilicon/poplar/include/poplar_layout.h, plat/hisilicon/poplar/plat_storage.c, plat/hisilicon/poplar/platform.mk
=> poplar: Enable emmc and recovery build support

plat/hisilicon/hikey960/hikey960_bl31_setup.c
When some interrupts are configured as group 0 in GICv2, these
interrupts trigger FIQ signal; this results in the Linux kernel panic
by reporting log: "Bad mode in FIQ handler detected on CPU0, code
0x00000000 -- Unknown/Uncategorized".  Unfortunately from kernel side it
has no permission to read the GIC register for group 0 interrupts so we
have no chance to get to know which interrupt is configured as secure
interrupt and cause the kernel panic.
For upper reason, this commit enables FIQ exception handling for
SPD_none case.  If the system has not enabled SPD the FIQ interrupt is
trapped into EL3 and the FIQ handler can report the interrupt number so
we can easily narrow down which FIQ introduce unexpected interrupt.
After enable SPD we can rely on SPD interrupt route model to handle …
=> Hikey960: Enable invalid FIQ handling

maintainers.rst
=> maintainers.rst: Add maintainer for plat Poplar

bl1/bl1.ld.S, bl2/bl2.ld.S, bl2/bl2_el3.ld.S, bl2u/bl2u.ld.S, bl31/aarch64/bl31_entrypoint.S, bl31/bl31.ld.S, bl32/sp_min/sp_min.ld.S, bl32/tsp/tsp.ld.S, include/lib/xlat_tables/xlat_mmu_helpers.h, include/lib/xlat_tables/xlat_tables_defs.h, lib/psci/aarch32/psci_helpers.S, lib/psci/aarch64/psci_helpers.S, plat/mediatek/mt6795/bl31.ld.S
- Add a missing TLBI during warm boot when the dynamic translation tables support is enabled.
- Improve comments related to the translation tables library.
For more details, check the individual commit messages.
=> Clarify comments in xlat tables lib and fixes related to the TLB

docs/spd/trusty-dispatcher.rst, plat/nvidia/tegra/common/tegra_bl31_setup.c, services/spd/trusty/generic-arm64-smcall.c, services/spd/trusty/generic-arm64-smcall.h, services/spd/trusty/trusty.c, services/spd/trusty/trusty.mk
Trusty spd updates. Restore trusty setup code and add some missing patches.
=> Trusty fixes

Makefile
Change-Id: Ib215150272acc2ecec43f9b69624ebbbd5d7492d
=> Release v1.5: Update minor version number to 5

plat/rockchip/rk3399/drivers/pmu/pmu.c
there are two fix for save/restore watchdog register:
1. watchdog plck will shutdown after secure_watchdog_disable(), so need
to save register before it and restore after secure_watchdog_enable().
2. need write 0x76 to cnt_restart to keep watchdog alive when restore
watchdog register.
Change-Id: I1f6fbceae22186e3b72a87df6332a110adf37479
Signed-off-by: Lin Huang <hl@rock-chips.com>
=> rockchip/rk3399: save/restore watchdog register correctly

plat/arm/board/sgi575/platform.mk, plat/arm/css/sgi/aarch64/sgi_helper.S, plat/arm/css/sgi/include/plat_macros.S, plat/arm/css/sgi/include/platform_def.h, plat/arm/css/sgi/include/sgi_plat_config.h, plat/arm/css/sgi/include/sgi_variant.h, plat/arm/css/sgi/sgi-common.mk, plat/arm/css/sgi/sgi_bl1_setup.c, plat/arm/css/sgi/sgi_bl31_setup.c, plat/arm/css/sgi/sgi_gic_config.c, plat/arm/css/sgi/sgi_interconnect.c, plat/arm/css/sgi/sgi_plat.c, plat/arm/css/sgi/sgi_plat_config.c, plat/arm/css/sgi/sgi_security.c, plat/arm/css/sgi/sgi_topology.c
Add support for System Guidance for Infrastructure platform SGI575.
Change-Id: I0125c2ed4469fbc8367dafcc8adce770b6b3147d
Signed-off-by: Nariman Poushin <nariman.poushin@linaro.org>
=> ARM platforms: Add support for SGI575

lib/xlat_tables_v2/xlat_tables_internal.c
The last entry in the mapping table is not necessarily the same as the
end of the table. This patch loops through the table to find the last
entry marker, on every new mmap addition. The memove operation then
has to only move the memory between current entry and the last entry.
For platforms that arrange their MMIO map properly, this opearation
turns out to be a NOP.
The previous implementation added significant overhead per mmap
addition as the memmove operation always moved the difference between
the current mmap entry and the end of the table.
Tested on Tegra platforms and this new approach improves the memory
mapping time by ~75%, thus significantly reducing boot time on some
platforms.
Change-Id: Ie3478fa5942379282ef58bee2085da799137e2ca
Signed-off-by: Varun Wadekar …
=> lib: xlat_tables_v2: reduce time required to add a mmap region

bl1/bl1_fwu.c, bl1/tbbr/tbbr_img_desc.c, bl2/bl2_image_load.c, bl2/bl2_image_load_v2.c, bl32/tsp/tsp_private.h, drivers/auth/auth_mod.c, drivers/auth/crypto_mod.c, drivers/auth/mbedtls/mbedtls_common.c, include/bl2/bl2.h, include/common/tbbr/tbbr_img_def.h, include/drivers/auth/auth_mod.h, include/drivers/auth/crypto_mod.h, include/drivers/auth/img_parser_mod.h, plat/arm/board/fvp/fvp_private.h, plat/arm/common/arm_bl1_fwu.c, plat/arm/common/arm_dyn_cfg_helpers.c, plat/arm/css/drivers/scp/css_pm_scmi.c, plat/arm/css/drivers/scp/css_pm_scpi.c, services/spd/tspd/tspd_private.h
Fix MISRA defects for rules 8.3, 8.4, 8.5 and 8.8
=> Misra changes

bl32/tsp/tsp_interrupt.c, bl32/tsp/tsp_main.c, drivers/arm/gic/gic_v3.c, include/lib/aarch64/arch_helpers.h, include/lib/stdlib/machine/_types.h, plat/common/aarch64/plat_common.c, plat/hisilicon/hikey/hikey_bl1_setup.c, plat/mediatek/common/custom/oem_svc.c, plat/mediatek/common/mtk_plat_common.c, plat/mediatek/common/mtk_plat_common.h, plat/mediatek/common/mtk_sip_svc.c, plat/nvidia/tegra/common/tegra_sip_calls.c, plat/nvidia/tegra/soc/t186/drivers/mce/mce.c, plat/rockchip/common/params_setup.c, plat/rockchip/common/rockchip_sip_svc.c, plat/rockchip/rk3368/plat_sip_calls.c, plat/rockchip/rk3399/plat_sip_calls.c, plat/xilinx/zynqmp/plat_startup.c, plat/xilinx/zynqmp/sip_svc_setup.c, services/spd/opteed/opteed_main.c, services/spd/opteed/opteed_pm.c, services/spd/tlkd/tlkd_main.c, services/spd/tlkd/tlkd_pm.c, services/spd/trusty/trusty.c, services/spd/tspd/tspd_main.c, services/spd/tspd/tspd_pm.c, services/spd/tspd/tspd_private.h
=> Use consistent int-ll64 typedefs for aarch32 and aarch64

include/common/aarch64/el3_common_macros.S
File: include/common/aarch64/el3_common_macros.S
Change-Id: I619401e961a3f627ad8864781b5f90bc747c3ddb
Signed-off-by: Qixiang Xu <qixiang.xu@arm.com>
=> Correct some typo errors in comment

common/runtime_svc.c, plat/arm/common/arm_bl2_setup.c
Reverts ARM-software/arm-trusted-firmware#1389
Causes build failures.
=> Revert "Code change to fix small bugs"

common/bl_common.c, common/tf_printf.c, drivers/arm/gic/v3/gicv3_helpers.c, drivers/arm/gic/v3/gicv3_main.c, drivers/arm/gic/v3/gicv3_private.h, drivers/arm/smmu/smmu_v3.c, drivers/arm/tzc/tzc400.c, include/common/bl_common.h, include/lib/xlat_tables/aarch32/xlat_tables_aarch32.h, include/lib/xlat_tables/aarch64/xlat_tables_aarch64.h, lib/cpus/aarch64/cpuamu.c, lib/locks/bakery/bakery_lock_coherent.c, lib/locks/bakery/bakery_lock_normal.c, lib/optee/optee_utils.c, lib/psci/psci_private.h, plat/arm/css/drivers/mhu/css_mhu_doorbell.h, plat/arm/css/drivers/scmi/scmi_private.h, plat/arm/css/drivers/scp/css_pm_scmi.c, plat/arm/css/drivers/sds/sds_private.h, services/spd/opteed/opteed_main.c, services/spd/opteed/opteed_pm.c, services/spd/opteed/opteed_private.h, services/spd/tspd/tspd_private.h
Changes to make the code base compliant with MISRA rules 5.1, 5.3 & 5.7
=> MISRA 5.1, 5.3 & 5.7 compliance changes

bl31/bl31.ld.S, include/lib/xlat_tables/xlat_mmu_helpers.h, include/plat/arm/common/arm_def.h, include/services/secure_partition.h, lib/xlat_tables_v2/aarch32/xlat_tables_arch.c, lib/xlat_tables_v2/aarch64/xlat_tables_arch.c, plat/arm/common/arm_common.c, services/std_svc/spm/sp_setup.c
For more details, check the individual commits.
=> Minor fixes to SPM

lib/cpus/aarch64/cortex_a57.S, lib/cpus/aarch64/cortex_a72.S, lib/cpus/aarch64/cortex_a73.S, lib/cpus/aarch64/cortex_a75.S
Change-Id: I18a41bb9fedda635c3c002a7f112578808410ef6
=> cpulib: Add ISBs or comment why they are unneeded

plat/xilinx/zynqmp/aarch64/zynqmp_common.c, plat/xilinx/zynqmp/include/platform_def.h
Patches to fix issue https://github.com/ARM-software/tf-issues/issues/589
=> xilinx: fix zynqmp build when tsp is enabled

docs/user-guide.rst, drivers/auth/mbedtls/mbedtls_common.mk
To build with the new release, we pick couple of more files from mbedTLS
library.
Change-Id: I77dfe5723284cb26d4e5c717fb0e6f6dd803cb6b
=> Move to mbedtls-2.10.0 tag

include/plat/arm/board/common/board_arm_def.h
Change-Id: I67e64bb79cc984ea3263f069e22738a42321c46d
=> fvp: Increase BL2 size for TBBR builds

plat/ti/k3/common/k3_psci.c, plat/ti/k3/common/k3_topology.c, plat/ti/k3/include/platform_def.h
This set is a couple trivial fixups that were found during internal review.
=> Couple of fixups for K3 platform

include/lib/xlat_tables/xlat_tables_v2.h, include/lib/xlat_tables/xlat_tables_v2_helpers.h, lib/xlat_tables_v2/aarch32/xlat_tables_arch.c, lib/xlat_tables_v2/aarch32/xlat_tables_arch_private.h, lib/xlat_tables_v2/aarch64/xlat_tables_arch.c, lib/xlat_tables_v2/aarch64/xlat_tables_arch_private.h, lib/xlat_tables_v2/xlat_tables.mk, lib/xlat_tables_v2/xlat_tables_context.c, lib/xlat_tables_v2/xlat_tables_core.c, lib/xlat_tables_v2/xlat_tables_private.h, lib/xlat_tables_v2/xlat_tables_utils.c
Cleanup of the code. The update to the documentation will come shortly.
=> Refactor of the xlat tables v2 library

drivers/io/io_fip.c
Platform can define MAX_NUM_FIP_DEVICES in platform_def.h
to define the number of FIP io devices.
Signed-off-by: Ruchika Gupta <ruchika.gupta@nxp.com>
=> Extend FIP io driver to support multiple FIP devices

include/plat/arm/board/common/board_arm_def.h, include/plat/arm/common/arm_def.h, include/plat/arm/common/plat_arm.h, include/plat/arm/css/common/css_def.h, plat/arm/board/common/board_css_common.c, plat/arm/board/juno/include/platform_def.h, plat/arm/common/arm_bl1_setup.c, plat/arm/common/arm_bl2_el3_setup.c, plat/arm/common/arm_bl2_setup.c, plat/arm/common/arm_bl2u_setup.c, plat/arm/common/arm_bl31_setup.c, plat/arm/common/arm_common.c, plat/arm/common/sp_min/arm_sp_min_setup.c, plat/arm/common/tsp/arm_tsp_setup.c, plat/ti/k3/common/k3_bl31_setup.c, plat/xilinx/zynqmp/bl31_zynqmp_setup.c, plat/xilinx/zynqmp/tsp/tsp_plat_setup.c
Change arm_setup_page_tables() to take a variable number of memory
regions
Change-Id: I790054e3b20b056dda1043a4a67bd7ac2d6a3bc0
=> Rework page table setup for varying number of mem regions

readme.rst
Added information on how disjunctively dual licensed code from
other projects is treated in the TF-A project.
Change-Id: Idca329abba4d36bd3c4fd722ac1556940b9135a2
=> Update license information in readme.rst

plat/arm/board/sgm775/fdts/sgm775_tb_fw_config.dts, plat/arm/board/sgm775/include/platform_def.h, plat/arm/board/sgm775/platform.mk, plat/arm/common/arm_tzc_dmc500.c, plat/arm/css/common/css_topology.c, plat/arm/css/drivers/scp/css_pm_scmi.c, plat/arm/css/sgm/aarch64/css_sgm_helpers.S, plat/arm/css/sgm/fdts/sgm_tb_fw_config.dts, plat/arm/css/sgm/include/plat_macros.S, plat/arm/css/sgm/include/platform_oid.h, plat/arm/css/sgm/include/sgm_base_platform_def.h, plat/arm/css/sgm/include/sgm_plat_config.h, plat/arm/css/sgm/include/sgm_variant.h, plat/arm/css/sgm/sgm-common.mk, plat/arm/css/sgm/sgm_bl1_setup.c, plat/arm/css/sgm/sgm_bl31_setup.c, plat/arm/css/sgm/sgm_interconnect.c, plat/arm/css/sgm/sgm_mmap_config.c, plat/arm/css/sgm/sgm_plat_config.c, plat/arm/css/sgm/sgm_security.c, plat/arm/css/sgm/sgm_topology.c, plat/arm/css/sgm/tsp/sgm_tsp_setup.c, plat/arm/css/sgm/tsp/tsp-sgm.mk
This set of commits adds support for the Arm System Guidance for Mobile (SGM) fixed virtual platform, akin to the System Guidance for Infrastructure (SGI) previously contributed.
=> Add support for Arm System Guidance for Mobile fixed virtual platform

drivers/mmc/mmc.c
A new function mmc_reset_to_idle is also created.
=> mmc: add required delays when retrying commands

readme.rst
Fixes ARM-software/tf-issues#607
Change-Id: I5637f53e7f4857c85ee8b3af06ebcf86b9e4f1bc
=> readme: Add information about the TF-A IRC channel

drivers/console/aarch64/multi_console.S
Change-Id: Ibac859c4bcef0e92a0dcacc6b58ac19bc69b8342
=> Console: Use callee-saved registers

docs/psci-pd-tree.rst
Change-Id: I426ffc8717757e35e556f675162a729ba095b7d5
=> Fix typo in documentation page title

docs/user-guide.rst
Change-Id: Ice87052e41a24b0ede5610467e12941ae1d886e0
=> DTC: Add recommended device tree compiler version

bl31/ehf.c, include/bl31/ehf.h, include/bl31/interrupt_mgmt.h, include/common/param_header.h, include/drivers/arm/gic_common.h, include/lib/el3_runtime/aarch64/context.h, include/lib/extensions/ras.h, include/lib/extensions/ras_arch.h, include/services/sdei.h, lib/extensions/ras/ras_common.c, lib/extensions/ras/std_err_record.c, plat/arm/common/arm_sip_svc.c, plat/arm/common/execution_state_switch.c, services/std_svc/sdei/sdei_event.c, services/std_svc/sdei/sdei_intr_mgmt.c, services/std_svc/sdei/sdei_main.c, services/std_svc/sdei/sdei_private.h, services/std_svc/sdei/sdei_state.c
MISRA fixes for SDEI, RAS, and EHF. Also some functional fixes for SDEI.
=> MISRA fixes

lib/optee/optee_utils.c
Updated the code to fix issue https://github.com/ARM-software/tf-issues/issues/603 related to the tee-validate-header bug.
=> Update optee_utils.c to fix ARM-software/tf-issues#603

lib/extensions/ras/std_err_record.c
Change-Id: Ia02a2dbfd4e25547776e78bed40a91f3452553d7
=> RAS: Fix assert condition

Makefile
Change-Id: I67382383fc9d18ab57c7e51f793145cb14c6fec5
=> Update release minor version string

docs/firmware-design.rst, docs/porting-guide.rst, docs/user-guide.rst
Change-Id: I69e2720f534583a0f8d0e44f2e7b6f393f6fd093
=> docs: update for removal of deprecated interfaces.

docs/plaform-compatibility-policy.rst, docs/porting-guide.rst
Information regarding platform compatibility policy
is added to the documentation.
Change-Id: If9f2a11160f81354ee2c678f0fca9d67fc7366e6
=> docs: Add platform compatibility policy document

Makefile
Change-Id: Icbc556d47a58d0870577b1bf1cd27cc5827fd56d
=> Update the version to 2.0

docs/change-log.rst, readme.rst
Change-Id: Iaa5c586b65f0abdd4ddbdee4c73d07811a0aff49
Signed-off-by: Joanna Farley <joanna.farley@arm.com>
=> Release docs updates for v2.0 release

maintainers.rst
Signed-off-by: Nariman Poushin <nariman.poushin@linaro.org>
=> maintainers: Correct github username for nariman to npoushin

bl31/aarch64/bl31_entrypoint.S, common/bl_common.c, common/desc_image_load.c, common/runtime_svc.c, include/common/bl_common.h, include/common/fdt_wrappers.h, include/common/runtime_svc.h, include/lib/aarch32/smccc_helpers.h, include/lib/aarch64/smccc_helpers.h, include/lib/pmf/pmf_asm_macros.S, include/lib/runtime_instr.h, include/plat/common/common_def.h
=> Remove some MISRA defects in common code

include/common/runtime_svc.h, include/plat/arm/board/common/v2m_def.h, plat/arm/board/fvp/drivers/pwrc/fvp_pwrc.h, plat/arm/board/fvp/fvp_def.h, plat/arm/board/fvp/fvp_pm.c, plat/arm/common/arm_pm.c
Change-Id: Ia00eba2b18804e6498d935d33ec104953e0e5e03
=> Fix misra warnings in SMC and power mgmt code

lib/psci/psci_common.c
Here are the two first patches of the pull request [here](https://github.com/ARM-software/arm-trusted-firmware/pull/1553). As these two patches are not the subject of that pull request and are a bit less controversial I'd like to get them in independently here.
Thanks,
Andrew
=> PSCI cache flush and comment fixup

drivers/partition/partition.c
=> drivers: partition: correct compilation error in VERBOSE mode

docs/plat/stm32mp1.rst
Add U-Boot compilation information.
Add a chapter about how to populate SD-card.
=> docs: stm32mp1: complete compilation and flashing steps

common/fdt_wrappers.c, include/common/fdt_wrappers.h, include/lib/libc/string.h, lib/libc/libc.mk, lib/libc/strlcpy.c
Introduce helpers to read strings and arrays of 32-bit cells.
=> Introduce new fdt helpers

drivers/renesas/rcar/watchdog/swdt.c, drivers/staging/renesas/rcar/ddr/ddr_a/ddr_init_e3.c, drivers/staging/renesas/rcar/ddr/ddr_a/ddr_init_e3.h, plat/renesas/rcar/aarch64/plat_helpers.S, plat/renesas/rcar/bl2_cpg_init.c
Target builds but has not been tested.
Signed-off-by: ldts <jorge.ramirez.ortiz@gmail.com>
=> rcar_gen3: E3 target: fix compilation issues

drivers/arm/ccn/ccn.c, include/drivers/arm/ccn.h
Signed-off-by: Pankaj Gupta <pankaj.gupta@nxp.com>
=> ccn: Introduce API to set and read value of node register

docs/marvell/build.txt, drivers/marvell/ap807_clocks_init.c, drivers/marvell/comphy/phy-comphy-common.h, drivers/marvell/comphy/phy-comphy-cp110.c, drivers/marvell/comphy/phy-comphy-cp110.h, include/drivers/marvell/ap807_clocks_init.h, plat/marvell/a3700/common/plat_pm.c, plat/marvell/a8k/a80x0/board/phy-porting-layer.h, plat/marvell/a8k/common/a8k_common.mk, plat/marvell/a8k/common/mss/mss_pm_ipc.c, plat/marvell/a8k/common/plat_ble_setup.c, plat/marvell/a8k/common/plat_pm.c, plat/marvell/common/mrvl_sip_svc.c, plat/marvell/version.mk
Sync with Marvell branch "atf-v2.0-devel-18.12"
=> Update code with latest changes from Marvell LSP 18.12

plat/arm/board/sgiclarkh/fdts/sgiclarkh_nt_fw_config.dts, plat/arm/board/sgiclarkh/fdts/sgiclarkh_tb_fw_config.dts, plat/arm/board/sgiclarkh/include/platform_def.h, plat/arm/board/sgiclarkh/platform.mk, plat/arm/board/sgiclarkh/sgiclarkh_plat.c, plat/arm/board/sgiclarkh/sgiclarkh_security.c, plat/arm/css/sgi/include/sgi_variant.h, plat/arm/css/sgi/sgi_bl31_setup.c, plat/arm/css/sgi/sgi_topology.c
These patches depend on https://github.com/ARM-software/arm-trusted-firmware/pull/1713 which has to get merged before this PR gets merged.
These patches add the platform and board support for SGI-Clark.Helios platform.
=> SGI-Clark.Helios platform support patches

drivers/console/multi_console.c
Change-Id: I2d67bb1bebd15e6a7d69ea5e7b6fda9c972f9d86
=> multi_console: Check functions are not NULL

drivers/rpi3/gpio/rpi3_gpio.c, include/drivers/rpi3/gpio/rpi3_gpio.h, plat/rpi3/platform.mk, plat/rpi3/rpi3_bl2_setup.c, plat/rpi3/rpi3_hw.h
Hello. I'm adding this GPIO driver for reviewing. I plan to implement a SDHost driver in ATF so that we can load FIP from the SDCard directly. The SDHost driver needs to set the GPIO alt function and tweak the pull resistors. Thus this driver is needed. Many Thanks.
=> Rpi3 gpio driver

drivers/partition/partition.c, drivers/synopsys/ufs/dw_ufs.c, drivers/ufs/ufs.c
Signed-off-by: Florian La Roche <Florian.LaRoche@gmail.com>
=> Change some vars and functions to be static.

drivers/partition/partition.c
This is to add simple MBR partition entry support. This will read all four
MBR partition into the partition list, and the partition type will be saved
in the list.name[0] entry.
Signed-off-by: Loh Tien Hock <tien.hock.loh@intel.com>
=> drivers: partition: Add simple MBR partition entries support

bl31/bl31_main.c, bl31/ehf.c, docs/arm-sip-service.rst, docs/exception-handling.rst, docs/firmware-design.rst, docs/platform-interrupt-controller-API.rst, docs/porting-guide.rst, docs/ras.rst, docs/sdei.rst, docs/user-guide.rst, drivers/arm/css/scpi/css_scpi.c, drivers/arm/gic/v2/gicv2_main.c, include/lib/el3_runtime/pubsub.h, include/lib/extensions/ras.h, lib/el3_runtime/aarch64/context.S, make_helpers/defaults.mk, plat/common/aarch64/platform_mp_stack.S
Fix some typos and clarify some sentences.
=> Minor changes to documentation and comments

Makefile, docs/plat/nvidia-tegra.rst, docs/user-guide.rst, include/common/bl_common.h, include/lib/el3_runtime/pubsub.h, lib/cpus/aarch32/cpu_helpers.S, lib/cpus/aarch64/cpu_helpers.S, make_helpers/build_macros.mk, plat/nvidia/tegra/platform.mk, plat/nvidia/tegra/scat/bl31.scat
This is actually a PR to get some thoughts on the approach. This has been verified for Tegra platforms only.
=> Tegra scatter file support

lib/xlat_tables_v2/xlat_tables_core.c
This PR creates several helper functions to reduce cyclomatic complexity metric for  xlat_tables_map_region/unmap_region functions.
fixes arm-software/tf-issues#673
=> Reduce cyclomatic complexity metric

plat/intel/soc/stratix10/drivers/qspi/cadence_qspi.c, plat/intel/soc/stratix10/drivers/qspi/cadence_qspi.h
To support the enablement of QSPI booting
Signed-off-by: Muhammad Hadi Asyrafi Abdul Halim <muhammad.hadi.asyrafi.abdul.halim@intel.com>
=> intel: Add driver for QSPI

drivers/intel/soc/stratix10/io/s10_memmap_qspi.c, plat/intel/soc/stratix10/aarch64/stratix10_private.h, plat/intel/soc/stratix10/bl2_plat_setup.c, plat/intel/soc/stratix10/plat_storage.c, plat/intel/soc/stratix10/platform.mk
Manages QSPI initialization, configuration and IO handling as boot device
Signed-off-by: Muhammad Hadi Asyrafi Abdul Halim <muhammad.hadi.asyrafi.abdul.halim@intel.com>
=> intel: QSPI boot enablement

Makefile, lib/aarch64/misc_helpers.S
fix minor typo and linking with pie with binutils > 2.27
=> PIE: fix linking with pie and binutils > 2.27 

Makefile, docs/firmware-design.rst
Change-Id: I56ea088f415bdb9077c385bd3450ff4b2cfa2eac
=> Allow setting compiler's target architecture

docs/user-guide.rst
Change-Id: I1854b5830dbd48e909a4ce1b931c13fb3e997600
=> Update documentation for mbed TLS v2.16

include/lib/cpus/aarch64/neoverse_zeus.h, lib/cpus/aarch64/neoverse_zeus.S, plat/arm/board/fvp/platform.mk
Change-Id: If56d1e200a31bd716726d7fdc1cc0ae8a63ba3ee
=> Introduce preliminary support for Neoverse Zeus

include/lib/cpus/aarch64/neoverse_e1.h
Change-Id: I75ee39d78c81ecb528a671c0cfadfc2fe7b5d818
=> Fix MIDR_EL1 value for Neoverse E1

bl31/aarch64/runtime_exceptions.S
Change-Id: I8fb346743b7afddbb8bf5908db4f27ee5a26f99b
=> Restore PAuth context in case of unknown SMC call

docs/user-guide.rst
Change-Id: I4261fec500184383980b7fc9475620a485cf6c28
=> Add USE_ROMLIB build option to user guide

docs/user-guide.rst
Make sure the steps in the user guide are up to date and can be
performed out of the box.
=> Update user guide for 2.1 release

docs/change-log.rst
Change-Id: Ib6a20ffdddad11b9629d7dca7f841182299bf860
=> doc: Update change log for v2.1

docs/contents.rst, readme.rst
Prepares the primary readme file for the v2.1 release and adds a contents page for the documentation
=> doc: Prepare readme for 2.1 release

docs/user-guide.rst, readme.rst
Update both the readme and user guide on their shared "platform" section.
=> Documentation: update tested platforms

docs/change-log.rst
Change-Id: Ib37215ca4c9b515e54054290952eed5034582ba4
=> docs: List MB version dependancy for Juno FWU as known issue

Makefile
Change-Id: I6d8a6419df4d4924214115facbce90715a1a0371
=> Update TF-A version to 2.1

docs/change-log.rst, readme.rst
These SPM-related specifications are mentioned in the readme and
the change log. Update references to these specs to make it clear
that they are in draft form and are expected to change.
Change-Id: Ia2791c48c371a828246d96f102a402747cd69f96
=> doc: Clarify draft status of SPCI and SPRT specs

plat/intel/soc/stratix10/bl2_plat_setup.c, plat/intel/soc/stratix10/drivers/wdt/watchdog.c, plat/intel/soc/stratix10/drivers/wdt/watchdog.h, plat/intel/soc/stratix10/include/s10_clock_manager.h, plat/intel/soc/stratix10/platform.mk, plat/intel/soc/stratix10/soc/s10_clock_manager.c
Watchdog driver support & enablement during platform setup
Signed-off-by: Muhammad Hadi Asyrafi Abdul Halim <muhammad.hadi.asyrafi.abdul.halim@intel.com>
=> intel: Enable watchdog timer on Intel S10 platform

.gitignore, docs/plat/meson-gxl.rst, drivers/meson/gxl/crypto/sha_dma.c, include/drivers/meson/gxl/crypto/sha_dma.h, maintainers.rst, plat/meson/gxl/aarch64/gxl_helpers.S, plat/meson/gxl/gxl_bl31_setup.c, plat/meson/gxl/gxl_common.c, plat/meson/gxl/gxl_def.h, plat/meson/gxl/gxl_efuse.c, plat/meson/gxl/gxl_mhu.c, plat/meson/gxl/gxl_pm.c, plat/meson/gxl/gxl_private.h, plat/meson/gxl/gxl_scpi.c, plat/meson/gxl/gxl_sip_svc.c, plat/meson/gxl/gxl_thermal.c, plat/meson/gxl/gxl_topology.c, plat/meson/gxl/include/plat_macros.S, plat/meson/gxl/include/platform_def.h, plat/meson/gxl/platform.mk, readme.rst, tools/meson/Makefile, tools/meson/doimage.c
This patchset adds support for Amlogic s905x aka GXL boards. It has been tested on a lepotato board and boot up a Linux fine.
=> Add support for Amlogic s905x (GXL)

contributing.rst, docs/frequently-asked-questions.rst, docs/user-guide.rst, readme.rst
Update the documentation for trustedfirmware.org migration
=> doc: Update contribution guidelines
