- plat/fvp/fvp_def.h
- plat/juno/juno_def.h
In both FVP and Juno ports, IRQ #16, which is a PPI, is incorrectly
identified as secure SGI #8 through the constant IRQ_SEC_SGI_8.
This patch removes it.
Fixes ARM-software/tf-issues#282
> Remove IRQ_SEC_SGI_8 constant

- bl2/bl2_main.c
This patch initializes the version field in the bl30_image_info
structure when loading BL30. This initialization must be done before
calling load_image().
Fixes ARM-software/tf-issues#274
Change-Id: I74a05167d66fff51d257ad611abc7b5436e5d912
> Bug fix: initialize bl30_image_info fields before use

- include/lib/aarch64/arch_helpers.h
Calls to system register read accessors functions may be optimised
out by the compiler if called twice in a row for the same register.
This is because the compiler is not aware that the result from
the instruction may be modified by external agents. Therefore, if
nothing modifies the register between the 2 reads as far as the
compiler knows then it might consider that it is useless to read
it twice and emit only 1 call.
This behaviour is faulty for registers that may not have the same
value if read twice in succession. E.g.: counters, timer
control/countdown registers, GICv3 interrupt status registers and
so on.
The same problem happens for calls to system register write
accessors functions. The compiler might optimise out some calls
if it considers that it will produce the same result. …
> Prevent optimisation of sysregs accessors calls

- docs/user-guide.md
Previously, the User Guide recommended launching the Foundation
FVP with the parameter --no-secure-memory, which disabled security
control of the address map. This was due to missing support for
secure memory regions in v1 of the Foundation FVP. This is no longer
needed as secure memory is now supported on the Foundation FVP.
This patch updates the User Guide to recommend enabling secure
memory instead.
> User Guide: Enable secure memory on Foundation FVP

- Makefile
- docs/user-guide.md
This patch allows to define the name of the FIP at build time by
defining the FIP_NAME variable. If FIP_NAME is not defined, default
name 'fip.bin' is used.
Documentation updated accordingly.
Change-Id: Ic41f42aac379b0c958b3dfd02863ba8ba7108710
> Specify FIP filename at build time

- docs/firmware-design.md
- plat/juno/include/platform_def.h
- plat/juno/juno_def.h
This patch allows the BL3-1 NOBITS section to overlap the BL1 R/W
section since the former will always be used after the latter.
Similarly, the BL3-2 NOBITS section can overlay the BL2 image
when BL3-2 is loaded in Trusted SRAM.
Due to the current size of the images, there is no actual overlap.
Nevertheless, this reorganization may help to optimise the Trusted
SRAM usage when the images size grows.
Note that because BL3-1 NOBITS section is allowed to overlap the
BL1 R/W section, BL1 global variables will remain valid only until
execution reaches the BL3-1 entry point during a cold boot.
Documentation updated accordingly.
Fixes ARM-software/tf-issues#254
Change-Id: Id538f4d1c7f1f7858108280fd7b97e138572b879
> Juno: Add support for image overlaying in Trusted SRAM

- include/bl31/cpu_data.h
- lib/cpus/aarch64/cpu_helpers.S
- services/std_svc/psci/psci_setup.c
This patch fixes a crash due to corruption of cpu_ops
data structure. During the secondary CPU boot, after the
cpu_ops has been initialized in the per cpu-data, the
dcache lines need to invalidated so that the update in
memory can be seen later on when the dcaches are turned ON.
Also, after initializing the psci per cpu data, the dcache
lines are flushed so that they are written back to memory
and dirty dcache lines are avoided.
Fixes ARM-Software/tf-issues#271
Change-Id: Ia90f55e9882690ead61226eea5a5a9146d35f313
> Invalidate the dcache after initializing cpu-ops

- include/bl31/runtime_svc.h
- include/bl31/services/psci.h
- services/std_svc/psci/psci_afflvl_off.c
- services/std_svc/psci/psci_afflvl_on.c
- services/std_svc/psci/psci_afflvl_suspend.c
- services/std_svc/psci/psci_common.c
- services/std_svc/psci/psci_main.c
- services/std_svc/psci/psci_private.h
- services/std_svc/psci/psci_setup.c
- services/std_svc/psci/psci_system_off.c
This patch-set reworks the MIGRATE, MIGRATE_INFO_TYPE and MIGRATE_INFO_UP_CPU PSCI APIs. It also implements the FEATURES API which is a mandatory API in PSCI 1.0 specification.
> Rework PSCI migrate APIs and implement the FEATURES API

- include/bl31/runtime_svc.h
- include/bl31/services/psci.h
- services/std_svc/psci/psci_afflvl_off.c
- services/std_svc/psci/psci_afflvl_on.c
- services/std_svc/psci/psci_afflvl_suspend.c
- services/std_svc/psci/psci_common.c
- services/std_svc/psci/psci_main.c
- services/std_svc/psci/psci_private.h
- services/std_svc/psci/psci_setup.c
- services/std_svc/psci/psci_system_off.c
This patch-set reworks the MIGRATE, MIGRATE_INFO_TYPE and MIGRATE_INFO_UP_CPU PSCI APIs. It also implements the FEATURES API which is a mandatory API in PSCI 1.0 specification.
> Rework PSCI migrate APIs and implement the FEATURES API v2

- bl31/interrupt_mgmt.c
- docs/user-guide.md
- include/bl31/interrupt_mgmt.h
- services/spd/tspd/tspd.mk
- services/spd/tspd/tspd_main.c
- services/spd/tspd/tspd_pm.c
- services/spd/tspd/tspd_private.h
This patch provides an option to specify a interrupt routing model
where non-secure interrupts (IRQs) are routed to EL3 instead of S-EL1.
When such an interrupt occurs, the TSPD arranges a return to
the normal world after saving any necessary context. The interrupt
routing model to route IRQs to EL3 is enabled only during STD SMC
processing. Thus the pre-emption of S-EL1 is disabled during Fast SMC
and Secure Interrupt processing.
A new build option TSPD_ROUTE_NS_INT_EL3 is introduced to change
the non secure interrupt target execution level to EL3.
Fixes ARM-software/tf-issues#225
Change-Id: Ia1e779fbbb6d627091e665c73fa6315637cfdd32
> Demonstrate model for routing IRQs to EL3

- bl31/aarch64/bl31_entrypoint.S
- docs/firmware-design.md
- docs/porting-guide.md
- include/common/bl_common.h
- include/lib/cpus/aarch64/cpu_macros.S
- lib/cpus/aarch64/cortex_a53.S
- lib/cpus/aarch64/cortex_a57.S
- lib/cpus/aarch64/cpu_helpers.S
- plat/juno/aarch64/plat_helpers.S
- services/std_svc/psci/psci_entry.S
This patch adds support to call the reset_handler() function in BL3-1 in the
cold and warm boot paths when another Boot ROM reset_handler() has already run.
This means the BL1 and BL3-1 versions of the CPU and platform specific reset
handlers may execute different code to each other. This enables a developer to
perform additional actions or undo actions already performed during the first
call of the reset handlers e.g. apply additional errata workarounds.
Typically, the reset handler will be first called from the BL1 Boot ROM. Any
additional functionality can be added to the reset handler when it is called
from BL3-1 resident in RW memory. The constant FIRST_RESET_HANDLER_CALL is used
to identify whether this is the first version of the reset handler code to be
executed or an overridden …
> Call reset handlers upon BL3-1 entry.

- docs/porting-guide.md
- lib/cpus/aarch64/cortex_a53.S
- lib/cpus/aarch64/cortex_a57.S
- lib/cpus/aarch64/cpu_helpers.S
The CPU specific reset handlers no longer have the freedom
of using any general purpose register because it is being invoked
by the BL3-1 entry point in addition to BL1. The Cortex-A57 CPU
specific reset handler was overwriting x20 register which was being
used by the BL3-1 entry point to save the entry point information.
This patch fixes this bug by reworking the register allocation in the
Cortex-A57 reset handler to avoid using x20. The patch also
explicitly mentions the register clobber list for each of the
callee functions invoked by the reset handler
Change-Id: I28fcff8e742aeed883eaec8f6c4ee2bd3fce30df
> Fix the Cortex-A57 reset handler register usage

- docs/firmware-design.md
- docs/porting-guide.md
- lib/cpus/aarch64/cortex_a53.S
- lib/cpus/aarch64/cortex_a57.S
- lib/cpus/aarch64/cpu_helpers.S
The CPU specific reset handlers no longer have the freedom
of using any general purpose register because it is being invoked
by the BL3-1 entry point in addition to BL1. The Cortex-A57 CPU
specific reset handler was overwriting x20 register which was being
used by the BL3-1 entry point to save the entry point information.
This patch fixes this bug by reworking the register allocation in the
Cortex-A57 reset handler to avoid using x20. The patch also
explicitly mentions the register clobber list for each of the
callee functions invoked by the reset handler
Change-Id: I28fcff8e742aeed883eaec8f6c4ee2bd3fce30df
> Fix the Cortex-A57 reset handler register usage v2

- docs/user-guide.md
Move up the version numbers in the user guide of:
* DS-5 (to v5.20)
* EDK2 (to v2.1-rc0)
* Linux Kernel (to 1.3-Juno)
* Linaro file-system (to 14.12)
* Juno SCP binary (to 1.5.0-rc0 within board recovery image 0.10.1).
Also remove duplicate information that is available from the
ARM Connected Community website.
* Base FVP (to 6.2)
* Foundation FVP (to 9.1). Also update the name of the Foundation
FVP binary since it has changed since version 2.1.
Co-Authored-By: Dan Handley <dan.handley@arm.com>
Change-Id: I1cf2f2b1a3f1b997ac905a4ab440876d265698c0
> Move up dependency versions in user guide

- docs/porting-guide.md
- docs/trusted-board-boot.md
- docs/user-guide.md
This patch updates the user-guide.md with the various build options related to
Trusted Board Boot and steps to build a FIP image which includes this
support. It also adds a trusted-board-boot.md which describes the scope and
design of this feature.
Change-Id: Ifb421268ebf7e06a135684c8ebb04c94835ce061
> TBB: Add documentation for Trusted Board Boot

- docs/user-guide.md
The command line options specified in the User Guide to run the AEMv8 Base FVP
with the legacy VE memory map apply only when the model is configured to use GIC
v2.0. This patch adds the 'gicv3.gicv2-only=1' to the command line to ensure
that the right version of GIC is used.
Change-Id: I34c44e19fd42c29818b734ac8f6aa9bf97b4e891
> Fix model command line for legacy VE memory map

- plat/fvp/aarch64/fvp_common.c
- plat/fvp/fvp_def.h
- plat/fvp/include/platform_def.h
- plat/juno/aarch64/juno_common.c
- plat/juno/include/platform_def.h
- plat/juno/juno_def.h
This patch defines MAX_MMAP_REGIONS separately for each BL stage
as per its requirements. This minimizes the size of the mmap[]
array.
Fixes ARM-Software/tf-issues#201
Change-Id: I19b15e1a91a8365b2ecf24e2cd71937cb73916b2
> Minimize MAX_MMAP_REGIONS for each BL stage

- plat/juno/juno_def.h
- plat/juno/plat_security.c
By default the SMMU for the DMA-330 is configured to mark some stream IDs
as always belonging to the Secure world. As a result, if EL1 software turns
the SMMU on, certain Non-Secure accesses get rewritten as Secure, making
them bypass translation and access Secure physical addresses directly.
Since the current Juno board firmware configures the DMA-330 hardware as
Non-Secure, rewrite the SMMU's default SSD table as well to prevent any
unexpected behaviour in EL1.
Change-Id: Iaa81d883eecf28d80eb182b9ce475684bf9c718c
> Juno: clear DMA-330 SMMU security state

- Makefile
- common/tf_printf.c
- plat/fvp/fvp_pm.c
- plat/juno/bl31_plat_setup.c
- plat/juno/plat_topology.c
- services/std_svc/psci/psci_afflvl_suspend.c
- services/std_svc/psci/psci_common.c
The C library source files embedded into the Trusted Firmware
tree are not required to comply to the Linux Coding Style.
Unfortunately, 'make checkpatch' does take them into account.
This patch modifies the Makefile so that the C library source
and header files are now ignored by 'make checkpatch'.
It also instructs the checkpatch.pl script to not treat the
presence of a 'Change-Id' line in the commit message as an error.
> Ignore C library files when checking coding style

- docs/trusted-board-boot.md
- tools/cert_create/src/cert.c
This patch replaces SHA1 by SHA256 in the 'cert_create' tool, so
certificate signatures are generated according to the NSA Suite B
cryptographic algorithm requirements.
Documentation updated accordingly.
Change-Id: I7be79e6b2b62dac8dc78a4f4f5006e37686bccf6
> TBB: use SHA256 to generate the certificate signatures

- Makefile
By default, the checkpatch script requires that commit references
included in commit messages follow a predefined format. Github
merge commits do not follow this convention, causing the code
style test to fail when a new pull request is created.
This patch adds the ignore GIT_COMMIT_ID option to the checkpatch
parameters. This flag indicates the tool to ignore the commit
message format.
Change-Id: I37133cc5cf803f664b8ff00f62d458b39f06918c
> checkpatch: ignore GIT_COMMIT_ID

- bl31/runtime_svc.c
- bl32/tsp/tsp_main.c
- include/common/debug.h
- include/stdlib/stdio.h
- plat/juno/bl1_plat_setup.c
This patch modifies the declarations of the functions printf() et al.
and adds the right GCC attribute to request the compiler to check
the type of the arguments passed to these functions against the given
format string. This will ensure that the compiler outputs warning
messages like the following whenever it detects an inconsistency:
file.c:42: warning: format ‘%d’ expects type ‘int’, but argument 3 has type ‘long int’
It also fixes the type mismatch inconsistencies that it revealed
across the code base.
NOTE: THIS PATCH MAY FORCE PLATFORM PORTS OR SP/SPDS THAT USE THE
PRINTF FAMILY OF FUNCTIONS TO FIX ANY TYPE MISMATCH INCONSISTENCIES.
> Enable type-checking of arguments passed to printf() et al.

- Makefile
Build target 'all' fails when GENERATE_COT=1 and no BL3-3 or
BL3-0 (if required) images are specified. The reason is that,
when GENERATE_COT=1, a dependency on the certificates is added
to the target 'all', and the certificates depend on the BL3-3
and BL3-0 images, causing the build process to fail if the
images are not specified.
This patch moves the dependency on the certificates from 'all' to
'fip'. Target 'all' may be used to build the individual images.
The certificates will be created by calling the target 'fip', where
BL3-3 and BL3-0 (if required) must be specified.
Change-Id: I870beb4e8f9f1bfad1d35b09c850a7ce3c9f4ec6
> TBB: fix build target 'all' dependency on certificates

- plat/juno/platform.mk
Cortex-A57 erratum #806969 applies to revision r0p0 of the CPU
but does not manifest itself on Juno r0. It is not applicable
to Juno r1 in any case.
This patch modifies the Juno platform Makefile to no longer
compile this erratum workaround in.
> Juno: Disable workaround for Cortex-A57 erratum #806969

- include/lib/cpus/aarch64/cortex_a72.h
- lib/cpus/aarch64/cortex_a72.S
This patch adds support for ARM Cortex-A72 processor in the CPU
specific framework.
Change-Id: I5986855fc1b875aadf3eba8c36e989d8a05e5175
> Add support for ARM Cortex-A72 processor

- plat/juno/aarch64/plat_helpers.S
- plat/juno/juno_def.h
For Juno r0, the platform reset handler needs to:
- Implement the workaround for defect #831273
- Increase the L2 Data and Tag RAM latencies for Cortex-A57.
Defect #831273 does not affect Juno r1. Also, the default value
for the L2 Tag RAM latency for Cortex-A57 is suitable on Juno r1.
The L2 Data RAM latency for Cortex-A57 still needs to be
increased, though.
This patch modifies the Juno platform reset handler to detect
the board revision and skip the unnecessary steps on Juno r1.
The behaviour on Juno r0 is unchanged.
> Add support for Juno r1 in the platform reset handler

- Makefile
The shell command used to list all files but the libc's ones
introduced in commit 95d5353c33 was incorrect. It was listing
subdirectories without referencing their parent directories.
This patch fixes it.
Also, the command used to invoke the checkpatch.pl script is now
printed when V=1.
> Bug Fix: Fix checkpatch rule in Makefile

- include/lib/bakery_lock.h
- lib/locks/bakery/bakery_lock_coherent.c
- lib/locks/bakery/bakery_lock_normal.c
This patch-set applies several optimizations to bakery lock implementation that uses coherent memory. It also adds assertion checks to prevent recursive acquisition for the implementation that uses normal memory.
> Optimize the bakery lock implementation

- Makefile
The ARCH variable, which defaults to 'aarch64', gives the wrong
impression that the Trusted Firmware can be built for other
architectures. This patch removes it. This doesn't have any
consequence on the rest of the build system because the variable
was unused.
> Remove the ARCH build configuration from the Makefile

- include/bl32/payloads/tlk.h
- services/spd/tlkd/tlkd_main.c
This patch removes the need for a shared buffer between the EL3 and S-EL1
levels. We now use the CPU registers, x0-x7, while passing data between
the two levels. Since TLK is a 32-bit Trusted OS, tlkd has to unpack the
arguments in the x0-x7 registers. TLK in turn gets these values via r0-r7.
> Pass arguments/results between EL3/S-EL1 via CPU registers (x0-x7)

- Makefile
The ARCH variable, which defaults to 'aarch64', gives the wrong
impression that the Trusted Firmware can be built for other
architectures. This patch removes it. This doesn't have any
consequence on the rest of the build system because the variable
was unused.
Change-Id: I97130f11f7733a3cbdfc89989587f2ebecaf3294
> Remove the ARCH build configuration from the Makefile v2

- include/bl32/payloads/tlk.h
- services/spd/tlkd/tlkd_main.c
This patch removes the need for a shared buffer between the EL3 and S-EL1
levels. We now use the CPU registers, x0-x7, while passing data between
the two levels. Since TLK is a 32-bit Trusted OS, tlkd has to unpack the
arguments in the x0-x7 registers. TLK in turn gets these values via r0-r7.
> Pass arguments/results between EL3/S-EL1 via CPU registers (x0-x7) v4

- lib/cpus/aarch64/aem_generic.S
This patch fixes an issue in the cpu specific register reporting
of FVP AEM model whereby crash reporting itself triggers an exception
thus resulting in recursive crash prints. The input to the
'size_controlled_print' in the crash reporting framework should
be a NULL terminated string. As there were no cpu specific register
to be reported on FVP AEM model, the issue was caused by passing 0
instead of NULL terminated string to the above mentioned function.
Change-Id: I664427b22b89977b389175dfde84c815f02c705a
> Fix recursive crash prints on FVP AEM model

- plat/arm/board/fvp/fvp_topology.c
Fix the return type of the FVP `plat_arm_topology_setup` function
to be `void` instead of `int` to match the declaration in
`plat_arm.h`.
This does not result in any change in behavior.
Change-Id: I62edfa7652b83bd26cffb7d167153959b38e37e7
> Fix return type of FVP plat_arm_topology_setup

- Makefile
- docs/plat/nvidia-tegra.md
- drivers/ti/uart/16550_console.S
- include/drivers/ti/uart/uart_16550.h
- plat/nvidia/tegra/common/aarch64/tegra_helpers.S
- plat/nvidia/tegra/common/drivers/flowctrl/flowctrl.c
- plat/nvidia/tegra/common/drivers/memctrl/memctrl.c
- plat/nvidia/tegra/common/drivers/pmc/pmc.c
- plat/nvidia/tegra/common/tegra_bl31_setup.c
- plat/nvidia/tegra/common/tegra_common.mk
- plat/nvidia/tegra/common/tegra_gic.c
- plat/nvidia/tegra/common/tegra_pm.c
- plat/nvidia/tegra/common/tegra_topology.c
- plat/nvidia/tegra/include/drivers/flowctrl.h
- plat/nvidia/tegra/include/drivers/memctrl.h
- plat/nvidia/tegra/include/drivers/pmc.h
- plat/nvidia/tegra/include/plat_macros.S
- plat/nvidia/tegra/include/platform_def.h
- plat/nvidia/tegra/include/t210/tegra_def.h
- plat/nvidia/tegra/include/tegra_private.h
- plat/nvidia/tegra/platform.mk
- plat/nvidia/tegra/soc/t210/plat_psci_handlers.c
- plat/nvidia/tegra/soc/t210/plat_secondary.c
- plat/nvidia/tegra/soc/t210/plat_setup.c
- plat/nvidia/tegra/soc/t210/platform_t210.mk
T210 is the latest chip in the Tegra family of SoCs from NVIDIA. It is an
ARM v8 dual-cluster (A57/A53) SoC, with any one of the clusters being active
at a given point in time.
This patch adds support to boot the Trusted Firmware on T210 SoCs. The patch
also adds support to boot secondary CPUs, enter/exit core power states for
all CPUs in the slow/fast clusters. The support to switch between clusters
is still not available in this patch and would be available later.
> Tegra soc support v4

- include/plat/arm/css/common/css_def.h
- plat/arm/css/common/aarch64/css_helpers.S
This patch fixes the incorrect bit width used to extract the primary
cpu id from `ap_data` exported by scp at SCP_BOOT_CFG_ADDR in
platform_is_primary_cpu().
Change-Id: I14abb361685f31164ecce0755fc1a145903b27aa
> CSS: Extract primary cpu id using the correct bit width

- plat/arm/board/fvp/aarch64/fvp_helpers.S
- plat/arm/board/fvp/drivers/pwrc/fvp_pwrc.h
This patch fixes the incorrect bit width used to extract the wakeup
reason from PSYSR in platform_get_entrypoint() function. This defect
did not have any observed regression.
Change-Id: I42652dbffc99f5bf50cc86a5878f28d730720d9a
> FVP: Correct the PSYSR_WK bit width in platform_get_entrypoint

- docs/user-guide.md
The 'ARM_TSP_RAM_LOCATION_ID' option specified in the user guide
corresponds to the internal definition not visible to the final
user. The proper build option is 'ARM_TSP_RAM_LOCATION'. This
patch fixes it.
Fixes ARM-software/tf-issues#308
Change-Id: Ica8cb72c0c5e8b3503f60b5357d16698e869b1bd
> Fix build option 'ARM_TSP_RAM_LOCATION' in user guide

- plat/nvidia/tegra/common/drivers/memctrl/memctrl.c
- plat/nvidia/tegra/common/tegra_bl31_setup.c
- plat/nvidia/tegra/common/tegra_common.mk
- plat/nvidia/tegra/common/tegra_sip_calls.c
- plat/nvidia/tegra/include/drivers/memctrl.h
This patch adds support to reserve a memory carveout region in the
DRAM on Tegra SoCs. The memory controller provides specific registers
to specify the aperture's base and size. This aperture can also be
changed dynamically in order to re-size the memory available for
DRM video playback. In case of the new aperture not overlapping
the previous one, the previous aperture has to be cleared before
setting up the new one. This means we do not "leak" any video data
to the NS world.
> Reserve a Video Memory aperture in DRAM memory

- services/std_svc/psci/psci_common.c
`mpidr_set_aff_inst()` is left shifting an int constant and an
unsigned char value to construct an `MPIDR`. For affinity level 3 a
shift of 32 would result in shifting out of the 32-bit type and
have no effect on the `MPIDR`.
These values need to be extended to unsigned long before shifting
to ensure correct results for affinity level 3.
> Fix integer extension in mpidr_set_aff_inst()

- bl1/bl1_main.c
The validation of the caching enable state in `bl1_main()` was
incorrect resulting in the state not being checked. Using the right
operator fixes this.
> Fix incorrect assertions in bl1_main()

- Makefile
- bl1/aarch64/bl1_entrypoint.S
- bl31/aarch64/bl31_entrypoint.S
- docs/firmware-design.md
- docs/porting-guide.md
- docs/user-guide.md
- include/common/asm_macros.S
- include/common/bl_common.h
- include/common/el3_common_macros.S
- plat/arm/board/fvp/fvp_bl31_setup.c
- plat/arm/board/juno/aarch64/juno_helpers.S
- plat/arm/common/arm_bl31_setup.c
- services/std_svc/psci/psci_entry.S
This patch stack implements phase 1 of https://github.com/ARM-software/tf-issues/issues/304, i.e.:
* Always enable CCI coherency in BL3-1
* Remove FIRST_RESET_HANDLER_CALL build option
* Rationalize reset handling code
* Introduce PROGRAMMABLE_RESET_ADDRESS build option
> Enhance BL3-1 entrypoint handling to support non-TF boot firmware - Phase 1

- plat/nvidia/tegra/common/tegra_common.mk
- plat/nvidia/tegra/common/tegra_gic.c
In order to handle secure/non-secure interrupts, overload the plat_ic_*
functions and copy GIC helper functions from arm_gic.c. Use arm_gic.c
as the reference to add Tegra's GIC helper functions.
Now that Tegra has its own GIC implementation, we have no use for
plat_gic.c and arm_gic.c files.
> Add missing features to the Tegra GIC driver

- include/common/el3_common_macros.S
This patch fixes the build time condition deciding whether the
read-write data should be relocated from ROM to RAM. It was incorrectly
using __DATA_ROM_START__, which is a linker symbol and not a compiler
build flag. As a result, the relocation code was always compiled out.
This bug has been introduced by the following patch:
"Rationalize reset handling code"
> Bug fix: Build time condition to relocate RW data

- tools/cert_create/include/key.h
- tools/cert_create/src/key.c
- tools/cert_create/src/main.c
Some Linux distributions include an OpenSSL library which has been
built without ECDSA support. Trying to build the certificate
generation tool on those distributions will result in a build error.
This patch fixes that issue by including ECDSA support only if
OpenSSL has been built with ECDSA. In that case, the OpenSSL
configuration file does not define the OPENSSL_NO_EC macro. The tool
will build successfully, although the resulting binary will not
support ECDSA keys.
Change-Id: I4627d1abd19eef7ad3251997d8218599187eb902
> TBB: build 'cert_create' with ECDSA only if OpenSSL supports it

- docs/firmware-design.md
- docs/porting-guide.md
- include/bl31/services/psci.h
- services/std_svc/psci/psci_common.c
- services/std_svc/psci/psci_main.c
- services/std_svc/psci/psci_private.h
- services/std_svc/psci/psci_setup.c
This patch adds support for SYSTEM_SUSPEND API as mentioned in the PSCI 1.0
specification. This API, on being invoked on the last running core on a
supported platform, will put the system into a low power mode with memory
retention.
The psci_afflvl_suspend() internal API has been reused as most of the actions
to suspend a system are the same as invoking the PSCI CPU_SUSPEND API with the
target affinity level as 'system'. This API needs the 'power state' parameter
for the target low power state. This parameter is not passed by the caller of
the SYSTEM_SUSPEND API. Hence, the platform needs to implement the
get_sys_suspend_power_state() platform function to provide this information.
Also, the platform also needs to add support for suspending the system to the
existing 'plat_pm_ops' …
> PSCI: Add SYSTEM_SUSPEND API support

- docs/plat/nvidia-tegra.md
- plat/nvidia/tegra/common/tegra_pm.c
- plat/nvidia/tegra/include/t210/tegra_def.h
- plat/nvidia/tegra/soc/t210/plat_psci_handlers.c
This patch implements the get_sys_suspend_power_state() handler required by
the PSCI SYSTEM_SUSPEND API. The intent of this handler is to return the
appropriate State-ID field which can be utilized in `affinst_suspend()` to
suspend to system affinity level.
> Implement get_sys_suspend_power_state() handler for Tegra

- drivers/arm/cci/cci.c
- drivers/arm/cci400/cci400.c
- drivers/arm/gic/arm_gic.c
- drivers/arm/gic/gic_v2.c
- drivers/arm/pl011/pl011_console.S
- drivers/arm/tzc400/tzc400.c
- drivers/console/console.S
- drivers/console/skeleton_console.S
- include/drivers/arm/arm_gic.h
- include/drivers/arm/cci.h
- include/drivers/arm/cci400.h
- include/drivers/arm/gic_v2.h
- include/drivers/arm/tzc400.h
- include/drivers/console.h
- include/plat/arm/common/arm_config.h
This patch changes the type of the base address parameter in the
ARM device driver APIs to uintptr_t (GIC, CCI, TZC400, PL011). The
uintptr_t type allows coverage of the whole memory space and to
perform arithmetic operations on the addresses. ARM platform code
has also been updated to use uintptr_t as GIC base address in the
configuration.
Fixes ARM-software/tf-issues#214
Change-Id: I1b87daedadcc8b63e8f113477979675e07d788f1
> Use uintptr_t as base address type in ARM driver APIs

- drivers/io/io_semihosting.c
- lib/semihosting/semihosting.c
The return value from the SYS_WRITE semihosting operation is 0 if
the call is successful or the number of bytes not written, if there
is an error. The implementation of the write function in the
semihosting driver treats the return value as the number of bytes
written, which is wrong. This patch fixes it.
Change-Id: Id39dac3d17b5eac557408b8995abe90924c85b85
> Fix bug in semihosting write function

- docs/plat/nvidia-tegra.md
- services/spd/tlkd/tlkd.mk
Remove the 'NEED_BL32' flag from the makefile. TLK compiles using a
completely different build system and is present on the device as a
binary blob. The NEED_BL32 flag does not influence the TLK load/boot
sequence at all. Moreover, it expects that TLK binary be present on
the host before we can compile BL31 support for Tegra.
This patch removes the flag from the makefile and thus decouples both
the build systems.
Tested by booting TLK without the NEED_BL32 flag on Tegra.
> tlkd: delete 'NEED_BL32' build variable

- plat/nvidia/tegra/include/t210/tegra_def.h
- plat/nvidia/tegra/soc/t210/plat_psci_handlers.c
The Memory Select Switch Controller routes any CPU transactions to
the appropriate slave depending on the transaction address. During
system suspend, it loses all config settings and hence the CPU has
to restore them during resume.
This patch restores the controller's settings for enabling WRAP to
INCR burst type conversions on the master ports, for any incoming
requests from the AXI slave ports.
Tested by performing multiple system suspend cycles.
> Tegra210: enable WRAP to INCR burst type conversions

- docs/plat/nvidia-tegra.md
- docs/spd/tlk-dispatcher.md
- plat/nvidia/tegra/common/tegra_bl31_setup.c
- plat/nvidia/tegra/include/tegra_private.h
- plat/nvidia/tegra/soc/t132/platform_t132.mk
* Tegra: retrieve BL32's bootargs from bl32_ep_info
* Tegra132: set TZDRAM_BASE to 0xF5C00000
* docs: fix the command to compile BL31 on Tegra
> Bootargs tzdram base v2

- .gitignore
- tools/cert_create/Makefile
- tools/cert_create/include/cert.h
- tools/cert_create/include/ext.h
- tools/cert_create/include/key.h
- tools/cert_create/include/tbbr/tbb_cert.h
- tools/cert_create/include/tbbr/tbb_ext.h
- tools/cert_create/include/tbbr/tbb_key.h
- tools/cert_create/src/cert.c
- tools/cert_create/src/ext.c
- tools/cert_create/src/main.c
- tools/cert_create/src/tbbr/tbb_cert.c
- tools/cert_create/src/tbbr/tbb_ext.c
- tools/cert_create/src/tbbr/tbb_key.c
This patch reworks the certificate generation tool to follow a data
driven approach. The user may specify at build time the certificates,
keys and extensions defined in the CoT, register them using the
appropiate macros and the tool will take care of creating the
certificates corresponding to the CoT specified.
Change-Id: I29950b39343c3e1b71718fce0e77dcf2a9a0be2f
> TBB: rework cert_create tool to follow a data driven approach

- docs/interrupt-framework-design.md
This patch fixes a pair of typos. The security state had been described
as non-secure where it should have been secure.
> Some minor fixes to interrupt-framework-design.md

- plat/nvidia/tegra/common/tegra_bl31_setup.c
On Tegra SoCs, the TZDRAM contains the BL31 and BL32 images. This patch
uses only the actual memory available for BL31 instead of mapping the
entire TZDRAM.
> Tegra: memmap the actual memory available for BL31

- plat/nvidia/tegra/include/platform_def.h
Tegra: fix PLATFORM_{CORE_COUNT|NUM_AFFS} macros
This patch fixes the following macros for Tegra SoCs.
* PLATFORM_CORE_COUNT: PLATFORM_CLUSTER_COUNT * PLATFORM_MAX_CPUS_PER_CLUSTER
* PLATFORM_NUM_AFFS: PLATFORM_CORE_COUNT + PLATFORM_CLUSTER_COUNT + 1
> Tegra: fix PLATFORM_{MAX_AFFLVL|CORE_COUNT|NUM_AFFS} macros

- include/plat/arm/common/arm_config.h
- include/plat/arm/soc/common/soc_css.h
If Trusted Firmware is built with optimizations disabled (-O0), the
linker throws the following error:
undefined reference to 'xxx'
Where 'xxx' is a raw inline function defined in a header file. The
reason is that, with optimizations disabled, GCC may decide to skip
the inlining. If that is the case, an external definition to the
compilation unit must be provided. Because no external definition
is present, the linker throws the error.
This patch fixes the problem by declaring the following inline
functions static, so the internal definition is used:
inline void soc_css_security_setup(void)
inline const arm_config_t *get_arm_config(void)
Change-Id: Id650d6be1b1396bdb48af1ac8a4c7900d212e95f
> Fix build error with optimizations disabled (-O0)

- plat/mediatek/mt8173/plat_topology.c
Use constant macro defined in platform_def.h to replace hardcoded value.
This patch fix following assert in new psci-1.0 framework.
ASSERT: populate_power_domain_tree <183> : j == PLATFORM_CORE_COUNT
Change-Id: I9b7eda525479464a8c3805b6fe14ffb10debaf72
Signed-off-by: Jimmy Huang <jimmy.huang@mediatek.com>
> mt8173: Fix cluster 0 core count

- docs/platform-migration-guide.md
This patch corrects some typos in the platform migration guide. More                                                                                                                                                                                                              
importantly, the commit ID of the patch that implements migration of ARM
Reference platforms to the new platform API has been corrected.
Change-Id: Ib0109ea42c3d2bad2c6856ab725862652da7f3c8
> docs: Fixes to platform-migration-guide.md

- bl2/bl2_main.c
- common/bl_common.c
- include/common/bl_common.h
BL3-2 image (Secure Payload) is optional. If the image cannot be
loaded a warning message is printed and the boot process continues.
According to the TBBR document, this behaviour should not apply in
case of an authentication error, where the boot process should be
aborted.
This patch modifies the load_auth_image() function to distinguish
between a load error and an authentication error. The caller uses
the return value to abort the boot process or continue.
In case of authentication error, the memory region used to store
the image is wiped clean.
Change-Id: I534391d526d514b2a85981c3dda00de67e0e7992
> TBB: abort boot if BL3-2 cannot be authenticated

- plat/nvidia/tegra/common/drivers/memctrl/memctrl.c
The previous logic in the memctrl driver was not catering to cases
where the new memory region lied inside the older region. This patch
fixes the if/elseif/elseif logic in the driver to take care of this
case.
Reported by: Vikram Kanigiri <vikram.kanigiri@arm.com>
> Tegra: fix logic to clear videomem regions

- docs/firmware-design.md
- include/plat/arm/css/common/css_def.h
- plat/arm/board/fvp/aarch64/fvp_common.c
- plat/arm/board/fvp/fvp_def.h
- plat/arm/board/juno/include/platform_def.h
- plat/arm/board/juno/juno_def.h
ARM TF configures all interrupts as non-secure except those which
are present in irq_sec_array. This patch updates the irq_sec_array
with the missing secure interrupts for ARM platforms.
It also updates the documentation to be inline with the latest
implementation.
Fixes ARM-software/tf-issues#312
Change-Id: I39956c56a319086e3929d1fa89030b4ec4b01fcc
> Configure all secure interrupts on ARM platforms

- bl1/bl1_main.c
- common/bl_common.c
- include/common/bl_common.h
BL2 loads secure runtime code(BL3-1, BL3-2) and hence it has to
run in secure world otherwise BL3-1/BL3-2 have to execute from
non-secure memory. Hence, This patch removes the change_security_state()
call in bl1_run_bl2() and replaces it with an assert to confirm
the BL2 as secure.
Fixes ARM-software/tf-issues#314
Change-Id: I611b83f5c4090e58a76a2e950b0d797b46df3c29
> Ensure BL2 security state is secure

- bl32/tsp/tsp_main.c
- include/bl31/services/psci.h
- services/spd/opteed/opteed_pm.c
- services/spd/tspd/tspd_pm.c
- services/std_svc/psci/psci_suspend.c
In certain Trusted OS implementations it is a requirement to pass them the
highest power level which will enter a power down state during a PSCI
CPU_SUSPEND or SYSTEM_SUSPEND API invocation. This patch passes this power level
to the SPD in the "max_off_pwrlvl" parameter of the svc_suspend() hook.
Currently, the highest power level which was requested to be placed in a low
power state (retention or power down) is passed to the SPD svc_suspend_finish()
hook. This hook is called after emerging from the low power state. It is more
useful to pass the highest power level which was powered down instead. This
patch does this by changing the semantics of the parameter passed to an SPD's
svc_suspend_finish() hook. The name of the parameter has been changed from
"suspend_level" to "max_off_pwrlvl" …
> Pass the target suspend level to SPD suspend hooks

- bl31/bl31.ld.S
- docs/firmware-design.md
- docs/porting-guide.md
- include/bl31/services/psci.h
- include/lib/bakery_lock.h
- include/plat/arm/common/arm_def.h
- include/plat/arm/common/plat_arm.h
- lib/locks/bakery/bakery_lock_coherent.c
- lib/locks/bakery/bakery_lock_normal.c
- plat/mediatek/mt8173/drivers/spm/spm.c
- services/std_svc/psci/psci_common.c
- services/std_svc/psci/psci_private.h
- services/std_svc/psci/psci_setup.c
This request contains following changes:
1. Re-design of bakery lock memory allocation and algorithm by unifying macros, apis across coherent memory and normal memory usage.
2. Updates ARM platform ports to use the new bakery lock apis
3. Update mediatek port to use the new bakery lock macros.
> Re-design bakery lock allocation and algorithm

- bl2/aarch64/bl2_entrypoint.S
- bl2/bl2.ld.S
- bl31/aarch64/bl31_entrypoint.S
- bl31/bl31.ld.S
- bl31/bl31_main.c
- bl32/tsp/aarch64/tsp_entrypoint.S
- bl32/tsp/tsp.ld.S
- drivers/arm/ccn/ccn.c
- drivers/arm/ccn/ccn_private.h
- include/common/el3_common_macros.S
- include/drivers/arm/ccn.h
- include/lib/aarch64/arch_helpers.h
- lib/aarch64/cache_helpers.S
- lib/aarch64/misc_helpers.S
- plat/arm/common/arm_common.mk
- plat/nvidia/tegra/common/drivers/memctrl/memctrl.c
- services/std_svc/psci/psci_on.c
- services/std_svc/psci/psci_setup.c
- services/std_svc/psci/psci_suspend.c
This PR adds support in ARM TF to run on platforms that have system caches e.g. platforms that use CCN IP. It further adds a generic driver to configure any variant of the CCN IP.
> Support for ARM CoreLink CCN interconnects

- bl31/bl31.ld.S
- docs/porting-guide.md
When a platform port does not define PLAT_PERCPU_BAKERY_LOCK_SIZE, the total
memory that should be allocated per-cpu to accommodate all bakery locks is
calculated by the linker in bl31.ld.S. The linker stores this value in the
__PERCPU_BAKERY_LOCK_SIZE__ linker symbol. The runtime value of this symbol is
different from the link time value as the symbol is relocated into the current
section (.bss). This patch fixes this issue by marking the symbol as ABSOLUTE
which allows it to retain its correct value even at runtime.
The description of PLAT_PERCPU_BAKERY_LOCK_SIZE in the porting-guide.md has been
made clearer as well.
Change-Id: Ia0cfd42f51deaf739d792297e60cad5c6e6e610b
> Fix relocation of __PERCPU_BAKERY_LOCK_SIZE__ in PR #390

- include/bl32/payloads/tlk.h
- services/spd/tlkd/tlkd_main.c
- services/spd/tlkd/tlkd_pm.c
This patch adds PM handlers to TLKD for the system suspend/resume and
system poweroff/reset cases. TLK expects all SMCs through a single
handler, which then fork out into multiple handlers depending on the
SMC. We tap into the same single entrypoint by restoring the S-EL1
context before passing the PM event via register 'x0'. On completion
of the PM event, TLK sends a completion SMC and TLKD then moves on
with the PM process.
> Send power management events to the Trusted OS (TLK)

- include/drivers/arm/sp804_delay_timer.h
The generic delay timer driver expects a pointer to a timer_ops_t
structure containing the specific timer driver information. It
doesn't make a copy of the structure, instead it just keeps the
pointer. Therefore, this pointer must remain valid over time.
The SP804 driver doesn't satisfy this requirement. The
sp804_timer_init() macro creates a temporary instanciation of the
timer_ops_t structure on the fly and passes it to the generic
delay timer. When this temporary instanciation gets deallocated,
the generic delay timer is left with a pointer to invalid data.
This patch fixes this bug by statically allocating the SP804
timer_ops_t structure.
Change-Id: I8fbf75907583aef06701e3fd9fabe0b2c9bc95bf
> Bug fix in the SP804 dual timer driver

- services/spd/tlkd/tlkd_main.c
TLK sends the "preempted" event to the NS world along with an
identifier for certain use cases. The NS world driver is then
expected to take appropriate action depending on the identifier
value. Upon completion, the NS world driver then sends the
results to TLK (via x1-x3) with the TLK_RESUME_FID function ID.
This patch uses the already present code to pass the results
from the NS world to TLK for the TLK_RESUME_FID function ID.
> TLKD: pass results with TLK_RESUME_FID function ID

- drivers/arm/cci400/cci400.c
This patch fixes a copy and paste issue that resulted in the cluster
indexes not being checked as intended. Note that this fix applies to
the deprecated CCI-400 driver, not the unified one.
> Fix debug assertion in deprecated CCI-400 driver

- plat/arm/common/arm_bl1_setup.c
This patch fixes the relative path to the 'bl1_private.h' header file
included from 'arm_bl1_setup.c'. Note that, although the path was
incorrect, it wasn't causing a compilation error because the header
file still got included through an alternative include search path.
> Fix #include path in ARM platform BL1 setup code

- include/lib/cassert.h
The CASSERT() macro introduces a typedef for the sole purpose of
triggering a compilation error if the condition to check is false.
This typedef is not used afterwards. As a consequence, when the
CASSERT() macro is called from withing a function block, the compiler
complains and outputs the following error message:
error: typedef 'msg' locally defined but not used [-Werror=unused-local-typedefs]
This patch adds the "unused" attribute for the aforementioned
typedef. This silences the compiler warning and thus makes the
CASSERT() macro callable from within function blocks as well.
> Make CASSERT() macro callable from anywhere

- bl1/aarch64/bl1_exceptions.S
The AArch64 synchronous exception vector code in BL1 is almost
reaching its architectural limit of 32 instructions. This means
there is very little space for this code to grow.
This patch reduces the size of the exception vector code by
moving most of its code in a function to which we branch from
SynchronousExceptionA64.
> Break down BL1 AArch64 synchronous exception handler

- include/plat/arm/css/common/css_def.h
- include/plat/arm/css/common/css_pm.h
- plat/arm/board/fvp/aarch64/fvp_helpers.S
- plat/arm/board/fvp/fvp_def.h
- plat/arm/board/fvp/fvp_pm.c
- plat/arm/board/fvp/include/platform_def.h
- plat/arm/common/arm_pm.c
- plat/arm/css/common/aarch64/css_helpers.S
- plat/arm/css/common/css_pm.c
This patch does the following reorganization to psci power management (PM)
handler setup for ARM standard platform ports :
1. The mailbox programming required during `plat_setup_psci_ops()` is identical
for all ARM platforms. Hence the implementation of this API is now moved
to the common `arm_pm.c` file. Each ARM platform now must define the
PLAT_ARM_TRUSTED_MAILBOX_BASE macro, which in current platforms is the same
as ARM_SHARED_RAM_BASE.
2. The PSCI PM handler callback structure, `plat_psci_ops`, must now be
exported via `plat_arm_psci_pm_ops`. This allows the common implementation
of `plat_setup_psci_ops()` to return a platform specific `plat_psci_ops`.
In the case of CSS platforms, a default weak implementation of the same is
provided in `css_pm.c` which can be overridden by each CSS …
> Reorganise PSCI PM handler setup on ARM Standard platforms

- plat/arm/board/juno/aarch64/juno_helpers.S
- plat/arm/css/common/aarch64/css_helpers.S
Currently all ARM CSS platforms that include css_helpers.S use the same
strong definition of `plat_arm_calc_core_pos`. This patch allows these CSS
platforms to define their own strong definition of this function.
* Replace the strong definition of `plat_arm_calc_core_pos` in
css_helpers.S with a utility function `css_calc_core_pos_swap_cluster`
does the same thing (swaps cluster IDs). ARM CSS platforms may choose
to use this function or not.
* Add a Juno strong definition of `plat_arm_calc_core_pos`, which uses
`css_calc_core_pos_swap_cluster`.
> Allow CSS to redefine function `plat_arm_calc_core_pos`

- bl1/bl1_main.c
- bl2/bl2_main.c
- docs/porting-guide.md
- include/plat/common/platform.h
- plat/common/aarch64/platform_helpers.S
This patch adds an optional API to the platform port:
void plat_error_handler(int err) __dead2;
The platform error handler is called when there is a specific error
condition after which Trusted Firmware cannot continue. While panic()
simply prints the crash report (if enabled) and spins, the platform
error handler can be used to hand control over to the platform port
so it can perform specific bookeeping or post-error actions (for
example, reset the system). This function must not return.
The parameter indicates the type of error using standard codes from
errno.h. Possible errors reported by the generic code are:
-EAUTH  : a certificate or image could not be authenticated
(when Trusted Board Boot is enabled)
-ENOENT : the requested image or certificate could not be found
or an IO error …
> Add optional platform error handler API

- include/plat/arm/common/plat_arm.h
This patch fixes a compilation issue for platforms that are aligned to ARM
Standard platforms and include the `plat_arm.h` header in their platform port.
The compilation would fail for such a platform because `xlat_tables.h` which
has the definition for `mmap_region_t` is not included in `plat_arm.h`. This
patch fixes this by including `xlat_tables.h` in `plat_arm.h` header.
Fixes ARM-Software/tf-issues#318
Change-Id: I75f990cfb4078b3996fc353c8cd37c9de61d555e
> Include xlat_tables.h in plat_arm.h

- plat/arm/board/juno/platform.mk
Cortex-A72 library support is now compiled into the Juno platform port to go
with the existing A53/A57 support. This enables a single set of Juno TF
binaries to run on Juno R0, R1 and R2 boards.
Change-Id: I4a601dc4f671e98bdb19d98bbb66f02f0d8b7fc7
> Add Cortex-A72 support for Juno R2

- common/bl_common.c
- drivers/io/io_fip.c
- drivers/io/io_memmap.c
- drivers/io/io_semihosting.c
- drivers/io/io_storage.c
- include/drivers/io/io_storage.h
- plat/arm/board/fvp/fvp_io_storage.c
- plat/arm/common/arm_io_storage.c
Patch 7e26fe1f deprecates IO specific return definitions in favour
of standard errno codes. This patch removes those definitions
and its usage from the IO framework, IO drivers and IO platform
layer. Following this patch, standard errno codes must be used
when checking the return value of an IO function.
Change-Id: Id6e0e9d0a7daf15a81ec598cf74de83d5768650f
> Remove deprecated IO return definitions

- Makefile
Commit #73c99d4eb377e0e25f7951be53087bf92e7b4b18 had refactored the top level
Makefile. This commit also broke platform ports that still rely on an enabled
ENABLE_PLAT_COMPAT build option since the evaluation of this option was also
accidentally removed from the Makefile.
This patch fixes this break by re-introducing the necessary support to ensure
that this build option is enabled by default if a platform port does not disable
it explicitly.
Fixes ARM-software/tf-issues#332
Change-Id: I2217595d2e0bccae7de98cc6c0ea448b5bf3dae2
> Re-introduce evaluation of ENABLE_PLAT_COMPAT build flag

- bl31/interrupt_mgmt.c
The set_routing_model() function in the Interrupt Management
Framework calls the context management library to update the
SCR_EL3 register. This context management library assumes that
the context has been previously initialized. Consequently, if
a Secure Payload Dispatcher (SPD) tries to set the routing model
before initializing the context, the system will fail (in debug
mode, an assertion will be raised).
This patch fixes the issue by checking if the context has been
initialized before updating SCR_EL3. If a valid context is not
available, SCR_EL3 update will be done when the SPD calls the
context initialization function. This function will call
get_scr_el3_from_routing_model() to obtain the SCR_EL3 value.
If the SPD does not call the context initialization function
then it is SPD's …
> IMF: postpone SCR_EL3 update if context is not initialized

- plat/nvidia/tegra/common/tegra_pm.c
- plat/nvidia/tegra/soc/t132/plat_psci_handlers.c
- plat/nvidia/tegra/soc/t210/plat_psci_handlers.c
This patch adds a per-soc system reset handler for Tegra chips. The
handler gets executed before the actual system resets. This allows
for custom handling of the system reset sequence on each SoC.
> Tegra: introduce per-soc system reset handler

- Makefile
ARMv8 architecture allows unaligned memory accesses. However,
Trusted Firmware disables such feature by setting the SCTLR_A_BIT
and SCTLR_SA_BIT in the SCTLR_EL3 register (it enables alignment
checks).
This patch adds -mstrict-align to the gcc build options. Although
there are not explicit unaligned memory accesses in Trusted Firmware,
this flag will tell the compiler not to use them.
Fixes ARM-software/tf-issues#294
Change-Id: I69748c6cf28504be9ca3dc975a331d14459c9ef1
> Add -mstrict-align to the gcc options

- Makefile
- make_helpers/tbbr/tbbr_tools.mk
If an SPD wants to use a prebuilt binary as BL32 image (for example,
the OPTEE Dispatcher), it must point the `BL32` variable to the
image file. This dependency should apply only to the `fip` target.
However, it also applies to the `all` target at the moment. If the
user tries to build all individual TF images using `make all`
without setting BL32, the build fails. The following command will
throw the error:
make CROSS_COMPILE=aarch64-linux-gnu- SPD=opteed all
...
...
aarch64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
make: *** [build/fvp/release/bl32/bl32.ld] Error 1
The reason is that the build system checks if BL32 is defined, and
if it is not, it will try to build BL32 from source. If the SPD
makefile does not provide support for that (as is the case of the …
> Fix build error when `BL32` is not defined

- Makefile
- bl31/context_mgmt.c
- docs/user-guide.md
- include/common/asm_macros.S
- include/plat/common/common_def.h
This patch changes the build time behaviour when using deprecated API within
Trusted Firmware. Previously the use of deprecated APIs would only trigger a
build warning (which was always treated as a build error), when
WARN_DEPRECATED = 1. Now, the use of deprecated C declarations will always
trigger a build time warning. Whether this warning is treated as error or not
is determined by the build flag ERROR_DEPRECATED which is disabled by default.
When the build flag ERROR_DEPRECATED=1, the invocation of deprecated API or
inclusion of deprecated headers will result in a build error.
Also the deprecated context management helpers in context_mgmt.c are now
conditionally compiled depending on the value of ERROR_DEPRECATED flag
so that the APIs themselves do not result in a build error when the …
> Replace build macro WARN_DEPRECATED with ERROR_DEPRECATED

- drivers/arm/gic/common/gic_common.c
- drivers/arm/gic/v2/gicv2_helpers.c
- drivers/arm/gic/v2/gicv2_main.c
- drivers/arm/gic/v2/gicv2_private.h
- drivers/arm/gic/v3/gicv3_helpers.c
- drivers/arm/gic/v3/gicv3_main.c
- drivers/arm/gic/v3/gicv3_private.h
- include/drivers/arm/arm_gic.h
- include/drivers/arm/gic_common.h
- include/drivers/arm/gic_v2.h
- include/drivers/arm/gic_v3.h
- include/drivers/arm/gicv2.h
- include/drivers/arm/gicv3.h
- include/lib/aarch64/arch.h
- include/lib/aarch64/arch_helpers.h
This patch stack introduces new GICv3 driver without support for legacy
operation. It also introduces a GICv2 driver which is optimised for GICv2
and does not support GICv3 systems in GICv2 compatibility mode. The
existing legacy GIC driver is deprecated to encourage platform ports to
migrate to the new drivers.
> Introduce new GICv3 and GICv2 drivers

- bl31/aarch64/runtime_exceptions.S
- bl31/bl31.mk
- docs/interrupt-framework-design.md
- docs/porting-guide.md
- docs/user-guide.md
- services/spd/opteed/opteed_main.c
- services/spd/tspd/tspd_main.c
The IMF_READ_INTERRUPT_ID build option enables a feature where the interrupt
ID of the highest priority pending interrupt is passed as a parameter to the
interrupt handler registered for that type of interrupt. This additional read
of highest pending interrupt id from GIC is problematic as it is possible that
the original interrupt may get deasserted and another interrupt of different
type maybe become the highest pending interrupt. Hence it is safer to prevent
such behaviour by removing the IMF_READ_INTERRUPT_ID build option.
The `id` parameter of the interrupt handler `interrupt_type_handler_t` is
now made a reserved parameter with this patch. It will always contain
INTR_ID_UNAVAILABLE.
Fixes ARM-software/tf-issues#307
Change-Id: I2173aae1dd37edad7ba6bdfb1a99868635fa34de
> Remove the IMF_READ_INTERRUPT_ID build option

- Makefile
- bl1/aarch64/bl1_entrypoint.S
- bl1/aarch64/bl1_exceptions.S
- bl1/bl1_main.c
- bl2/bl2_main.c
- bl31/aarch64/bl31_entrypoint.S
- docs/porting-guide.md
- docs/user-guide.md
- include/plat/arm/common/plat_arm.h
- plat/arm/board/fvp/aarch64/fvp_helpers.S
- plat/arm/common/arm_bl1_setup.c
- plat/arm/common/arm_common.mk
- plat/arm/common/arm_pm.c
- plat/arm/common/arm_security.c
- plat/arm/css/common/aarch64/css_helpers.S
- plat/arm/css/common/css_bl2_setup.c
- plat/common/aarch64/platform_helpers.S
This PR is a combination of two features:
*  Support to load and execute a binary file in EL3 instead of the BL3-1 image
*  Optimize the code footprint in case only a single CPU is released from reset at cold boot on a given platform
> Add support to boot EL3 payloads and only a single CPU at cold reset

- include/plat/arm/board/common/board_arm_oid.h
This patch adds ARM specific OIDs which will be used to extract
the extension data from the certificates. These OIDs are arranged
as a subtree whose root node has been specifically allocated for
ARM Ltd.
{ iso(1) identified-organization(3) dod(6) internet(1)
private(4) enterprise(1) 4128 }
Change-Id: Ice20b3c8a31ddefe9102f3bd42f7429986f3ac34
> TBB: add ARM OIDs

- drivers/arm/tzc400/tzc400.c
- include/drivers/arm/tzc400.h
The TZC-400 driver implementation incorrectly uses the component
ID registers to detect the TZC-400 peripheral. As all ARM
peripherals share the same component ID, it doesn't allow to
uniquely identify the TZC-400 peripheral. This patch fixes the
TZC-400 driver by relying on the `part_number_0` and
`part_number_1` fields in the `PID` registers instead.
The `tzc_read_component_id` function has been replaced by
`tzc_read_peripheral_id`, which reads the 'part_number' values
and compares them with the TZC-400 peripheral ID.
Also, it adds a debug assertion to detect when the TZC driver
initialisation function is called multiple times.
Change-Id: I35949f6501a51c0a794144cd1c3a6db62440dce6
> Fix TZC-400 peripheral detection

- include/drivers/arm/cci400.h
Add compile time `__warn_deprecated` flag to public api's in CCI-400
specific driver so that user is aware of the driver being deprecated.
Similarly, it also adds an error message when `ERROR_DEPRECATED` is set
to prevent succesful compilation if CCI-400 specific driver is used.
Change-Id: Id7e61a560262abc01cbbd432ca85b9bf448a194d
> Add CCI-400 specific driver to deprecated driver list

- bl31/aarch64/context.S
The `fpregs_context_restore()` function used to restore the floating point
regsiter context had a typo error wherein it was doing `str` instead of
`ldr` for a register. This issue remained undetected becuase none of the ARM
Standard development platforms save and restore the floating point register
context when a context switch is done. This patch corrects the issue.
Change-Id: Id178e0ba254a5e0a4a844f54b39d71dc34e0f6ea
> Fix issue in Floating point register restore

- drivers/arm/tzc400/tzc400.c
When resuming from system suspend the TZC needs to be
re-initialized. Hence the assertion for TZC base address
to detect re-initialization is removed.
Change-Id: I53d64146f6c919e95526441bb997f7b309c68141
> Remove the assert for TZC base during initialization

- plat/nvidia/tegra/include/tegra_private.h
The `plat/nvidia/tegra/include/tegra_private.h` file uses resources
from psci.h (for example, psci_power_state_t) but does not explicitly
include psci.h. This does not currently cause a problem since psci.h
is indirectly included via other headers. However, this may not be
the case in future.
This patch explicitly includes psci.h from tegra_private.h
Change-Id: Ia991147898dbd117c1d3496a95850995a5554c05
> Include psci.h from tegra platform header

- Makefile
- docs/user-guide.md
- drivers/arm/pl011/pl011_console.S
- include/drivers/arm/pl011.h
The Server Base System Architecture document (ARM-DEN-0029)
specifies a generic UART device. The programmer's view of this
generic UART is a subset of the ARM PL011 UART. However, the
current PL011 driver in Trusted Firmware uses some features
that are outside the generic UART specification.
This patch modifies the PL011 driver to exclude features outside
the SBSA generic UART specification by setting the boolean build
option 'PL011_GENERIC_UART=1'. Default value is 0 (use full
PL011 features).
User guide updated.
Fixes ARM-software/tf-issues#216
Change-Id: I6e0eb86f9d69569bc3980fb57e70d6da5d91a737
> De-feature PL011 UART driver to match generic UART spec

- docs/auth-framework.md
- docs/user-guide.md
- drivers/auth/mbedtls/mbedtls_common.c
- drivers/auth/mbedtls/mbedtls_common.mk
- drivers/auth/mbedtls/mbedtls_crypto.c
- drivers/auth/mbedtls/mbedtls_crypto.mk
- drivers/auth/mbedtls/mbedtls_x509_parser.c
- include/drivers/auth/mbedtls/mbedtls_config.h
The mbed TLS library has introduced some changes in the API from
the 1.3.x to the 2.x releases. Using the 2.x releases requires
some changes to the crypto and transport modules.
This patch updates both modules to the mbed TLS 2.x API.
All references to the mbed TLS library in the code or documentation
have been updated to 'mbed TLS'. Old references to PolarSSL have
been updated to 'mbed TLS'.
User guide updated to use mbed TLS 2.2.0.
NOTE: moving up to mbed TLS 2.x from 1.3.x is not backward compatible.
Applying this patch will require an mbed TLS 2.x release to be used.
Also note that the mbed TLS license changed to Apache version 2.0.
Change-Id: Iba4584408653cf153091f2ca2ee23bc9add7fda4
> Move up to mbed TLS 2.x

- bl1/bl1_fwu.c
The implementation of FWU_SMC_IMAGE_AUTH performs a number of
pre-condition checks before authenticating the image. One of
these checks calls `bl1_plat_mem_check()` to ensure the image
source is mapped in when authenticating an image in place.
The framework incorrectly passes the security state of the
caller into this function instead of the security state of
the source image.
This patch corrects the defect. The defect would only
manifest itself for secure world callers authenticating
non-secure images in place, which is not done by current
upstream platforms.
Change-Id: I617c7b43e02ac7149f266aeaf3874316e62f3003
> FWU: Fix secure memory check in image auth

- bl1/bl1_fwu.c
- include/plat/common/platform.h
- plat/arm/board/juno/juno_bl1_setup.c
- plat/common/plat_bl1_common.c
The current FWU_SMC_UPDATE_DONE implementation incorrectly passes
an unused framework cookie through to the 1st argument in the
platform function `bl1_plat_fwu_done`. The intent is to allow
the SMC caller to pass a cookie through to this function.
This patch fixes FWU_SMC_UPDATE_DONE to pass x1 from the caller
through to `bl1_plat_fwu_done`. The argument names are updated
for clarity.
Upstream platforms currently do not use this argument so no
impact is expected.
Change-Id: I107f4b51eb03e7394f66d9a534ffab1cbc09a9b2
> FWU: Pass client cookie to FWU_SMC_UPDATE_DONE

- docs/user-guide.md
- `FVP_TSP_RAM_LOCATION` has been renamed into `ARM_TSP_RAM_LOCATION`
- `FVP_SHARED_DATA_LOCATION` has been deprecated (and removed)
> Documentation: Clean legacy variables in User Guide

- drivers/console/console.S
The 'ret' was missing in console_uninit() implementation, so the
program doesn't return from console_uninit(). Instead, it keeps
executing the following instructions which is not expected.
Change-Id: I810684f37f61c41c6f95a3bb36914d0765da8571
Signed-off-by: Jimmy Huang <jimmy.huang@mediatek.com>
> Add ret to return from console_uninit() function

- drivers/auth/mbedtls/mbedtls_common.mk
- drivers/auth/mbedtls/mbedtls_crypto.c
- include/drivers/auth/auth_mod.h
- tools/cert_create/include/cert.h
- tools/cert_create/include/ext.h
- tools/cert_create/include/key.h
* Fix build errors flagged by '-pedantic' in the mbed TLS authentication module
* Enable '-pedantic' compiler flag in the mbed TLS authentication module makefile
> Always build with '-pedantic'

- include/lib/cpus/aarch64/cortex_a35.h
- lib/cpus/aarch64/cortex_a35.S
- plat/arm/board/fvp/platform.mk
This patch adds support for ARM Cortex-A35 processor in the CPU
specific framework, as described in the Cortex-A35 TRM (r0p0).
> Add support for ARM Cortex-A35 processor

- include/bl31/runtime_svc.h
- include/common/bl_common.h
- include/drivers/auth/auth_mod.h
This patchset rearranges fields of some TF data structures to reduce
padding and thereby reduce memory footprint. It also changes the
`DECLARE_RT_SVC` macro to use designated initialization of
`rt_svc_desc` structure which is less error prone.
> Rearrange fields in TF data structures to reduce padding

- docs/porting-guide.md
This patch adds a brief description of 'MAX_MMAP_REGIONS' and
'ADDR_SPACE_SIZE' to the Porting Guide. These fields must be defined
by the platform in order to use the translation table library.
Change-Id: Ida366458fe2bc01979091a014dc38da0fae5991e
> Add 'MAX_MMAP_REGIONS' and 'ADDR_SPACE_SIZE' to the Porting Guide

- plat/arm/board/fvp/platform.mk
Enable the ARM Cortex-A72 support in BL1 and BL31 on FVP.
This allows the same TF binaries to run on a Cortex-A72 based FVP
without recompiling them.
> FVP: Compile ARM Cortex-A72 CPU support in

- docs/porting-guide.md
- drivers/io/io_fip.c
- drivers/io/io_memmap.c
- drivers/io/io_semihosting.c
- include/bl31/runtime_svc.h
- include/common/context_mgmt.h
- include/drivers/arm/arm_gic.h
- include/drivers/arm/cci400.h
- include/drivers/auth/img_parser_mod.h
- include/lib/bakery_lock.h
- include/lib/cassert.h
- include/plat/common/common_def.h
- include/plat/common/platform.h
- include/stdlib/sys/cdefs.h
- lib/aarch64/xlat_tables.c
- plat/arm/common/arm_io_storage.c
- plat/mediatek/mt8173/drivers/spm/spm.c
- services/std_svc/psci/psci_common.c
Move common compiler-specific macros into a generic, common header.
Fixes ARM-software/tf-issues#340
> Clean up __attribute__ usage

- docs/firmware-design.md
Since commit 804040d106, the Juno port has moved from per-CPU mailboxes
to a single shared one. This patch updates an out-dated reference to
the former per-CPU mailboxes mechanism in the Firmware Design.
> Doc: Update out-dated info about Juno's mailbox

- docs/porting-guide.md
GIC v2 and v3 specification references in the porting guide
should refer to publically visible links, not ARM internal links.
Change-Id: Ib47c8adda6a03581f23bcaed72d71c08c7dd9fb1
Signed-off-by: Yuping Luo <yuping.luo@arm.com>
> Update doc links in the porting guide

- docs/user-guide.md
- plat/arm/common/aarch64/arm_common.c
- plat/arm/common/arm_common.mk
Currently, Trusted Firmware on ARM platforms unlocks access to the
timer frame registers that will be used by the Non-Secure world. This
unlock operation should be done by the Non-Secure software itself,
instead of relying on secure firmware settings.
This patch adds a new ARM specific build option 'ARM_CONFIG_CNTACR'
to unlock access to the timer frame by setting the corresponding
bits in the CNTACR<N> register. The frame id <N> is defined by
'PLAT_ARM_NSTIMER_FRAME_ID'. Default value is true (unlock timer
access).
Documentation updated accordingly.
Fixes ARM-software/tf-issues#170
Change-Id: Id9d606efd781e43bc581868cd2e5f9c8905bdbf6
> ARM plat: add build option to unlock access to non-secure timer

- include/stdlib/sys/cdefs.h
Use the form with underscores to define the '__deprecated' macro to avoid
collisions with potentially defined macros, as suggested in gcc docs
(https://gcc.gnu.org/onlinedocs/gcc/Attribute-Syntax.html#Attribute-Syntax).
> cdefs.h: Use __deprecated__ instead of deprecated

- docs/porting-guide.md
- drivers/arm/pl011/pl011_console.S
- drivers/console/console.S
- include/drivers/arm/pl011.h
- plat/arm/common/aarch64/arm_helpers.S
- plat/mediatek/mt8173/aarch64/plat_helpers.S
- plat/nvidia/tegra/common/aarch64/tegra_helpers.S
The PL011 TRM (ARM DDI 0183G) specifies that the UART must be
disabled before any of the control registers are programmed. The
PL011 driver included in TF does not disable the UART, so the
initialization in BL2 and BL31 is violating this requirement
(and potentially in BL1 if the UART is enabled after reset).
This patch modifies the initialization function in the PL011
console driver to disable the UART before programming the
control registers.
Register clobber list and documentation updated.
Fixes ARM-software/tf-issues#300
Change-Id: I839b2d681d48b03f821ac53663a6a78e8b30a1a1
> Disable PL011 UART before configuring it

- docs/porting-guide.md
The memory translation library in Trusted Firmware supports
non-identity mappings for Physical to Virtual addresses since commit
f984ce84ba. However, the porting guide hasn't been updated
accordingly and still mandates the platform ports to use
identity-mapped page tables for all addresses.
This patch removes this out-dated information from the Porting Guide
and clarifies in which circumstances non-identity mapping may safely
be used.
Fixes ARM-software/tf-issues#258
> Porting Guide: Clarify identity-mapping requirement

- include/plat/arm/board/common/board_arm_def.h
- lib/aarch64/xlat_tables.c
- plat/mediatek/mt8173/include/platform_def.h
- plat/nvidia/tegra/include/platform_def.h
The debug prints used to debug translation table setup in xlat_tables.c
used the `printf()` standard library function instead of the stack
optimized `tf_printf()` API. DEBUG_XLAT_TABLE option was used to enable
debug logs within xlat_tables.c and it configured a much larger stack
size for the platform in case it was enabled. This patch modifies these
debug prints within xlat_tables.c to use tf_printf() and modifies the format
specifiers to be compatible with tf_printf(). The debug prints are now enabled
if the VERBOSE prints are enabled in Trusted Firmware via LOG_LEVEL build
option.
The much larger stack size definition when DEBUG_XLAT_TABLE is defined
is no longer required and the platform ports are modified to remove this
stack size definition.
Change-Id: …
> Use tf_printf() for debug logs from xlat_tables.c

- services/std_svc/psci/psci_off.c
- services/std_svc/psci/psci_on.c
- services/std_svc/psci/psci_private.h
When a CPU is powered down using PSCI CPU OFF API, it disables its caches
and updates its `aff_info_state` to OFF. The corresponding cache line is
invalidated by the CPU so that the update will be observed by other CPUs
running with caches enabled. There is a possibility that another CPU
which has been trying to turn ON this CPU via PSCI CPU ON API,
has already seen the update to `aff_info_state` and proceeds to update
the state to ON_PENDING prior to the cache invalidation. This may result
in the update of the state to ON_PENDING being discarded.
This patch fixes this issue by making sure that the update of `aff_info_state`
to ON_PENDING sticks by reading back the value after the cache flush and
retrying it if not updated. The patch also adds a dsbish() to
`psci_do_cpu_off()` to ensure …
> Fix PSCI CPU ON race when setting state to ON_PENDING

- Makefile
- docs/cpu-specific-build-macros.md
- include/lib/cpus/aarch64/cortex_a57.h
- lib/cpus/aarch64/cortex_a35.S
- lib/cpus/aarch64/cortex_a53.S
- lib/cpus/aarch64/cortex_a57.S
- lib/cpus/aarch64/cpu_helpers.S
- lib/cpus/cpu-ops.mk
The LDNP/STNP instructions as implemented on Cortex-A53 and
Cortex-A57 do not behave in a way most programmers expect, and will
most probably result in a significant speed degradation to any code
that employs them. The ARMv8-A architecture (see Document ARM DDI
0487A.h, section D3.4.3) allows cores to ignore the non-temporal hint
and treat LDNP/STNP as LDP/STP instead.
Introduce 2 new build flags: A53_DISABLE_NON_TEMPORAL_HINT and
A57_DISABLE_NON_TEMPORAL_HINT to enforce this behaviour on
Cortex-A53 and Cortex-A57. They are enabled by default.
Also unconditionally apply CPU reset operations for Cortex A35/A53/A57.
> Disable non-temporal hint on Cortex-A53/57

- services/std_svc/psci/psci_common.c
When BL31 is compiled at `-O3` optimization level using Linaro GCC 4.9
AArch64 toolchain, it reports the following error:
```
services/std_svc/psci/psci_common.c: In function 'psci_do_state_coordination':
services/std_svc/psci/psci_common.c:220:27: error: array subscript is above
array bounds [-Werror=array-bounds]
psci_req_local_pwr_states[pwrlvl - 1][cpu_idx] = req_pwr_state;
^
```
This error is a false positive and this patch resolves the error by asserting
the array bounds in `psci_do_state_coordination()`.
Fixes ARM-software/tf-issues#347
Change-Id: I3584ed7b2e28faf455b082cb3281d6e1d11d6495
> PSCI: Resolve GCC static analysis false positive

- drivers/arm/ccn/ccn.c
- drivers/arm/ccn/ccn_private.h
Currently, `ccn_snoop_dvm_domain_common()` is responsible for providing
a bitmap of HN-F and HN-I nodes in the interconnect. There is a request
node (RN) corresponding to the master interface (e.g. cluster) that needs
to be added or removed from the snoop/DVM domain. This request node is
removed from or added to each HN-F or HN-I node present in the bitmap
depending upon the type of domain.
The above logic is incorrect when participation of a master interface in
the DVM domain has to be managed. The request node should be removed
from or added to the single Miscellaneous Node (MN) in the system
instead of each HN-I node.
This patch fixes this by removing the intermediate
`ccn_snoop_dvm_domain_common()` and instead reads the MN registers to
get the needed node Id bitmap for snoop(HN-F …
> Bug fix: Rectify logic to enter or exit from DVM domain

- make_helpers/build_macros.mk
This allows reproducible builds (same source and same compiler produce
bit-identical results) and also allows coordinating the timestamp across
multiple projects, eg. with another firmware.
Signed-off-by: Patrick Georgi <pgeorgi@google.com>
[tested both with passing an override and without. both produced an image with the expected string]
> build system: allow overriding the build's timestamp

- include/plat/arm/common/aarch64/arm_macros.S
- include/plat/arm/common/aarch64/cci_macros.S
- include/plat/arm/common/plat_arm.h
- plat/arm/board/fvp/aarch64/fvp_common.c
- plat/arm/board/fvp/fvp_bl1_setup.c
- plat/arm/board/fvp/fvp_bl31_setup.c
- plat/arm/board/fvp/fvp_pm.c
- plat/arm/board/fvp/fvp_private.h
- plat/arm/board/fvp/include/plat_macros.S
- plat/arm/board/fvp/platform.mk
- plat/arm/board/juno/include/plat_macros.S
- plat/arm/board/juno/platform.mk
- plat/arm/common/aarch64/arm_common.c
- plat/arm/common/arm_bl1_setup.c
- plat/arm/common/arm_bl31_setup.c
- plat/arm/common/arm_cci.c
- plat/arm/common/arm_ccn.c
- plat/arm/common/arm_common.mk
- plat/arm/css/common/css_pm.c
ARM Trusted Firmware supports 2 different interconnect peripheral
drivers: CCI and CCN. ARM platforms are implemented using either of the
interconnect peripherals.
This patch adds a layer of abstraction to help ARM platform ports to
choose the right interconnect driver and corresponding platform support.
This is as described below:
1. A set of ARM common functions have been implemented to initialise an
interconnect and for entering/exiting a cluster from coherency. These
functions are prefixed as "plat_arm_interconnect_". Weak definitions of
these functions have been provided for each type of driver.
2.`plat_print_interconnect_regs` macro used for printing CCI registers is
moved from a common arm_macros.S to cci_macros.S.
3. The `ARM_CONFIG_HAS_CCI` flag used in `arm_config_flags` …
> Rework use of interconnect drivers

- docs/user-guide.md
The folowing build options were missing from the User Guide and have been
documented:
- CTX_INCLUDE_FPREGS
- DISABLE_PEDANTIC
- BUILD_STRING
- VERSION_STRING
- BUILD_MESSAGE_TIMESTAMP
Change-Id: I6a9c39ff52cad8ff04deff3ac197af84d437b8b7
> Add missing build options to the User Guide

- plat/arm/css/common/css_scpi.h
Replaced a long dash in a comment by the ASCII character '-'. Support
for multibyte character in the source character set is not enforced by
the C99 standard. To maximize compatibility with C processing tools
(e.g. compilers or static code analysis tools), they should be removed.
Change-Id: Ie318e380d3b44755109f042a76ebfd2229f42ae3
> Remove non-ASCII character from comment

- docs/user-guide.md
Move up to Base FVP version 7.2 (build 0.8/7202) and Foundation FVP version
9.5 (build 9.5.41) in the user guide.
Change-Id: Ie9900596216808cadf45f042eec639d906e497b2
> Move up FVP versions in the user guide

- docs/cpu-specific-build-macros.md
This patch adds a link to the Cortex-A57 Software Optimization Guide
in the ARM CPU Specific Build Macros document to justify the default
value of the A57_DISABLE_NON_TEMPORAL_HINT build flag.
> Cortex-A57: Add link to software optimization guide

- bl31/runtime_svc.c
- common/bl_common.c
- common/tf_printf.c
- drivers/arm/gic/gic_v3.c
This patch adds support for the `%p` format specifier in tf_printf()
following the example of the printf implementation of the stdlib used
in the trusted firmware.
Fixes ARM-software/tf-issues#292
Change-Id: I0b3230c783f735d3e039be25a9405f00023420da
> Add support for %p in tf_printf()

- docs/user-guide.md
- include/plat/arm/common/arm_def.h
- include/plat/arm/common/plat_arm.h
- plat/arm/board/fvp/fvp_def.h
- plat/arm/board/fvp/fvp_topology.c
- plat/arm/board/fvp/include/platform_def.h
- plat/arm/board/fvp/platform.mk
- plat/arm/board/juno/include/platform_def.h
- plat/arm/board/juno/juno_def.h
- plat/arm/board/juno/juno_topology.c
- plat/arm/board/juno/platform.mk
- plat/arm/board/juno/tsp/tsp-juno.mk
- plat/arm/css/common/css_topology.c
The common topology description helper funtions and macros for
ARM Standard platforms assumed a dual cluster system. This is not
flexible enough to scale to multi cluster platforms. This patch does
the following changes for more flexibility in defining topology:
1. The `plat_get_power_domain_tree_desc()` definition is moved from
`arm_topology.c` to platform specific files, that is `fvp_topology.c`
and `juno_topology.c`. Similarly the common definition of the porting
macro `PLATFORM_CORE_COUNT` in `arm_def.h` is moved to platform
specific `platform_def.h` header.
2. The ARM common layer porting macros which were dual cluster specific
are now removed and a new macro PLAT_ARM_CLUSTER_COUNT is introduced
which must be defined by each ARM standard platform.
3. A new mandatory ARM common layer …
> Allow multi cluster topology definitions for ARM platforms

- plat/mediatek/mt8173/drivers/gpio/gpio.c
- plat/mediatek/mt8173/plat_pm.c
All files including plat/mediatek/mt8173/drivers/gpio/gpio.h were
using system includes instead of user includes, which may cause the
wrong version of the header to be included. Said includes have been
changed to user includes to make sure that the included file is the
wanted one.
Change-Id: I29bdfe96fbd9a7900875e2357bbb43f3ea431fa5
> Fix gpio includes of mt8173 platform to avoid collision.

- docs/porting-guide.md
- drivers/arm/pl061/pl061_gpio.c
- drivers/gpio/gpio.c
- include/drivers/arm/pl061_gpio.h
- include/drivers/gpio.h
Implement gpio framework and PL061 gpio driver. ARM-software/tf-issues#351
Changelog:
v5:
1. Move comments after license text.
2. Use CASSERT on PLAT_PL061_MAX_GPIOS.
3. Add assert(ops) in gpio driver.
4. Adjust the comments of PLAT_PL061_MAX_GPIOS in document.
v4:
1. Clean code with more assert.
2. Remove return flag in set_direction() and set_value().
3. Add PLAT_PL061_MAX_GPIOS define.
v3:
1. Add more comments in gpio driver.
2. Add more assert in both gpio & pl061 driver.
3. Add get_direction() in gpio ops.
v2:
1. Update with the standard copyright text.
2. Replace "uint32_t" by "unsigned int" according to the rules in wiki.
> Pl061 gpio v5

- docs/user-guide.md
- include/plat/arm/board/common/board_arm_def.h
- plat/arm/board/common/board_common.mk
- plat/arm/board/juno/include/platform_def.h
- plat/arm/board/juno/platform.mk
`board_arm_def.h` contains multiple definitions of
`PLAT_ARM_MMAP_ENTRIES` and `MAX_XLAT_TABLES` that are optimised for
memory usage depending upon the chosen build configuration. To ease
maintenance of these constants, this patch replaces their multiple
definitions with a single set of definitions that will work on all ARM
platforms.
Platforms can override the defaults with optimal values by enabling the
`ARM_BOARD_OPTIMISE_MMAP` build option. An example has been provided in
the Juno ADP port.
Additionally, `PLAT_ARM_MMAP_ENTRIES` is increased by one to accomodate
future ARM platforms.
Change-Id: I5ba6490fdd1e118cc9cc2d988ad7e9c38492b6f0
> Rationalise MMU and Page table related constants on ARM platforms

- drivers/arm/pl011/pl011_console.S
The PL011 initialization function disables the UART, flushes the FIFO
and waits for the current character to be transmitted before applying
the configuration and enabling the UART. This waiting might result in
a deadlock if the FIFO is disabled while another CPU is printing a
message since the flush of FIFO will never finish.
This patch fixes the problem by removing the flush operation and the
loop for last character completion from the initialization function.
The UART is disabled, configured and enabled again.
Change-Id: I1ca0b6bd9f352c12856f10f174a9f6eaca3ab4ea
> Fix potential deadlock in PL011 init function

- bl1/bl1_context_mgmt.c
- bl1/bl1_fwu.c
- bl1/tbbr/tbbr_img_desc.c
- include/common/bl_common.h
- include/plat/arm/board/common/board_arm_def.h
- include/plat/arm/common/arm_def.h
- include/plat/common/common_def.h
- plat/arm/common/arm_bl1_fwu.c
- plat/arm/common/arm_common.mk
This patch fixes inconsistencies in bl1_tbbr_image_descs[]
and miscellaneous fixes in Firmware Update code.
Following are the changes:
* As part of the original FWU changes, a `copied_size`
field was added to `image_info_t`. This was a subtle binary
compatibility break because it changed the size of the
`bl31_params_t` struct, which could cause problems if
somebody used different versions of BL2 or BL31, one with
the old `image_info_t` and one with the new version.
This patch put the `copied_size` within the `image_desc_t`.
* EXECUTABLE flag is now stored in `ep_info.h.attr` in place
of `image_info.h.attr`, associating it to an entrypoint.
* The `image_info.image_base` is only relevant for secure
images that are copied from non-secure memory into secure
memory. This patch removes …
> Fix the inconsistencies in bl1_tbbr_image_descs[]

- docs/porting-guide.md
This patch clarifies a porting API in the Porting Guide that do not
follow the ARM Architecture Program Calling Standards (AAPCS). The
list of registers that are allowed to be clobbered by this API has
been updated in the Porting Guide.
Fixes ARM-software/tf-issues#259
Change-Id: Ibf2adda2e1fb3e9b8f53d8a918d5998356eb8fce
> Porting guide: Clarify API that don't follow AAPCS

- include/lib/aarch64/arch.h
- include/lib/aarch64/xlat_tables.h
- lib/aarch64/xlat_tables.c
At the moment, the memory translation library allows to create memory
mappings of 2 types:
- Device nGnRE memory (named MT_DEVICE in the library);
- Normal, Inner Write-back non-transient, Outer Write-back
non-transient memory (named MT_MEMORY in the library).
As a consequence, the library code treats the memory type field as a
boolean: everything that is not device memory is normal memory and
vice-versa.
In reality, the ARMv8 architecture allows up to 8 types of memory to
be used at a single time for a given exception level. This patch
reworks the memory attributes such that the memory type is now defined
as an integer ranging from 0 to 7 instead of a boolean. This makes it
possible to extend the list of memory types supported by the memory
translation library.
The priority system …
> Extend memory attributes to map non-cacheable memory

- bl2/aarch64/bl2_entrypoint.S
- bl2u/aarch64/bl2u_entrypoint.S
- bl31/aarch64/crash_reporting.S
- bl32/tsp/aarch64/tsp_entrypoint.S
- bl32/tsp/aarch64/tsp_exceptions.S
- common/aarch64/debug.S
- docs/porting-guide.md
- include/common/el3_common_macros.S
- include/plat/common/platform.h
- plat/arm/board/fvp/aarch64/fvp_helpers.S
- plat/arm/board/juno/aarch64/juno_helpers.S
- plat/common/aarch64/platform_helpers.S
Added a new platform porting function plat_panic_handler, to allow
platforms to handle unexpected error situations. It must be
implemented in assembly as it may be called before the C environment
is initialized. A default implementation is provided, which simply
spins.
Corrected all dead loops in generic code to call this function
instead. This includes the dead loop that occurs at the end of the
call to panic().
All unnecesary wfis from bl32/tsp/aarch64/tsp_exceptions.S have
been removed.
Change-Id: I67cb85f6112fa8e77bd62f5718efcef4173d8134
> Remove all non-configurable dead loops

- include/common/debug.h
- lib/cpus/aarch64/cortex_a53.S
- lib/cpus/aarch64/cortex_a57.S
- lib/cpus/aarch64/cpu_helpers.S
The assembler helper function `print_revision_warning` is used when a
CPU specific operation is enabled in the debug build (e.g. an errata
workaround) but doesn't apply to the executing CPU's revision/part number.
However, in some cases the system integrator may want a single binary to
support multiple platforms with different IP versions, only some of which
contain a specific erratum.  In this case, the warning can be emitted very
frequently when CPUs are being powered on/off.
This patch modifies this warning print behaviour so that it is emitted only
when LOG_LEVEL >= LOG_LEVEL_VERBOSE. The `debug.h` header file now contains
guard macros so that it can be included in assembly code.
Change-Id: Ic6e7a07f128dcdb8498a5bfdae920a8feeea1345
> Make cpu operations warning a VERBOSE print

- docs/firmware-design.md
- docs/porting-guide.md
The Firmware Design document is meant to provide a general overview
of the Trusted Firmware code. Although it is useful to provide some
guidance around the responsibilities of the platform layer, it should
not provide too much platform specific implementation details. Right
now, some sections are too tied to the implementation on ARM
platforms. This makes the Firmware Design document harder to digest.
This patch simplifies this aspect of the Firmware Design document.
The sections relating the platform initialisations performed by the
different BL stages have been simplified and the extra details about
the ARM platforms implementation have been moved to the Porting Guide
when appropriate.
This patch also provides various documentation fixes and additions
in the Firmware Design and Platform …
> Simplify Firmware Design document

- Makefile
- bl2/bl2_main.c
- docs/porting-guide.md
- docs/user-guide.md
Enable alternative boot flow where BL2 does not load BL33 from
non-volatile storage, and BL31 hands execution over to a preloaded
BL33.
The flag used to enable this bootflow is BL33_BASE, which must hold
the entrypoint address of the BL33 image. The User Guide has been
updated with an example of how to use this option with a bootwrapped
kernel.
Change-Id: I48087421a7b0636ac40dca7d457d745129da474f
> Enable preloaded BL33 alternative boot flow

- bl1/aarch64/bl1_arch_setup.c
- bl31/aarch64/bl31_arch_setup.c
- bl31/aarch64/crash_reporting.S
- common/context_mgmt.c
- docs/firmware-design.md
- docs/user-guide.md
- include/common/el3_common_macros.S
- include/lib/aarch64/arch.h
- include/lib/aarch64/arch_helpers.h
On r0p2 revision and above revision, despite what is stated in ARM DDI0500D TRM
Cortex A53 r0p2 SCR_EL3 description in Table 4-77, asynchronous exceptions
generated by the code running in EL3 are not taken in EL3 when SCR_EL3[EA] is
zero.
DDI0487A.b Architecture Reference Manual does not reflect the actual
behaviour of r0p2.
DDI0487A.e Architecture Reference Manual D7.2.80 SCR_EL3 description depicts
the observed behaviour.
Fixes arm-software/tf-issues#368
Signed-off-by: Gerald Lejeune <gerald.lejeune@st.com>
> Enable asynchronous abort exceptions during boot

- docs/user-guide.md
- include/plat/arm/board/common/board_arm_def.h
- include/plat/arm/common/arm_def.h
- plat/arm/board/fvp/aarch64/fvp_common.c
- plat/arm/board/fvp/include/platform_def.h
- plat/arm/common/arm_bl2_setup.c
- plat/arm/common/arm_common.mk
This patch adds an option to the ARM common platforms to load BL31 in the
TZC secured DRAM instead of the default secure SRAM.
To enable this feature, set `ARM_BL31_IN_DRAM` to 1 in build options.
If TSP is present, then setting this option also sets the TSP location
to DRAM and ignores the `ARM_TSP_RAM_LOCATION` build flag.
To use this feature, BL2 platform code must map in the DRAM used by
BL31. The macro ARM_MAP_BL31_SEC_DRAM is provided for this purpose.
Currently, only the FVP BL2 platform code maps in this DRAM.
Change-Id: If5f7cc9deb569cfe68353a174d4caa48acd78d67
> Add support to load BL31 in DRAM

- plat/mediatek/mt8173/bl31_plat_setup.c
- plat/mediatek/mt8173/drivers/spm/spm.c
- plat/mediatek/mt8173/include/mt8173_def.h
BL31 usually handles confidential stuff, its memory must not be
read/write accessible from non-secure world. This patch protects
the BL31 memory range from non-secure read/write access.
Change-Id: I442fb92b667bb2f9a62d471a90508b1ba4489911
Signed-off-by: Jimmy Huang <jimmy.huang@mediatek.com>
> mt8173: Protect BL31 memory from non-secure access

- docs/porting-guide.md
- include/plat/common/platform.h
- plat/arm/common/aarch64/arm_common.c
This patch modifies the return type of the platform API
`plat_get_ns_image_entrypoint()` from `unsigned long` to
`uintptr_t` in accordance with the coding guidelines.
Change-Id: Icb4510ca98b706aa4d535fe27e203394184fb4ca
> Modify return type of plat_get_ns_image_entrypoint()

- common/tf_printf.c
Add support for %z format specific in tf_printf() to support
printing data of type size_t
Fixes ARM-software/tf-issues#380
Signed-off-by Scott Branden <scott.branden@broadcom.com>
> Add support for %z in tf_print()

- .gitignore
- Makefile
- bl32/tsp/tsp.mk
- docs/user-guide.md
- make_helpers/build_env.mk
- make_helpers/build_macros.mk
- make_helpers/cygwin.mk
- make_helpers/msys.mk
- make_helpers/plat_helpers.mk
- make_helpers/unix.mk
- make_helpers/windows.mk
- tools/cert_create/Makefile
- tools/fip_create/Makefile
- tools/fip_create/firmware_image_package.h
- tools/fip_create/uuid.h
These changes enable building on host environments other than Linux/Unix.
This is for developer convenience, rather than a full solution, as the certification tool build is not tested.
This patch set adds changes for building on Windows CMD.EXE, Cygwin and MinGW.
> Make improvements for host environment portability

- plat/mediatek/mt8173/drivers/spm/spm.c
To fix build errors in following build conditions,
DEBUG=1 LOG_LEVEL<40
DEBUG=0 LOG_LEVEL>=40
Change-Id: Ib34aed07b2ae0abd8a3a46948adc9fbeaae715aa
Signed-off-by: yt.lee <yt.lee@mediatek.com>
> mt8173: fix spm driver build errors

- docs/firmware-design.md
- include/common/el3_common_macros.S
This patch enables the SCR_EL3.SIF (Secure Instruction Fetch) bit in BL1 and
BL31 common architectural setup code. When in secure state, this disables
instruction fetches from Non-secure memory.
NOTE: THIS COULD BREAK PLATFORMS THAT HAVE SECURE WORLD CODE EXECUTING FROM
NON-SECURE MEMORY, BUT THIS IS CONSIDERED UNLIKELY AND IS A SERIOUS SECURITY
RISK.
Fixes ARM-Software/tf-issues#372
Change-Id: I684e84b8d523c3b246e9a5fabfa085b6405df319
> Enable SCR_EL3.SIF bit

- Makefile
- include/plat/arm/common/arm_def.h
- plat/arm/common/arm_bl2_setup.c
Previously, when building TF without SPD support, BL2 tried to load a
BL32 image from the FIP and fails to find one, which resulted on
warning messages on the console. Even if there is a BL32 image in the
FIP it shouldn't be loaded because there is no way to transfer
control to the Secure Payload without SPD support.
The Makefile has been modified to pass a define of the form
SPD_${SPD} to the source code the same way it's done for PLAT. The
define SPD_none is then used to undefine BL32_BASE when BL32 is not
used to prevent BL2 from trying to load a BL32 image and failing,
thus removing the warning messages mentioned above.
Fixes ARM-software/tf-issues#287
Change-Id: Ifeb6f1c26935efb76afd353fea88e87ba09e9658
> Remove BL32_BASE when building without SPD for FVP

- Makefile
- bl2/bl2_main.c
- docs/porting-guide.md
- docs/user-guide.md
- plat/arm/common/arm_bl31_setup.c
- Fixed boot when both BL33_BASE and RESET_TO_BL31 are used.
- BL33_BASE build option renamed to PRELOADED_BL33_BASE to avoid confusion with other options with similar name.
NOTE: PLATFORMS USING BUILD OPTION `BL33_BASE` MUST CHANGE TO THE NEW
BUILD OPTION `PRELOADED_BL33_BASE`.
> Rename BL33_BASE and make it work with RESET_TO_BL31

- Makefile
Fixed coding style check target of the Makefile. Prevent it from checking documentation files.
> Fix style check and remove markdown files from it

- acknowledgements.md
- docs/plat/xilinx-zynqmp.md
- drivers/cadence/uart/cdns_console.S
- include/drivers/cadence/cdns_uart.h
- plat/arm/common/aarch64/arm_common.c
- plat/xilinx/zynqmp/aarch64/zynqmp_common.c
- plat/xilinx/zynqmp/aarch64/zynqmp_helpers.S
- plat/xilinx/zynqmp/bl31_zynqmp_setup.c
- plat/xilinx/zynqmp/include/plat_macros.S
- plat/xilinx/zynqmp/include/platform_def.h
- plat/xilinx/zynqmp/plat_psci.c
- plat/xilinx/zynqmp/plat_topology.c
- plat/xilinx/zynqmp/plat_zynqmp.c
- plat/xilinx/zynqmp/platform.mk
- plat/xilinx/zynqmp/pm_service/pm_api_sys.c
- plat/xilinx/zynqmp/pm_service/pm_api_sys.h
- plat/xilinx/zynqmp/pm_service/pm_client.c
- plat/xilinx/zynqmp/pm_service/pm_client.h
- plat/xilinx/zynqmp/pm_service/pm_common.h
- plat/xilinx/zynqmp/pm_service/pm_defs.h
- plat/xilinx/zynqmp/pm_service/pm_ipi.c
- plat/xilinx/zynqmp/pm_service/pm_ipi.h
- plat/xilinx/zynqmp/pm_service/pm_svc_main.c
- plat/xilinx/zynqmp/pm_service/pm_svc_main.h
- plat/xilinx/zynqmp/sip_svc_setup.c
- plat/xilinx/zynqmp/tsp/tsp-zynqmp.mk
- plat/xilinx/zynqmp/tsp/tsp_plat_setup.c
- plat/xilinx/zynqmp/zynqmp_def.h
- plat/xilinx/zynqmp/zynqmp_private.h
This series provides the initial support for [Xilinx Zynq UltraScale+ MPSoC](http://www.xilinx.com/products/silicon-devices/soc/zynq-ultrascale-mpsoc.html). The ATF runs on the quad A53 cluster of the SoC.
In the current state, this provides enough to boot up the system and a shallow implementation of suspend.
> Support for Xilinx Zynq UltraScale+ MPSoC

- services/spd/opteed/opteed_main.c
In new communication protocol between optee os and linux driver,
r0-r6 registers are used. opteed need to copy these registers
as well when optee context registers are initialized.
Change-Id: Ifb47b73f847c61746cb58ea78411c1c71f208030
Signed-off-by: Ashutosh Singh <ashutosh.singh@arm.com>
> pass r0-r6 as part of smc param

- plat/rockchip/rk3368/drivers/pmu/pmu.c
This patch fixes the compilation error in Rockchip rk3368 platform port when
it is built in release mode.
Fixes ARM-software/tf-issues#389
Change-Id: I1a3508ac3a620289cf700e79db8f08569331ac53
> Fix build error in Rockchip platform

- drivers/arm/tzc/tzc400.c
- drivers/arm/tzc/tzc_common_private.c
- drivers/arm/tzc/tzc_dmc500.c
- include/drivers/arm/tzc400.h
- include/drivers/arm/tzc_dmc500.h
Currently the `tzc400_configure_region` and `tzc_dmc500_configure_region`
functions uses uintptr_t as the data type for `region_top` and `region_base`
variables, which will be converted to 32/64 bits for AArch32/AArch64
respectively. But the expectation is to keep these addresses at least 64 bit.
This patch modifies the data types to make it at least 64 bit by using
unsigned long long instead of uintptr_t for the `region_top` and
`region_base` variables. It also modifies the associated macros
`_tzc##fn_name##_write_region_xxx` accordingly.
Change-Id: I4e3c6a8a39ad04205cf0f3bda336c3970b15a28b
> Use unsigned long long instead of uintptr_t in TZC400/DMC500 drivers

- Makefile
- include/common/context_mgmt.h
- include/lib/bakery_lock.h
- make_helpers/build_macros.mk
- make_helpers/windows.mk
- Give user's compiler flags precedence over default ones
- Fix build error with optimizations disabled (-O0)
> Add support for unoptimised (-O0) build

- include/plat/common/platform.h
- plat/arm/common/aarch64/arm_common.c
- plat/arm/common/arm_bl31_setup.c
- plat/mediatek/mt8173/aarch64/platform_common.c
- plat/nvidia/tegra/include/tegra_private.h
- plat/nvidia/tegra/soc/t132/plat_setup.c
- plat/nvidia/tegra/soc/t210/plat_setup.c
- plat/rockchip/common/aarch64/platform_common.c
- plat/xilinx/zynqmp/aarch64/zynqmp_common.c
This patch moves the definition for `plat_get_syscnt_freq()`
from arm_bl31_setup.c to arm_common.c. This could be useful
in case a delay timer needs to be installed based on the
generic timer in other BLs.
This patch also modifies the return type for this function
from `uint64_t` to `unsigned long long` within ARM and other
platform files.
Change-Id: Iccdfa811948e660d4fdcaae60ad1d700e4eda80d
> Move `plat_get_syscnt_freq()` to arm_common.c

- plat/rockchip/rk3368/include/platform_def.h
- plat/rockchip/rk3399/include/platform_def.h
- plat/rockchip/rk3399/rk3399_def.h
This patch has the following change for rk3399.
* Set the uart to 115200 since the loader decide to set
uart baud to 115200Hz. So the ATF also should set uart baud to 115200.
* We need ensure the bl31 base is greater than 4KB since there are have
the shared mem for coreboot.(Note: the previous vesion was tested with uboot)
Otherwise, we will happen the exception crash since the ddr area won't
to work from the shared ram address in some cases.
For example, the exception crash:
CBFS: Found @ offset 19c80 size 24074
exception _sync_sp_el0
ELR = 0x0000000000008000
ESR = 0x0000000002000000
SPSR = 0x600003cc
FAR = 0xffffffff00000000
SP = 0x00000000ff8ed230
...
X29 = 0x00000000ff8c1fc0
X30 = 0x000000000030e3b0
exception death
Change-Id: I8bc557c6bcaf6804d2a313b38667d3e2517881d7
Signed-off-by: …
> rockchip: fixes for the required

- plat/arm/common/aarch64/arm_common.c
This patch puts the definition of `plat_get_syscnt_freq()`
under `#ifdef ARM_SYS_CNTCTL_BASE` in arm_common.c file.
This is the fix for compilation error introduced by commit-id
`749ade4`, for platforms that use arm_common.c but do not
provide a memory mapped interface to the generic counter.
Fixes ARM-software/tf-issues#395
Change-Id: I2f2b10bd9500fa15308541ccb15829306a76a745
> Conditionally compile `plat_get_syscnt_freq()` in ARM standard platforms

- lib/xlat_tables/xlat_tables_common.c
This patch fixes the computation of the bitmask used to isolate
the level 1 field of a virtual address. The whole computation needs
to work on 64-bit values to produce the correct bitmask value.
XLAT_TABLE_ENTRIES_MASK being a C constant, it is a 32-bit value
so it needs to be extended to a 64-bit value before it takes part
in any other computation.
This patch fixes this bug by casting XLAT_TABLE_ENTRIES_MASK as
an unsigned long long.
Note that this bug doesn't manifest itself in practice because
address spaces larger than 39 bits are not yet supported in the
Trusted Firmware.
> Fix computation of L1 bitmask in the translation table lib

- tools/fip_create/fip_create.c
Not sure whether I should submit against `integration` or `master` so I've done both, just reject whichever is wrong.
> fip_create: Fix exit status for missing output filename (2)

- docs/porting-guide.md
The translation table library code has moved from lib/aarch64/ to
lib/xlat_tables/ since commit 3ca9928df but the Porting Guide still
points to the old location. This patch fixes this issue.
> Doc: Fix the path to the xlat lib

- plat/rockchip/rk3368/drivers/pmu/pmu.c
- plat/rockchip/rk3399/drivers/pmu/pmu.c
This patch adds some debug assertions ensuring that array indices
are within the bounds of the array.
Change-Id: I96ee81d14834c1e92cdfb7e60b49995cdacfd93a
> Rockchip: Add some debug assertions in the PMU driver

- docs/user-guide.md
- drivers/arm/ccn/ccn.c
- drivers/arm/ccn/ccn_private.h
- include/drivers/arm/ccn.h
- plat/arm/board/fvp/fvp_common.c
- plat/arm/board/fvp/fvp_def.h
- plat/arm/board/fvp/include/plat_macros.S
- plat/arm/board/fvp/include/platform_def.h
- plat/arm/board/fvp/platform.mk
- plat/arm/common/arm_ccn.c
This patch set adds support for FVP models with CCN-502 as the interconnect.
> Add CCN support to FVP

- docs/porting-guide.md
- include/bl31/services/psci.h
- services/std_svc/psci/psci_entry.S
- services/std_svc/psci/psci_off.c
- services/std_svc/psci/psci_suspend.c
This patch adds a new optional platform hook `pwr_domain_pwr_down_wfi()` in
the plat_psci_ops structure. This hook allows the platform to perform platform
specific actions including the wfi invocation to enter powerdown. This hook
is invoked by both psci_do_cpu_off() and psci_cpu_suspend_start() functions.
The porting-guide.md is also updated for the same.
This patch also modifies the `psci_power_down_wfi()` function to invoke
`plat_panic_handler` incase of panic instead of the busy while loop.
Fixes ARM-Software/tf-issues#375
Change-Id: Iba104469a1445ee8d59fb3a6fdd0a98e7f24dfa3
> PSCI: Add pwr_domain_pwr_down_wfi() hook in plat_psci_ops

- drivers/gpio/gpio.c
- include/drivers/gpio.h
- plat/rockchip/common/bl31_plat_setup.c
- plat/rockchip/common/include/plat_params.h
- plat/rockchip/common/include/plat_private.h
- plat/rockchip/common/params_setup.c
- plat/rockchip/common/plat_pm.c
- plat/rockchip/rk3368/platform.mk
- plat/rockchip/rk3399/drivers/gpio/rk3399_gpio.c
- plat/rockchip/rk3399/drivers/pmu/pmu.c
- plat/rockchip/rk3399/drivers/pmu/pmu.h
- plat/rockchip/rk3399/drivers/soc/soc.c
- plat/rockchip/rk3399/drivers/soc/soc.h
- plat/rockchip/rk3399/include/platform_def.h
- plat/rockchip/rk3399/platform.mk
- plat/rockchip/rk3399/rk3399_def.h
Add the gpio configure to complete the system off/reset soc.
In order to properly reboot, the AP should not use the standar dreboot methods. We need to use "AP_EC_WARM_RESET_REQ" .
The reason for this is that the reset method won't reset the TPM.
That means:
I think the ARM Trusted Firmware is in charge of rebooting the machine, even when the kernel is running (PSCI is used to call ATF). That means the firmware needs to do this.
Also if the firmware sees that a Hardware Watchdog Reset happened it should log (using the event log) and then do a GPIO-based reset so that the TPM gets rebooted.
> rockchip/rk3399: Support the gpio driver and configure

- Makefile
- bl1/bl1_context_mgmt.c
- bl31/bl31_main.c
- common/aarch64/context.S
- docs/user-guide.md
- include/common/context.h
The system registers that are saved and restored in CPU context include
AArch32 systems registers like SPSR_ABT, SPSR_UND, SPSR_IRQ, SPSR_FIQ,
DACR32_EL2, IFSR32_EL2 and FPEXC32_EL2. Accessing these registers on an
AArch64-only (i.e. on hardware that does not implement AArch32, or at least not
at EL1 and higher ELs) platform leads to an exception. This patch introduces the
build option `CTX_INCLUDE_AARCH32_REGS` to specify whether to include
these AArch32 systems registers in the cpu context or not. By default this build
option is set to 1 to ensure compatibility. AArch64-only platforms must set it to 0.
A runtime check is added in BL1 and BL31 cold boot path to verify this.
Fixes ARM-software/tf-issues#386
Change-Id: I720cdbd7ed7f7d8516635a2ec80d025f478b95ee
> Build option to include AArch32 registers in cpu context

- include/lib/cpus/aarch64/cortex_a73.h
- lib/cpus/aarch64/cortex_a73.S
- plat/arm/board/fvp/platform.mk
This patch adds ARM Cortex-A73 MPCore Processor support
in the CPU specific operations framework. It also includes
this support for the Base FVP port.
Change-Id: I0e26b594f2ec1d28eb815db9810c682e3885716d
> Add support for ARM Cortex-A73 MPCore Processor

- plat/arm/common/aarch64/arm_common.c
Building TF with ERROR_DEPRECATED=1 fails because of a missing
semi-column. This patch fixes this syntax error.
> Fix a syntax error in plat/arm/common/aarch64/arm_common.c

- plat/arm/board/common/board_arm_trusted_boot.c
- plat/arm/board/fvp/fvp_common.c
- plat/arm/board/fvp/fvp_trusted_boot.c
- plat/arm/board/fvp/platform.mk
Replaced placeholder implementation of plat_set_nv_ctr for FVP
platforms by a working one.
On FVP, the mapping of region DEVICE2 has been changed from RO to RW
to prevent exceptions when writing to the NV counter, which is
contained in this region.
Change-Id: I56a49631432ce13905572378cbdf106f69c82f57
> Implement plat_set_nv_ctr for FVP platforms

- include/lib/xlat_tables.h
As of commit e1ea9290bb, if the attributes of an inner memory region
are different than the outer region, new page tables are generated
regardless of how "restrictive" they are. This patch removes an
out-dated comment still referring to the old priority system based
on which attributes were more restrictive.
> xlat lib: Remove out-dated comment

- docs/porting-guide.md
- drivers/auth/auth_mod.c
- include/plat/common/platform.h
A production ROM with TBB enabled must have the ability to boot test software
before a real ROTPK is deployed (e.g. manufacturing mode). Previously the
function plat_get_rotpk_info() must return a valid ROTPK for TBB to succeed.
This patch adds an additional bit `ROTPK_NOT_DEPLOYED` in the output `flags`
parameter from plat_get_rotpk_info(). If this bit is set, then the ROTPK
in certificate is used without verifying against the platform value.
Fixes ARM-software/tf-issues#381
Change-Id: Icbbffab6bff8ed76b72431ee21337f550d8fdbbb
> Allow dynamic overriding of ROTPK verification

- plat/arm/css/common/css_pm.c
In GICv3 mode, the non secure group1 interrupts are signalled via the
FIQ line in EL3. To support waking up from CPU_SUSPEND to standby on
these systems, EL3 should route FIQ to EL3 temporarily before wfi and
restore the original setting after resume. This patch makes this change
for the CSS platforms in the `css_cpu_standby` psci pm ops hook.
Change-Id: Ibf3295d16e2f08da490847c1457bc839e1bac144
> CSS: Add support to wake up the core from wfi in GICv3

- services/spd/opteed/opteed_main.c
OPTEE to execute in aarch64 bit mode, set it accordingly
when execution transitions from EL3 to EL1
Change-Id: I59f2f940bdc1aac10543045b006a137d107ec95f
Signed-off-by: Ashutosh Singh <ashutosh.singh@arm.com>
> opteed: assume aarch64 for optee

- docs/plat/xilinx-zynqmp.md
- make_helpers/build_macros.mk
- plat/xilinx/zynqmp/bl31_zynqmp_setup.c
- plat/xilinx/zynqmp/platform.mk
- plat/xilinx/zynqmp/tsp/tsp_plat_setup.c
- plat/xilinx/zynqmp/zynqmp_def.h
Add a zynqmp-specific config option, ZYNQMP_CONSOLE, to select a UART device.
> zynqmp: Make UART selectable

- tools/cert_create/src/main.c
With the introduction of commit `96103d5a`, the Certificate
Generation tool is not able to generate FWU certificate and
while doing so it does segmentation fault.
This happens because it is now required to pass non-volatile
counter values to the `cert_create` tool from the command line
for creating the trusted firmware certificates.
But in case of creating FWU certificate these counter values are not
being passed to the tool and as a consequence the `cert_create` tool
try to use the NULL argument and errors out with Segmentation fault.
This patch fixes this issue by providing a check before using the
command line argument passed in the case of `EXT_TYPE_NVCOUNTER`
certificate extension.
Change-Id: Ie17d0c1502b52aaa8500f3659c2da2448ab0347a
> Fix `cert_create` tool for Segmentation fault

- include/lib/cpus/aarch64/cortex_a53.h
- include/lib/cpus/aarch64/cortex_a57.h
- include/lib/cpus/aarch64/cortex_a72.h
- include/lib/cpus/aarch64/cortex_a73.h
- lib/cpus/aarch64/cortex_a53.S
- lib/cpus/aarch64/cortex_a57.S
- lib/cpus/aarch64/cortex_a72.S
- lib/cpus/aarch64/cortex_a73.S
This patch adds cpumerrsr_el1 and l2merrsr_el1 error reporting
registers to non_el3_sys_regs.
These registers hold the ECC errors on L1 and L2 Caches.
Signed-off-by: Naga Sureshkumar Relli <nagasure@xilinx.com>
> bl31: Add error reporting registers

- drivers/arm/gic/arm_gic.c
The legacy GIC driver assumes that the SGIs and PPIs are Group0 during
initialization. This is true if the driver is the first one to initialize
the GIC hardware after reset. But in some cases, earlier BL stages could
have already initialized the GIC hardware which means that SGI and PPI
configuration are not the expected reset values causing assertion failure
in `gicd_set_ipriorityr()`. This patch explicitly resets the SGI and PPI
to Group0 prior to their initialization in the driver. The same patch is
not done in the GICv2-only driver because unlike in the legacy driver,
`gicd_set_ipriorityr()` of GICv2 driver doesn't enforce this policy and
the appropriate group is set irrespective of the initial value.
Fixes ARM-software/tf-issues#396
Change-Id: …
> GIC: Ensure SGIs and PPIs are Group0 before setup

- include/common/asm_macros.S
- plat/common/aarch64/platform_mp_stack.S
- plat/common/aarch64/platform_up_stack.S
The per-cpu stacks should be aligned to the cache-line size and
the `declare_stack` helper in asm_macros.S macro assumed a
cache-line size of 64 bytes. The platform defines the cache-line
size via CACHE_WRITEBACK_GRANULE macro. This patch modifies
`declare_stack` helper macro to derive stack alignment from the
platform defined macro.
Change-Id: I1e1b00fc8806ecc88190ed169f4c8d3dd25fe95b
> Derive stack alignment from CACHE_WRITEBACK_GRANULE

- plat/rockchip/common/include/rockchip_sip_svc.h
- plat/rockchip/common/rockchip_sip_svc.c
- plat/rockchip/rk3368/include/plat_sip_calls.h
- plat/rockchip/rk3368/plat_sip_calls.c
- plat/rockchip/rk3368/platform.mk
- plat/rockchip/rk3399/include/plat_sip_calls.h
- plat/rockchip/rk3399/plat_sip_calls.c
- plat/rockchip/rk3399/platform.mk
Software executing in the normal world and in the trusted world at
exception levels lower than EL3 will request runtime services using the
SMC instrction.
See the documentation here:
https://github.com/ARM-software/arm-trusted-firmware/blob/master/docs/
rt-svc-writers-guide.md
Okay, on the moment.
This to be implemented as an EL3 Runtime Service in rockchip BL31
platform port, using the "SiP Service Call" range as specified in the
SMC Calling Convention.
Change-Id: I0a638dd0b653c28b08f79d89f77ed7c69864017d
> rockchip: support plat SIP runtime service for rk3399

- lib/psci/psci_common.c
- lib/psci/psci_private.h
- lib/psci/psci_suspend.c
A PSCI CPU_SUSPEND request to place a CPU in retention states at power levels
higher than the CPU power level is subject to the same state coordination as a
power down state. A CPU could implement multiple retention states at a
particular power level. When exiting WFI, the non-CPU power levels may be in a
different retention state to what was initially requested, therefore each CPU
should refresh its view of the states of all power levels.
Previously, a CPU re-used the state of the power levels when it entered the
retention state. This patch fixes this issue by ensuring that a CPU upon exit
from retention reads the state of each power level afresh.
Change-Id: I93b5f5065c63400c6fd2598dbaafac385748f989
> Fix use of stale power states in PSCI standby finisher

- docs/user-guide.md
- include/plat/arm/board/common/board_arm_def.h
- plat/arm/board/common/board_common.mk
- plat/arm/board/fvp/include/platform_def.h
- plat/arm/board/juno/include/platform_def.h
- plat/arm/board/juno/platform.mk
Compile option `ARM_BOARD_OPTIMISE_MMAP` has been renamed to
`ARM_BOARD_OPTIMISE_MEM` because it now applies not only to defines
related to the translation tables but to the image size as well.
The defines `PLAT_ARM_MAX_BL1_RW_SIZE`, `PLAT_ARM_MAX_BL2_SIZE` and
`PLAT_ARM_MAX_BL31_SIZE` have been moved to the file board_arm_def.h.
This way, ARM platforms no longer have to set their own values if
`ARM_BOARD_OPTIMISE_MEM=0` and they can specify optimized values
otherwise. The common sizes have been set to the highest values used
for any of the current build configurations.
This is needed because in some build configurations some images are
running out of space. This way there is a common set of values known
to work for all of them and it can be optimized for each particular
platform if …
> ARM platforms: Define common image sizes

- drivers/arm/gic/v3/gicv3_private.h
- include/drivers/arm/gicv3.h
This patch fixes the offset of GICD_IROUTER register defined in gicv3.h.
Although the GICv3 documention mentions that the offset for this register
is 0x6100-0x7FD8, the offset calculation for an interrupt id `n` is :
0x6000 + 8n, where n >= 32
This requires the offset for GICD_IROUTER to be defined as 0x6000.
Fixes ARM-software/tf-issues#410
Change-Id: If9e91e30d946afe7f1f60fea4f065c7567093fa8
> GICv3: Fix the GICD_IROUTER offset

- common/runtime_svc.c
This patch improves the debug assertion for runtime svc number
- Remove useless comparison ensuring that the number of descriptors
is a positive number. The variable is an unsigned integer so can't
be negative.
- Check that the end address of the descriptors is sane relative
to the start address.
Change-Id: Iea7be6b34e33b8b1cbd394eb923cc834ea964831
> Improve debug assertion for runtime svc number

- drivers/emmc/emmc.c
- include/drivers/emmc.h
Support CMD23. When CMD23 is used, CMD12 could be avoided.
Two scenarios:
1. CMD17 for single block, CMD18 + CMD12 for multiple blocks.
2. CMD23 + CMD18 for both single block and multiple blocks.
The emmc_init() should initialize whether CMD23 is supported
or not.
Fix the issue in ARM-software/tf-issues#412
It's the updated version of https://github.com/ARM-software/arm-trusted-firmware/pull/675
> emmc: support CMD23

- drivers/arm/gic/v3/gicv3_main.c
As per the GICv3 specification, to power down a processor using GICv3
and allow automatic power-on if an interrupt must be sent to a processor,
software must set Enable to zero for all interrupt groups(by writing to
GICC_CTLR or ICC_IGRPEN{0,1}_EL1/3 as appropriate.
Also, NonSecure EL1 software may not be aware of the CPU power state
details and fail to choose right states that require quiescing the CPU
interface. So it's preferred that the PSCI implementation handles it as
it is fully aware of the CPU power states.
This patch adds disabling of Group1 NonSecure interrupts during processor
power down along with Group0 and Group1 Secure interrupts so that all the
interrupt groups are handled at once as per specification.
Change-Id: Ib564d773c9c4c41f2ca9471451c030e3de75e641
> gicv3: disable Group1 NonSecure interrupts during core powerdown

- docs/user-guide.md
This patch updates the User Guide to move up from version 7.2 to 7.6
of the Base FVP.
> Move up to Base FVP version 7.6

- plat/arm/board/fvp/fvp_err.c
- plat/arm/board/juno/juno_err.c
- plat/common/aarch64/platform_helpers.S
This patch adds a WFI instruction in the default implementations of
plat_error_handler() and plat_panic_handler(). This potentially reduces
power consumption by allowing the hardware to enter a low-power state.
The same change has been made to the FVP and Juno platform ports.
> Add WFI in platform's unexpected error handlers

- tools/fiptool/fiptool.c
It should be 'fiptool' instead of 'fiptfool'.
Change-Id: I84ce1b6aaae5b8b33e5781bfe4f9e9cf462edb03
> fiptool: Fix typo in create and update usage functions

- include/lib/aarch32/arch.h
- include/lib/aarch64/arch.h
- include/lib/xlat_tables.h
- lib/xlat_tables/aarch32/xlat_tables.c
- lib/xlat_tables/aarch64/xlat_tables.c
- lib/xlat_tables/xlat_tables_common.c
- lib/xlat_tables/xlat_tables_private.h
Instead of hardcoding a level 1 table as the base translation level
table, let the code decide which level is the most appropriate given
the virtual address space size.
As the table granularity is 4 KB, this allows the code to select
level 0, 1 or 2 as base level for AArch64. This way, instead of
limiting the virtual address space width to 39-31 bits, widths of
48-25 bit can be used.
For AArch32, this change allows the code to select level 1 or 2
as the base translation level table and use virtual address space
width of 32-25 bits.
Also removed some unused definitions related to translation tables.
Fixes ARM-software/tf-issues#362
Change-Id: Ie3bb5d6d1a4730a26700b09827c79f37ca3cdb65
> Automatically select initial xlation lookup level

- bl1/aarch64/bl1_exceptions.S
- common/aarch64/early_exceptions.S
This patch removes the tight loop that calls `plat_report_exception`
in unhandled exceptions in AArch64 state.
The new behaviour is to call the `plat_report_exception` only
once followed by call to `plat_panic_handler`.
This allows platforms to take platform-specific action when
there is an unhandled exception, instead of always spinning
in a tight loop.
Note: This is a subtle break in behaviour for platforms that
expect `plat_report_exception` to be continuously executed
when there is an unhandled exception.
Change-Id: Ie2453804b9b7caf9b010ee73e1a90eeb8384e4e8
> Remove looping around `plat_report_exception`

- common/bl_common.c
- lib/el3_runtime/aarch32/context_mgmt.c
This patch fixes a build error and CPU context initialization bug in the AArch32
port of context management library.
> Fixes for AArch32 port of TF

- plat/rockchip/common/plat_pm.c
- plat/rockchip/rk3399/drivers/pmu/pmu.c
As rk3399 reported the d8/octane scores drop 10% with cpu idle.
The root cause is thc cpu cluster enter the slow mode.
We don't need switch the clock to 24MHz if cpu cluster enter the
retention mode. In order to improve performance, it just needs for
cluster enter powering off mode.
Also, we shouldn't do anything for hlvl if the system is off.
Change-Id: I2a02962a01343abd0cba47ed63192c1cdf88b119
> rockchip: fix the scu idle for rk3399

- lib/psci/psci_setup.c
The `psci_plat_pm_ops` global pointer is initialized during cold boot by the
primary CPU and will be accessed by the secondary CPUs before enabling data
cache during warm boot. This patch adds a missing data cache flush of
`psci_plat_psci_ops` after initialization during psci_setup() so that
secondaries can see the updated `psci_plat_psci_ops` pointer.
Fixes ARM-software/tf-issues#424
Change-Id: Id4554800b5646302b944115a33be69507d53cedb
> Flush `psci_plat_pm_ops` after initialization

- plat/rockchip/common/include/plat_params.h
- plat/rockchip/common/include/plat_private.h
- plat/rockchip/common/params_setup.c
- plat/rockchip/rk3399/drivers/gpio/rk3399_gpio.c
- plat/rockchip/rk3399/drivers/pmu/pmu.c
- plat/rockchip/rk3399/drivers/pmu/pmu.h
Set APIO powered pins (APIO1 - APIO5) as no pull inputs in S3
* In S3 we unpower the APIO pads because the board was designed to work with PD_ALIVE turned off.
> Set apio for rk3399

- plat/rockchip/rk3399/drivers/pmu/pmu.c
We make sure the resuming of gic need to be enabled.
Otherwise, The resume will hit the below panic.
...
[   24.230541] CPU0: update max cpu_capacity 451
[   24.236029] CPU5: update max cpu_capacity 1024
[   24.236046] CPU4: shutdown
[   24.243205] psci: CPU4 killed.
[   24.258730] CPU5: shutdown
[   24.261472] psci: CPU5 killed.
[   24.270417] GIC: unable to set SRE (disabled at EL2), panic ahead
[   24.270417] cat[7801]: undefined instruction: pc=ffffffc0004e65d0
[   24.270417] Code: b0003940 91274400 97f871af d2801e00 (d5184600)
[   24.270417] Internal error: Oops - undefined instruction: 0 [#1] PREEMPT
Change-Id: Ie9542c8d5768ba0accfa073453da8bfe06d4f921
> rockchip: fixes the gic panic for rk3399 resume

- include/plat/arm/common/plat_arm.h
This patch adds a couple of missing forward declarations in plat_arm.h
so that all types it references are known within this header file,
without relying on previous header inclusions. This concerns the
meminfo and bl31_params structures, which are defined in bl_common.h.
Other external types referenced from plat_arm.h (e.g. mmap_region_t)
get declared through header files included by arm_plat.h so they
don't need forward declarations.
> Add some missing forward declarations in plat_arm.h

- include/lib/xlat_tables.h
Commit e8719552a24 removed some definitions related to translation
tables from the xlat_tables.h header file, based on the assumption
that they weren't used by any platform. These are actually used by
some partners so this patch restores them.
> Restore some defines in xlat_tables.h

- docs/user-guide.md
- tools/fiptool/Makefile
- tools/fiptool/fiptool.c
This feature allows one to quickly verify that the expected
image is contained in the FIP without extracting the image and
running sha256sum(1) on it.
The sha256 digest is only shown when the verbose flag is used.
This change requires libssl-dev to be installed in order to build
Trusted Firmware. Previously, libssl-dev was optionally needed only
to support Trusted Board Boot configurations.
Fixes ARM-Software/tf-issues#124
Change-Id: Ifb1408d17f483d482bb270a589ee74add25ec5a6
> fiptool: Add support for printing the sha256 digest with info command

- include/lib/pmf/pmf_asm_macros.S
The macro calculates an absolute address rather than an offset so
rename it to avoid confusion.
Change-Id: I351f73dfd809fd28c0c30d38928caf5c5cd1af04
> Rename `pmf_calc_timestamp_offset` to `pmf_calc_timestamp_addr`

- tools/fiptool/fiptool.c
Instead of always calling the top level usage function when an
error is detected, call the command-specific usage function.
For example running `fiptool create` will produce the same output
as `fiptool help create`.  This is more convenient for the user
when they make a mistake.
Change-Id: I60178ab89d47adf93cdfe6d8b5d5f778a5ea3bca
> fiptool: Invoke command specific usage function

- bl1/aarch32/bl1_context_mgmt.c
The Virtualization field in the ID_PFR1 register has only 2
valid values (0 or 1) but it was incorrectly checked against
unrelated value tied to the SPSR register instead.
This patch fixes the detection of virtualization support by
using the valid values in BL1 context management code.
Change-Id: If12592e343770e1da90f0f5fecf0a3376047ac29
> AArch32: Fix detection of virtualization support

- docs/user-guide.md
This patch updates the User Guide to recommend the latest version
of some of the software dependencies of ARM Trusted Firmware.
- Upgrade Linaro release:     16.02 -> 16.06
- Upgrade FVPs
- Foundation v8 FVP:       9.5 -> 10.1
- Base FVPs:               7.6 -> 7.7
- Upgrade mbed TLS library:   2.2.0 -> 2.2.1
Note that the latest release of mbed TLS as of today is 2.3.0 but it has
compilations issues with the set of library configuration options that
Trusted Firmware uses. 2.2.1 is the next most recent release known to
build with TF.
This patch also fixes the markdown formatting of a link in the
User Guide.
> Upgrade Linaro release, FVPs and mbed TLS versions

- contributing.md
- dco.txt
It is no longer necessary for contributors to send a CLA to ARM
before making contributions. Contributors must instead add a
"Signed-off-by:" line to each commit, which certifies that the
contribution is made under the Developer Certificate of Origin
(DCO).
Update contributing.md to reflect this new policy and add a copy of
the DCO to the repository.
Change-Id: I7ca98bffc3bf57e8bdd51d763c24f13e415a328b
> Drop requirement for CLA in contribution.md

- docs/firmware-design.md
- docs/psci-lib-integration-guide.md
This patch adds the PSCI library integration guide for AArch32 ARMv8-A
systems `psci-lib-integration-guide.md` to the documentation. The
patch also adds appropriate reference to the new document in
the `firmware-design.md` document.
Change-Id: I2d5b5c6b612452371713399702e318e3c73a8ee0
> Docs: Add the PSCI library integration guide

- include/common/aarch32/el3_common_macros.S
- lib/aarch32/misc_helpers.S
At present the `el3_entrypoint_common` macro uses `memcpy`
function defined in lib/stdlib/mem.c file, to copy data
from ROM to RAM for BL1. Depending on the compiler being
used the stack could potentially be used, in `memcpy`,
for storing the local variables. Since the stack is
initialized much later in `el3_entrypoint_common` it
may result in unknown behaviour.
This patch adds `memcpy4` function definition in assembly so
that it can be used before the stack is initialized and it
also replaces `memcpy` by `memcpy4` in `el3_entrypoint_common`
macro, to copy data from ROM to RAM for BL1.
Change-Id: I3357a0e8095f05f71bbbf0b185585d9499bfd5e0
> AArch32: Add `memcpy4` function in assembly

- docs/porting-guide.md
Fix one of the two titles that ended up being the same, although both
describe different things.
Change-Id: I66ecf369643709898ee4c014659d8f85c0480643
> Docs: Rename duplicate title in porting guide

- docs/user-guide.md
The user guide incorrectly claimed that it is possible to load a
bootwrapped kernel over JTAG on Juno in the same manner as an EL3
payload. In the EL3 payload boot flow, some of the platform
initialisations in BL2 are modified. In particular, the TZC settings
are modified to allow unrestricted access to DRAM. This in turn allows
the debugger to access the DRAM and therefore to load the image there.
In the BL33-preloaded boot flow though, BL2 uses the default TZC
programming, which prevent access to most of the DRAM from secure state.
When execution reaches the SPIN_ON_BL1_EXIT loop, the MMU is disabled
and thus DS-5 presumably issues secure access transactions while trying
to load the image, which fails.
One way around it is to stop execution at the end of BL2 instead. At
this point, the …
> Fix documentation of bootwrapper boot on juno

- docs/user-guide.md
Updated the user guide to clarify building FIP for AArch32.
The instructions were previously specific to building a FIP for AArch64.
Change-Id: I7bd1a6b8e810cfda411f707e04f479006817858e
> Release v1.3: Minor updates to user guide

- plat/rockchip/rk3399/drivers/soc/soc.c
- plat/rockchip/rk3399/drivers/soc/soc.h
As the new RK3399TRM v1.1, there are some wrong set for CRU_CLKSEL_CON
register.
As the CRU_CLKSEL_CON96～107 high 16-bit isn't write mask and the
CRU_CLKSEL_CON offset is 0x100,not 0x80.
Change-Id: Ie127e9de74b87100af9a0150aad43e89e4972529
> rockchip: fixes the clock select and divide register for rk3399

- Makefile
- bl31/aarch64/bl31_entrypoint.S
- bl31/aarch64/runtime_exceptions.S
- bl31/bl31_main.c
- include/lib/el3_runtime/cpu_data.h
- include/lib/pmf/pmf.h
- include/lib/pmf/pmf_helpers.h
- include/lib/runtime_instr.h
- include/plat/arm/common/arm_sip_svc.h
- lib/psci/psci_main.c
- lib/psci/psci_off.c
- lib/psci/psci_suspend.c
- plat/arm/common/arm_common.mk
- plat/arm/common/arm_sip_svc.c
- services/std_svc/std_svc_setup.c
These patches add instrumentation support for PSCI using the Performance Measurement Framework (PMF).  To enable this feature, ENABLE_RUNTIME_INSTRUMENTATION needs to be set to 1 (off by default).
> Add instrumentation support for PSCI

- include/lib/stdlib/sys/uuid.h
This include provides nothing useful for TF and prevents building
the fiptool using musl libc[0].
[0] https://www.musl-libc.org/
Change-Id: Ied35e16b9ea2b40213433f2a8185dddc59077884
> Remove non-standard <sys/cdefs.h> include from uuid.h

- Makefile
Insert a cosmetic space before "(FIP)" in `make help` output.
Signed-off-by: Andreas Färber <afaerber@suse.de>
> Makefile: Add missing space in help output

- include/lib/aarch32/arch.h
- include/lib/aarch64/arch.h
- lib/el3_runtime/aarch32/context_mgmt.c
- lib/el3_runtime/aarch64/context_mgmt.c
The values of CP15BEN, nTWI & nTWE bits in SCTLR_EL1 are architecturally
unknown if EL3 is AARCH64 whereas they reset to 1 if EL3 is AArch32. This
might be a compatibility break for legacy AArch32 normal world software if
these bits are not set to 1 when EL3 is AArch64. This patch enables the
CP15BEN, nTWI and nTWE bits in the SCTLR_EL1 if the lower non-secure EL is
AArch32. This unifies the SCTLR settings for lower non-secure EL in AArch32
mode for both AArch64 and AArch32 builds of Trusted Firmware.
Fixes ARM-software/tf-issues#428
Change-Id: I3152d1580e4869c0ea745c5bd9da765f9c254947
> Unify SCTLR initialization for AArch32 normal world

- plat/rockchip/common/aarch64/plat_helpers.S
The default value of L2CTLR_DATA_RAM_LATENCY is 2, depends to
the test result on rk3399, the A72 will need lower voltage for
high frequency if it's set to be 5, and almost no effect on performance.
Change-Id: I99a6a43edcc0c58f7775c10f4b85669dc3eff66d
> rockchip: fix A72 L2CTLR_DATA_RAM_LATENCY to 5

- bl31/bl31.ld.S
- plat/rockchip/common/aarch64/platform_common.c
- plat/rockchip/common/bl31_plat_setup.c
- plat/rockchip/common/include/plat_private.h
- plat/rockchip/common/plat_pm.c
- plat/rockchip/common/pmusram/pmu_sram.h
- plat/rockchip/rk3399/drivers/m0/Makefile
- plat/rockchip/rk3399/drivers/m0/include/rk3399_mcu.h
- plat/rockchip/rk3399/drivers/m0/src/main.c
- plat/rockchip/rk3399/drivers/m0/src/rk3399m0.ld
- plat/rockchip/rk3399/drivers/m0/src/startup.c
- plat/rockchip/rk3399/drivers/pmu/pmu.c
- plat/rockchip/rk3399/drivers/pmu/pmu_fw.c
- plat/rockchip/rk3399/drivers/pmu/rk3399m0.h
- plat/rockchip/rk3399/drivers/soc/soc.c
- plat/rockchip/rk3399/drivers/soc/soc.h
- plat/rockchip/rk3399/include/plat.ld.S
- plat/rockchip/rk3399/platform.mk
Add the common extra.ld.S and customized rk3399.ld.S to extend
to more features for different platforms.
For example, we can add SRAM section and specific address to
load there if we need it, and the common bl31.ld.S not need to
be modified.
Therefore, we can remove the unused codes which copying explicitly
from the function pmusram_prepare(). It looks like more clear.
Change-Id: Ibffa2da5e8e3d1d2fca80085ebb296ceb967fce8
(cherry-picked pick from Xing Zheng <zhengxing@rock-chips.com> works
on https://chromium-review.googlesource.com/#/c/389114/)
> rockchip: optimize the link mechanism for SRAM code

- tools/fiptool/fiptool.c
- tools/fiptool/fiptool.h
- tools/fiptool/tbbr_config.c
- tools/fiptool/tbbr_config.h
The `toc_entry` and `image` data structures had a cyclic
relationship.  This patch removes the explicit dependencies and introduces
functions to link them via the UUID.
This change highlights the intent of the code better and makes it more
flexible for future enhancements.
Change-Id: I0c3dd7bfda2a631a3827c8ba4831849c500affe9
> fiptool: Link `toc_entry` and `image` structures via UUID

- .checkpatch.conf
This patch updates the configuration file for the checkpatch.pl
script to check for the presence of a 'Signed-off-by' line in the
commit message. This is now required by TF contribution process.
> Mandate 'Signed-off-by' line in commit messages

- tools/fiptool/fiptool.c
Fix the following bug:
$ tools/fiptool/fiptool -v
Segmentation fault (core dumped)
> fiptool: fix Segmentation fault when only --verbose option is given

- Makefile
Checkpatch is a script developed to verify the style of Linux kernel
patches. As Kernel developers use emails to send patches for review,
checkpatch is prepared for that specific format. This change adapts
the Makefile to use said format.
As a result, indentation in the commit message has been removed, thus
fixing the warnings about Signed-off-by lines being preceded by
whitespace.
Fixes ARM-software/tf-issues#432
Change-Id: I00cb86365fe15f7e2c3a99a306c8eb51cf02fe86
> Fix format of patches passed to checkpatch

- docs/user-guide.md
- services/std_svc/std_svc_setup.c
The first patch documents the ENABLE_RUNTIME_INSTRUMENTATION option in the user guide.  The second patch fixes a cache maintenance issue in the implementation of runtime instrumentation.  See the individual patches for more details.
> BL31 runtime instrumentation fixes and documentation update

- docs/porting-guide.md
This patch fixes the type of the return value of bl1_plat_mem_check()
in the porting guide. It also specifies the expected return value.
> Porting guide: Improve bl1_plat_mem_check() doc

- plat/rockchip/rk3399/drivers/pmu/pmu.c
- plat/rockchip/rk3399/drivers/soc/soc.c
- plat/rockchip/rk3399/drivers/soc/soc.h
Update the below patches for rk3399.
0607716 rockchip: remove no needed code for rk3399
a14e091 rockchip: disable watchdog during suspend
> rk3399: fixes and updates for s2r

- readme.md
The platform testing information in the readme currently states which
Linaro release has been tested on Juno platform.
This patch adds the same information for the AArch64/32 FVPs platforms.
Change-Id: Ifa89843ee1744e5030367197648b7a2f4c44cc24
> readme.md: Add tested Linaro release information for FVPs

- docs/firmware-design.md
Fix a link broken by a missing space that turned
it into a link to an non-existent anchor.
Change-Id: Ie863e963db28afa3a28b69d3f63bd7638bdf5af9
> firmware-design.md: Fix broken link

- bl31/aarch64/runtime_exceptions.S
* Move comments on unhandled exceptions at the right place.
* Reformat the existing comments to highlight the start of
each block of 4 entries in the exception table to ease
navigation (lines of dash reserved for head comments).
* Reflow comments to 80 columns.
Change-Id: I5ab88a93d0628af8e151852cb5b597eb34437677
> Cosmetic change to exception table

- docs/spd/trusty-dispatcher.md
- services/spd/trusty/sm_err.h
- services/spd/trusty/smcall.h
- services/spd/trusty/trusty.c
- services/spd/trusty/trusty.mk
- services/spd/trusty/trusty_helpers.S
This patch adds the secure payload dispatcher for interacting
with Google's Trusty TEE. Documentation for Trusty can be found
at https://source.android.com/security/trusty
Original authors:
-----------------
* Arve Hjønnevåg <arve@android.com>
* Michael Ryleev <gmar@google.com>
> spd: dispatcher for interacting with the Trusty TEE

- docs/user-guide.md
- plat/arm/common/arm_common.mk
Add dependency information in the user guide for ARM_RECOM_STATE_ID_ENC
that needs to be set when using PSCI_EXTENDED_STATE_ID on ARM
platforms. Also clarify the build error message.
Change-Id: Id125a0299b179f5f222bca4e2503204bf89a3c59
> Clarify dependency for PSCI_EXTENDED_STATE_ID

- include/common/asm_macros_common.S
This allows the debugger to print the callstack when there is an
assembly function in the callstack.
It will work as long as the CFA pointer (frame pointer) location is not
modified (i.e. x29 is not touched in AArch64 state). It is the case in
almost all assembly functions, so this patch improves the average
debugging experience. Call stacks from the debugger should still be
interpreted with care. In more complex functions, one could use .cfi*
directives to inform the debugger about the new location of the CFA
pointer.
Change-Id: I9dabfbc033b45e8528e67f4823c17de7bf02fa24
> Add CFI debug frame information for ASM functions

- plat/rockchip/rk3399/drivers/pmu/plat_pmu_macros.S
Commit b91d935feebdf2c3edef19949023645b6cb34b20
("Add CFI debug frame information for ASM functions") modifies the
assembly macros 'func' and 'endfunc' to include CFI debug frame
information.
The rockchip platform uses a custom version of the 'func' macro with the
common 'endfunc' macro. The custom macro wasn't updated in
b91d935feebdf2c3edef19949023645b6cb34b20 resulting in the following
build error:
plat/rockchip/rk3399/drivers/pmu/plat_pmu_macros.S: Assembler messages:
plat/rockchip/rk3399/drivers/pmu/plat_pmu_macros.S:155: Error: .cfi_endproc without corresponding .cfi_startproc
Makefile:532: recipe for target 'build/rk3399/release/bl31/plat_helpers.o' failed
make: *** [build/rk3399/release/bl31/plat_helpers.o] Error 1
Fixing this by updating the sram_func macro in the rk3399 port. …
> rk3399: Add CFI debug information to SRAM functions

- services/spd/trusty/trusty.c
Add a debug assertion in the initialization function of Trusty's SPD
to check for the presence of Trusty. If Trusty is absent then the SPD's
setup function already detects it and returns an error code so the init
function will never been called. Therefore, a debug assertion is enough
to catch this improbable error case.
> Check Trusty is present during the SPD's initialization

- include/drivers/emmc.h
C99 restricts bitfields type is signed and unsigned integer or _Bool.
See section 6.7.2.1 Structure and union specifiers.
"A bit-field shall have a type that is a qualified or unqualified version
of _Bool, signed int, unsigned int, or some other implementation-defined type."
Since the compiler packs bitfields anyways, actual data layout in the structure is unaffected.
> For C99 compliance, changed the unsigned char/short bitfield to unsigned int bitfields

- include/plat/arm/common/plat_arm.h
- plat/arm/board/fvp/fvp_pm.c
- plat/arm/board/juno/juno_pm.c
- plat/arm/common/arm_pm.c
- plat/arm/css/common/css_common.mk
- plat/arm/css/common/css_pm.c
- plat/arm/css/common/css_scp_bootloader.c
- plat/arm/css/drivers/scp/css_pm_scpi.c
- plat/arm/css/drivers/scp/css_scp.h
- plat/arm/css/drivers/scpi/css_mhu.c
- plat/arm/css/drivers/scpi/css_mhu.h
- plat/arm/css/drivers/scpi/css_scpi.c
- plat/arm/css/drivers/scpi/css_scpi.h
This patch introduces an additional layer of abstraction between
CSS power management hooks and the SCPI driver. A new set of APIs
are introduced in order to abstract out power management operations
from underlying communication mechanism with the SCP.
> Introduce SCP power management abstraction

- drivers/arm/pl011/aarch32/pl011_console.S
- include/lib/aarch32/smcc_macros.S
- plat/common/aarch32/platform_helpers.S
This patch makes following miscellaneous fixes:
* pl011_console.S: Fixed the bit mask used to check if the
transmit FIFO is full or empty.
* smcc_macros.S: Added `_fsxc` suffix while updating the SPSR.
By default the assembler assumes `_fc` suffix which does not
update all the fields in SPSR. By adding `_fsxc` suffix all
the fields gets updated.
* platform_helpers.S: Removed the weak definition for
`plat_my_core_pos()` as this is a mandatory function which
needs to be defined by all platforms.
Change-Id: I8302292533c943686fff8d7c749a07132c052a3b
Signed-off-by: Yatharth Kochar <yatharth.kochar@arm.com>
> AArch32: Miscellaneous fixes in the AArch32 code

- bl1/aarch64/bl1_exceptions.S
- bl2/aarch32/bl2_entrypoint.S
- bl2/aarch64/bl2_entrypoint.S
- bl2u/aarch64/bl2u_entrypoint.S
- bl31/aarch64/crash_reporting.S
- bl31/aarch64/runtime_exceptions.S
- bl32/tsp/aarch64/tsp_entrypoint.S
- bl32/tsp/aarch64/tsp_exceptions.S
- common/aarch32/debug.S
- common/aarch64/debug.S
- common/aarch64/early_exceptions.S
- include/common/aarch32/asm_macros.S
- include/common/aarch32/el3_common_macros.S
- include/common/aarch64/asm_macros.S
- lib/psci/aarch32/psci_helpers.S
- lib/psci/aarch64/psci_helpers.S
- plat/arm/board/fvp/aarch64/fvp_helpers.S
- plat/arm/board/juno/aarch64/juno_helpers.S
- plat/xilinx/zynqmp/aarch64/zynqmp_helpers.S
There are many instances in ARM Trusted Firmware where control is
transferred to functions from which return isn't expected. Such jumps
are made using 'bl' instruction to provide the callee with the location
from which it was jumped to. Additionally, debuggers infer the caller by
examining where 'lr' register points to. If a 'bl' of the nature
described above falls at the end of an assembly function, 'lr' will be
left pointing to a location outside of the function range. This misleads
the debugger back trace.
This patch defines a 'no_ret' macro to be used when jumping to functions
from which return isn't expected. The macro ensures to use 'bl'
instruction for the jump, and also, for debug builds, places a 'nop'
instruction immediately thereafter (unless instructed otherwise) so as
to …
> Define and use no_ret macro where no return is expected

- bl32/sp_min/aarch32/entrypoint.S
- include/lib/aarch32/smcc_helpers.h
- include/lib/aarch32/smcc_macros.S
- lib/cpus/aarch32/cortex_a32.S
- lib/cpus/aarch32/cpu_helpers.S
- lib/el3_runtime/aarch32/cpu_data.S
- lib/psci/aarch32/psci_helpers.S
The AArch32 Procedure call Standard mandates that the stack must be aligned
to 8 byte boundary at external interfaces. This patch does the required
changes.
This problem was detected when a crash was encountered in
`psci_print_power_domain_map()` while printing 64 bit values. Aligning
the stack to 8 byte boundary resolved the problem.
Fixes ARM-Software/tf-issues#437
Change-Id: I517bd8203601bb88e9311bd36d477fb7b3efb292
> AArch32: Fix the stack alignment issue

- lib/stdlib/mem.c
There is no guarantee on the signedness of char.  It can be either
signed or unsigned.  On ARM it is unsigned and hence this memcmp()
implementation works as intended.
On other machines, char can be signed (x86 for example).  In that case
(and assuming a 2's complement implementation), interpreting a
bit-pattern of 0xFF as signed char can yield -1.  If *s1 is 0 and *s2
is 255 then the difference *s1 - *s2 should be negative.  The C
integer promotion rules guarantee that the unsigned chars will be
converted to int before the operation takes place.  The current
implementation will return a positive value (0 - (-1)) instead, which
is wrong.
Fix it by changing the signedness to unsigned to avoid surprises for
anyone using this code on non-ARM systems.
Change-Id: …
> stdlib: Fix signedness issue in memcmp()

- lib/aarch64/misc_helpers.S
Unsigned conditions should be used instead of signed ones when comparing
addresses or sizes in assembly.
Change-Id: Id3bd9ccaf58c37037761af35ac600907c4bb0580
> Fix integer comparison in memcpy16

- fdts/fvp-foundation-gicv2-psci.dts
- fdts/fvp-foundation-motherboard.dtsi
- include/drivers/io/io_fip.h
- make_helpers/build_env.mk
- plat/rockchip/common/drivers/pmu/pmu_com.h
- plat/rockchip/common/include/rockchip_sip_svc.h
- plat/rockchip/common/pmusram/pmu_sram.c
- plat/rockchip/common/pmusram/pmu_sram.h
- plat/rockchip/common/pmusram/pmu_sram_cpus_on.S
- plat/rockchip/common/rockchip_sip_svc.c
- plat/rockchip/rk3368/drivers/ddr/ddr_rk3368.c
- plat/rockchip/rk3368/drivers/ddr/ddr_rk3368.h
- plat/rockchip/rk3368/drivers/pmu/plat_pmu_macros.S
- plat/rockchip/rk3368/drivers/pmu/pmu.c
- plat/rockchip/rk3368/drivers/pmu/pmu.h
- plat/rockchip/rk3368/drivers/soc/soc.c
- plat/rockchip/rk3368/drivers/soc/soc.h
- plat/rockchip/rk3368/include/plat_sip_calls.h
- plat/rockchip/rk3368/plat_sip_calls.c
- plat/rockchip/rk3399/drivers/pmu/plat_pmu_macros.S
- plat/rockchip/rk3399/include/plat_sip_calls.h
- plat/rockchip/rk3399/plat_sip_calls.c
- plat/xilinx/zynqmp/platform.mk
- plat/xilinx/zynqmp/tsp/tsp-zynqmp.mk
Some files have incorrect copyright notices, this patch fixes all
files with deviations from the standard notice.
Change-Id: I66b73e78a50a235acb55f1e2ec2052a42c0570d2
> Fix incorrect copyright notices

- docs/user-guide.md
Foundation Model release 10.2 has been made available and Trusted
Firmware has been tested against that it as part of its CI system.
This patch updates the user guide documentation to reflect the version
of Foundation Model that Trusted Firmware has been tested against.
Change-Id: I8571e1027b24892b41d04b93b24245a371ca2cae
> Update Foundation Model version

- Makefile
- bl1/bl1_fwu.c
- bl1/tbbr/tbbr_img_desc.c
- include/plat/arm/css/common/css_def.h
- plat/arm/board/juno/include/platform_def.h
- plat/arm/common/arm_common.mk
This patch enables TRUSTED_BOARD_BOOT (Authentication and FWU)
support, for AArch64, when LOAD_IMAGE_V2 is enabled.
This patch also enables LOAD_IMAGE_V2 for ARM platforms.
Change-Id: I294a2eebce7a30b6784c80c9d4ac7752808ee3ad
Signed-off-by: Yatharth Kochar <yatharth.kochar@arm.com>
> Enable TRUSTED_BOARD_BOOT support for LOAD_IMAGE_V2=1

- docs/porting-guide.md
- drivers/auth/auth_mod.c
- include/plat/common/platform.h
- plat/arm/common/arm_common.mk
- plat/common/tbbr/plat_tbbr.c
The previous code required that a certificate be signed with the ROT
key before the platform's NV counter could be updated with the value
in the certificate.  This implies that the Non-Trusted NV counter was
not being updated for Non-Trusted content certificates, as they cannot
be signed with the ROT key in the TBBR CoT scheme.
The code is reworked to only allow updating the platform's Trusted NV
counter when a certificate protected by the Trusted NV counter is
signed with the ROT key.
Content certificates protected by the Non-Trusted NV counter are
allowed to update the platform's Non-Trusted NV counter, assuming
that the certificate value is higher than the platform's value.
A new optional platform API has been introduced, named
plat_set_nv_ctr2().  Platforms may choose to implement it …
> tbbr: Fix updating of Non-Trusted NV counter

- docs/firmware-design.md
- include/lib/cpus/aarch32/cpu_macros.S
- include/lib/cpus/aarch64/cpu_macros.S
- lib/cpus/aarch32/aem_generic.S
- lib/cpus/aarch32/cortex_a32.S
- lib/cpus/aarch32/cpu_helpers.S
- lib/cpus/aarch64/aem_generic.S
- lib/cpus/aarch64/cortex_a35.S
- lib/cpus/aarch64/cortex_a53.S
- lib/cpus/aarch64/cortex_a57.S
- lib/cpus/aarch64/cortex_a72.S
- lib/cpus/aarch64/cortex_a73.S
- lib/cpus/aarch64/cpu_helpers.S
- lib/cpus/aarch64/denver.S
- lib/psci/aarch32/psci_helpers.S
- lib/psci/aarch64/psci_helpers.S
Various CPU drivers in ARM Trusted Firmware register functions to handle
power-down operations. At present, separate functions are registered to
power down individual cores and clusters.
This scheme operates on the basis of core and cluster, and doesn't cater
for extending the hierarchy for power-down operations. For example,
future CPUs might support multiple threads which might need powering
down individually.
This patch therefore reworks the CPU operations framework to allow for
registering power down handlers on specific level basis. Henceforth:
- Generic code invokes CPU power down operations by the level
required.
- CPU drivers explicitly mention CPU_NO_RESET_FUNC when the CPU has no
reset function.
- CPU drivers register power down handlers as a list: a mandatory
handler for level …
> Add provision to extend CPU operations at more levels

- common/aarch32/debug.S
- include/common/aarch32/assert_macros.S
- plat/arm/common/aarch32/arm_helpers.S
ASM_ASSERT failure and panic messages are suppressed at present. This
patch enables printing the PC location for panic messages, and file name
and line number upon assembly assert failure.
Change-Id: I80cb715988e7ce766f64da1e1d7065a74a096a0c
> AArch32: Print ASM_ASSERT and panic messages

- plat/xilinx/zynqmp/platform.mk
The platform.mk sets build options required for ZynqMP, but users
can still change them from the command line, like:
make PLAT=zynqmp RESET_TO_BL31=0 CROSS_COMPILE=...
Then, the makefile shows an error message in that case:
Using BL31 as the reset vector is only one option supported on ZynqMP.
Please set RESET_TO_BL31 to 1.
If the option is not user-configurable, the makefile can specify
"override" to prevent users from changing it.  We do not need the
error message for the case that never happens.
Likewise, ENABLE_PLAT_COMPAT := 0 and PROGRAMMABLE_RESET_ADDRESS := 1
are mandatory to avoid build error.
Acked-by: Soren Brinkmann <soren.brinkmann@xilinx.com>
> zynqmp: add "override" directive to mandatory options

- include/bl32/tsp/tsp.h
Enforce valid FID input in TSP_STD_FID and TSP_FAST_FID macros.
Also remove an undefined behavior by using unsigned literals.
Change-Id: Id37e908da861980a4eaa3a70b37a729f416ce272
> Fix TSP_STD_FID macro

- bl32/tsp/aarch64/tsp_entrypoint.S
- bl32/tsp/tsp_main.c
- include/bl32/tsp/tsp.h
- services/spd/tspd/tspd_common.c
- services/spd/tspd/tspd_main.c
- services/spd/tspd/tspd_pm.c
- services/spd/tspd/tspd_private.h
Standard SMC requests that are handled in the secure-world by the Secure
Payload can be preempted by interrupts that must be handled in the
normal world. When the TSP is preempted the secure context is stored and
control is passed to the normal world to handle the non-secure
interrupt. Once completed the preempted secure context is restored. When
restoring the preempted context, the dispatcher assumes that the TSP
preempted context is still stored as the SECURE context by the context
management library.
However, PSCI power management operations causes synchronous entry into
TSP. This overwrites the preempted SECURE context in the context
management library. When restoring back the SECURE context, the Secure
Payload crashes because this context is not the preempted context
anymore.
This …
> Abort preempted TSP STD SMC after PSCI CPU suspend

- plat/rockchip/rk3399/drivers/m0/Makefile
Depending on the compiler used, it might try to link in libc even though
it's not required. Stop it from doing that.
Signed-off-by: Patrick Georgi <pgeorgi@google.com>
> rockchip: Build m0 firmware without standard libraries

- drivers/auth/mbedtls/mbedtls_crypto.mk
This comment block says the default algorithm is ESDSA, while the
code obviously sets the default to RSA:
ifeq (${MBEDTLS_KEY_ALG},)
MBEDTLS_KEY_ALG            :=      rsa
endif
The git log of commit 7d37aa171158 ("TBB: add mbedTLS authentication
related libraries") states available options are:
* 'rsa' (for RSA-2048) (default option)
* 'ecdsa' (for ECDSA-SECP256R1)
So, my best guess is the comment block is wrong.
The mismatch between the code and the comment is confusing. Fix it.
> TBB: fix comment about MBEDTLS_KEY_ALG default

- plat/xilinx/zynqmp/include/platform_def.h
Commit 0029624fe2d4c327ac885d04d5933f82f38e7071 ("Add
PLAT_xxx_ADDR_SPACE_SIZE definition") deprecates 'ADDR_SPACE_SIZE' in
favor of PLAT_(PHY|VIRT)_ADDRESS_SPACE_SIZE. Migrate the zynqmp platform
to use the new interface.
> zynqmp: Migrate to new address space macros

- drivers/ti/uart/aarch64/16550_console.S
- include/drivers/ti/uart/uart_16550.h
tbz check for RDR status is to check for a bit being zero.
Unfortunately, we are using a mask rather than the bit position.
Further as per http://www.ti.com/lit/ds/symlink/pc16550d.pdf (page 17),
LSR register bit 0 is Data ready status (RDR), not bit position 2.
Update the same to match the specification.
Reported-by: Sekhar Nori <nsekhar@ti.com>
Signed-off-by: Nishanth Menon <nm@ti.com>
> uart: 16550: Fix getc

- plat/mediatek/mt8173/drivers/spm/spm_mcdi.c
The actual length of the firmware is 1001 32 bit words.
Signed-off-by: Paul Kocialkowski <contact@paulk.fr>
> mt8173: Correct SPM MCDI firmware length

- lib/cpus/aarch64/cpu_helpers.S
NOTE - this is patch does not address all occurrences of system
includes not being in alphabetical order, just this one case.
Change-Id: I3cd23702d69b1f60a4a9dd7fd4ae27418f15b7a3
> Correct system include order

- drivers/auth/mbedtls/mbedtls_x509_parser.c
- include/lib/aarch32/arch_helpers.h
- include/lib/aarch64/arch_helpers.h
In mbedtls_x509_parser.c there are some static arrays that are filled during the integrity check and then read whenever an authentication parameter is requested. However, they aren't cleared in case of an integrity check failure, which can be problematic from a security point of view. This patch clears these arrays in the case of failure.
Fix some declaration of maintenance functions of data cache.
> Clear static variables in X509 parser on error

- make_helpers/build_macros.mk
Soren reports build fails if -j option is given:
$ make -j16 CROSS_COMPILE=aarch64-linux-gnu-
Building fvp
make: *** No rule to make target 'build/fvp/release/bl1/',
needed by 'build/fvp/release/bl1/bl1.ld'.  Stop.
make: *** Waiting for unfinished jobs....
The cause of the failure is that $(dir ) leaves a trailing / on the
directory names.   It must be ripped off to let Make create the
directory.
Reported-by: Soren Brinkmann <soren.brinkmann@xilinx.com>
> Fix parallel building

- drivers/synopsys/emmc/dw_mmc.c
- include/drivers/synopsys/dw_mmc.h
Support Designware eMMC driver. It's based on both IO block
and eMMC driver.
> drivers: add designware emmc driver

- include/lib/stdlib/string.h
- lib/stdlib/stdlib.mk
- lib/stdlib/strnlen.c
This code has been imported and slightly adapted from FreeBSD:
https://github.com/freebsd/freebsd/blob/6253393ad8df55730481bf2aafd76bdd6182e2f5/lib/libc/string/strnlen.c
> Add strnlen() to local C library

- include/bl32/payloads/tlk.h
- include/lib/smcc.h
- include/lib/utils.h
- include/plat/arm/board/common/board_css_def.h
- include/plat/arm/common/arm_def.h
- include/plat/arm/soc/common/soc_css_def.h
- include/plat/common/common_def.h
- plat/arm/board/fvp/include/platform_def.h
- services/spd/trusty/smcall.h
With GCC 6.2 compiler, more C undefined behaviour is being flagged as
warnings, which result in build errors in ARM TF build.
The specific issue that this patch resolves is the use of (1 << 31),
which is predominantly used in case statements, where 1 is represented
as a signed int. When shifted to msb the behaviour is undefined.
The resolution is to specify 1 as an unsigned int using a convenience
macro ULL(). A duplicate macro MAKE_ULL() is replaced.
Fixes ARM-software/tf-issues#438
Change-Id: I08e3053bbcf4c022ee2be33a75bd0056da4073e1
> Resolve build errors flagged by GCC 6.2

- docs/user-guide.md
The current user guide mentions that Foundation model doesn't support
debugger interface. Clarify that all FVPs support --cadi-server option
such that a CADI-compliant debugger can connect to and control model
execution.
Also fix broken URL to FVP home page.
Change-Id: Ia14d618a4e0abb4b228eb1616040f9b51fb3f6f9
> user-guide.md: Fix FVP references

- Makefile
Disable the automatic substitution of functions with builtins. The
existing -ffreestanding option should already do this but explicitly
adding -fno-builtin reduces the risk of compiler variation. With this
option, GCC is not supposed to be able to make assumptions on what the
function does, which could otherwise lead to security-sensitive code
removal.
This can lead to potentially less efficient code but improves
predictability of what code is actually compiled into the binary.
Change-Id: I06ad151c61318bd1b00d84976f051d2d94314acc
> Add -fno-builtin to CFLAGS

- .gitignore
GNU GLOBAL (https://www.gnu.org/software/global/) is source code
tagging system.  It creates 4 tag files (GTAGS, GRTAGS, GSYMS and
GPATH) for the symbol cross-reference.  Ignore them.
> gitignore: ignore GNU GLOBAL tag files

- docs/plat/xilinx-zynqmp.md
RESET_TO_BL31=1 is specified by plat/xilinx/zynqmp/platform.mk with
"override" directive.  So, RESET_TO_BL31=1 is guaranteed without any
operation on users' side.
> zynqmp: remove RESET_TO_BL31=1 from build instruction

- docs/user-guide.md
AEMv8-A Model release v8.2 has been made available and Trusted Firmware
has been tested against these versions as part of its CI system. This
patch updates the user guide documentation to reflect the version of AEM
and Cortex Models that Trusted Firmware has been tested against.
Also, the Linaro Release Notes link was broken and this patch updates the
link.
Change-Id: I88729cef909a69fff629036f480fd6168ad7dc9a
> Update AEM and Cortex Models versions

- Makefile
- docs/porting-guide.md
- docs/user-guide.md
- include/plat/common/platform.h
- lib/psci/psci_common.c
- lib/psci/psci_main.c
- lib/psci/psci_off.c
- lib/psci/psci_private.h
- lib/psci/psci_stat.c
- lib/psci/psci_suspend.c
- plat/arm/common/arm_common.mk
- plat/common/plat_psci_common.c
The original PSCI stat implementation was coupled with PMF.  This patch introduces 3 optional PSCI interfaces that a platform can implement in order to calculate the PSCI stat residency without necessarily using PMF.
> Decouple PSCI stat residency calculation from PMF

- Makefile
Currently, the BUILD_STRING is just 7-digits git hash.  It is true
we can identify which version is running, but we can not get a quick
idea about how new or old it is.
The command "git describe" provides us a bit more useful information
in the format of:
(tag-name)-(number of commits on top the tag)-g(7 digits hash)
I added some options:
--always
Make "git describe" work without any tag in case the upstream
ATF is cloned, but all the tags are locally dropped.
--tags
Use any tag instead of only annotated tags.  In ATF, only some
tags are annotated, actually the last annotated tag is "v0.2",
whereas we are on "v1.3" tag now.  This option is needed to get
something like v1.3-233-gbcc2bf0 instead of v0.2-1713-gbcc2bf0.
--dirty
The mark "-dirty" is appended if the source tree is locally …
> Makefile: use git describe for BUILD_STRING

- docs/user-guide.md
This Linaro release updates both the binaries and the toolchain:
Linaro binaries upgraded 16.06 --> 16.12
AArch64 compiler upgraded 15.05 (gcc 4.9) --> 5.3-2015.05 (gcc 5.3)
AArch32 compiler upgraded 15.05 (gcc 4.9) --> 5.3-2015.05 (gcc 5.3)
The ARM TF codebase has been tested against these new binaries. This patch
updates the User Guide to reflect that the 16.12 release is now a supported
Linaro Release.
Change-Id: I6247e820f591df7d05df4f622ee45a3abf2c2d72
> Migrate to Linaro Release 16.12

- drivers/io/io_semihosting.c
- tools/cert_create/src/ext.c
cppcheck highlighted variables that were initialized but then later
reassigned.
Change-Id: Ie12742c01fd3bf48b2d6c05a3b448da91d57a2e4
> Fix minor issues found by cppcheck

- Makefile
- docs/firmware-design.md
- docs/user-guide.md
- lib/locks/exclusive/aarch64/spinlock.S
- make_helpers/build_macros.mk
- make_helpers/defaults.mk
The ARMv8v.1 architecture extension has introduced support for far
atomics, which includes compare-and-swap. Compare and Swap instruction
is only available for AArch64.
Introduce build options to choose the architecture versions to target
ARM Trusted Firmware:
- ARM_ARCH_MAJOR: selects the major version of target ARM
Architecture. Default value is 8.
- ARM_ARCH_MINOR: selects the minor version of target ARM
Architecture. Default value is 0.
When:
(ARM_ARCH_MAJOR > 8) || ((ARM_ARCH_MAJOR == 8) && (ARM_ARCH_MINOR >= 1)),
for AArch64, Compare and Swap instruction is used to implement spin
locks. Otherwise, the implementation falls back to using
load-/store-exclusive instructions.
Update user guide, and introduce a section in Firmware Design guide to
summarize support for features introduced …
> Introduce locking primitives using CAS instruction

- drivers/auth/mbedtls/mbedtls_crypto.c
- drivers/auth/mbedtls/mbedtls_x509_parser.c
This reverts commit b621fb503c76f3bdf06ed5ed1d3a995df8da9c50.
Because of the Trusted Firmware design, timing-safe functions are not
needed. Using them may be misleading as it could be interpreted as being
a protection against private data leakage, which isn't the case here.
For each image, the SHA-256 hash is calculated. Some padding is appended
and the result is encrypted with a private key using RSA-2048. This is
the signature of the image. The public key is stored along with BL1 in
read-only memory and the encrypted hash is stored in the FIP.
When authenticating an image, the TF decrypts the hash stored in the FIP
and recalculates the hash of the image. If they don't match, the boot
sequence won't continue.
A constant-time comparison does not provide additional security as all
the data …
> Revert "tbbr: Use constant-time bcmp() to compare hashes"

- Makefile
Sharing the same CFLAGS for both the firmware and host tools is not
useful and can lead to compilation failure when CFLAGS is set on the
command line.
This patch make MAKEOVERRIDES special variable empty so make's command
line variable definitions are not implicitly forwarded to sub make
invocations. However, make options are still forwarded like "-s" option
to make the build silent.
Change-Id: Ia921c02beb1fd2041696a26160b9e7974ae000fa
> build: Use separate CFLAGS for tools

- docs/cpu-specific-build-macros.md
- lib/cpus/cpu-ops.mk
The errata is enabled by default on r0p4, which is confusing given that
we state we do not enable errata by default.
This patch clarifies this sentence by saying it is enabled in hardware
by default.
Change-Id: I70a062d93e1da2416d5f6d5776a77a659da737aa
> Clarify errata ERRATA_A53_836870 documentation

- drivers/io/io_memmap.c
Static checks flag an assert added in commit 1f786b0 that compares
unsigned value to 0, which will never fail.
Change-Id: I4b02031c2cfbd9a25255d12156919dda7d4805a0
> Remove redundant assert

- docs/user-guide.md
Now the TRUSTED_BOARD_BOOT is supported for AArch64 when LOAD_IMAGE_V2
is enabled. This patch updates the user-guide.md documentation for the
same.
Change-Id: I97de07435c81258c2a5f41a30a69736863a10bd1
Signed-off-by: Summer Qin <summer.qin@arm.com>
> Update LOAD_IMAGE_V2 user guide documentation

- plat/rockchip/common/include/plat_private.h
- plat/rockchip/common/plat_pm.c
- plat/rockchip/rk3368/drivers/pmu/pmu.c
- plat/rockchip/rk3368/drivers/soc/soc.c
- plat/rockchip/rk3368/drivers/soc/soc.h
- plat/rockchip/rk3399/drivers/pmu/pmu.c
Remove struct rockchip_pm_ops_cb and instead of using weak functions
implement; in this way we want the codes look clear and simple;
Change-Id: Ib9e8a5e932fdfc2b3e6a1ec502c40dfe720ac400
Signed-off-by: tony.xie <tony.xie@rock-chips.com>
> rockchip: plat_pm.c: Change callbacks implement for our SOCs.

- tools/fiptool/fiptool.c
- tools/fiptool/fiptool.h
Currently, fiptool uses two linked lists.  One to chain together all
the images and one for all the image descriptors.  Initially this was
done because not all images had a corresponding image descriptor.
This was the case for unknown images which existed in the FIP but
there was no descriptor in the builtin table for them.  When support
for the --blob option came in, we started building descriptors for the
unknown images on the fly.  As a result every image now has a
corresponding image descriptor and therefore it is no longer necessary
to keep track of them separately.
To simplify the design, maintain only a single linked list of image
descriptors.  An image descriptor contains a pointer to the
corresponding image.  If the pointer is NULL, then the descriptor is
skipped in all the …
> fiptool: Embed a pointer to an image within the image descriptor

- plat/nvidia/tegra/platform.mk
- plat/nvidia/tegra/soc/t210/platform_t210.mk
This patch enables the following erratas for the Tegra210 SoC:
* Cortex-A57
=========
- A57_DISABLE_NON_TEMPORAL_HINT
- ERRATA_A57_826974
- ERRATA_A57_826977
- ERRATA_A57_828024
- ERRATA_A57_829520
- ERRATA_A57_833471
* Cortex-A53
=========
- A53_DISABLE_NON_TEMPORAL_HINT
- ERRATA_A53_826319
- ERRATA_A53_836870
Tegra210 uses Cortex-A57 revision: r1p1 and Cortex-A53 revision: r0p2.
> Tegra210: enable errata for Cortex-A57 and Cortex-A53 CPUs

- drivers/arm/gic/v2/gicv2_main.c
- drivers/arm/gic/v3/gicv3_main.c
The GIC driver data is initialized by the primary CPU with caches
enabled. When the secondary CPU boots up, it initializes the
GICC/GICR interface with the caches disabled and there is a chance that
the driver data is not yet written back to the memory. This patch fixes
this problem by flushing the driver data after they have been
initialized.
Change-Id: Ie9477029683846209593ff005d2bac559bb8f5e6
> Flush the GIC driver data after init

- Makefile
- bl1/bl1.mk
- bl2/bl2.mk
- bl2u/bl2u.mk
- bl31/bl31.mk
- plat/arm/common/arm_common.mk
- plat/common/aarch32/platform_up_stack.S
- plat/common/aarch64/platform_up_stack.S
- plat/mediatek/mt6795/platform.mk
- plat/mediatek/mt8173/platform.mk
- plat/nvidia/tegra/common/tegra_common.mk
- plat/qemu/platform.mk
- plat/rockchip/rk3368/platform.mk
- plat/rockchip/rk3399/platform.mk
- plat/xilinx/zynqmp/platform.mk
These source file definitions should be defined in generic
Makefiles so that all platforms can benefit. Ensure that the
symbols are properly marked as weak so they can be overridden
by platforms.
NOTE: This change is a potential compatibility break for
non-upstream platforms.
Change-Id: I7b892efa9f2d6d216931360dc6c436e1d10cffed
> Move plat/common source file definitions to generic Makefiles

- plat/nvidia/tegra/common/drivers/memctrl/memctrl_v2.c
This patch fixes the logic to calculate the higher bits for TZRAM's base/end
addresses.
Fixes coverity error "31853: Wrong operator used (CONSTANT_EXPRESSION_RESULT)"
Change-Id: Iff62ef18cba59cd41ad63a5c71664872728356a8
> Tegra: memctrl_v2: fix logic to calculate TZRAM_ADDR_HI bits

- docs/user-guide.md
- include/lib/aarch32/arch.h
- include/lib/aarch64/arch.h
- include/plat/arm/common/plat_arm.h
- plat/arm/common/arm_common.mk
- plat/arm/common/arm_topology.c
- plat/arm/css/common/css_topology.c
- plat/arm/css/drivers/scpi/css_scpi.c
This patch modifies some of the functions in ARM platform layer to cater
for the case when multi-threading `MT` is set in MPIDR. A new build flag
`ARM_PLAT_MT` is added, and when enabled, the functions accessing MPIDR
now assume that the `MT` bit is set for the platform and access the bit
fields accordingly.
Also, a new API plat_arm_get_cpu_pe_count is added when `ARM_PLAT_MT` is
enabled, returning the PE count within the physical cpu corresponding to
`mpidr`.
Change-Id: I04ccf212ac3054a60882761f4087bae299af13cb
Signed-off-by: Summer Qin <summer.qin@arm.com>
> ARM platforms: Add support for MT bit in MPIDR

- include/lib/xlat_tables/xlat_tables_defs.h
- lib/xlat_tables/aarch32/xlat_tables.c
- lib/xlat_tables/aarch64/xlat_tables.c
- lib/xlat_tables_v2/aarch32/xlat_tables_arch.c
- lib/xlat_tables_v2/aarch64/xlat_tables_arch.c
This patch adds an additional flag `XLAT_TABLE_NC` which marks the
translation tables as Non-cacheable for MMU accesses.
Change-Id: I7c28ab87f0ce67da237fadc3627beb6792860fd4
Signed-off-by: Summer Qin <summer.qin@arm.com>
> Add support to change xlat_tables to non-cacheable

- drivers/auth/mbedtls/mbedtls_common.c
- drivers/auth/mbedtls/mbedtls_crypto.mk
- include/drivers/auth/mbedtls/mbedtls_config.h
These macros are not part of mbed TLS so they should not be prefixed
with `MBEDTLS_` to avoid potential collision in the future. Use the
`TBBR_` suffix to highlight that they only used in TF.
`MBEDTLS_KEY_ALG` was not modified because that is documented and used
by platforms to select the key algorithm.
Change-Id: Ief224681715c481691c80810501830ce16e210b0
> mbedtls: Namespace TF specific macros

- include/common/bl_common.h
- include/common/ep_info.h
- include/common/param_header.h
- include/lib/el3_runtime/context_mgmt.h
- include/lib/psci/psci.h
- include/lib/psci/psci_lib.h
This patch re-factors the following headers to make it easier to
integrate the PSCI library with an AArch32 Secure Payload :
*  bl_common.h : The entry point information and the param
header data structures are factored out into separate
headers ep_info.h and param_headers.h
*  psci.h : The PSCI library interfaces are factored out
into the new header psci_lib.h
*  context_mgmt.h : The header file is modified to not include
arch.h when compiled for AArch32 mode.
No functional changes are introduced by this patch.
Change-Id: I5e21a843c0af2ba8e47dee4e577cf95929be8cd4
> Re-factor header files for easier PSCI library integration

- docs/user-guide.md
This patch updates the User Guide to recommend the latest version
of mbed TLS library to use with ARM Trusted Firmware.
- Upgrade mbed TLS library:   2.2.1 -> 2.4.2
Change-Id: Ifb5386fec0673d6dbfdaa474233e397afc279c85
> Upgrade mbed TLS version

- plat/arm/board/juno/platform.mk
Juno platform Makefile is responsible for enabling all the relevant
errata. As the Juno platform port does not know which revision of Juno
the TF
is compiled for, the revision of the cores are unknown and so all errata
up to this date are needed on at least one revision of Juno.
Change-Id: I38e1d6efc17e703f2bd55e0714f8d8fa4778f696
> Enable all A53 and A57 errata workarounds for Juno

- Makefile
- bl1/bl1.ld.S
- bl2/aarch32/bl2_entrypoint.S
- bl2/aarch64/bl2_entrypoint.S
- bl2/bl2.ld.S
- bl2u/aarch64/bl2u_entrypoint.S
- bl2u/bl2u.ld.S
- bl31/bl31.ld.S
- bl32/tsp/aarch64/tsp_entrypoint.S
- docs/porting-guide.md
- docs/user-guide.md
- include/common/aarch32/el3_common_macros.S
- include/common/aarch64/el3_common_macros.S
- include/common/debug.h
- include/lib/utils.h
- include/plat/common/platform.h
- lib/stack_protector/aarch32/asm_stack_protector.S
- lib/stack_protector/aarch64/asm_stack_protector.S
- lib/stack_protector/stack_protector.c
- lib/stack_protector/stack_protector.mk
- make_helpers/defaults.mk
- plat/arm/board/fvp/fvp_stack_protector.c
- plat/arm/board/fvp/platform.mk
- plat/arm/board/juno/juno_decl.h
- plat/arm/board/juno/juno_def.h
- plat/arm/board/juno/juno_stack_protector.c
- plat/arm/board/juno/juno_trng.c
- plat/arm/board/juno/platform.mk
- plat/mediatek/mt6795/bl31.ld.S
Introduce new build option ENABLE_STACK_PROTECTOR. It enables
compilation of all BL images with one of the GCC -fstack-protector-*
options.
A new platform function plat_get_stack_protector_canary() is introduced.
It returns a value that is used to initialize the canary for stack
corruption detection. Returning a random value will prevent an attacker
from predicting the value and greatly increase the effectiveness of the
protection.
A message is printed at the ERROR level when a stack corruption is
detected.
To be effective, the global data must be stored at an address
lower than the base of the stacks. Failure to do so would allow an
attacker to overwrite the canary as part of an attack which would void
the protection.
FVP implementation of plat_get_stack_protector_canary is weak as
there …
> Add support for GCC stack protection

- plat/rockchip/common/plat_pm.c
The rockchip_pd_pwr_down_wfi function is currently unused, which may
trigger compiler warnings or errors. Remove it.
Change-Id: I7e1b0ae092e8855528ac2065ecefc8bd45305f31
Signed-off-by: Paul Kocialkowski <contact@paulk.fr>
> rockchip: Remove unused rockchip_pd_pwr_down_wfi function

- include/plat/arm/board/common/board_css_def.h
- include/plat/arm/common/arm_def.h
- include/plat/arm/soc/common/soc_css_def.h
- plat/arm/board/fvp/include/platform_def.h
Some header files using the ULL() macro were not directly including
utils.h where the macro definition resides. As a consequence, a linker
script with values using this macro did not see the macro definition
and kept the "ULL(<value>)" call in the preprocessed file, which lead to
link error.
Files using ULL() macro now include utils.h directly.
Change-Id: I433a7f36bd21a156c20e69bc2a2bb406140ebdf9
> Fix ARM_BL31_IN_DRAM build

- plat/rockchip/rk3399/drivers/dram/dfs.c
The printf() isn't used by the firmware itself, just by the tools under
the ./tools/ folder.
Change-Id: Ie699ccb54a5be9a2cbbd7b8d4193b57075a2f57a
Signed-off-by: Caesar Wang <wxt@rock-chips.com>
> rockchip/rk3399: the printf changed to tf_printf for console output

- plat/nvidia/tegra/common/drivers/memctrl/memctrl_v1.c
- plat/nvidia/tegra/common/tegra_common.mk
- plat/nvidia/tegra/include/platform_def.h
This patch enables the 'xlat_table_v2' library for the Tegra Memory
Controller driver. This library allows us to dynamically map/unmap
memory regions, with MMU enabled.
The Memory Controller driver maps/unmaps non-overlapping Video Memory
region, to clean it of any secure contents, before it resizes the
region.
> Tegra: memctrl_v1: enable 'xlat_table_v2' library

- Makefile
- plat/arm/css/common/css_common.mk
If SCP_BL2 is passed in from the command line, it is recognized by
make_helpers/tbbr/tbbr_tools.mk, and the cert_create tool generates
the corresponding key and content certificates.
On the other hand, the top-level Makefile does not care SCP_BL2, so
the --scp-fw option is not passed to the fiptool.  As far as I see
plat/arm/css/common/css_common.mk, it looks like a platform's job to
add $(eval $(call FIP_ADD_IMG,SCP_BL2,--scp-fw)).
We can make the top-level Makefile kind enough to take care of it.
This is useful when we want to have optional SCP_BL2 firmware.
Adjust css_common.mk so that Juno still requires SCP_BL2 by default.
> Build: add generic way to include SCP_BL2 into FIP image

- drivers/arm/cci/cci.c
The amount of console output is controlled by the LOG_LEVEL build
option. Using tf_printf without any #ifdef depending on the LOG_LEVEL
doesn't give the user that flexibility.
This patch replaces all occurrences of tf_printf that prints error, but
aren't dependent on LOG_LEVEL, with the ERROR macro.
Change-Id: Ib5147f14fc1579398a11f19ddd0e840ff6692831
> Replace tf_printf occurrences with ERROR

- plat/nvidia/tegra/common/drivers/smmu/smmu.c
This patch fixes the size used to save the context, when the
device enters System Suspend.
Reported by: David Cunado
> Tegra: smmu: fix the size used to save context

- Makefile
- bl1/bl1_main.c
- common/aarch32/debug.S
- common/aarch64/debug.S
- docs/user-guide.md
- drivers/arm/cci/cci.c
- drivers/arm/ccn/ccn.c
- drivers/arm/tzc/tzc400.c
- drivers/arm/tzc/tzc_common_private.h
- drivers/arm/tzc/tzc_dmc500.c
- drivers/io/io_storage.c
- include/common/aarch32/el3_common_macros.S
- include/lib/el3_runtime/context_mgmt.h
- include/lib/stdlib/assert.h
- lib/aarch32/misc_helpers.S
- lib/aarch64/misc_helpers.S
- lib/cpus/aarch32/aem_generic.S
- lib/cpus/aarch32/cortex_a32.S
- lib/cpus/aarch32/cpu_helpers.S
- lib/cpus/aarch64/cpu_helpers.S
- lib/stdlib/assert.c
- lib/xlat_tables/aarch32/xlat_tables.c
- lib/xlat_tables/aarch64/xlat_tables.c
- lib/xlat_tables/xlat_tables_common.c
- lib/xlat_tables_v2/aarch32/xlat_tables_arch.c
- lib/xlat_tables_v2/aarch64/xlat_tables_arch.c
- plat/common/aarch64/platform_mp_stack.S
Add the new build option `ENABLE_ASSERTIONS` that controls whether or
not assert functions are compiled out. It defaults to 1 for debug builds
and to 0 for release builds.
Assert messages are now only printed if LOG_LEVEL >= LOG_LEVEL_INFO,
which is the default for debug builds.
All occurrences of `ASM_ASSERTION` in common code and ARM platforms have
been replaced by `ENABLE_ASSERTIONS`.
> Add `ENABLE_ASSERTIONS` build option

- docs/user-guide.md
- include/plat/arm/board/common/v2m_def.h
- include/plat/arm/common/arm_xlat_tables.h
- include/plat/arm/common/plat_arm.h
- plat/arm/common/arm_bl1_setup.c
- plat/arm/common/arm_common.c
- plat/arm/common/arm_common.mk
ARM platforms have migrated to the translation tables library v2.
However, for testing purposes, it can be useful to temporarily switch
back to the old version.
This patch introduces the option `ARM_XLAT_TABLES_LIB_V1`, that switches
to v1 of the library when is set to 1. By default, it is 0, so that ARM
platforms use the new version unless specifically stated.
Updated User Guide.
Change-Id: I53d3c8dd97706f6af9c6fca0364a88ef341efd31
> ARM platforms: Add option to use xlat tables lib v1

- Makefile
- bl31/aarch64/bl31_entrypoint.S
- bl32/sp_min/aarch32/entrypoint.S
- docs/user-guide.md
- lib/psci/psci_on.c
- lib/psci/psci_suspend.c
- make_helpers/defaults.mk
This patch introduces a build option to enable D-cache early on the CPU
after warm boot. This is applicable for platforms which do not require
interconnect programming to enable cache coherency (eg: single cluster
platforms). If this option is enabled, then warm boot path enables
D-caches immediately after enabling MMU.
Fixes ARM-Software/tf-issues#456
Change-Id: I44c8787d116d7217837ced3bcf0b1d3441c8d80e
> PSCI: Build option to enable D-Caches early in warmboot

- plat/nvidia/tegra/common/tegra_sip_calls.c
- plat/nvidia/tegra/soc/t186/plat_sip_calls.c
On Tegra systems, there are multiple software components that
require to interact with MCE. The components can either be 32-bit
or 64-bit payloads. This patch supports MCE SMC functions ID for
AARCH32 and AARCH64 architectures to support such clients.
> Tegra186: Support AARCH32/64 encoding for MCE calls

- plat/nvidia/tegra/common/drivers/smmu/smmu.c
- plat/nvidia/tegra/soc/t186/plat_psci_handlers.c
- plat/nvidia/tegra/soc/t186/plat_trampoline.S
This patch sanity checks the SMMU context created by the platform
code. The first entry contains the size of the array; which the
driver now verifies before moving on with the save.
This patch also fixes an error in the calculation of the size of
the context that gets copied to TZDRAM.
> Tegra: smmu: make the context save sequence robust

- include/lib/xlat_tables/xlat_tables.h
- include/lib/xlat_tables/xlat_tables_v2.h
- lib/xlat_tables/xlat_tables_common.c
- lib/xlat_tables_v2/xlat_tables_common.c
- lib/xlat_tables_v2/xlat_tables_internal.c
This patch modifies both versions of the translation table library
to use the mmap_attr_t type consistently wherever it is manipulating
MT_* attributes variables. It used to use mmap_attr_t or plain integer
types interchangeably, which compiles fine because an enumeration type
can be silently converted to an integer, but which is semantically
incorrect.
This patch removes this assumption by using the abstract type
'mmap_attr_t' all the time.
> xlat lib: Use mmap_attr_t type consistently

- bl2/bl2_image_load_v2.c
- common/desc_image_load.c
Previously, get_next_bl_params_from_mem_params_desc() populated arg0
in the EL3 runtime entrypoint with a bl_params_t pointer. This is the
responsibility of the generic LOAD_IMAGE_V2 framework instead of the
descriptor-based image loading utility functions. Therefore this patch
moves that code to bl2_load_images().
Also, this patch moves the code that flushes the bl_params structure to
flush_bl_params_desc(), together with the other descriptor-based image
loading flushing code.
Change-Id: I4541e3f50e3878dde7cf89e9e8f31fe0b173fb9d
> Minor refactor of BL2 image load v2

- include/lib/stdlib/stdbool.h
This patch pulls the stdbool.h header file from the FreeBSD
project. The platforms require this header to fix many MISRA
defects among other things.
> lib: stdbool header from the FreeBSD project

- tools/fiptool/fiptool.c
An alignment value of 0x4000 is much easier to type than 16384,
so enhance get_image_align() to recognize a 0x prefix.
Signed-off-by: Andreas Färber <afaerber@suse.de>
> fiptool: Support non-decimal --align arguments

- drivers/ti/uart/aarch64/16550_console.S
UARTFCR is a write-only register and so a read-modify-write is not
applicable. This patch updates the programming sequence to remove this
logic and write to it directly from console_core_putc().
Signed-off-by: Vincent Zhang <xunz@nvidia.com>
> drivers: ti: uart: remove UART_FCR read-modify-write

- bl1/bl1_fwu.c
- include/lib/smcc.h
- services/spd/tspd/tspd_main.c
SMC_RET0 should only be used when the SMC code works as a function that
returns void. If the code of the SMC uses SMC_RET1 to return a value to
signify success and doesn't return anything in case of an error (or the
other way around) SMC_RET1 should always be used to return clearly
identifiable values.
This patch fixes two cases in which the code used SMC_RET0 instead of
SMC_RET1.
It also introduces the define SMC_OK to use when an SMC must return a
value to tell that it succeeded, the same way as SMC_UNK is used in case
of failure.
> tspd:FWU:Fix usage of SMC_RET0

- include/lib/xlat_tables/xlat_tables_defs.h
- lib/xlat_tables/aarch32/xlat_tables.c
- lib/xlat_tables/aarch64/xlat_tables.c
- lib/xlat_tables/xlat_tables_common.c
- lib/xlat_tables/xlat_tables_private.h
- lib/xlat_tables_v2/aarch32/xlat_tables_arch.c
- lib/xlat_tables_v2/aarch64/xlat_tables_arch.c
- lib/xlat_tables_v2/xlat_tables_common.c
- lib/xlat_tables_v2/xlat_tables_internal.c
- lib/xlat_tables_v2/xlat_tables_private.h
Translation regimes that only support one virtual address space (such as the ones for EL2 and EL3) can flag memory regions as execute-never by setting to 1 the XN bit in the Upper Attributes field in the translation tables descriptors. Translation regimes that support two different virtual address spaces (such as the one shared by EL1 and EL0) use bits PXN and UXN instead.
The Trusted Firmware runs at EL3 and EL1, it has to handle translation tables of both translation regimes, but the previous code handled both regimes the same way, as if both had only 1 VA range.
When trying to set a descriptor as execute-never it would set the XN bit correctly in EL3, but it would set the XN bit in EL1 as well. XN is at the same bit position as UXN, which means that EL0 was being prevented from …
> Fix execute-never permissions in xlat tables libs

- plat/rockchip/common/plat_pm.c
This reverts commit b6dcbf588af442fa87721dc707ff9e54d04ff504.
This function wasn't used when it was removed, but it is needed to compile the new changes proposed for Rockchip platforms.
The commit was introduced in this PR: https://github.com/ARM-software/arm-trusted-firmware/pull/889
It prevents the following PR to be successfully merged: https://github.com/ARM-software/arm-trusted-firmware/pull/918
> Revert "rockchip: Remove unused rockchip_pd_pwr_down_wfi function"

- plat/rockchip/common/bl31_plat_setup.c
- plat/rockchip/common/drivers/parameter/ddr_parameter.c
- plat/rockchip/common/drivers/parameter/ddr_parameter.h
- plat/rockchip/common/drivers/pmu/pmu_com.h
- plat/rockchip/common/plat_pm.c
- plat/rockchip/rk3328/drivers/pmu/plat_pmu_macros.S
- plat/rockchip/rk3328/drivers/pmu/pmu.c
- plat/rockchip/rk3328/drivers/pmu/pmu.h
- plat/rockchip/rk3328/drivers/soc/soc.c
- plat/rockchip/rk3328/drivers/soc/soc.h
- plat/rockchip/rk3328/include/plat.ld.S
- plat/rockchip/rk3328/include/platform_def.h
- plat/rockchip/rk3328/platform.mk
- plat/rockchip/rk3328/rk3328_def.h
rk3328 is a Quad-core soc and Cortex-a53 inside!
This patch supports the following functions:
1、power up/off cpus
2、suspend/resume cpus
3、suspend/resume system
4、reset system
5、power off system
Change-Id: I60687058d13912c6929293b06fed9c6bc72bdc84
Signed-off-by: tony.xie <tony.xie@rock-chips.com>
> rockchip: rk3328: support rk3328

- plat/arm/common/execution_state_switch.c
A new file added as part of arm-trusted-firmware#927 was missing the
SPDX license identifier - this patch adds the missing identifier.
Change-Id: Id1355f2bdca930b7e65bb54eff7e6c764ebb0d96
> Add missing SPDX header

- plat/rockchip/rk3328/drivers/pmu/pmu.c
Add assert() check for cpuson_flags[] and cpuson_entry_point[].
Change-Id: I971fe54c2baa3b4514a3979042341220f5e20901
Signed-off-by: tony.xie <tony.xie@rock-chips.com>
> rockchip: rk3328: Add assert check in pmu.c

- plat/arm/board/juno/sp_min/sp_min-juno.mk
The commit abd2aba99ef108e0d0bb5d71c0b6e9c47ca26377 introduced a
regression to the AArch32 sp_min Juno build. This patch fixes that.
Change-Id: I4b141717684d6aee60c761ea17f23170aa6708c3
> Juno: Fix AArch32 sp_min build

- docs/porting-guide.md
- include/lib/stdlib/assert.h
- lib/stdlib/assert.c
The behaviour of assert() now depends on the value of the new optional platform define `PLAT_LOG_LEVEL_ASSERT`. This defaults to `LOG_LEVEL` if not defined by the platform.
- If `PLAT_LOG_LEVEL_ASSERT` >= `LOG_LEVEL_VERBOSE`, it prints the file name, line and asserted expression.
- If `PLAT_LOG_LEVEL_ASSERT` >= `LOG_LEVEL_INFO`, it prints the file name and line.
- If not, it doesn't print anything.
Note the old behaviour was to print the function name whereas now it prints the file name. This reduces memory usage because the file name is shared between all assert calls in a given file. Also, the default
behaviour in debug builds is to no longer print the asserted expression, greatly reducing the string usage.
For FVP debug builds this change saves approximately:
```
No TBBR    TBBR
BL1 …
```
> Simplify assert() to reduce memory usage

- license.md
Added note regarding use of SPDX identifiers following this example:
https://github.com/pocoproject/poco/blob/develop/LICENSE
Change-Id: I22a280bce57f9145e4786c5ad32f663c2c9c6545
Signed-off-by: Jilayne Lovejoy <jilayne.lovejoy@arm.com>
> Add note about SPDX identifiers in license.md

- lib/xlat_tables_v2/aarch32/xlat_tables_arch.h
- lib/xlat_tables_v2/aarch64/xlat_tables_arch.h
`xlat_tables_arch.h` uses the platform macro `PLAT_VIRT_ADDR_SPACE_SIZE`. This macro is defined in `xlat_tables_private.h` only if the platform still uses the deprecated `ADDR_SPACE_SIZE`.
> xlat: Fix missing header file dependency

- docs/user-guide.md
This Linaro release updates just the binaries:
Linaro binaries upgraded 16.12 --> 17.01
The toolchain remains at 5.3-2015.05 (gcc 5.3) for both AArch64
and AArch32.
The ARM TF codebase has been tested against these new binaries. This patch
updates the User Guide to reflect that the 17.01 release is now a supported
Linaro Release.
Change-Id: I83c579dabd3fa9861ba0d41507036efbd87abcb5
> Migrate to Linaro Release 17.01

- Makefile
- common/tf_snprintf.c
- docs/auth-framework.md
- drivers/auth/mbedtls/mbedtls_common.c
- include/common/debug.h
- include/drivers/auth/mbedtls/mbedtls_config.h
- plat/arm/common/arm_common.mk
This pull request introduces two changes that reduce the code size of BL1 and BL2 by approximately 4.6 KB when the Trusted Firmware is built with Trusted Board Boot enabled. Other images aren't affected by this change.
> Reduce code size when building with Trusted Board Boot enabled

- plat/hisilicon/hikey/hikey_ddr.c
Fix issue in https://github.com/ARM-software/tf-issues/issues/483
Fix uninitliazed variable in ddr driver code.
> hikey: fix uninitialized variable in ddr code

- drivers/auth/mbedtls/mbedtls_common.c
mbed TLS provides the debug API `mbedtls_memory_buffer_alloc_status()` to analyse the RAM usage of the library.
When RSA is selected as algorithm, the maximum heap usage in FVP and Juno has been determined empirically to be approximately 5.5 KiB. However, The default heap size used when RSA is selected is 8 KiB.
This patch reduces the buffer from 8 KiB to 6 KiB so that the BSS sections of both BL1 and BL2 are 2 KiB smaller when the firmware is compiled with Trusted Board Boot support.
> mbedtls: Define optimized mbed TLS heap size

- Makefile
- bl1/bl1_fwu.c
- docs/firmware-update.md
- docs/porting-guide.md
- docs/user-guide.md
- include/bl1/bl1.h
- make_helpers/defaults.mk
Added checks to `FWU_SMC_IMAGE_COPY` to prevent loading data into a memory region where another image data is already loaded.
Without this check, if two images are configured to be loaded in overlapping memory regions, one of them can be loaded and authenticated and the copy function is still able to load data from the second image on top of the first one. Since the first image is still in authenticated state, it can be executed, which could lead to the execution of unauthenticated arbitrary code of the second image.
The new SMC is a means for the image loading state machine to go from `COPYING`, `COPIED` or `AUTHENTICATED` states to `RESET` state. Previously, this was only done when the authentication of an image failed or when the execution of the image finished.
Firmware update …
> FWU: Check for overlaps when loading images, introduce `FWU_SMC_IMAGE_RESET`

- include/lib/cpus/aarch64/cortex_a55.h
- include/lib/cpus/aarch64/cortex_a75.h
- lib/cpus/aarch64/cortex_a55.S
- lib/cpus/aarch64/cortex_a75.S
- plat/arm/board/fvp/platform.mk
Both Cortex-A75 and Cortex-A55 CPUs use the ARM DynamIQ Shared Unit
(DSU). The power-down and power-up sequences are therefore mostly
managed in hardware, and required software operations are considerably
simpler.
Change-Id: I68b30e6e1ebe7c041d5e67f39c59f08575fc7ecc
Co-authored-by: Sandrine Bailleux <sandrine.bailleux@arm.com>
> Add support for Cortex-A75 and Cortex-A55 CPUs

- docs/user-guide.md
- drivers/arm/gic/v3/gic600.c
- drivers/arm/gic/v3/gicv3_main.c
- drivers/arm/gic/v3/gicv3_private.h
- plat/arm/board/fvp/platform.mk
ARM GIC-600 IP complies with ARM GICv3 architecture, but among others,
implements a power control register in the Redistributor frame. This
register must be programmed to mark the frame as powered on, before
accessing other registers in the frame. Rest of initialization sequence
remains the same.
The driver provides APIs for Redistributor power management, and
overrides those in the generic GICv3 driver. The driver data is shared
between generic GICv3 driver and that of GIC-600.
For FVP platform, the GIC-600 driver is chosen when FVP_USE_GIC_DRIVER
is set to FVP_GIC600. Also update user guide.
Change-Id: I321b2360728d69f6d4b0a747b2cfcc3fe5a20d67
> Introduce ARM GIC-600 driver

- drivers/auth/mbedtls/mbedtls_common.c
If `MBEDTLS_PLATFORM_SNPRINTF_ALT` isn't used, the function `mbedtls_platform_set_snprintf()` isn't defined.
In case a platform uses a different mbed TLS configuration file than the one provided by the Trusted Firmware, and it doesn't define the mentioned build option, this will result in a build error.
This patch modifies the initialization code so that `mbedtls_platform_set_snprintf()` is only used if `MBEDTLS_PLATFORM_SNPRINTF_ALT` is defined, allowing platforms to use it or not depending on their needs.
Fixes ARM-software/tf-issues#487
> mbedtls: Don't use tf_snprintf if option not defined

- contributing.md
- maintainers.md
Clarify copyright requirements in contributing.md.
Also clarify maintainership structure by adding a new maintainers.md. This
imports individual maintainer details from the GitHub wiki.
Fixes ARM-software/tf-issues#488
Change-Id: I7135d3f77ea45533f667de7e1dcdf65697486a91
> Docs: Clarify copyright requirements

- plat/nvidia/tegra/common/tegra_bl31_setup.c
The 'impl' variable is guarded by the symbold DEBUG, but used in an INFO
level print statement. INFO is defined based on LOG_LEVEL. Hence, builds
would faile when
- DEBUG=0 && LOG_LEVEL=>LOG_LEVEL_INFO with a variable used but not defined
- DEBUG=1 && LOG_LEVEL<LOG_LEVEL_INFO with a defined but not used
Fixing this by guarding impl with the same condition that guards INFO.
Fixes ARM-software/tf-issues#490
> tegra: Fix build errors

- include/lib/stdlib/machine/_limits.h
- include/lib/stdlib/machine/_stdint.h
Some of the macro defines in the header files of `include/lib/stdlib/machine/`
folder are not correct for AArch32. This patch fixes the same.
Change-Id: I8bfaf638a7986fd902648d2074537bd26c313cb3
> Fix stdlib defines for AArch32

- tools/cert_create/Makefile
- tools/fiptool/Makefile
When V is set from the command line, the value is passed to the tools'
Makefiles as well.
Change-Id: I91a1f66de5c1ae6f36b6c9f0a9bd550d4a30f092
> tools: Use exported quiet flag from top-level Makefile

- plat/arm/css/drivers/scp/css_pm_scpi.c
- plat/arm/css/drivers/scpi/css_scpi.c
The ARM_PLAT_MT bit enables the support for MT bit in
MPIDR format. This means that the level 0 affinity
represents the thread and CPU / Cluster levels are
at affinity level 1 and 2 respectively.
This was not catered for in the scpi 'css_scp_get_power_state, API.
Since the SCPI driver can only cater for single threaded CPUs,
this patch fixes the problem by catering for this shift by
effectively ignoring the Thread (level 0) affinity level.
Change-Id: If44f55c9fb2773c8d3f8a9bbcf5420a6f7409dfe
Signed-off-by: jagadeesh ujja <jagadeesh.ujja@arm.com>
> CSS:Fix scpi "get_power_state" when ARM_PLAT_MT is set

- plat/hisilicon/hikey960/aarch64/hikey960_helpers.S
The patch fb7d32e5881ef2445e8fe2305005f5590d4a7cfa migrated the CPU
libraries to have unique defines, prefixing them with the CPU name.
This patch migrates the hikey960 platform port to use the A53 specific
defines.
Change-Id: Id76f544b0b236bbd4974ab5ffa1203f073c20021
> hikey960: migrate to use A53 specific defines

- lib/xlat_tables_v2/xlat_tables_internal.c
This patch changes input param level in xlat_tables_print_internal() to
an unsigned int to fix the signed/unsigned comparison warnings. The
compiler complains about these warnings, thus halting the build flow
for Tegra platforms.
Change-Id: Ieccc262a63daca7a26ca6a14d81466397af8b89f
> xlat_tables_v2: fix signed/unsigned comparisons

- plat/hisilicon/hikey960/hikey960_pm.c
In CPU off callback function, the old code uses the function
hisi_test_pwrdn_allcores() to check if all CPUs in cluster have been
powered off and if it's valid then power off the whole cluster. But the
function hisi_test_pwrdn_allcores() only maintains the different power
states only for CPU suspend/resume flow, so it cannot return correct
states for CPU on/off flow.
This patch is to change use hisi_test_cpu_down() to check if all CPUs
have been powered off, so that can power off the whole cluster properly
when all CPUs in cluster have been hotplugged off.
Signed-off-by: Tao Wang <kevin.wangtao@hisilicon.com>
Signed-off-by: Leo Yan <leo.yan@linaro.org>
> plat: Hikey960: fix the CPU hotplug

- include/lib/aarch32/arch_helpers.h
- lib/xlat_tables/aarch32/xlat_tables.c
- lib/xlat_tables_v2/aarch32/xlat_tables_arch.c
TLBI instructions for monitor mode won't have the desired effect under
specific circumstances in Cortex-A57 r0p0. The workaround is to
execute DSB and TLBI twice each time.
Even though this errata is only needed in r0p0, the current errata
framework is not prepared to apply run-time workarounds. The current one
is always applied if compiled in, regardless of the CPU or its revision.
The `DSB` instruction used when initializing the translation tables has
been changed to `DSB ISH` as an optimization and to be consistent with
the barriers used for the workaround.
NOTE: This workaround is present in AArch64 TF and already enabled by
default on Juno.
Change-Id: I10b0baa304ed64b13b7b26ea766e61461e759dfa
> aarch32: Apply workaround for errata 813419 of Cortex-A57

- lib/psci/psci_stat.c
- lib/psci/psci_suspend.c
This change fixes minor issues in the psci library:
- Call `svc_suspend_finish()` if registered.
- `psci_get_stat()` is static to psci_stat.c
- Fix types used in comparison.
- Fix coding style
Change-Id: I73e582f2c9e8504d1c567c6dcb7045c3684f4525
Signed-off-by: Etienne Carriere <etienne.carriere@st.com>
> psci: minor fixes in lib

- plat/nvidia/tegra/platform.mk
Use TF_CFLAGS instead of CFLAGS, to allow CFLAGS to be overriden from
the make command line.
Change-Id: I3e5726c04bcd0176f232581b8be2c94413374ac7
> Fix Tegra CFLAGS usage

- Makefile
- lib/cpus/aarch64/cortex_a53.S
- lib/cpus/cpu-ops.mk
- plat/arm/board/juno/platform.mk
These errata are only applicable to AArch64 state. See the errata notice
for more details:
http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.epm048406/index.html
Introduce the build options ERRATA_A53_835769 and ERRATA_A53_843419.
Enable both of them for Juno.
Apply the 835769 workaround as following:
* Compile with -mfix-cortex-a53-835769
* Link with --fix-cortex-a53-835769
Apply the 843419 workaround as following:
* Link with --fix-cortex-a53-843419
The erratum 843419 workaround can lead the linker to create new sections
suffixed with "*.stub*" and 4KB aligned. The erratum 835769 can lead the
linker to create new "*.stub" sections with no particular alignment.
Also add support for LDFLAGS_aarch32 and LDFLAGS_aarch64 in Makefile for
architecture-specific linker options. …
> Apply workarounds for A53 Cat A Errata 835769 and 843419

- docs/change-log.md
- docs/firmware-update.md
Fix link in docs/firmware-update.md and docs/change-log.md:
https://github.com/ARM-software/arm-trusted-firmware/wiki/ARM-Trusted-Firmware-Image-Terminology
Change-Id: I2d51d373fd0f7da59b548cd6bed52c47772014fd
> Fix broken link in documentation

- plat/rockchip/rk3399/platform.mk
For rk3399, the L2ACTLR[14] is 0 by default, as ACE CCI-500 doesn't
support WriteEvict. and you will hit the condition L2ACTLR[3] with 0,
as the Evict transactions should propagate to CCI-500 since it has
snoop filters.
Maybe this erratum applies to all Cortex-A53 cores so far, especially
if RK3399's A53 is a r0p4. we should enable it to avoid data corruption,
Change-Id: Ib86933f1fc84f8919c8e43dac41af60fd0c3ce2f
Signed-off-by: Caesar Wang <wxt@rock-chips.com>
> rockchip: enable A53's erratum 855873 for rk3399

- docs/firmware-design.md
Without the additional newlines all the text becomes a single paragraph
and next newlines are ignored.
Change-Id: I783198477f654e3923fcabb21248f2bc62c33e9d
> Improve format of exception vectors in BL1 description

- Makefile
- docs/user-guide.md
- lib/cpus/cpu-ops.mk
- make_helpers/build_macros.mk
Use TF_LDFLAGS from the Makefiles, and still append LDFLAGS as well to
the compiler's invocation. This allows passing extra options from the
make command line using LDFLAGS.
Document new LDFLAGS Makefile option.
Change-Id: I88c5ac26ca12ac2b2d60a6f150ae027639991f27
> Introduce TF_LDFLAGS and improve CFLAGS documentation

- docs/user-guide.rst
Trusted Firmware has been tested as part of its CI system against Cortex
and Foundation models in the 11.0 Model release available on
developer.arm.com. Trusted Firmware has also been tested against the v8.5
AEM model.
This patch updates the user guide documentation to reflect the version of
the Foundation, AEM and Cortex Models that Trusted Firmware has been
tested against.
Change-Id: I3b5b4d1e4220bda1dcc88aa9cfa01fa711ed92cd
> Update Foundation, AEM and Cortex Models versions

- docs/user-guide.rst
ARM TF has been tested against Linaro Release 17.04 - the Linaro
binaries have been update and also the version of the compiler.
Linaro binaries: 17.01 --> 17.04
AArch64 & AArch32 compilers: 5.3-2015.05 (gcc 5.3) -> 6.2-2016.11 (gcc 6.2)
This patch updates the User Guide is to state that Linaro
release 17.04 is supported.
Additionally, the following fixes are made to the User Guide:
- Removed out of date reference to Linaro release 16.06.
- Updated the Juno variant coverage to include r2.
Change-Id: Iebbced3356f8c6b3c2bff2df62574db9f937ca7b
> Migrate to Linaro release 17.04

- plat/hisilicon/hikey/platform.mk
Fix cortex a53 errata issues: #836870, #843419, #855873.
Fix https://github.com/ARM-software/tf-issues/issues/498
> hikey: enable options to fix errata

- plat/xilinx/zynqmp/pm_service/pm_client.c
Fixing compilation errors due to duplicate 'const' keyword:
plat/xilinx/zynqmp/pm_service/pm_client.c:39:29: error: duplicate 'const' declaration specifier [-Werror=duplicate-decl-specifier]
static const struct pm_proc const pm_procs_all[] = {
^~~~~
> zynqmp: Remove duplicate 'const' declaration

- docs/plat/poplar.rst
- plat/hisilicon/poplar/aarch64/platform_common.c
- plat/hisilicon/poplar/bl1_plat_setup.c
- plat/hisilicon/poplar/bl2_plat_setup.c
- plat/hisilicon/poplar/bl31_plat_setup.c
- plat/hisilicon/poplar/include/hi3798cv200.h
- plat/hisilicon/poplar/include/plat_macros.S
- plat/hisilicon/poplar/include/plat_private.h
- plat/hisilicon/poplar/include/platform_def.h
- plat/hisilicon/poplar/include/poplar_layout.h
- plat/hisilicon/poplar/plat_pm.c
- plat/hisilicon/poplar/plat_storage.c
- plat/hisilicon/poplar/plat_topology.c
- plat/hisilicon/poplar/platform.mk
The board features the Hi3798C V200 with an integrated quad-core
64-bit ARM Cortex A53 processor and high performance Mali T720 GPU,
making it capable of running any commercial set-top solution based on
Linux or Android. Its high performance specification also supports a
premium user experience with up to H.265 HEVC decoding of 4K video at
60 frames per second.
SOC  Hisilicon Hi3798CV200
CPU  Quad-core ARM Cortex-A53 64 bit
DRAM DDR3/3L/4 SDRAM interface, maximum 32-bit data width 2 GB
USB  Two USB 2.0 ports One USB 3.0 ports
CONSOLE  USB-micro port for console support
ETHERNET  1 GBe Ethernet
PCIE  One PCIe 2.0 interfaces
JTAG  8-Pin JTAG
EXPANSION INTERFACE  Linaro 96Boards Low Speed Expansion slot
DIMENSION Standard 160×120 mm 96Boards Enterprice Edition form factor
WIFI  802.11AC 2*2 …
> Poplar: Initial commit for Poplar E-96Boards

- lib/stdlib/assert.c
This format is understood by almost all the UNIX tools (vi, emacs, acme, ...),
and it allows these tools to jump directly to the line where the assert
failed.
Change-Id: I648fa93c7cc65f911a17dcad5e1a775ac1ae5ed4
> Use standard UNIX file:line format in assert

- docs/cpu-specific-build-macros.rst
Add documentation for errata 835769 and 843419 workarounds introduced in
commit a94cc374ab57b80d86974f8771565d65b38403ef
Fixes ARM-software/tf-issues#504
Change-Id: I7f3db53dfc5f3827b32663f483d3302bc9679b19
> Add doc for some Cortex A53 errata workarounds

- lib/xlat_tables_v2/xlat_tables_internal.c
This patch changes the sign of the loop variable used in
xlat_tables_print(). It needs to be unsigned because it is compared
against another unsigned int.
> Fix sign of variable in xlat_tables_print()

- docs/platform-migration-guide.rst
- docs/porting-guide.rst
- include/lib/psci/psci.h
- lib/psci/psci_suspend.c
- plat/nvidia/tegra/common/tegra_pm.c
This patch adds an early suspend handler, that executes with
SMP and data cache enabled. This handler allows platforms to
perform any early actions during the CPU suspend entry sequence.
This handler is optional and platforms can choose to implement it
depending on their needs. The `pwr_domain_suspend` handler still
exists and platforms can keep on using it without any side effects.
> lib: psci: early suspend handler for platforms

- tools/fiptool/fiptool.c
- tools/fiptool/fiptool.h
- tools/fiptool/tbbr_config.c
This fix modifies the order of system includes to meet the ARM TF coding
standard whilst retaining header groupings.
Change-Id: Ib91968f8e2cac9e96033d73d3ad9d0a2ae228b13
Signed-off-by: Isla Mitchell <isla.mitchell@arm.com>
> Fix order of #includes

- docs/change-log.rst
With the migration to .rst from .md, the Issues Resolved and
Known Issues sections for v1.4 were using Header 1 format.
This patch changes to using Header 2 for these sections.
Change-Id: Ic3127d84eb169a65039fd4cc8284c6429302732d
> Fix to change.log

- plat/qemu/platform.mk
- plat/qemu/qemu_common.c
Almost all the arm platform has switch to translation tables library v2 as
default. Because qemu platform doesn't use arm_common.mk like other arm
platforms, QEMU haven't switched to v2 yet.
This patch adds all the necessary code for adding translation tables
library v2 support on QEMU and use it as default.
Fixes ARM-software/tf-issues#508
Signed-off-by: Fu Wei <fu.wei@linaro.org>
> qemu: use translation tables library v2 as default.

- bl2u/aarch32/bl2u_entrypoint.S
Replace the use of r12 by r10 to save the value of a parameter of
bl2u_entrypoint to pass it to bl2u_early_platform_setup at the end of
the function. r10 is a callee saved register so it will not become
corrupted by C code, whereas r12 is the The Intra-Procedure-call scratch
register potentially used by veneers. See the ARM AAPCS document (ARM
IHI 0042F).
Change-Id: I4f37e54a6b550719edb40bb24cd8f498827e2749
> Fix BL2U entrypoint possible parameter corruption

- plat/qemu/platform.mk
- plat/qemu/qemu_bl1_setup.c
- plat/qemu/qemu_bl2_mem_params_desc.c
- plat/qemu/qemu_bl2_setup.c
- plat/qemu/qemu_bl31_setup.c
- plat/qemu/qemu_image_load.c
The generic LOAD_IMAGE_V2 framework has been merged and enable for almost
all the arm platform. Because qemu platform doesn't share those common
files with arm, QEMU haven't got this support yet.
This patch add all the necessary code the files for adding LOAD_IMAGE_V2
support on QEMU and enable it as default.
Fixes ARM-software/tf-issues#507
Signed-off-by: Fu Wei <fu.wei@linaro.org>
> qemu: Add LOAD_IMAGE_V2 support

- bl32/sp_min/aarch32/entrypoint.S
- bl32/sp_min/sp_min.mk
- bl32/sp_min/sp_min_main.c
- bl32/sp_min/sp_min_private.h
- docs/user-guide.rst
- include/bl32/sp_min/platform_sp_min.h
Propose a minimal secure interrupt service in sp_min for the AArch32
implementation.
Change-Id: I1f7d1dc7b21f6f90011b7f3fcd921e455592f5e7
Signed-off-by: Etienne Carriere <etienne.carriere@st.com>
> bl32: add secure interrupt handling in AArch32 sp_min

- plat/hisilicon/hikey960/hikey960_pm.c
Hikey960: fix PSCI suspend stuck issue
Clear the cpuidle flag when resuming from idle. This flag is set when entering idle, and if it remains set when resuming, it can prevent the cluster from powering off during the next system suspend operation. During system suspend, all CPUs are plugged out except the last CPU, which is suspended. If any of the cpuidle flags are set at this point, the last CPU will be stuck in a WFI loop and will not be powered off.
This problem only occurs during system suspend.
fixes ARM-software/tf-issues#509
Signed-off-by: Tao Wang <kevin.wangtao@linaro.org>
> Hikey960: fix PSCI suspend stuck issue

- bl32/tsp/aarch64/tsp_entrypoint.S
- include/common/asm_macros_common.S
- plat/hisilicon/hikey/hisi_pwrc_sram.S
- plat/nvidia/tegra/common/aarch64/tegra_helpers.S
- plat/nvidia/tegra/soc/t186/plat_trampoline.S
- plat/rockchip/common/aarch64/plat_helpers.S
Assembler programmers are used to being able to define functions with a
specific aligment with a pattern like this:
.align X
myfunction:
However, this pattern is subtly broken when instead of a direct label
like 'myfunction:', you use the 'func myfunction' macro that's standard
in Trusted Firmware. Since the func macro declares a new section for the
function, the .align directive written above it actually applies to the
*previous* section in the assembly file, and the function it was
supposed to apply to is linked with default alignment.
An extreme case can be seen in Rockchip's plat_helpers.S which contains
this code:
[...]
endfunc plat_crash_console_putc
.align 16
func platform_cpu_warmboot
[...]
This assembles into the following plat_helpers.o:
Sections:
Idx Name …
> Add new alignment parameter to func assembler macro

- bl31/aarch64/runtime_exceptions.S
- bl32/tsp/aarch64/tsp_exceptions.S
- common/aarch32/debug.S
- common/aarch64/debug.S
Some error paths that lead to a crash dump will overwrite the value in
the x30 register by calling functions with the no_ret macro, which
resolves to a BL instruction. This is not very useful and not what the
reader would expect, since a crash dump should usually show all
registers in the state they were in when the exception happened. This
patch replaces the offending function calls with a B instruction to
preserve the value in x30.
Change-Id: I2a3636f2943f79bab0cd911f89d070012e697c2a
Signed-off-by: Julius Werner <jwerner@chromium.org>
> Fix x30 reporting for unhandled exceptions

- lib/psci/psci_common.c
Previously commit 555ebb34db8f3424c1b394df2f10ec attmpted to fix this
GCC issue:
services/std_svc/psci/psci_common.c: In function 'psci_do_state_coordination':
services/std_svc/psci/psci_common.c:220:27: error: array subscript is above
array bounds [-Werror=array-bounds]
psci_req_local_pwr_states[pwrlvl - 1][cpu_idx] = req_pwr_state;
This fix doesn't work as asserts aren't built in non-debug build flows.
Let's ensure this error is fixed for all build cases.
Signed-off-by: Alistair Francis <alistair.francis@xilinx.com>
Signed-off-by: Nathan Rossi <nathan@nathanrossi.com>
> psci_common: Resolve GCC static analysis false positive

- docs/firmware-design.rst
The format conversion wrongly formatted a couple of sections. These were
also missing from the Table of Contents.
Change-Id: I324216c27e7b4711e6cc5e25782f4b53842140cc
> firmware-design.rst: Fix formatting

- lib/el3_runtime/aarch64/context_mgmt.c
which will cause write_sctlr_el2 use all sctlr_el1 value except the EE bit
the code doesn't "Use SCTLR_EL1.EE value to initialise sctlr_el2"
but, read out SCTLR_EL1 and clear EE bit, then set to sctlr_el2
Signed-off-by: Ken Kuang <ken.kuang@spreadtrum.com>
> fix a typo abort sctlr_el2

- plat/arm/board/fvp/fvp_common.c
At present, the MPIDR validation on FVP relies on MT bit set along
with shifted affinities. This currently is additionally dependent
on the FVP model being of variant C. This however should be based
on the presence of MT bit alone.
This patch makes the change to always assume that the affinities
are shifted in the FVP model when MT bit is present.
Change-Id: I09fcb0126e1b38d29124bdeaf3450a60b95d485d
Signed-off-by: Isla Mitchell <isla.mitchell@arm.com>
> FVP: Always assume shifted affinity with MT bit

- include/plat/arm/common/plat_arm.h
- plat/arm/board/fvp/drivers/pwrc/fvp_pwrc.c
- plat/arm/css/drivers/scp/css_pm_scmi.c
- plat/arm/css/drivers/scpi/css_mhu.c
The current definition of ARM_INSTANTIATE_LOCK macro includes a
semicolon, which means it's omitted where it's used. This is anomalous
for a C statement in global scope.
Fix this by removing semicolon from the definition; and where it's a
NOP, declare a file-scoped variable explicitly tagged as unused to avoid
compiler warning.
No functional changes.
Change-Id: I2c1d92ece4777e272a025011e03b8003f3543335
> plat/arm: Fix ARM_INSTANTIATE_LOCK syntax anomaly

- docs/user-guide.rst
The internal synchronisation timings of the FVP model version
11.0 build 11.0.34 and version 8.5 build 0.8.5202 has been
changed compared to older version of the models.
This change may have an impact on how the model behaves depending
on the workload being run on the model. For example test failures
have been seen where the primary core has powered on a secondary
core but was then starved of host CPU time and so was not able to
update power status, resulting a test failure due to an incorrect
status. This, or similar behaviour, is not to be expected from
real hardware platforms.
This patch adds a usage note on how to launch these models so
that internal synchronisation timing matches that of the older
version of the models, specifically adding the -Q 100 option.
Change-Id: …
> Add usage note for FVP model versions 11.0 and 8.5

- plat/arm/css/common/css_bl2_setup.c
zero_normalmem only can zero memory when caches are enabled
and the target memory is a normal memory, otherwise an abort is
generated. In the case of EL3_PAYLOAD_BASE bl2_platform_setup was
calling zero_normalmem with device memory and it generated an abort.
Change-Id: If013603f209a12af488a9c54481f97a8f395b26a
> Don't use zero_normalmem in bl2_platform_setup

- tools/fiptool/fiptool.c
Unix does not distinguish binary and text modes.
On Windows the 'b' flag (e.g. "rb" instead of "r") is used to
indicate that files should be opened in binary mode.
This has no impact on Unix, but is needed on Windows to avoid
end-of-line issues.
Change-Id: I69424c55735d5d563d36c50bedd6357b8e05137e
Signed-off-by: Evan Lloyd <evan.lloyd@arm.com>
> fiptool: Update file open modes with 'b' (for Windows)

- plat/hisilicon/hikey/hisi_pwrc.c
At the system boot time we need enable watchdog reset, otherwise after
the watchdog is timeout it cannot reset the SoC. We need set the bit 0
and bit 16 together, the bit 16 is mask bit so after set bit 16 we have
permission to operate bit 0 and bit 0 is watchdog reset enabling bit.
Signed-off-by: Leo Yan <leo.yan@linaro.org>
> Hikey: enable watchdog reset

- plat/arm/board/juno/include/platform_def.h
This patch fixes the PLAT_LOG_LEVEL_ASSERT to 40 which corresponds
to LOG_LEVEL_INFO. Having this level of log for assertions means that the
`assert()` will not generate the strings implied in the expression taken
as parameter. This allows to save some memory when Juno is built for
LOG_LEVEL = LOG_LEVEL_VERBOSE and DEBUG = 1.
Fixes ARM-software/tf-issues#511
Change-Id: Id84a40f803ab07a5a8f6e587167af96694a07d04
> Juno: Define PLAT_LOG_LEVEL_ASSERT to LOG_LEVEL_INFO

- docs/porting-guide.rst
Fix the level of the section
"13.   Function : plat_setup_psci_ops() [mandatory]",
including all the subsections.
Fix the level of the section
"12.7.   plat_psci_ops.pwr_domain_suspend_pwrdown_early() [optional]"
to lower it like the surrounding functions.
Change-Id: I781823bc96ece669f8fde4bd39c4e333c7bf4d1a
> porting-guide.rst: Fix some sections' level

- include/plat/arm/common/arm_def.h
- plat/arm/board/common/board_css_common.c
- plat/arm/board/fvp/fvp_common.c
This patch ensures that the ARM_MAP_TSP_SEC_MEM memory region is mapped
in BL2 only if the TSPD has been included in the build. This saves one
entry in the plat_arm_mmap[] array and avoids to map extra memory when
it's not needed.
> ARM platforms: Map TSP only when TSPD is included

- include/plat/arm/common/arm_def.h
- plat/arm/board/common/board_css_common.c
- plat/arm/board/fvp/fvp_common.c
The commit 3eb2d67 optimizes the memory map for BL2 when TSP
is not present. But this also broke OP-TEE as it was reusing
the TSP mapping. This patch fixes this problem by adding a
separate mapping for OP-TEE in the BL2 memory map table.
Change-Id: I130a2ea552b7b62d8478081feb1f4ddf5292a118
> Fix BL2 memory map when OP-TEE is the Secure Payload

- include/common/aarch32/asm_macros.S
- include/lib/el3_runtime/cpu_data.h
- lib/el3_runtime/aarch32/cpu_data.S
- lib/el3_runtime/aarch64/cpu_data.S
Platform may use specific cache sizes. Since CPU_DATA_LOG2SIZE
depends on the cache line size, this change sets CPU_DATA_LOG2SIZE
according to CACHE_WRITEBACK_SHIFT which is already set by several
platforms. In case the platform does not specify the cache line size,
ATF assumes the legacy value of 64 byte large cache lines.
Change-Id: Ic2d49ffe0c3e51649425fd9c8c99559c582ac5a1
Signed-off-by: Etienne Carriere <etienne.carriere@st.com>
> CPU_DATA_LOG2SIZE depends on cache line size

- include/common/aarch64/asm_macros.S
Add Call Frame Information assembler directives to vector entries so
that debuggers display the backtrace of functions that triggered a
synchronous exception. For example, a function triggering a data abort
will be easier to debug if the backtrace can be displayed from a
breakpoint at the beginning of the synchronous exception vector.
DS-5 needs CFI otherwise it will not attempt to display the backtrace.
Other debuggers might have other needs. These debug information are
stored in the ELF file but not in the final binary.
Change-Id: I32dc4e4b7af02546c93c1a45c71a1f6d710d36b1
> Add CFI debug info to vector entries

- plat/arm/board/juno/aarch64/juno_helpers.S
plat_get_my_entrypoint was branching to juno_do_reset_to_aarch_32_state,
which is not supposed to return, and in case of returning it implemented
an infinite loop. The problem was that plat_get_my_entrypoint was using
"b" instead of "bl", so juno_do_reset_to_aarch_32_state was returning to
the caller of plat_get_my_entrypoint instead of stop the system with a
panic.
To avoid this problem juno_do_reset_to_aarch_32_state was modified to
call directly to plat_panic_handler if it tries to return.
Change-Id: I591cf2dd78d27d8568fb15b91366e4b3dce027b5
> juno: Fix bug in plat_get_my_entrypoint

- bl32/sp_min/sp_min_main.c
When ARM TF executes in AArch32 state, the NS version of SCTLR
is not being set during warmboot flow. This results in secondary
CPUs entering the Non-secure world with the default reset value
in SCTLR.
This patch explicitly sets the value of the NS version of SCTLR
during the warmboot flow rather than relying on the h/w.
Change-Id: I86bf52b6294baae0a5bd8af0cd0358cc4f55c416
> Set NS version SCTLR during warmboot path
